### ISSUE TITLE
DOI Registration Reports

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#10]
As a member, I want to have statistics, so that I can report my impact.

#### Related User Stories

* As a member, I want up to date statistics/infos, so that I can keep track and see the impact.
* As a data manager, I want better reporting, so more people understand the impact of their data.

**Comment by mfenner** [comment]
Related user story:

* As a member, I want up to date statistics/infos, so that I can keep track and see the impact.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
