### ISSUE TITLE
Public user stories

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#101]
As a member, I would like to see a list of all user stories and should be able to add information, so that I can participate in the development of DataCite infrastructure.

#### DEV NOTES

* provide them at https://www.datacite.org/user-stories.html
* get them from the new user stories API (#99)
* provide explanatory text
* provide search interface by service category, status and search string

**Comment by pcruse** [comment]
Great!

**Comment by mfenner** [comment]
Two APIs, for user stories (#100) and for milestones (#99). The latter is for the roadmap. The reason we build DataCite APIs vs. using the GitHub APIs directly is that it simplifies the code for embedding the user stories in the homepage.
