### ISSUE TITLE
Clean up prefix 10.34739 and associated DOIs following transfer to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1020]
The following DOIs have been transferred to Crossref. Confirmation received that metadata has been re-registered in Crossref. 

Please delete DOIs corresponding to:

10.34739 | PSNC.UPH

**Comment by mfenner** [comment]
* 94 DOIs with prefix 10.34739 deleted.
* Prefix 10.34739 deleted.
