### ISSUE TITLE
Clean up prefixes belonging to GESIS and associated DOIs following transfer to Crossref 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1021]
The following DOIs have been transferred to Crossref. Confirmation received that metadata has been re-registered in Crossref. 

Please delete DOIs corresponding to:

10.21240 | GESIS.PHZH
10.14763 | GESIS.HIIG
10.13152 | GESIS.IJRVET

**Comment by mfenner** [comment]
* 0 DOIs with prefix 10.21240 deleted.
* 155 DOIs with prefix 10.14763 deleted.
* 100 DOIs with prefix 10.13152 deleted.
