### ISSUE TITLE
Clean up DOI metadata for prefix 10.13152

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1023]
Prefix 10.13152 (GESIS.IJRVET) has been transferred to Crossref and the corresponding metadata has been reregistered. Please delete metadata from DataCite.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nr6d)

**Comment by mfenner** [comment]
0 DOIs found for prefix 10.13152.
