### ISSUE TITLE
Rewrite all tests to use *.stage.datacite.org instead of *.test.datacite.org

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#1028]
- [x] poodle
- [x] cheetoh
- [x] viringo

**Comment by richardhallett** [comment]
We can scratch viringo as doesn't actually use the test system to test, It is using mocked test data to avoid reliance on the external API.
There is only one test which is actually setup against live service to ensure the API contract is okay.

**Comment by richardhallett** [comment]
Environments switched, see related PR's for specific change notes.
