### ISSUE TITLE
Move active Pivotal stories to Github Issues

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#103]

**Comment by kjgarza** [comment]
#98

**Comment by kjgarza** [comment]
All Pivotal stories in:

- Current iteration
- Backlog 
- Icebox (only those assigned)

now live in Github issues

**Comment by mfenner** [comment]
@kjgarza do I need to double-check anything?

We need to harmonize the labels with the labels from datacite/datacite. And we need to check for duplicates.

**Comment by kjgarza** [comment]
- We need to harmonize the labels with the labels from datacite/datacite: this is true , but we need to define how.
- And we need to check for duplicates: I think this can be done on the case by case basis. I mean when we close one item we can close whatever might feel like a duplicated. For example adding additional content in the individual item result in Search. There are/were 3 different but similar issues.
