### ISSUE TITLE
Rewrite more tests to use *.stage.datacite.org instead of *.test.datacite.org

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#1033]
- [x] content-negotiation
- [x] bracco
- [x] levriero
- [x] sashimi

**Comment by kjgarza** [comment]
@mfenner question on this. do DOIs with the doi in url form with `handle.test.datacite.org` still remain with `test` subdomain or those ones also change to `stage` ?

https://github.com/datacite/levriero/blob/4b58815/app/models/base.rb#L157

**Comment by mfenner** [comment]
I am not sure I understand the question. As we duplicated the database, we now have about one million DOIs available both via `test` and `stage`. This will change over time.

**Comment by kjgarza** [comment]
should the code in https://github.com/datacite/levriero/blob/4b58815/app/models/base.rb#L157 change as well:

```
  def self.doi_from_url(url)
    if /\A(?:(http|https):\/\/(dx\.)?(doi.org|handle.test.datacite.org)\/)?(doi:)?(10\.\d{4,5}\/.+)\z/.match(url)
      uri = Addressable::URI.parse(url)
      uri.path.gsub(/^\//, '').downcase
    end
  end
```

from handle.test.datacite.org to handle.stage.datacite.org or include both

**Comment by mfenner** [comment]
levriero will be running both in stage and test.
