### ISSUE TITLE
DOIs transferred to RWTH.PUBLICATIONS not appearing in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1035]
Following this transfer on 27 May:
Old Repository ID: [TIB.RWTH]
New Repository ID: [RWTH.PUBLICATIONS]
Prefix: [10.18154]

Some DOIs are still not appearing in Fabrica e.g. 10.18154/rwth-conv-220779. Possibly still under old repo in the db

**Comment by mfenner** [comment]
46 datasets not transferred.

**Comment by mfenner** [comment]
Fixed via datacite/lupo#536
