### ISSUE TITLE
Unknown key for a VALUE_BOOLEAN in [search_after].

### ISSUE THREAD

**Issue by miku** [datacite/datacite#1038]
**Describe the bug**

When using [cursor based pagination](https://support.datacite.org/docs/pagination#cursor), the intial request works:

* [https://api.datacite.org/dois?page[cursor]=1&page[size]=50...](https://api.datacite.org/dois?page[cursor]=1&page[size]=50&query=updated%3A[2020-05-15T00%3A00%3A00.000Z+TO+2020-05-15T23%3A59%3A59.999Z])

The response will correctly contain a link to the next page, but that subsequent request will fail with an HTTP 400 Bad Request.

Example [response](https://gist.github.com/miku/dec75b641cbb14b24044f84b77cbafa5) contains - under `links.next` - the following link:

* [https://api.datacite.org/dois?page%5Bcursor%5D=MTMyMjgyMjAyMDAwMCwxMC4xNTk0L3BhbmdhZWEuMjA3OTEw&page%5Bsize%5D=50&query=updated%3A%5B2020-05-15T00%3A00%3A00.000Z+TO+2020-05-15T23%3A59%3A59.999Z%5D](https://api.datacite.org/dois?page%5Bcursor%5D=MTMyMjgyMjAyMDAwMCwxMC4xNTk0L3BhbmdhZWEuMjA3OTEw&page%5Bsize%5D=50&query=updated%3A%5B2020-05-15T00%3A00%3A00.000Z+TO+2020-05-15T23%3A59%3A59.999Z%5D)

**To Reproduce**

Quickly:

```
$ curl -v $(curl -sLg "https://is.gd/1IkxFk" | jq -r .links.next) | jq .
...
< HTTP/2 400 
< date: Fri, 29 May 2020 14:16:37 GMT
< content-type: application/json; charset=utf-8
< status: 400 Bad Request
< x-anonymous-consumer: true
< cache-control: no-cache
< vary: Accept-Encoding, Origin
< x-request-id: 11828fdb-d8dd-4778-8abf-8f4683b2d8d7
< x-runtime: 0.058778
< x-powered-by: Phusion Passenger 6.0.4
< server: nginx/1.14.0 + Phusion Passenger 6.0.4
< 
{ [73 bytes data]
100    73    0    73    0     0    171      0 --:--:-- --:--:-- --:--:--   171
* Connection #0 to host api.datacite.org left intact
{
  "errors": {
    "title": "Unknown key for a VALUE_BOOLEAN in [search_after]."
  }
}

```

Details:

1. Make an API request.

*  [https://api.datacite.org/dois?page[cursor]=1&page[size]=50...](https://api.datacite.org/dois?page[cursor]=1&page[size]=50&query=updated%3A[2020-05-15T00%3A00%3A00.000Z+TO+2020-05-15T23%3A59%3A59.999Z])

2. Find "links.next" in the resulting JSON.

If you use the command line and [curl](https://curl.haxx.se/) and [jq](https://stedolan.github.io/jq/), you can combine step 1 and 2 ([original url](https://api.datacite.org/dois?page[cursor]=1&page[size]=50&query=updated%3A[2020-05-15T00%3A00%3A00.000Z+TO+2020-05-15T23%3A59%3A59.999Z]) shortened for readability):

```
$ curl -sLg "https://is.gd/1IkxFk" | jq -r .links.next
```

3. Go to the next page link and see the following error message:

```json
{
  "errors": {
    "title": "Unknown key for a VALUE_BOOLEAN in [search_after]."
  }
}
``` 

**Expected behavior**

An HTTP 200 with "application/json" response containing page 2 of results for the given query.

**Screenshots**

![](https://i.imgur.com/LISs8MI.png)

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser  Firefox
 - Version 76.0.1

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**

NA.

**Comment by mfenner** [comment]
Thank you @miku. We have fixed this bug in pull request https://github.com/datacite/lupo/pull/537 that should go live in production in the next few hours.

**Comment by mfenner** [comment]
The fix has been deployed and your above example now works as expected.

**Comment by miku** [comment]
Thanks for the blitz-fix!
