### ISSUE TITLE
Clean up metadata for prefix 10.26045

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1039]
Prefix 10.26045 and associated DOIs have been transferred to Crossref. Please remove DOI metadata from DataCite

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nst1)

**Comment by mfenner** [comment]
26 DOIs with prefix 10.26045 deleted. The prefix was also deleted.
