### ISSUE TITLE
Assigned prefixes not appearing in prefixes list

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1041]
### Expected Behaviour

Prefix appears in list of prefixes after being assigned to a repository (after refresh)

### Current Behaviour

A newly assigned prefix does not appear in the list of prefixes assigned to a repository even after refreshing

### Steps to Reproduce

1. assign prefix 10.80468 (409 generated because prefix is already assigned)
<img width="1298" alt="Screen Shot 2020-06-10 at 10 18 42" src="https://user-images.githubusercontent.com/44582654/84245148-e9dcc500-ab04-11ea-9dfa-49c61c2b0287.png">

2. 10.80468 does not appear in prefixes list
<img width="1281" alt="Screen Shot 2020-06-10 at 10 20 46" src="https://user-images.githubusercontent.com/44582654/84245167-eea17900-ab04-11ea-874c-70d2b2952f3d.png">

### Context (Environment)

Fabrica test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nt3p)

**Comment by richardhallett** [comment]
I looked a little and this might not just be a refresh issue, the prefix did not appear against the repository via the API either, i refreshed the index and it seemed to appear.

**Comment by richardhallett** [comment]
This appears to not be Fabrica related and instead the results are not being returned correctly from the call it makes to the API:

```https://api.test.datacite.org/repository-prefixes?client-id=&page%5Bnumber%5D=1&page%5Bsize%5D=25&provider-id=&query=&repository-id=dev.busaql&size=25&year=```
