### ISSUE TITLE
Domain filter should restrict DOI Registration based on filter

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1049]
The domain option that can be set for repositories currently does not restrict DOI registration.

Consider that this should either be removed to avoid confusion, or in fact made to work as an additional security measure.

Additionally the visible documentation in Fabrica also says that DOIs must match a specific domain, but this is not technically true, so this will need to be updated to reflect decisions made.

**Comment by vpeil** [comment]
Any updates or progress on this issue?

**Comment by mfenner** [comment]
This has been resolved and will be deployed to DataCite production infrastructure this week.

**Comment by vpeil** [comment]
> This has been resolved and will be deployed to DataCite production infrastructure this week.

Thanks a lot! Another (maybe minor) issue is: It's not possible to register more than 13 domains. In that case I can't submit the form.

**Comment by mfenner** [comment]
Thanks for the feedback. I will look into this, but I am pretty sure this is because we store this in a database table that only holds 256 characters. This is easy to fix, but I will open a new issue for it.
