### ISSUE TITLE
Delete 10.5903, 10.24445,10.26043,10.18754,10.24434, 10.21257,10.34778 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1055]
Prefix and repo:
10.5903 (ETHZ.UZH-AL)
10.24445 (ETHZ.HOPECONEXUS)
10.26043 (ETHZ.HOPE-GISO)
10.18754 (ETHZ.HOPEPSY)
10.24434 (ETHZ.HOPESC)
10.21257 (ETHZ.HOPESUI)
10.34778 (no repo)
Status: approved

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nuol)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by sallyjennings** [comment]
Thanks for approving these transfers, @MaryHirsch - I'll be in touch.

**Comment by MaryHirsch** [comment]
the metadata has been reregistered with Crossref. Please delete from DataCite

**Comment by kjgarza** [comment]
https://api.datacite.org/prefixes/10.24434 deleted
https://api.datacite.org/prefixes/10.5903 deleted
https://api.datacite.org/prefixes/10.24445 deleted
https://api.datacite.org/prefixes/10.26043 deleted
https://api.datacite.org/prefixes/10.18754 deleted
https://api.datacite.org/prefixes/10.21257 deleted
https://api.datacite.org/prefixes/10.34778 deleted

**Comment by kjgarza** [comment]
re run the task with 


Note: This does not delete any associated prefix.
{"message":"0 DOIs found for prefix 10.5903.","@timestamp":"2020-11-11T09:11:33.698+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
0 DOIs with prefix 10.5903 deleted.

Note: This does not delete any associated prefix.
{"message":"37 DOIs found for prefix 10.5903.","@timestamp":"2020-11-11T09:05:13.861+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 37 DOIs starting with _id 1503532.","@timestamp":"2020-11-11T09:05:15.309+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
37 DOIs with prefix 10.5903 deleted.

Note: This does not delete any associated prefix.
{"message":"28 DOIs found for prefix 10.24445.","@timestamp":"2020-11-11T09:06:00.926+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 28 DOIs starting with _id 17368789.","@timestamp":"2020-11-11T09:06:01.263+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
20 DOIs with prefix 10.24445 deleted.


Note: This does not delete any associated prefix.
{"message":"8 DOIs found for prefix 10.26043.","@timestamp":"2020-11-11T09:06:46.671+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 8 DOIs starting with _id 32739292.","@timestamp":"2020-11-11T09:06:46.795+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
8 DOIs with prefix 10.26043 deleted.

Note: This does not delete any associated prefix.
{"message":"266 DOIs found for prefix 10.18754.","@timestamp":"2020-11-11T09:07:30.523+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 266 DOIs starting with _id 8373770.","@timestamp":"2020-11-11T09:07:33.574+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
216 DOIs with prefix 10.18754 deleted.

Note: This does not delete any associated prefix.
{"message":"87 DOIs found for prefix 10.24434.","@timestamp":"2020-11-11T09:08:32.433+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 87 DOIs starting with _id 12283552.","@timestamp":"2020-11-11T09:08:34.836+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
87 DOIs with prefix 10.24434 deleted.

Note: This does not delete any associated prefix.
{"message":"136 DOIs found for prefix 10.21257.","@timestamp":"2020-11-11T09:09:40.266+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 136 DOIs starting with _id 9352726.","@timestamp":"2020-11-11T09:09:42.252+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
100 DOIs with prefix 10.21257 deleted.

Note: This does not delete any associated prefix.
{"message":"0 DOIs found for prefix 10.34778.","@timestamp":"2020-11-11T09:10:28.367+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
0 DOIs with prefix 10.34778 deleted.

**Comment by kjgarza** [comment]
https://api.datacite.org/dois?prefix=10.5903
https://api.datacite.org/dois?prefix=10.34778
https://api.datacite.org/dois?prefix=10.21257
https://api.datacite.org/dois?prefix=10.24434
https://api.datacite.org/dois?prefix=10.18754
https://api.datacite.org/dois?prefix=10.26043
https://api.datacite.org/dois?prefix=10.24445

**Comment by kjgarza** [comment]
Queries to check the database is in zero

Select doi from dataset
WHERE doi LIKE '10.18754%'	

Select doi from dataset
WHERE doi LIKE '10.24434%'	
- has crossref doi.

Select doi from dataset
WHERE doi LIKE '10.34778%'	

Select doi from dataset
WHERE doi LIKE '10.21257%'	

Select doi from dataset
WHERE doi LIKE '10.18754%'	

Select doi from dataset
WHERE doi LIKE '10.26043%'	

Select doi from dataset
WHERE doi LIKE '10.24445%'	

Select doi from dataset
WHERE doi LIKE '10.5903%'
