### ISSUE TITLE
Investigate sending XML with HTTPS instead of HTTP

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1056]
Request from member to have “HTTPS” references in XML or  support changing all “HTTP” to “HTTPS” in XML 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nus5)

**Comment by mfenner** [comment]
Nothing to do.
