### ISSUE TITLE
Update Solr schema for indexing

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#106]
- [x] date issued
- [x] funderIdentifier
- [x] awardNumber
- [x] geoLocationPlace
- [x] geoLocationPoint
- [x] remove refQuality
- [x] add combined field to index that holds name, nameIdentifier, nameIdentifierScheme, contributorRole and affiliation for creators and contributors
- [x] standard license field

**Comment by mfenner** [comment]
* geoLocationPoint is tracked in #281
* combined name field is tracked in #282
