### ISSUE TITLE
Hosting member application form and membership enquiry

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#1068]
FormStack is used to create a member application form. This allows candidate members to submit their interest which can directly go into SalesForce. This needs to be hosted somewhere to enable members to submit their application.

<p></p>

**Decision**

- Agreed to go ahead with embedded forms

- URL for the forms

  - /members/application

  - /members/enquiry

- Timeline - by the end of July

<p></p>

Requirements document: <https://docs.google.com/document/d/1Y_uba6HB3OQ1Oj9yYg3rq7Ze1ZIWgJRdl3azOHDjVMU/edit>

**Comment by daslerr** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/5150314

**Comment by mjbuys** [comment]
@sarala I have updated FormStack for SF and FormStack documents (@hcousijn @brittadreyer FYI). Please see below the embedded code for the two respective forms:

**Membership Application**
<div id="iFrameWrapper"><div id="ffDialog"></div><div id="ffLookupDialog"></div><iframe frameborder="0" scrolling="no" name="ffEmbedFrame" id="ffEmbedFrame"></iframe><script type="text/javascript">function FFSetIframeSize(t,e){var n=document.getElementById("ffEmbedFrame");n.height=t,n.width=e}var i=document.getElementById("ffEmbedFrame");i=i.contentWindow?i.contentWindow:i.contentDocument.document?i.contentDocument.document:i.contentDocument,i.document.open(),i.document.write('<script type="text/javascript" id="jsFastForms" src="https://sfapi.formstack.io/FormEngine/Scripts/Main.js?d=N5sfpqY_HIj6mWVrD0PZik2_xhWe-fUcbhNnRByU9y22uP2FyE_u6t23alhnLECL"></' + 'script>'),i.document.close();</script></div>

**Membership Enquiry**
<div id="iFrameWrapper"><div id="ffDialog"></div><div id="ffLookupDialog"></div><iframe frameborder="0" scrolling="no" name="ffEmbedFrame" id="ffEmbedFrame"></iframe><script type="text/javascript">function FFSetIframeSize(t,e){var n=document.getElementById("ffEmbedFrame");n.height=t,n.width=e}var i=document.getElementById("ffEmbedFrame");i=i.contentWindow?i.contentWindow:i.contentDocument.document?i.contentDocument.document:i.contentDocument,i.document.open(),i.document.write('<script type="text/javascript" id="jsFastForms" src="https://sfapi.formstack.io/FormEngine/Scripts/Main.js?d=N5sfpqY_HIj6mWVrD0PZik2_xhWe-fUcbhNnRByU9y3QtNIEcw42rGui2U6ic9IP"></' + 'script>'),i.document.close();</script></div>

**Comment by sarala** [comment]
@mjbuys Thanks.

@mfenner, this is ready to be implemented.

**Comment by kjgarza** [comment]
should the navigation to the Form be in the "Become member page" ?

![image](https://user-images.githubusercontent.com/1092861/94128637-acedd180-fe5a-11ea-9859-c89ac481548e.png)
