### ISSUE TITLE
Opt-in/Opt-out workflow

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1070]
Following legal advice, DataCite is updating the [<u>privacy policy</u>](https://drive.google.com/file/d/1sNV_Msk8X70QIMKMS8auSskj2R0JVdAO/view). This requires DataCite to obtain members’ prior consent.

<p></p>

**Decision:**  

- Add simple text to Fabrica UI where needed. 

- Opt-in managed through Campaign Monitor and synced to Salesforce. 

- Timeline - preferably by the end of August

<p></p>

Requirements document: <https://docs.google.com/document/d/1Kbjk59vP-cmeFu5-YhbP-HX7b3XEQztAraTnHh-vJws/edit>

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/5159177

**Comment by sarala** [comment]
@mfenner, I've had a look at the implementation. I've got a couple of suggestions - 
1. Is it possible to link to the privacy policy from the text?
2. It might be better if the text is at the bottom before ‘update repository’, then we don’t need to hide the text.

**Comment by mfenner** [comment]
Yes and yes. I can do both.

**Comment by sarala** [comment]
@mfenner all looks good for this, thanks. We can push this to production.
