### ISSUE TITLE
Delete DOIs with prefix 10.7559 from Crossref Citations repository

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1072]
Prefix 10.7559 has been transferred to DataCite from Crossref, but the end users cannot register all the DOIs in DataCite beccuase they were already directly imported from Crossref. Please delete 168 DOIs https://doi.datacite.org/dois?client-id=crossref.citations&page=NaN&query=10.7559*&sort=relevance

**Comment by kjgarza** [comment]
We cannot use rake tasks because there are more than one repo with the same prefix 

https://doi.datacite.org/dois?client-id=&page=NaN&prefix=10.7559&query=10.7559*&sort=relevance

**Comment by kjgarza** [comment]
@MaryHirsch FYI  there are only 148 dois , so i am assuming the issue has a typo or that was different 3 days ago https://doi.datacite.org/dois?client-id=crossref.citations&page=NaN&prefix=10.7559

**Comment by kjgarza** [comment]
FYI @mfenner , I'll be deleting the DOIS like this 

```
DELETE dataset, metadata
FROM dataset
INNER JOIN metadata ON dataset.id = metadata.dataset
WHERE dataset.datacentre = 32349 AND dataset.doi LIKE '10.7559/%' 
```

**Comment by mfenner** [comment]
This looks good, I had a similar query in mind. And it is 148 DOIs.

**Comment by kjgarza** [comment]
unfortunately, is not that easy.

`Cannot delete or update a parent row: a foreign key constraint fails (`datacite`.`metadata`, CONSTRAINT `FKE52D7B2F4D3D6B1B` FOREIGN KEY (`dataset`) REFERENCES `dataset` (`id`))
`

i'll need to check this further

**Comment by mfenner** [comment]
You need to delete the metadata first.

**Comment by kjgarza** [comment]
indeed. 

```


#delete metadata
DELETE metadata
FROM metadata
INNER JOIN dataset ON dataset.id = metadata.dataset
WHERE dataset.datacentre = 32349 AND dataset.doi LIKE "10.7559/%"


# delete dois n 
DELETE 
FROM dataset 
WHERE dataset.datacentre = "32349" AND dataset.doi LIKE '10.7559/%' 

#check results 0
select doi, aasm_state
from dataset
WHERE dataset.datacentre = "32349" AND dataset.doi LIKE '10.7559/%' 

```

I am going to run it in the morning because I don't have time to monitor it tonight

**Comment by kjgarza** [comment]
completed.

you can see in the API directly the dois do not exist in db

https://api.datacite.org/dois/10.7559/citarj.v7i2.158
