### ISSUE TITLE
Delete prefix 10.26119: transferred to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1073]
Prefix: 10.26119
DataCite Repo: RADS.SAO
Status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nzx1)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
@sallyjennings confirmed that the metadata has been re-registered with Crossref. Please delete from DataCite.

**Comment by richardhallett** [comment]
Deleted prefix and dois
