### ISSUE TITLE
Multiselect fields for Service Provider listing

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#1078]
The fields FocusArea and ServiceAudience are multiselect on the Service Provider application form, so the Service Provider listing should match. 

Country should also be multiselect to accommodate those organizations that are registered in more than one place.

**Comment by richardhallett** [comment]
I added bug label, but not sure if it is a bug, @mfenner Is this part of the work for the integration of new form?

CC: @sarala

**Comment by mfenner** [comment]
It is a new feature. I changed the label.

**Comment by kjgarza** [comment]
:wave: @daslerr, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
