### ISSUE TITLE
Jupyter Notebook for funder (DOI), organization (ROR), or repository (DOI) DMP list

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1081]
**Is your feature request related to a problem? Please describe.**
maDMP request

**Describe the solution you'd like**
Generate a formatted list from all the DMPs of a given funder (DOI), organization (ROR), or repository (DOI).

- include a input widget

**Comment by kjgarza** [comment]
@mfenner I was expecting to be able to do something along the lines of:

```
{
organisation(id:"https://ror.org/4343"){
  id
  dataManagementPlans{
  id
  }
}
```

to get all the DMPs by the organization but it seems the API doesn't have that connection

So, In https://github.com/datacite/pidgraph-notebooks-python/pull/9, I ended up calling:

```
{
dataManagementPlans(memberId:"cern){
  id
  }
}
```

is this how you intended the API to be used? Or the first case?

**Comment by mfenner** [comment]
You have a typo, it should be `organization` (and the ROR ID obviously doesn't exist). And you always need to use `nodes` when receiving a list of records.

And `dataManagementPlans` is currently not a field. I can add it today. You need it only for `organization` and `funder`?

**Comment by kjgarza** [comment]
yes, basically to address the use case in notebook 2 in https://docs.google.com/document/d/1mF1ncpkEowkRHVIGlvjeI9AqhSs9KwDIHa577XHIwMo/edit#bookmark=id.urp3dbfq4ubx

**Comment by mfenner** [comment]
You need `dataManagementPlans` for organization, funder and repository?

**Comment by kjgarza** [comment]
yes

**Comment by mfenner** [comment]
I just pushed a change to `lupo` that will queries like this (from the test I wrote):

```
 {
        organization(id: "https://ror.org/00k4n6c32") {
          name
          dataManagementPlans {
            totalCount
            registrationAgencies {
              id
              title
              count
            }
            licenses {
              id
              title
              count
            }
            languages {
              id
              title
              count
            }
            nodes {
              id
              types {
                resourceTypeGeneral
                resourceType
                schemaOrg
              }
              registrationAgency {
                id
                name
              }
            }
          }
        }
```

Should be in stage in an hour or so. We can push to production if it looks ok, the transfers from today are done, and we fixed any CORS issues.

**Comment by mfenner** [comment]
This now works in stage, but no data management plans were registered there. So I added one and the query gives the expected result.
