### ISSUE TITLE
Uninterrupted services

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#109]
As a member or data center, I want to receive uninterrupted services, even when services are updated/maintained, so that my own services are minimally affected by scheduled maintenance.

Scheduled downtime should be minimized, using zero-downtime deployments and configuration changes.

Right now deployment of a container means 5 min downtime, deployment of a new AMI takes 15 min.

**DEV NOTES**
* this applies only to production services
* one requirement is duplication of services
* challenges: deploy new docker container, deploy new docker host, deploy new proxy

**Comment by mfenner** [comment]
With switching to AWS Application Load Balancers last week we have implemented zero downtime deployments for docker containers and ECS EC2 instances.

The open issue is deploying a new Solr container and re-using the index. We use an external EBS volume that can be re-attached to the new EC2 instance. This is tracked in #278.
