### ISSUE TITLE
Delete prefix 10.21247 and metadata (transferred to mEDRA)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1095]
prefix 10.21247
GESIS.IPARL 
status:delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o2dx)

**Comment by richardhallett** [comment]
Deleted 10.21247
