### ISSUE TITLE
Show additional information for organizations

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#1096]
Based on datacite/lupo#617, show additional information for single organizations using the wikidata API:

* inception year
* geolocation
* Twitter account

This is not only useful information not (yet) in ROR, but is also a nice blueprint for further wikidata integration going forward.

![Bildschirmfoto 2020-09-07 um 07.48.51.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/789e929e-05cf-4856-bf5b-7abbf4bf6cf1)

**Comment by sarala** [comment]
@mfenner This looks fine. Is it possible to move Geolocation after the links section. I don't think it is important information that should be at the top. 
I think it would be great to show a description if available at some point.

**Comment by mfenner** [comment]
Sounds good, will change. The description in Wikidata is rather uninformative ("a university in Bath, UK" etc), and I am not aware of any other source.

I find geolocation important, as it helps with disambiguation. But there is work underway to integrate this into ROR proper.

**Comment by sarala** [comment]
Great thanks. No point in adding useless information. Let's wait for ROR to add proper description.

**Comment by mfenner** [comment]
![Bildschirmfoto 2020-09-26 um 18.11.55.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/8a9a2738-cb07-49a4-bada-a0fcee711eff)

**Comment by sarala** [comment]
Thanks Martin. Looks good. However, what is the new "xx citations" mean?

**Comment by mfenner** [comment]
See datacite/akita#142.
