### ISSUE TITLE
Delete prefix 10.34671  from Datacite

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1099]
Prefix: 10.34671 
DataCite repository ID: RADS.SCH
Status: approved

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o2mt)

**Comment by MaryHirsch** [comment]
@sallyjennings confirmed that the metadata has been reregistered with Crossref. Please delete from DataCite

**Comment by kjgarza** [comment]
prefix has been disassociated https://api.datacite.org/prefixes/10.34671
and deleted

**Comment by kjgarza** [comment]
run it once again 

```
{"message":"217 DOIs found for prefix 10.34671.","@timestamp":"2020-11-11T09:01:17.314+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
{"message":"Deleting 217 DOIs starting with _id 32782714.","@timestamp":"2020-11-11T09:01:19.340+00:00","@version":"1","severity":"INFO","host":"ip-10-0-11-84.eu-west-1.compute.internal"}
67 DOIs with prefix 10.34671 deleted.
```

**Comment by kjgarza** [comment]
https://api.datacite.org/dois?prefix=10.34671

**Comment by kjgarza** [comment]
Select doi from dataset
WHERE doi LIKE '10.34671%'	

queires to check the datba se is in zeros
