### ISSUE TITLE
Configuration for receiving status service updates

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#110]
As a member or data center I want to be able to configure the way I am notified about incidents/maintenances/etc., so I can stay informed.

**DEV NOTES**
* channels for service updates: webpage, api, email, twitter, rss. Email, web and API most important.
* configuration in user account
* needs documentation

**Comment by kjgarza** [comment]
- [ ] Explore Statuspage.io API
- [ ] What functionality should be user-customizable?
- [ ] More detailed info in the emails sent out
- [ ]  Management of email subscriptions via DataCite, e.g. Profiles service.

**Comment by mfenner** [comment]
Keep open.

**Comment by kjgarza** [comment]
:wave: @kjgarza, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
