### ISSUE TITLE
Commons - Profiles login with ORCID CSRF error then UID has already been taken.

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1103]
**Describe the bug**
When login to profiles coming from commons, choosing ORCID, I initially got a CSRF error, however after trying again in fresh browser session, I now can not login and get the message: *UID: has already been taken*
Refresh and attempting a login again produces UID has already been taken.
This occurs with brand new sessions (delete all cookies).

**To Reproduce**
1. Go to profiles.stage.datacite.org
2. Click on Sign in
3. Choose Sign in with Globus
4. Choose Sign in with orcid
5. Login to orcid account
6. Redirect occurs see error.

**Screenshots**
![image](https://user-images.githubusercontent.com/7294431/92589690-374f0680-f29b-11ea-8959-b9dfa176ec76.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjero
 - Browser Firefox
 - Version : 79.0 (64-bit)

**Additional context**

Potentially useful console message

```Cookie “_volpino_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite```

**Comment by mfenner** [comment]
This has been resolved by deleting the duplicate account.
