### ISSUE TITLE
[tech debt] Backup raw CNRI resolutions logs

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1104]
**Is your feature request related to a problem? Please describe.**

Currently, regularly we have to ask for older logs, we have to contact them. The logs are backed up both in one of the old EC2 instances and in Kristian Laptop.

**Describe the solution you'd like**

Would creating a S3 bucket (or a S3 Glacier)  be a good idea? that way we can do whatever we want with them later without requesting CNRI anything again

### How big are the logs and how expensive would it be?

Compressed raw files per month we are talking to something along the lines of 200MB
similar sizes for example:
July 2018: 166 MB
July 2020:  309 MB

The [cost of storage ](https://aws.amazon.com/s3/pricing/)would be marginal.

### How can we deal with the Backlog?

- We can use the AWS Console Interface to upload the backlog to S3 as they are in disk.

### What about Uploading Logs periodically?

- To automate some sort of [monthly upload to S3](url) we would need some sort of regularity that logs production do not have at the moment:
  - Logs creation is not always on the same date.
  - Not all the logs have the same names every month (server seems to change).
- How to execute:
  - Could we use a lambda function that triggers a job such as we do with the [crossref agent](https://github.com/datacite/mastino/blob/master/prod-eu-west/services/crossref-orcid-agent/crossref-orcid-agent_runner.js)?
  - Downloading the logs can take 10s of minutes.

**Comment by kjgarza** [comment]
The procedure for logs archiving has been created (https://datacite.atlassian.net/l/c/j0kKA2iq) and the first logs are already there.

closing this ticket to track [tech debt] in https://github.com/datacite/datacite/issues/1115

**Comment by mfenner** [comment]
@kjgarza can you create a `housekeeping` GitHub issue to actually upload all logs to the s2 bucket? That should happen before #1115.

**Comment by kjgarza** [comment]
personal computer backlog to be tracked in https://github.com/datacite/datacite/issues/1118
