### ISSUE TITLE
ORCID auto-update not working as expected

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1107]
### Expected Behaviour

When an ORCID appears in the DOI metadata and the auto-update is enable by the user in profiles, the DataCite record should be sent automatically to the users ORCID record.

### Current Behaviour

Some DOI records with ORCID in metadata not sent to ORCID

### Steps to Reproduce

ORCID iD https://orcid.org/0000-0001-7460-7794  and  https://orcid.org/0000-0002-1598-7181 DOI: https://doi.org/10.23640/07243.12896927.v1 (Uploaded on August 31st)

ORCID iD https://orcid.org/0000-0002-1598-7181 DOI:  https://doi.org/10.23640/07243.12927377.v1 and https://doi.org/10.23640/07243.12911873.v1 (Uploaded the first week of September)

From August 26th, there is an example where everything worked correctly. In that case it was an upload in Zenodo.
ORCID iD: https://orcid.org/0000-0002-0687-7554 , DOIs:  https://doi.org/10.5281/zenodo.4001551 and  https://doi.org/10.5281/zenodo.4001563

Profiles showing claims failed: https://profiles.datacite.org/admin/claims?page=2&query=10.23640%2F07243.12896927.v1

### Context (Environment)

Production

### Hypothesis

related : https://app.frontapp.com/open/msg_egprm8l

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o3kl)

**Comment by kjgarza** [comment]
There are no `datacite-orcid-auto-update` events in event data since August 20th. 

https://api.datacite.org/events?source-id=datacite-orcid-auto-update&query=occurred_at%3A%5B2020-08-21%20TO%202020-12-12%5D


this might be related to the same problems of citations events https://github.com/datacite/lupo/issues/634

**Comment by kjgarza** [comment]
new events are fixed after : https://api.datacite.org/events?query=occurred_at%3A%5B2020-09-24%20TO%202020-12-12%5D&source-id=datacite-orcid-auto-update

https://github.com/datacite/lupo/commit/a85b4121ffd6a9d9d7bd30d4f0ae7d0c1ac03fd3

missed events from previous month still are pending.

**Comment by kjgarza** [comment]
currently re running the rake task for the last two months. There 1000s of events so we will have to monitor on monday

**Comment by MaryHirsch** [comment]
An example of a Figshare record missing from orcid:

Mejias, Gabriela; Berger, Dror (2020): 20200903 Unlocking the power of ORCID integrations in HR systems. ORCID. Presentation. https://doi.org/10.23640/07243.12927407.v1 
https://orcid.org/0000-0002-1598-7181
https://orcid.org/0000-0001-8512-9281

**Comment by richardhallett** [comment]
DOI 10.23640/07243.12927407.v1 will never appear in an orcid as it's a duplicated of 10.23640/07243.12927407

However 10.23640/07243.12927407 should appear, I've run the import for oricd updates again for September, and we'll see.

Current orcid updates seem to be working fine.

**Comment by richardhallett** [comment]
I've sent a manual request to add 10.23640/07243.12927407 to the orcid profiles, this worked fine and appears correctly.

**Comment by richardhallett** [comment]
I've done updates for orcids for this period and I think this was a temporary issue.
Going forward I think we can close this and manage case by case basis if there were any missed during this period of time.

**Comment by MaryHirsch** [comment]
We've now had feedback from 2 different members that this is not working

**Comment by richardhallett** [comment]
This is working as expected, the users were having specific unrelated problems.
Other automatic updates are continuing.
