### ISSUE TITLE
Create REST API records from Salesforce

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1109]
Specification: Create REST API member records from Salesforce

https://docs.google.com/document/d/1aBtrF3S9dyTdjTNUeul7t9qO3ObjWhcv-kBGoOh4UxE/edit#heading=h.tx7e3cf69dk4

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/5617427

**Comment by kjgarza** [comment]
- [ ] Remove buttons from detials section

![image](https://user-images.githubusercontent.com/1092861/115715433-67ee3700-a378-11eb-8adc-38341fe13e72.png)

**Comment by kjgarza** [comment]
- [ ] Scenario: Displaying the “Enable Production” Button
            Given that a Member application exist in Salesforce
When the user visits on a Salesforce “opportunity” view  page
	And the “Is Active” checkbox on the related organization record is set to “false”
	And at least a/one “contact” exist on the related  organization record
             Then a button with the label “Enable Production” should be made visible and be clickable on the “opportunity” view  page. [WireFrame]

- [ ] Scenario: Displaying the “Enable Test” Button
            Given that a Member application exist in Salesforce
When the user visits on the opportunity page
	And the “Is Active” checkbox on the related organization record is set to “false”
	And the “Fabrica Account ID” on the related organization record is “empty”
	And at least a/one “contact” exist on the related  organization record
             And “has Test account” field on the related organization record is set to “false”
             Then a button with the label “Enable Test” should be made visible and be clickable on the “opportunity” view  page. [WireFrame]

**Comment by kjgarza** [comment]
- [ ] Loading donut stays on for a long period after clicking. It should probably drop an error when the response is not successful.

![image](https://user-images.githubusercontent.com/1092861/115723730-8eb06b80-a380-11eb-9e5d-3052c7ad460a.png)


![image](https://user-images.githubusercontent.com/1092861/115721032-eb5e5700-a37d-11eb-905a-f299cd65c79b.png)

**Comment by kjgarza** [comment]
- [ ] The button shouldn't show. This opportunity has no contact but the button still is visible

https://datacite--devpartcop.lightning.force.com/lightning/r/Opportunity/0067a00000JIbsNAAT/view  

![image](https://user-images.githubusercontent.com/1092861/115727142-a4736000-a383-11eb-9eba-9cf08c62f9e1.png)

**Comment by kjgarza** [comment]
- [ ] Aligning the buttons would be something good

**Comment by Loveprogramming10** [comment]
> * [ ]  Loading donut stays on for a long period after clicking. It should probably drop an error when the response is not successful. it might be because "display name" is empty.
> 
> ![image](https://user-images.githubusercontent.com/1092861/115723730-8eb06b80-a380-11eb-9e5d-3052c7ad460a.png)
> 
> ![image](https://user-images.githubusercontent.com/1092861/115721032-eb5e5700-a37d-11eb-905a-f299cd65c79b.png)


Kristian | Kristian
-- | --

Hi Kristian, 
Can you please check now , i have fixed this

**Comment by Loveprogramming10** [comment]
> * [ ]  The button shouldn't show. This opportunity has no contact but the button still is visible
> 
> https://datacite--devpartcop.lightning.force.com/lightning/r/Opportunity/0067a00000JIbsNAAT/view
> 
> ![image](https://user-images.githubusercontent.com/1092861/115727142-a4736000-a383-11eb-9eba-9cf08c62f9e1.png)
-- | --
Kristian



Kristian | Kristian
-- | --
Kristian

Hi Kristian,
do we need to check contacts for Account as well as Opportunity
before I was checking the Account should have a contact, now I have added one more criteria Opportunity must have a contact role
is that right?

**Comment by kjgarza** [comment]
yes basically there are a few conditions

Scenario: Displaying the “Enable Production” Button
            Given that a Member application exist in Salesforce
When the user visits on a Salesforce “opportunity” view  page
	And the “Is Active” checkbox on the related organization record is set to “false”
	And at least a/one “contact” exist on the related  organization record
             Then a button with the label “Enable Production” should be made visible and be clickable on the “opportunity” view  page. [WireFrame]

Scenario: Displaying the “Enable Test” Button
            Given that a Member application exist in Salesforce
When the user visits on the opportunity page
	And the “Is Active” checkbox on the related organization record is set to “false”
	And the “Fabrica Account ID” on the related organization record is “empty”
	And at least a/one “contact” exist on the related  organization record
             And “has Test account” field on the related organization record is set to “false”
             Then a button with the label “Enable Test” should be made visible and be clickable on the “opportunity” view  page. [WireFrame]

**Comment by kjgarza** [comment]
@Loveprogramming10 I don't think any of the buttons is triggering any calls. Our API has not received any new request since the button were changed of position

**Comment by Loveprogramming10** [comment]
hi, @kjgarza  sorry for the trouble,
if any of the condition is false the button will be disabled,
Enable Production clickable: if Account is_Active = false AND Account have the least  one contact AND Opportunity have least one contact role (added this criteria later [you were facing issue](https://github.com/datacite/datacite/issues/1109#issuecomment-824868523) )
Enable Test clickable: if Account is_Active = false AND Fabrica Account ID = empty AND Account have the least  one contact  AND Opportunity have least one contact role (added this criteria later [you were facing issue])AND has Test account = false
Thank You
