### ISSUE TITLE
Using REST API in test environment does not allow to create a DOI

### ISSUE THREAD

**Issue by dirk-ecker** [datacite/datacite#1112]
Actual it is not possible to create a DOI in the test environment using https://api.test.datacite.org/dois, the same POST request in production creates a DOI (https://api.datacite.org/dois).

Test environment gives status: 403 and message "You are not authorized to access this resource."

POST https://api.test.datacite.org/dois
content-type: application/vnd.api+json
authorization: Basic .....

{"data":{"type":"dois","attributes":{"doi":"10.7971/342342-34"}}}

**Comment by mfenner** [comment]
There is not enough information to say whether this is a bug. Please reach out to support@datacite.org and provide more information, in particular the account ID you are using.

**Comment by dirk-ecker** [comment]
Sorry, I found the problem. It was sitting in front of the screen. I used the wrong password combination for the test environment. The only thing to complain would be the incorrect error message, that should be wrong login parameters.
