### ISSUE TITLE
Delete metadata for prefix 10.24415 (transferred to crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1113]
Prefix: 10.24415
Repository ID: DELFT.LUP
Status: delete 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o3th)

**Comment by MaryHirsch** [comment]
@sallyjennings  confirmed metadata registered with Crossref

**Comment by kjgarza** [comment]
To delete DOIs from transferred prefix (to Crossref) we use a rake task (:delete_by_prefix) , right ?

**Comment by kjgarza** [comment]
32 dois deleted and prefix removed
