### ISSUE TITLE
JALC report issue with citations formatter

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1114]
### Expected Behaviour

Citation formatter retrieves citation in correct format

### Current Behaviour

The citation formatter gives "no metadata found message" or "incomplete response"

### Steps to Reproduce

Example of OKay
https://japanlinkcenter.org/data/10.11371/tievciieej.5.2_74

Example of NG
https://japanlinkcenter.org/data/10.34343/ijpest.2020.14.e01001

Biside this, we confirmed to receive another error popup window stated as "<h2>Incomplete response received from application</h2>".
https://japanlinkcenter.org/data/10.34450/data.jsda.11868957

![Screen Shot 2020-09-25 at 12 36 50](https://user-images.githubusercontent.com/44582654/94258487-379f0100-ff2d-11ea-96a4-6619d0f14e64.png)

![Screen Shot 2020-09-25 at 12 42 44](https://user-images.githubusercontent.com/44582654/94258495-3b328800-ff2d-11ea-803a-2fedc095f803.png)

### Context (Environment)

https://citation.crosscite.org/

**Comment by kjgarza** [comment]
Content negotiation fails as well

https://data.crosscite.org/text/x-bibliography/10.34450/data.jsda.11868957?style=ieee&locale=de

**Comment by mfenner** [comment]
Can you please check the JaLC content negotiation? Our content content negotiation is not used for the citation formatter for JALC DOIs.

**Comment by kjgarza** [comment]
10.34450/data.jsda.11868957, is not returning content-type at all.
10.34343/ijpest.2020.14.e01001, is returning `text/html` rather than the requested `application/vnd.citationstyles.csl+json`
