### ISSUE TITLE
Backup backlog raw CNRI resolutions logs from personal computer

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1118]
Backup backlog raw CNRI resolutions logs from personal computer (2018-2020)

follow https://datacite.atlassian.net/wiki/spaces/TEC/pages/1732476929/Archiving+Raw+DOI+resolution+logs?atlOrigin=eyJpIjoiODk3MjVjNTRiYjI3NDcwYTgxMzc5OTVlMzIzNzQyMjYiLCJwIjoiYyJ9

**Comment by mfenner** [comment]
@kjgarza what is the timeline for completing this task?

**Comment by kjgarza** [comment]
Marking progress:
- [ ] 2017
- [ ] 2018
- [ ] 2019
- [ ] 2020

**Comment by kjgarza** [comment]
All resolutions logs that I have backed up in my laptop are now in [S3](https://s3.console.aws.amazon.com/s3/buckets/raw-resolution-logs.datacite.org?region=eu-west-1&tab=objects).
