### ISSUE TITLE
Move 64 DOIs from BL.CDCC to CCDC.CSD 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1121]
64 DOIs were transferred from BL.CDCC to CCDC.CSD e.g. https://doi.datacite.org/dois/10.5517%2Fcc14p9jn but they still appear under the old repository, but nothing shows up here https://doi.datacite.org/repositories/bl.ccdc/dois. They are missing required metadata and were not indexed properly. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o5at)

**Comment by richardhallett** [comment]
The dois have been moved.
