### ISSUE TITLE
Blog only shows the last 25 entries

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1122]
### Expected Behaviour

all blog posts available

### Current Behaviour

blog posts only available from 24 jan 2020 https://blog.datacite.org/
it does not show pages.

### Steps to Reproduce

1. https://blog.datacite.org/

### Context (Environment)

Blog production

### Possible Implementation

Refactoring Search Component in the Blog does not include pagination.
Implement pagination for search component

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o4yd)

**Comment by kjgarza** [comment]
@mfenner I am wondering if the behaviour here described is actually the new normal behaviour of the blog after the Search Component changes? See https://github.com/datacite/blog/commit/82d0bf75977837519d94ad39f6a9f56970d534d6

**Comment by mfenner** [comment]
I change the issue title, as it was not clear. The fundamental issue is missing pagination, and that for me it is a bug.
