### ISSUE TITLE
Transfer ETH prefixes to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1126]
Prefixes: 10.5077 / 10.24450 / 10.34913
Repository ID: ETHZ.GENFCONNEXE / ETHZ.GENFABREP / ETHZ.GENFLINGUA
Status: approved

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o5jp)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
@codycooperross prefixes 10.5077 / 10.24450 / 10.34913 have been transferred to Crossref and can be deleted the associated metadata set to registered. thanks

**Comment by codycooperross** [comment]
Prefix 10.5077 has been removed from DataCite and its associated metadata has been set to Registered state.
Prefix 10.24450 has been removed from DataCite and its associated metadata has been set to Registered state.
Prefix 10.34913 has been removed from DataCite and its associated metadata has been set to Registered state.
