### ISSUE TITLE
Change 'What we do link' it's incorrect in footer

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1130]
See usersnap but basically the link needs updating in our footers.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o5qt)

**Comment by richardhallett** [comment]
Investigated but actually cant see wrong link, on hold waiting for more feedback.

**Comment by mfenner** [comment]
As part of the consent cookie launch this week, most footers got updated, including the one in Fabrica.

**Comment by richardhallett** [comment]
In which case, closing as probably fixed.
