### ISSUE TITLE
Delete 10.24411 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1133]
Prefix: 10.24411 
Repo ID: CYBERL.CYBERDOI
Status: Delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o6ol)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
The DOIs have been reregistered and the prefix and DOIs can be removed from DataCite

**Comment by richardhallett** [comment]
The Prefix is still assigned to us, it looks like it was transferred to crossref then transferred back.
Additionally I can still see DOIS being registered against this repository.

**Comment by MaryHirsch** [comment]
I'll check with Crossref

**Comment by MaryHirsch** [comment]
The prefix is staying with DataCite
