### ISSUE TITLE
Duplicate DOI entries in ElasticSearch Index

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1134]
On occasions it seems there are being made duplicate entries in the elasticsearch index, this has the effect that it appears twice in our search listings (i.e. Fabrica), when in fact there is only one entry within the database.

Example DOI at time of writing this was: 10.21945/rivm-2020-0138

User reported this occurred after registration of new DOI.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o785)

**Comment by richardhallett** [comment]
Another reported DOI is 10.25944/znmwse.2020.03.8198 interestingly this causes the created date on listing page to be the unix epoch.

in ES there appears to be two entries, one has the normal _id of database identifier, the other appears randomly generated.

**Comment by richardhallett** [comment]
Summary of investigation and working theory:

## Identifying the problematic DOIS
You can see all the problem DOIs as they have an _id in ES as something not DB related, you also can search by looking for anything without a created date.

ES search query: -created:*

This brings back that this started on **October 13th.**

In addition it was noticeable that not all DOis appeared to be affected, only some DOIs, as reported by various users.

## Working theory

When we do **register_url**, on task **before_save** then at this point it hasn't gone to the DB, which shouldn't normally be a problem, except **register_url** also triggers an elasticsearch index:
https://github.com/datacite/lupo/blob/e50c928427ed8dc4b707a91353831ec198f8d3f5/app/models/concerns/helpable.rb#L63

So by causing an index at this point the model in rails hasn't got a **model.id** yet just some of the details, this also explains why it doesn't have a created date as this is generated after save.

### Why only some DOIs?
This affects workflow of direct to Findable DOIs, if you go to draft first, then it won't attempt to register a url.
MDS (largest commit of DOIS) always has this workflow, you send metadata first, then register the URL (i.e. move to findable)

**Comment by mfenner** [comment]
@richardhallett Elasticsearch indexing happens after the database update: https://github.com/datacite/lupo/blob/e50c928427ed8dc4b707a91353831ec198f8d3f5/app/models/concerns/helpable.rb#L60-L63

**Comment by richardhallett** [comment]
@mfenner Hmm my suspicion is that this is not actually saving, it might be returning false here and just updating the model record rather than going to DB.
The fact that there is no created date also hints at this because this happens after on before_create

https://github.com/datacite/lupo/blob/e50c928427ed8dc4b707a91353831ec198f8d3f5/app/models/doi.rb#L136

**Comment by mfenner** [comment]
@richardhallett I think a small but important change would be to only trigger Elasticsearch indexing when the database saving was successful. Do you want to make the change?
