### ISSUE TITLE
Delete 3 ETH dois and prefixes (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1135]
Prefix 10.12685 : 10.24437:  and 1021255
Repository:  ETHZ.UBASOJS, ETHZ.UBETERNA, ETHZ.UBEMO
Status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o7dh)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by svogt0511** [comment]
This is done.
