### ISSUE TITLE
It is not possible to add an alternate identifier through the web interface DataCite Fabrica Test or DataCite Fabrica 

### ISSUE THREAD

**Issue by dirk-ecker** [datacite/datacite#1136]
I have tried both environments to add an alternate identifier and it is not send to the REST API. Doing this myself via the API does work.

Webpage: https://doi.test.datacite.org (Optional Properties/Alternate Identifiers)
REST API: https://api.test.datacite.org

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oc9h)

**Comment by richardhallett** [comment]
Thanks for the report.

Adding potential related issues 
https://github.com/datacite/lupo/issues/674
https://github.com/datacite/lupo/issues/641

**Comment by glefebvr1** [comment]
Hello, it might be that the following issue is related:

On the Datacite TEST environment, when we request a doi, we proceed in 2 steps:
1. Request the doi as draft, with a set of metadata sent
2. Change the doi's status to findable

In step 1, we fill in the "alternateIdentifier" and "alternateIdentifierType", which then appear in "identifiers" field in Fabrica.
When doing step 2, the "identifiers" field gets emptied.
This behaviour seems quite strange to me.

**Comment by T-R-lib** [comment]
Hello, we are also experiencing this issue at Griffith University. Our repository mints using the MDS API. I have been trying and failing to add alternateIdentifier metadata to a small collection of DOIs but nothing sticks. We have attempted with new mint tasks, DOI metadata update tasks from within our repository using the API and we have attempted with the Fabrica dashboard. Those attempts have included using the controlled vocabulary of types and the schema syntax suggested by the Fabrica dashboard as well as user-defined types, e.g. "Local ID", and the basic ID, e.g. "Q123". None of these attempts have resulted in the entered metadata being applied to the DOI records.

**Comment by richardhallett** [comment]
This has been fixed and was part of same issue as #641.

In short it should now be possible to either mint using MDS API via XML sending alternateIdentifiers, or using either identifiers or alternateIdentifiers which are the same.

In a future JSON API version we will most likely remove having both identifiers and alternateIdentifiers, for now they function in the same way.
