### ISSUE TITLE
Transfer 101 DOIs to EUROP.ODIN

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1146]
Old repository: Delft.jrc https://search.datacite.org/repositories/delft.jrc
New repository: EUROP.ODIN

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o8id)

**Comment by richardhallett** [comment]
I can't see any dois for this, they may have been already transferred.

There is 1 DOI but it is a draft DOI, this can be deleted if required.

**Comment by richardhallett** [comment]
Remaining draft doi appears to be duplicated in index, needs manual fixing

**Comment by richardhallett** [comment]
Moved the remaining draft to EUROP.ODIN, it was missing a URL preventing transfer, put in dummy URL as it was draft and can be updated as required.
