### ISSUE TITLE
Delete prefixes 10.24446, 10.26034, 10.18753 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1149]
Prefixes 10.24446, 10.26034, 10.18753 
repository: ETHZ.FRAG, ETHZ.ROADSIDES, ETHZ.SOZ
Status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o8ph)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
@sallyjennings confirmed that these DOIs can be deleted

**Comment by MaryHirsch** [comment]
@codycooperross another old one. Prefixes 10.24446, 10.26034, 10.18753 can be deleted and the metadata set to registered state,. thanks.

**Comment by codycooperross** [comment]
Prefixes 10.24446, 10.26034, and 10.18753 have been removed from DataCite and their associated metadata has been set to Registered state.
