### ISSUE TITLE
Cookie banner is not mobile friendly

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1151]
**Is your feature request related to a problem? Please describe.**

Issue from user refers DataCite Search - site is not mobile friendly as the link to give feedback covers the option to close the cookie banner. This makes it difficult to accept the cookie notice and read the content 😕 Example here: https://share.icloud.com/photos/00pl2MyzHInjOgUd65jgPy6_w - however, could be applied to other DataCite Services

**Describe the solution you'd like**

Make sure cookie banner can easily be clicked in order to read content

**Describe alternatives you've considered**

**Additional context**

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o9cl)

**Comment by svogt0511** [comment]
We need to check the following sites to make sure they pick up style changes from homepage:

- DataCite Search
- DataCite Blog
- DataCite Fabrica
- DataCite Schema

Once they are fixed, this issue can be closed.

**Comment by svogt0511** [comment]
I checked the sites mentioned above.  Changes have been applied and they look ok.
