### ISSUE TITLE
Consent cookie does not properly enable Google Analytics tracking

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1152]
### Expected Behaviour

when accept the cookie GA tracking should take place

### Current Behaviour

the Cookie banner seems not to enable GoogleAnalytics when one accepts the Cookie ? I am looking at Search and Stats portal and there are no data since October (right around the integration of that).

![image](https://user-images.githubusercontent.com/1092861/99793857-9053da00-2b29-11eb-9f03-6e655aa23023.png)

### Steps to Reproduce

1. open a guest session
2. accept cookie banner
3. look at realtime tracking in ga https://analytics.google.com/analytics/web/#/realtime/rt-overview/a22806196w61174467p62626186/

### Context (Environment)

Problem can be seen in:
- Homepage
- Stats
- Search

**Comment by mfenner** [comment]
I renamed to properly describe the issue.

**Comment by kjgarza** [comment]
The homepage also seems to not be sending any analytics after the  cookie banner change 
![image](https://user-images.githubusercontent.com/1092861/106586790-26a07500-6549-11eb-85fa-8a65da3581c1.png)


https://analytics.google.com/analytics/web/#/report-home/a22806196w104253211p108421353

**Comment by mfenner** [comment]
This has been fixed.
