### ISSUE TITLE
DOI metadata enrichment  (subject area classification) for Data analysis

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1154]
To Create Technical Specification based on Product Specification in files:

https://github.com/datacite/tasks/tree/master/product_specifications/ELmjUzA-7

--------

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/6228024

**Comment by kjgarza** [comment]
OECD Mapping activities will be handle in https://github.com/datacite/frascati-mappings/issues/1

**Comment by kjgarza** [comment]
@jrhoads if they map to your tech spec you might want to re-open #727 #728 #729 as they were closed by stalebot. Otherwise, you can maybe unlink them
