### ISSUE TITLE
Remove prefix 10.17602 from DataCite

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1161]
Prefix 10.17602 is a Crossref prefix and should not appear in Fabrica. Delete prefix 10.17602 and associated DOI: 10.17602/C2F596

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oac5)

**Comment by richardhallett** [comment]
Prefix deleted and mistaken DOI deleted.
