### ISSUE TITLE
Transfer DOIs from GESIS.UBHD separate repositories

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1167]
•            10.21245: 1073 DOIs from VGZM.ARI to VGZM.XXTRLE

•            10.18446: 1059 DOIs from VGZM.ARI to VGZM.DHLILS

•            10.21938: 18 DOIs from GESIS.UBHD to VGZM.ARI

**Comment by richardhallett** [comment]
Dois have been transferred.
