### ISSUE TITLE
Move subset of 200,122 DOIs to IPK.GBIS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1173]
Prefix “10.25642” 
Old repository: TIB.IPK
New repository: IPK.GBIS
Number of DOIs: 200,122

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2obdh)

**Comment by richardhallett** [comment]
All dois transferred to IPK.GBIS

Additionally prefix moved to new member/repository.
