### ISSUE TITLE
Recover the deleted  DSJV.OJS test account

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1174]
The  DSJV.OJS account was deleted by they wish to use this ID. Please reactivate.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2obf9)

**Comment by mfenner** [comment]
The repository account is re-activated.
