### ISSUE TITLE
Investigate why DOIs are missing from NRC.IR in Fabrica test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1176]
In March prefix 10.4224 and all DOIs were transferred from CISTI.NRC to NRC.IR (this was requested by the member, see attached). Currently:

31 under new repository https://doi.test.datacite.org/repositories/nrc.ir/dois 
There is now 1 appearing under the old repo, https://doi.test.datacite.org/repositories/cisti.nrc/dois looks like there could be an issue with missing metadata. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oc2d)

**Comment by MaryHirsch** [comment]
Info from member on use of test might be useful for @sarala 
Our Test environment is essentially setup as a mirror of our Prod system. The data in Test is a snapshot of what exists in Prod and is updated periodically to match. The same 10.4224 prefix DOIs exist in record metadata in both environments. Our integration with DataCite in Test works exactly the same as in Prod except it is connecting to the Test MDS API instance and uses the Test credentials.
When testers perform an operation such as updating record metadata, that will trigger an update of the DOI metadata in DataCite. The system first checks to see if the DOI exists and if it does then just a simple update Is performed. If the DOI doesn’t exist then this is deemed to be a “new” DOI and the system performs the full registration/minting process and metadata update. So if an existing DOI is removed from DataCite’s Test system, the next time that it is updated in our Test system, it will be re-created in DataCite. As I said, this works fine for us as long as the re-creation process doesn’t fail. We also use the Test environment to try batch DOI operations before we do them in Prod to make sure that we’re not making any mistakes. The batch operations are identical between Test and Prod, so they rely on having the same DOIs available in both places.
This is why we requested that the same prefix (10.4224) be available for us in both Production and Test Fabrica accounts when we migrated last year. That was done and so far it has worked without any problems until just before Christmas. Let me know if you have any other questions.

**Comment by richardhallett** [comment]
This is an old issue, but fundamentally test may or may not include the same values as production, it should be used to test integrations and not be used as part of a production set up.
Given this is quite old now I'm to assume this is no longer an issue.
