### ISSUE TITLE
Some ORCID auto-update claims failing with "Invalid Token"

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1177]
#### Expected Behaviour

ORCID claiming via DataCite profiles automatically updates user ORCID profile when permission is set

#### Current Behaviour

Some claims fail with "Invalid Token"

#### Steps to Reproduce

1. See specific user example here: https://profiles.datacite.org/admin/claims?user_id=0000-0002-3675-0968 
2. successful claims and claims with errors in the recent claims: https://profiles.datacite.org/admin/claims

### Context (Environment)

Profiles

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oc7p)

**Comment by richardhallett** [comment]
I've investigated but I'm not sure there is a bug, the error is returned from Orcid went the token is invalid. It is possible that it was invalid at the time and we just need to trigger updates for this users dois.
I'm handling the issue via support as I believe it is not a general issue.
