### ISSUE TITLE
Fabrica Form won't save with contributer type of Data Curator

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1183]
Filling Data curator with a valid organisational name causes the form to continue proposing an error.
However there should be no validation error.

![image](https://user-images.githubusercontent.com/7294431/139603934-3371c331-ade3-49ee-a4bd-82d747cfc61b.png)

Reproduce

1. Create DOI
2. Add contributor set type to organisational
3. Update to data curator as contributor type
4. Notice error at bottom of form

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ocb9)

**Comment by digitaldogsbody** [comment]
Resolved in https://github.com/datacite/bracco/pull/573
