### ISSUE TITLE
Delete prefix 10.25557 - transferred to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1185]
Prefix : 10.25557
DataCite repo: RADS.IGPP
Status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ocet)

**Comment by MaryHirsch** [comment]
Delete as confirmed by @sallyjennings

**Comment by richardhallett** [comment]
Deleted all DOIS associated with 10.25557
