### ISSUE TITLE
DataCite Search is not showing citation formats

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1204]
#### Expected Behaviour

Clicking on cite from a record in DataCite Search displays the citation in the selected format

#### Current Behaviour

[object object] error appears for all citation formats

#### Steps to Reproduce

https://search.datacite.org/works#
![Screen Shot 2021-02-09 at 10 55 27](https://user-images.githubusercontent.com/44582654/107347173-d6d02980-6ac5-11eb-97c8-827f5b66c2d8.png)

### Context (Environment)

DataCite Search

**Comment by kjgarza** [comment]
This service will no be longer supported as of the end of 2022. See https://portal.productboard.com/datacite/1-roadmap-2022/c/44-consolidation-of-datacite-search-into-datacite-commons?utm_medium=social&utm_source=portal_share
