### ISSUE TITLE
Transfer subset of DOIs from GFZpublic to GFZ.IASS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1210]
Old repository: TIB.GFZBIB 
New repository: GFZ.IASS
DOIs: 257 (see attached)
[TIB_DOIs_10.2312:iass*.txt](https://github.com/datacite/datacite/files/6028226/TIB_DOIs_10.2312.iass.txt)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oez9)

**Comment by MaryHirsch** [comment]
@svandesandt please let me know when you plan to do this so I can let the member know. thanks

**Comment by svogt0511** [comment]
All dois successfully transferred.
