### ISSUE TITLE
delete prefix 10.25960 and DOIs (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1213]
Prefix 10.25960 
repository, SPBPU.PHP
127 DOIs
status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2of6d)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
@codycooperross this is an old one, the transfer of prefix 10.25960 was completed but I don't think it was removed. Could you delete and set the metadata to registered state? thanks!

**Comment by codycooperross** [comment]
Prefix 10.25960 has been removed from DataCite and its associated metadata has been set to Registered state.
