### ISSUE TITLE
Pagination in repository finder 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1214]
#### Expected Behaviour

Should be possible to scroll through the results in repository finder

#### Current Behaviour

Not possible to move to the next page

#### Steps to Reproduce

1. https://repositoryfinder.datacite.org/search

### Context (Environment)

Production

**Comment by kjgarza** [comment]
We will stop supporting this service as from late 2022. See https://blog.datacite.org/how-to-find-a-repository-for-your-research-outputs/
