### ISSUE TITLE
[Tech-Debt] Refactor Usage Stats service (Suzanne)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1216]
Refactor Usage Stats service to store reports in files not database

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/7196181

**Comment by kjgarza** [comment]
related: 

- https://github.com/datacite/sashimi/issues/133

**Comment by kjgarza** [comment]
closing as datacite/sashimi#133 is closed
