### ISSUE TITLE
Delete prefix 10.26080 and 10.24394 and DOIs (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1222]
Prefix 10.26080 and 10.24394
repository: MTAKIK.NATSOMOG
126 + 68 DOIs
Status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ofth)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by svogt0511** [comment]
This is done.  Closing the issue.
