### ISSUE TITLE
Deleted member accounts showing up in Fabrica as "inactive"

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1230]
### Expected Behaviour

Deleted member accounts do not appear in the Fabrica interface

### Current Behaviour

Deleted Member and Consortium organization accounts are appearing in Fabrica with the label "Inactive"

### Steps to Reproduce

1. https://doi.datacite.org/providers?page=NaN&query=CISTI&sort=relevance 
2. https://doi.datacite.org/providers?page=NaN&query=SPBPU&sort=relevance 

### Context (Environment)

Fabrica

**Comment by MaryHirsch** [comment]
TIB deleted Consortium Organizations

·       Bayerisches Forschungsinstitut für Digitale Transformation (bidt) (Inactive) - Member ID: POQL

·       Bibliothek der Hochschule Hannover (Inactive) - Member ID: ZZPR

·       Bibliothek der Stiftung Tierärztliche Hochschule Hannover (TiHo) (Inactive) - Member ID: MBZR

·       Deutsche Bundesstiftung Umwelt (Inactive) - Member ID: QQBH

·       HTW Berlin - University of Applied Sciences (Inactive) - Member ID: XMCR

·       Leibniz-Institut für Angewandte Geophysik (Inactive) - Member ID: QIWQ

·       Leibniz-Institut für Ostseeforschung Warnemünde (IOW) (Inactive) - Member ID: DHLZ

·       Leibniz-Institut für Plasmaforschung und Technologie e.V. (Inactive) - Member ID: JCFL

·       Westsächsische Hochschule Zwickau (Inactive) - Member ID: PGLS

**Comment by mfenner** [comment]
This was fixed by changing the query parameters.
