### ISSUE TITLE
transfer prefixes 10.24386 and 10.17202 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1233]
Prefix 10.24386 
repository MTAKIK.MICLEPID
25 DOIs.

Prefix 10.17202
repository MTAKIK.JUSO
9 DOIs.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ogph)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.17202 has been transferred to Crossref and can be deleted and the associated metadata set to registered. Thanks

**Comment by codycooperross** [comment]
Prefix 10.17202 has been removed from DataCite and its associated metadata has been set to Registered state.
