### ISSUE TITLE
Transfer Prefix 10.24365 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1238]
Prefix 10.24365
repository, MTAKIK.EGFEJL
301 DOIs 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ogyd)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.24365 has been transferred to Crossref and can be deleted and the associated metadata set to registered. thanks

**Comment by codycooperross** [comment]
Prefix 10.24365 has been removed from DataCite and its associated metadata has been set to Registered state.
