### ISSUE TITLE
Inactive member workflow (Suzanne)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1242]
[<u>Inactive member workflow</u>](https://docs.google.com/document/d/1T4MwA05vqA_2Plf1TQrMyWVNrgXpiAup381yVpZkwFM/edit) - 

- Requirement for member management

- Product spec is done and ready for the tech spec hand over

- Hand over date: [TBC]

- Development lead: [Richard]

<p></p>

Currently the inactive repositories are managed as follows: 

<https://docs.google.com/document/d/1VSYp78NrN_UEg2wBKJlz11jK_3uUzXmp6jd6JOwVA3M/edit>

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/5617403

**Comment by richardhallett** [comment]
Closing as think it needs reviewing/discussing as things have changed since original spec.
