### ISSUE TITLE
Improve Search on Page (Richard)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1244]
Product specification - <https://docs.google.com/document/d/1mhOm-LassOlPGE2t3_TwjENFHI4CApZaqH5R7sYjDKs/edit#heading=h.k72datyxd8rf>

Technical specification - <https://datacite.atlassian.net/wiki/spaces/DAT/pages/2522284033/Improving+Javascript+performance+in+DataCite+Commons>

**Comment by sarala** [comment]
Link to subfeature: https://datacite.productboard.com/feature-board/planning/features/6867164

**Comment by richardhallett** [comment]
Work is completed and deployed.
