### ISSUE TITLE
MDC - Resources Setup (GitHub Repository)

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1248]
- Add GitHub repository for self-hosted Plausible. (1 day)
- Add GitHub actions for deployment (workflows).
- Other GitHub configuration tasks?

**Comment by svogt0511** [comment]
Done.  Forked their repository into ours - [github.com/datacite/analytics](https://github.com/datacite/analytics).  I have a temporary [github.com/datacite/analytics-hosting](https://github.com/datacite/analytics) to work with their sample hosting config.  Eventually it should be only the 'analytics' repository.

**Comment by kjgarza** [comment]
@svogt0511 if this one is completed feel free to close it
