### ISSUE TITLE
MDC - COUNTER Spec Conformance Issues

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1257]
- Count unique vs total views and downloads (within 60 min session)
- Filter out double clicks (2nd click from same session within 30 seconds)
- Other? (2 days).

**Comment by svogt0511** [comment]
These are the COUNTER spec issues.  This has been item to after the initial release.

**Comment by richardhallett** [comment]
Closing in favour of tracking everything under epic datacite/datacite#1506
