### ISSUE TITLE
API queries only search the first field in the query string

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1258]
#### Expected Behaviour

API elastic search query recognises different objects when linked with AND

#### Current Behaviour

Only the first field of the query is recognised

#### Steps to Reproduce

example: https://api.datacite.org/dois?query=creators.familyName:Abbassi&publicationYear:2014  

### Context (Environment)

REST API

**Comment by mfenner** [comment]
No bug. Use correct API call, e.g. https://api.datacite.org/dois?query=creators.familyName:Abbassi%20AND%20publicationYear:2014
