### ISSUE TITLE
Fabrica is not showing assigned Roles to contacts when relationship are created with the API

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1260]
### Expected Behaviour

when creating relations between contacts and providers the relationships assignation should be visible in the Fabrica provide page (view and form).

### Current Behaviour

The relationships are created but the relationships are not visible in the provider setting page or form.

more details:

- https://docs.google.com/document/d/11DZovE3HX0JxKKAEgTLiih1p75NHPCCgwlKWBvc9LFQ/edit#
- https://datacite.slack.com/archives/C07V2UFEU/p1620401543063600

### Steps to Reproduce

1. create the provider with the API
2. create the contact  with the provider association and the role_name with the API
3. look at the fabrica provider page for the created provider

### Context (Environment)

example  https://api.test.datacite.org/providers/thwb?sort=-created

### Hypothesis

the provider contacts information in the providers model is empty and thus Fabrica cannot show it.

**Comment by svogt0511** [comment]
There are a couple more steps to make this happen via the API:

- create a provider
- create a contact (with the correct provider identified)
- update the contact with the correct roles
- update the provider with the appropriate contact data (email, given name, family name)

It looks like you might have missed the last step.  Here is a link to the [provider with contacts](https://doi.stage.datacite.org/providers/mwnw) that I created using the API in stage.

I am going to close this issue.  If I have missed something please let me know and we can re-open it.

**Comment by kjgarza** [comment]
I think the bug is in the last step @svogt0511 

The current integration is using the following payload to create the contacts after creating the provider:

```json
 {
	"data": {
		"attributes": {
			"email": $email,
			"familyName": $lastName,
			"givenName": $givenName,
“roleName”: ["voting","billing","secondary_billing","service","secondary_service","technical","secondary_technical"]
		},
"fromSalesforce": true,
		"relationships": {
			"provider": {
				"data": {
					"type": "providers",
					"id": $Fabrica_Account_ID
				}
			}
		},
		"type": "contacts"
	}}
    },
```

Effectively this payload creates the contact (step 2), adds the roles (step 3), and creates the relations to the provider (step 4). And you can see in the prefix-provider table that all this is actually happening.

What is not happening in Step 4 is the Provider being updated with the relationships in the model in the ES index. The bug is that there should be a need for an additional API call to update that. The model data in the ES should be updated automatically when the relationships are created in the database.

**Comment by svogt0511** [comment]
OK. I was thinking about that.  I will ask Martin tomorrow what he had in mind.

**Comment by svogt0511** [comment]
@kjgarza I had looked at how Fabrica is currently doing it and it does make that extra API call.  You are correct that Step 4 is not happening without that last call.  So what you need is in the contact creation, to see that $FromSalesforce in the payload to cause the update of the provider, as well (as in Step 4).  That can be done.  Since I am still coming up to speed, I need to ask for clarification on 'updating the model in ES index'.  As I understand it that is in the DB.  Is that correct?

**Comment by mfenner** [comment]
I am not sure $fromSalesforce is relevant here. Its intention is to manage what happens after contact/provider create/update actions.

**Comment by svogt0511** [comment]
@kjgarza  I have deployed this change to production.  Give it a try and I can close this.  Creating/updating/deleting contacts with roles through the API should work now.  Everything shows up in the database as it is supposed to.  Regarding seeing updated contact/role information in Fabrica, it looks good so far, but I think there are other issues going on with that which are unrelated to this issue. 

Give it a try and let me know.  I will close this issue, but we can re-open it if necessary.
