### ISSUE TITLE
Delete prefix 10.25807 and associated DOIs (Transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1261]
Prefix 10.25807 
repository, RADS.PBH.
 1,048 DOIs
Status delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ohg5)

**Comment by MaryHirsch** [comment]
@sallyjennings

**Comment by svogt0511** [comment]
This is done.
