### ISSUE TITLE
Functionality for linking DOIs from DataCite Search to ORCID records is not working

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1262]
#### Expected Behaviour

Authors can add DOI containing their ORCID record via DataCite Search

#### Current Behaviour

Clicking the button "Add to ORCID record" does nothing

#### Steps to Reproduce

1. Search.datacite.org
2. try to link a record to ORCID

<img width="470" alt="Screen Shot 2021-05-14 at 09 48 19" src="https://user-images.githubusercontent.com/44582654/118239194-bd11fa00-b499-11eb-88bf-0659ed832398.png">

### Context (Environment)

DataCite Search

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ohhx)

**Comment by richardhallett** [comment]
Additional info, this is actually a 422 from the API.

**Comment by jlwasserman** [comment]
Thanks for posting this issue for me, @MaryHirsch! Keep me posted.

**Comment by jlwasserman** [comment]
This is resolved on my end.

**Comment by richardhallett** [comment]
This is fixed, claims should be able to be made via search.datacite.org now.
