### ISSUE TITLE
Code review for Salesforce Integration

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1263]
Files where the code is.
https://datacite--devpartcop.lightning.force.com/lightning/setup/ApexClasses/page?address=%2F01p7a000002ijzPAAQ
Paths for ENV variables
https://datacite--devpartcop.lightning.force.com/lightning/setup/CustomMetadata/page?address=%2Fm057a000000Gno2

Notes:
https://docs.google.com/document/d/11DZovE3HX0JxKKAEgTLiih1p75NHPCCgwlKWBvc9LFQ/edit#heading=h.3i3iqyalrmtn

- [ ] Calls only for /providers and /contacts endpoints
- [ ] Calls are only POST calls
- [ ] No hardcoded credentials or urls

**Comment by richardhallett** [comment]
I had a look over the code, nothing obvious from a security point of view.
There is a test email to a personal gmail still, which will need removing, otherwise fine.

**Comment by kjgarza** [comment]
The feedback has been already applied by applikon.tech
