### ISSUE TITLE
Delete Salesforce Test Member xhiu and jcpl

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1269]
Delete Test members for the deployment of salesforce integration from aPI and database
https://doi.datacite.org/providers/xhiu
https://doi.datacite.org/providers/jcpl

and contacts:

Sebastian Vettel
https://doi.datacite.org/contacts/f91b86d0-b674-4736-bc66-9ed3e616766c

Aragon Lotr
https://doi.datacite.org/contacts/a69fde27-2467-4c27-bb16-afe0c0e0984b

**Comment by svogt0511** [comment]
Done.  Closing this issue.
