### ISSUE TITLE
Delete 21 DOIs with prefix 10.18737

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1276]
Prefix 10.18737 was transferred to Crossref but 21 DOIs were registered in DataCite after the transfer. These DOIs do not resolve and need to be deleted

https://doi.datacite.org/dois?prefix=10.18737

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ohw5)

**Comment by richardhallett** [comment]
Prefix now managed by prefixes, confirmed removal of old DOIs
