### ISSUE TITLE
When the creator is an organization, the name value is not displayed in DataCite Search

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1278]
#### Expected Behaviour

When the creator is an organization, the name value is displayed

#### Current Behaviour

When the creator is an organization, the name value is not displayed in DataCite Search

#### Steps to Reproduce

DataCite Search examples :
https://search.datacite.org/works/10.18167/infrastructure/00001
https://search.datacite.org/works/10.18167/infrastructure/00002
We could say that only the separator characters are displayed : "," and "&".

DataCite Commons examples:
https://commons.datacite.org/doi.org?query=10.18167%2Finfrastructure%2F00001
https://commons.datacite.org/doi.org?query=10.18167%2Finfrastructure%2F00002

### Context (Environment)

DataCite Search

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ohzp)

**Comment by codycooperross** [comment]
This issue appears to have been resolved in DataCite Commons and will not be resolved in DataCite Search pending its discontinuation. See the screenshots below for https://commons.datacite.org/doi.org/10.18167/infrastructure/00001: 

![Image](https://user-images.githubusercontent.com/50597551/192027316-36c9298f-6682-4c4b-aa59-afb807c1fbeb.png)

![Image](https://user-images.githubusercontent.com/50597551/192027375-06b162da-9b36-480b-a4a9-eb13de586dd4.png)
