### ISSUE TITLE
Show all data centers in API search result facet

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#128]
As a member, I want to see result numbers broken down by all my data centers when doing an API call, so that I can avoid multiple queries.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1x95)

**Comment by RachaelKotarski** [comment]
Thanks for adding!
I think there would be valid reasons for viewing all content for years and resource-types as well, although I note that there are *currently* less than 15 resourceTypeGeneral options.

**Comment by mfenner** [comment]
@RachaelKotarski that makes sense.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
