### ISSUE TITLE
"Copy to clipboard" does nothing in citation formatter

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1282]
#### Expected Behaviour

Clicking "Copy to clipboard"  data is copied into the clipboard 

#### Current Behaviour

Clicking "Copy to clipboard" button, does not copy date to  the clipboard 

#### Steps to Reproduce

1. Copy to clipboard function in citation formatter https://citation.crosscite.org/ 

### Context (Environment)

Safari, Firefox and Chrome

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7xrh1)

**Comment by KellyStathis** [comment]
https://github.com/crosscite/citeproc-doi-server/blob/efcd78818b978e306bcdca8629bb13a12174c7bf/public/index.html#L73

**Comment by richardhallett** [comment]
This actually is a wontfix now as there are plans in motion for this service to be maintained outside of DataCite.
