### ISSUE TITLE
Remove prefix 10.25803 and set DOIs to registered state (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1288]
Prefix 10.25803 
repository, RADS.SFI
114 DOIs
status: approved

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oihh)

**Comment by MaryHirsch** [comment]
The prefix can now be removed from DataCite and the DOIs all moved to registered state.

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.25803 has been transferred to Crossref and can be removed from DataCite and the metadata set to registered. thanks!

**Comment by codycooperross** [comment]
Prefix 10.25803 has been removed from DataCite and its associated metadata has been set to Registered state.
