### ISSUE TITLE
Delete prefix 10.24349 and associated dois (transferrred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1290]
Prefix 10.24349 
repository, INIST.ACAROLOG
271 DOIs
status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oil1)

**Comment by svogt0511** [comment]
@MaryHirsch This is done.
