### ISSUE TITLE
Delete 3 RADS prefixes and dois (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1296]
1. Prefix 10.34922 
repository, RADS.ESCULAP
226 DOIs
2. Prefix  10.26089 
repository, RADS.NUMNET
281 DOIs
3. Prefix 10.25986 
repository, RADS.IRI
181 DOIs

status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ois5)

**Comment by svogt0511** [comment]
This is done.
