### ISSUE TITLE
Delete Prefix 10.25636 and associated (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1300]
Prefix 10.25636 
repository, RADS.PMP
228 DOIs 
status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oivp)

**Comment by svogt0511** [comment]
Done.
