### ISSUE TITLE
Delete prefix 10.23671 and associated DOIs (Transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1301]
Prefix 10.23671  
repository, RADS.MAIN
1066 DOIs
https://doi.datacite.org/repositories/rads.main/dois?prefix=10.23671

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oixh)

**Comment by svogt0511** [comment]
This is done.

**Comment by svogt0511** [comment]
This is done.
