### ISSUE TITLE
Remove prefix 10.25685 (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1303]
Prefix 10.25685
repository, RADS.FP
298 DOIs
status: remove prefix and set DOIs to registered state.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oiz9)

**Comment by codycooperross** [comment]
Prefix 10.25685 has been removed and the 298 DOIs in RADS.FP have been changed to registered state.
