### ISSUE TITLE
remove test for validation of  fabrica bug

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1308]
remove the following members from fabrica and the database :

- https://doi.test.datacite.org/providers/gtuu
- https://doi.datacite.org/providers/psml

The feature is working as expected in both test and production : 

![image](https://user-images.githubusercontent.com/1092861/126773269-d7f2b055-35aa-4052-a5d7-ce983a6808cb.png)

![image](https://user-images.githubusercontent.com/1092861/126773319-cd6a1628-59a7-45c3-8740-71782e1d207d.png)

![image](https://user-images.githubusercontent.com/1092861/126773368-8a956612-e90b-4a23-9f19-7e8176c37d5c.png)

validation of: 
https://github.com/datacite/datacite/issues/1260

**Comment by svogt0511** [comment]
Done.
