### ISSUE TITLE
Some organization records throw an error in DataCite Commons

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1309]
#### Expected Behaviour

Clicking on organization link opens the full record in DataCite Commons

#### Current Behaviour

https://commons.datacite.org/ror.org/05dhe8b71 BL record throws an error
https://commons.datacite.org/ror.org/05dxps055 Caltech record throws an error

#### Steps to Reproduce

<img width="1369" alt="Screen Shot 2021-07-23 at 16 24 13" src="https://user-images.githubusercontent.com/44582654/126796371-a3ac0a48-cb90-4eb6-aaef-6ea2f10a127b.png">

 There seems to be a graphql DOWNSTREAM_SERVICE_ERROR in "authors".

### Context (Environment)

Commons

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oj85)

**Comment by kjgarza** [comment]
The co-authors facet was designed for the Profile pages ONLY (https://commons.datacite.org/orcid.org/). Not for the organisational pages. IMO it should not be shown on the https://commons.datacite.org/ror.org/ pages. Looking at the sentry error, the assumptions of the facet needs to be reviewed if it's to be used there. Sames goes for the https://commons.datacite.org/doi.org/ pages.

**Comment by MaryHirsch** [comment]
Another example: University of Iowa as a whole, https://commons.datacite.org/ror.org/036jqmy94

**Comment by codycooperross** [comment]
This issue is closed by this pull request: https://github.com/datacite/lupo/pull/832 . . . which also closes #1359 #1418
