### ISSUE TITLE
Transfer 77 DOIs to HELIOPHY.SPDF

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1316]
Old Repository: CDL.UCLA
New Repository ID: HELIOPHY.SPDF
Prefix: 10.21978
Number of DOIs: 77
[EZID_2_Datacite_list.txt](https://github.com/datacite/datacite/files/6893326/EZID_2_Datacite_list.txt)

**Comment by svogt0511** [comment]
Done.
