### ISSUE TITLE
Autogeneration of passwords

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#133]
As Member/Data centre I want my password to be autogenerated so I do not have to reach DataCite for passwords

**Comment by mfenner** [comment]
For convenience and security we should generate all passwords for users. Following [newer best practices](https://auth0.com/blog/dont-pass-on-the-new-nist-password-guidelines/) we can generate these passwords as passphrases using the https://github.com/iphoting/pwqgen.rb library.
