### ISSUE TITLE
Blog doesn't show last blog on listing

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1330]
The blog list doesn't show last blog https://blog.datacite.org/ even when new blogpost have been released https://blog.datacite.org/our-commitment-to-posi/ and a DOI has been minted https://doi.org/10.5438/vy7h-g464

#### Expected Behaviour

the blog list should shall the last item

#### Steps to Reproduce

1. Go to https://blog.datacite.org/

#### Screenshots

![image](https://user-images.githubusercontent.com/1092861/131478897-68e0f677-007f-4d14-986b-c08e8893ed61.png)

**Comment by richardhallett** [comment]
Not a bug, DOI must be findable to appear in the datacite blog overview as that list is based on findable DOIs.
Registered DOIs do not get returned by the API therefore don't show.
