### ISSUE TITLE
Some characters and accents are not displayed correctly in DataCite Commons

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1336]
#### Expected Behaviour

Characters and accents are correctly formatted in commons 

#### Current Behaviour

questions marks replace accents in author name and apostrophes

<img width="824" alt="Screen Shot 2021-09-09 at 11 17 30" src="https://user-images.githubusercontent.com/44582654/132659032-d151b3b3-2c3e-4db8-bdc4-fc8e3912408a.png">

#### Steps to Reproduce

e.g 1  https://commons.datacite.org/orcid.org/0000-0002-1988-274X
e.g 2 https://commons.datacite.org/ror.org/02trn6p95
e.g 3 https://commons.datacite.org/orcid.org/0000-0003-2926-8353

### Context (Environment)

DataCite Commons

#### Hypothesis
This is due to the data coming back from GraphQL API itself, that data appears to have not been parsed correctly from the original ORCID API.

If you use the orcid api to retrieve in JSON with this ORCID then you will see the employment information is returned correctly https://pub.orcid.org/v3.0/#!/Development_Public_API_v3.0/viewRecordv3

This is called in the backend lupo API here: https://github.com/datacite/lupo/blob/c50361ef7b8a53a6003011b3faceb01e113c8f39/app/models/person.rb#L102

I suspect we're not parsing the strings correctly and therefore it comes back encoded wrong.

Look to add a test for getting back the results from the get_orcid function to check results are correctly there.
If not then problem may lie in the graphql specific parsing of this data./

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2okwl)

**Comment by jrhoads** [comment]
I have a failing test in place for the results of the get_orcid fuction.  So it is unlikely that the graphql portion is a problem.

I suspect that it goes all the way back to the encoding that is enforced in the maremma library.
https://github.com/datacite/maremma/blob/master/lib/maremma.rb#L232

**Comment by MaryHirsch** [comment]
I'm still seeing this in the display in DataCite Commons https://commons.datacite.org/ror.org?query=Leibniz*
<img width="1002" alt="Screen Shot 2021-11-09 at 14 07 11" src="https://user-images.githubusercontent.com/44582654/140929579-984fbdad-1a5e-4384-a188-b4fbcba54186.png">

**Comment by jrhoads** [comment]
Sorry about that.  PR closed it but didn't get to deploy before Friday.  Should be deploying to production soon.

**Comment by MaryHirsch** [comment]
Ah ok no problem. Thanks!

**Comment by jrhoads** [comment]
Now deployed in production and with @MaryHirsch 's approval I will mark this as closed (for real this time).
