### ISSUE TITLE
Attaching an issue name in the seriesInformation breaks the citation style

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1338]
#### Expected Behaviour

It's possible to attach an issue name to a citation in the seriesInformation

#### Current Behaviour

Including the issue name e.g. spring 2019 breaks the citation

#### Steps to Reproduce

Create a DOI with the seriesInformation including issue name

<img width="1068" alt="Screen Shot 2021-09-10 at 10 31 14" src="https://user-images.githubusercontent.com/44582654/132824982-c3ddd481-4f9f-4500-bddd-41bea96fdd3b.png">

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ol5h)

**Comment by MaryHirsch** [comment]
Comment from the user:
We ran into a parsing issue:
For this DOI https://doi.datacite.org/dois/10.48558%2F0qk4-zz97
We'd like to also attach a Spring 2019 issue name but we don't know where to put it. When I put it into the SeriesInformation, it breaks the APA style. Can you maybe attempt to modify that DOI to see where we can attach the Spring 2019 issue name so that the following citations can be generated correctly (mind the italic text)?

APA
Youn, A., & Forti, M. (2019). Big Gift, Big Impact. Stanford Social Innovation Review, 17(2), B10. https://doi.org/10.48558/0QK4-ZZ97

MLA
Youn, Andrew, and Matthew Forti. “Big Gift, Big Impact.” Stanford Social Innovation Review, vol. 17, no. 2, spring 2019, pp. B10. doi:10.48558/0QK4-ZZ97.

Chicago
Youn, Andrew, and Matthew Forti. “Big Gift, Big Impact.” Stanford Social Innovation Review 17, no. 2 (Spring 2019): B10. https://doi.org/10.48558/0QK4-ZZ97.

**Comment by richardhallett** [comment]
I'm not sure I understand the problem here, you can enter series information and this is available in the metadata.

The seriesinformation is really a way to format a description, it does not nescessarily mean it is used by any citation tools.
The APA we generate is correct to me as there is nothing to say it should include this additional information.

This would be a feature request to change this, unless I am missing some context here.

**Comment by richardhallett** [comment]
Closing as not reproducible.
