### ISSUE TITLE
Service-Level Agreements

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#134]
As a member I want to be able to get preferred access to information about DOIs, so that my membership provides value.

#### DEV NOTES

* Different rate-limiting for authenticated vs. unauthenticated users of the DataCite API
* Not relevant for the MDS API

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
