### ISSUE TITLE
Integration of data centre api functions

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#135]
As a Member I want an API that help me to integrate the MDS fuctionality with my System

**Comment by kjgarza** [comment]
# Functionality to reproduce from the UI
- Allocators/Members
   - List All
   - Show one
   - Update
   - Create
   - Delete
- Datacentres
   - List All
   - Show one
   - Update
   - Create
   - Delete
- Prefixes
   - List All
   - Des/Associate
   - Show one
   - Create
- Media
    - None
- Datasets
    - None

**Comment by pcruse** [comment]
this is very helpful!

**Comment by kjgarza** [comment]
### Functionality to reproduce from the UI
- Allocators/Members
   [ ]  List All
   [ ]  Show one
   [ ]  Update
   [ ]  Create
   [ ] Delete
- Datacentres
  [ ] List All
  [ ] Show one
  [ ] Update
  [ ] Create
  [ ] Delete
- Prefixes
   [ ] List All
   [ ] Des/Associate
   [ ] Show one
   [ ] Create
- Datasets
   [ ] List All
   [ ] Show one
