### ISSUE TITLE
Click through citation to related resource in Commons not working

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1353]
#### Expected Behaviour

It should be possible to click on the "Citation" link to the related resource

#### Current Behaviour

Clicking on the citation does nothing

#### Steps to Reproduce

1. example: https://commons.datacite.org/doi.org/10.26275/maq2-eii4

### Context (Environment)

Commons production

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2omvp)

**Comment by kjgarza** [comment]
@MaryHirsch I think this is mislabeled the "1 citation" label are not click-trough. That's not a feature we have. 

Having said that, the this is more likely to be a reference and not a citation. Look at ED https://api.datacite.org/events?doi=10.26275/maq2-eii4

**Comment by MaryHirsch** [comment]
@kjgarza i thought we had discussed this and it should be possible to click on the "Cite" button to access the associated resource?

**Comment by kjgarza** [comment]
closing as discussed in https://app.frontapp.com/open/msg_h5xehqt
