### ISSUE TITLE
Search for a specific DOI in DataCite Commons generates an error

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1359]
#### Expected Behaviour

All DataCite DOIs in findable state can be retrieved in Commons

#### Current Behaviour

Doi generates an error

#### Steps to Reproduce

1. lower case: https://commons.datacite.org/doi.org?query=10.24416%2Fuu01-j81dsw
2. upper case: https://commons.datacite.org/doi.org?query=10.24416%2FUU01-J81DSW

<img width="1061" alt="Screen Shot 2021-10-19 at 18 23 12" src="https://user-images.githubusercontent.com/44582654/137960492-51d53227-63f4-4bb5-8bc9-5c1127f1975e.png">

it can be retrieved via Fabrica and the api https://doi.datacite.org/dois/10.24416%2Fuu01-j81dsw

Other dois can be retrieved in commons: https://commons.datacite.org/doi.org?query=10.24416%2Fuu01-fscv60

### Context (Environment)

Commons 

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2op5h)

**Comment by MaryHirsch** [comment]
There also seems to be a problem searching by title for some DOIs

Example:
Search by title: https://commons.datacite.org/doi.org?query=Toxicity+assessment+data+from+subchronic+inhalation+exposure+to+a+school+air+mixture+%28SAM%29+of+PCB
Search by DOI: https://commons.datacite.org/doi.org/10.25820/data.006120

**Comment by codycooperross** [comment]
This issue is closed by this pull request: https://github.com/datacite/lupo/pull/832 . . . which also closes #1309 #1418
