### ISSUE TITLE
Transfer a subset of DOIs to OCUL.SPDV

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1362]
Date/time: Tuesday, November 2nd, before 13:00 UTC

Old repository: UALBERTA.LIBRARY

New repository: OCUL.SPDV

Prefix: n/a (UALBERTA.LIBRARY will keep their current prefix)

DOIs: https://docs.google.com/spreadsheets/d/1poinqAsY3qiPFqWWWPn244M8E_0K6yAQ5ML8JEfhpbE/edit#gid=0

[UA DOIs for Published Datasets - 2021-10-26-15_58.csv](https://github.com/datacite/datacite/files/7425195/UA.DOIs.for.Published.Datasets.-.2021-10-26-15_58.csv)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oro5)

**Comment by richardhallett** [comment]
All doi's transferred.
