### ISSUE TITLE
Transfer 10.25993 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1363]
Prefix 10.25993 
repository, RADS.FM. 
41 DOIs
status approved

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ost1)

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.25993 has been transferred to Crossref and can be deleted and the associated metadata set to registered. Thanks.

**Comment by codycooperross** [comment]
Prefix 10.25993 has been removed from DataCite and its associated metadata has been set to Registered state.
