### ISSUE TITLE
The work type facet in DataCite Commons does not match the total number of records

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1365]
#### Expected Behaviour

The total number of work type in the facet in DataCite commons is the same as the total number of records retrieved

#### Current Behaviour

The total shown in work type facet and chart are different to total records retrieved

#### Steps to Reproduce

1. Go to https://commons.datacite.org/ror.org/006wxqw41?rorid=006wxqw41&registration-agency=datacite

Total records = 180
Work types facet = 34

<img width="1303" alt="Screen Shot 2021-11-03 at 17 15 45" src="https://user-images.githubusercontent.com/44582654/140099708-e7c4d00a-8346-41ec-bf25-1d6ad30b9959.png">

graphQL count is 180 

```
{
  "data": {
    "organization": {
      "name": "Gordon and Betty Moore Foundation",
      "works": {
        "totalCount": 180
      }
    }
  }
}
```

### Context (Environment)

DataCite commons

**Comment by jrhoads** [comment]
I think this may have been cleaned up in some recent work we did to make sure that Commons stopped caching facet values.

@MaryHirsch Can you see if this is still a problem?  I am not currently able to recreate it.

**Comment by richardhallett** [comment]
Closing as not reproducible. As Joseph said I think this has been fixed in related work. 
Please re-open if still a problem.
