### ISSUE TITLE
Repository search in DataCite Commons (Joseph)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1366]
[<u>Repository search in Commons</u>](https://docs.google.com/document/d/18CJvxMPM3jOiMneidiTl43wCdD_D_siwUcY6aihk3-A/edit) (3 Phases)

- Requirement for retiring search and FAIRsFAIR

- Product spec for Phase 1 is on hold as there are unresolved issues that need to be addressed

  - Unresolved repository identifier issues

  - [Action] Organise a meeting with relevant people to resolve this

<p></p>

**SP5: Adapting our processes and workflows to meet our members needs**

<p></p>

same as: https://github.com/datacite/datacite/issues/1345

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/5044621

**Comment by kjgarza** [comment]
same as: https://github.com/datacite/datacite/issues/1345

**Comment by kjgarza** [comment]
@jrhoads @sarala 
 https://app.zenhub.com/workspace/o/datacite/datacite/issues/1392  will be handle as part of https://portal.productboard.com/datacite/1-roadmap-2022/c/44-consolidation-of-datacite-search-into-datacite-commons?utm_medium=social&utm_source=portal_share
