### ISSUE TITLE
Error updating repository in Salesforce

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#1377]
The Fabrica/Salesforce synch has not transferred the repository information to Salesforce in some cases. Repositories were created in Fabrica but have not been transferred to Salesforce. This in turn causes errors when DOI numbers are synched. In other cases, the synch is trying to update deleted repositories, which no longer exist. 

#### Expected Behaviour
When a repository in Fabrica is created or the DOI number changes that information is synced with Salesforce. 

#### Current Behaviour
The synch is trying to update not existing repositories in Salesforce, which partially have not been created by the synch previously or are deleted repositories that no longer exist.

#### Steps to Reproduce
1. Example: Repository information has not been transferred to Salesforce by synch: The two repositories created on May 11, 2021 https://doi.datacite.org/providers/ktsw/repositories have not been transferred to Salesforce https://datacite.lightning.force.com/lightning/r/Account/0016N000004pWLhQAM/view
It seems that the repositories in this case were synched before the member account has synched with Salesforce. The member account and the repositories were created in Fabrica around May 11, 2021, 16:08:22 UTC but the member account has entered an Fabrica creation date 11.05.2021 18:03. This could mean that the repositories were synched before the member account which at this time did not exist. 
2. Repositories that are deleted in Fabrica do not synch with Salesforce. This could be related to the switch in member ID or because they have the status "inactive" in Salesforce.

See #Ops for details.

### Context (Environment)
The repositories in Salesforce hold the updated DOI numbers relevant for invoicing members.

### Proposal

1. Billing information must be correct, therefore it is necessary to understand which repositories have not synced with Salesforce. There are 2445 repos in Fabrica https://doi.datacite.org/repositories and 2437 repos in Salesforce currently https://datacite.lightning.force.com/lightning/r/Report/00O6N000000mC5CUAU/view.
2. Do not synch deleted repositories.

**Comment by richardhallett** [comment]
Regarding the 2nd part of this in updating deleted repositories, my question is:
**Why are there deleted repositories in Salesforce / How are they being deleted?**
as far as I understood it, there should always be a direct match between salesforce and Fabrica and that includes deleted repositories.

If we do not sync deleted repositories, **how do those repositories get updated and marked as deleted?** As I understood it, deleted in salesforce should be in_active much like in Fabrica and not actually removed as a record.

**Comment by svogt0511** [comment]
Regarding the KTSW repositories not updating.  The salesforce ID is wrong in Fabrica.  It should be 0016N000004pWLhQAM.  I am pretty sure that is why those repositories are not updating.  

I also think the  Salesforce ID inconsistency between Fabrica and Salesforce is causing many of the other INVALID_CROSS_REFERENCE_KEY errors we are seeing in #ops.

We need to find out why Salesforce IDs are not always properly updated in Fabrica.  Is it a programmatic or process error?

Regarding the sync job updates, they happen in the prescribed order: providers, repositories, contacts.

Billing information is handled in datacite/datacite#1379.  We have decided that Salesforc is where that is updated and Fabrica will no longer push billing info in the nightly updates.

**Comment by svogt0511** [comment]
@brittadreyer, @mjbuys, @sarala, @richardhallett I am closing this issue.  If you review it and see something that is missed, we can re-open, but I believe everything has been covered.
