### ISSUE TITLE
Moving prefixes

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#138]
As a member, I want to be able to move prefixes and DOIs between data centres, so I don't have to ask DataCite staff

**Comment by kjgarza** [comment]
How to manage multiple request operations. 
https://books.google.de/books?id=ed5ml0T3zyIC&pg=PA211&lpg=PA211&dq=Support+for+multiple+operations+in+a+single+request&source=bl&ots=58bm4fKVmr&sig=dd3pJcWCPsibGmbhqQfuPYM_Z_E&hl=en&sa=X&redir_esc=y#v=onepage&q=Support%20for%20multiple%20operations%20in%20a%20single%20request&f=false

**Comment by mfenner** [comment]
Implemented in DOI Fabrica.
