### ISSUE TITLE
DataCite user roles

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#139]
As a member or data center, I want to give my staff different roles when accessing the DOI registration service, so that I can be flexible.

Possible roles (with increasing permissions):

* anonymous (not logged in)
* user
* data center user
* data center admin
* member user
* member admin
* staff user
* staff admin

#### DEV NOTES

* roles are different from contact types (see #169)
* basic roles are `user` (read access) and `admin` (write access)
* roles are related to association with **member** and **data center**, or with DataCite. This gives us 7 roles.

**Comment by mfenner** [comment]
Closes #9.

**Comment by kjgarza** [comment]
+1 I'll be using this to define users in lupo with cancancan

**Comment by mfenner** [comment]
@kjgarza these roles are now used in the JWT generated in `test` and `production` Profiles service.

**Comment by pcruse** [comment]
Again - I think we need to separate administrative activities for user/data center activities.
