### ISSUE TITLE
Remove prefix 10.25965 from DataCite (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1412]
Prefix 10.25965 
repository, INIST.UNILIM
1,032 DOIs (set to registered state)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pknp)

**Comment by MaryHirsch** [comment]
@codycooperross @svogt0511 the associated DOIs should be set to registered state. Thanks

**Comment by codycooperross** [comment]
@MaryHirsch The prefix has been deleted and the 1,032 DOIs have been set to registered state.
