### ISSUE TITLE
Citation not appearing in the Graph QL/Commons for DOI with correct relatedIdentifiers metadata

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1413]
#### Expected Behaviour

If the DOI metadata is correctly formatted according to guidance  https://support.datacite.org/docs/relationtype_for_citation then one citation should appear for the corresponding DOI record.

#### Current Behaviour

The metadata is correctly formatted and includes all the correct elements and relationType but there is no citation count

#### Steps to Reproduce

https://api.datacite.org/dois/10.5281/zenodo.5140319 the metadata of this resource looks correctly formatted for it to have one citation. This is not the case here: https://commons.datacite.org/doi.org/10.5281/zenodo.5140319)

### Context (Environment)

Graph QL/ DataCite Commons

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pn2t)

**Comment by kjgarza** [comment]
another example: 

```
{
  "data": {
    "attributes": {
      "relatedIdentifiers": [
        {
          "relationType": "IsCitedBy",
          "relatedIdentifier": "10.1016/j.joule.2021.09.015",
          "relatedIdentifierType": "DOI"
        }
      ]
    }
  }
}
```

 https://api.datacite.org/dois/10.7302/pa3f-4w30

**Comment by MaryHirsch** [comment]
another example: https://api.datacite.org/dois/10.25820/data.006159 

```
{
  "data": {
    "attributes": {
 "relatedIdentifiers": [
    {
      "relationType": "IsSupplementTo",
      "relatedIdentifier": "10.1089/whr.2021.0105",
      "relatedIdentifierType": "DOI"
    }
  ],
```
