### ISSUE TITLE
Delete prefix 10.34759 and DOIs (Transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1415]
Prefix 10.34759
Repository: SPBPU.MAI
537 DOIs
status: delete

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pot1)

**Comment by codycooperross** [comment]
Prefix 10.34759 has been deleted and the 541 DOIs in SPBPU.MAI have been set to registered.
