### ISSUE TITLE
Remove prefix 10.25587 (transferred to CR)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1417]
Prefix 10.25587 
repository, RADS.NEFU
1,000 DOIs
status: delete prefix and set related DOIs to registered.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pp1x)

**Comment by codycooperross** [comment]
Prefix 10.25587 has been removed and the 1000 DOIs in RADS.NEFU have been set to registered state.
