### ISSUE TITLE
Some ORCIDs are generating an error in Commons and Graph QL

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1418]
#### Expected Behaviour

Searching for an ORCID ID generates a record in DataCite Commons

#### Current Behaviour

For a specific ORCID record an error is generated in Commons and Graph QL

#### Steps to Reproduce

See https://commons.datacite.org/orcid.org/0000-0002-0555-2280

### Context (Environment)

Commons

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ppg5)

**Comment by MaryHirsch** [comment]
another example: https://commons.datacite.org/orcid.org/0000-0002-3478-3221

**Comment by codycooperross** [comment]
This issue is closed by this pull request: https://github.com/datacite/lupo/pull/832 . . . which also closes #1309 #1359
