### ISSUE TITLE
Data center managing their own information

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#142]
As a data center I want to manage information about myself, so I won't have to ask others.

**Comment by pcruse** [comment]
Have we determined what "their own information" a data center will be managing?

**Comment by mfenner** [comment]
I suggest we start with these three:

* data center `name`
* data center `password`
* data center `contact email`

The `symbol` is set by the member, and is also used as username for login. The `name` is something a data center should be able to change. The `password` is automatically generated by the system and emailed to the `contact email`.
