### ISSUE TITLE
Delete prefix 10.25995 (Transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1422]
Prefix 10.25995 
repository, RADS.NIITIAG
147 DOIs
status: delete prefix. set dois to registered state

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pw0l)

**Comment by MaryHirsch** [comment]
set DOIs to registered state.

**Comment by svogt0511** [comment]
Should be done.

**Comment by MaryHirsch** [comment]
@svogt0511 prefix still appears in fabrica https://doi.datacite.org/prefixes?page=NaN&query=10.25995&sort=relevance maybe a reindex needed.

**Comment by MaryHirsch** [comment]
thanks!
