### ISSUE TITLE
Validation of Repository Finder in Commons

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1427]
# DOD: Validation of Repository Finder in Commons

### Development Checklist @jrhoads 
- [x] Feature: Repository Search
  - [x] Scenario: Searching repository/client that exist in datacite API under repository/datacenter/clients
- [x] Feature: Filtering Repository Search Results
  - [x] Scenario: Filtering by Certificates
- [x] Feature: Individual Repository Page
  - [x] Scenario: Repository Exists
- [x] Feature: Goto Repository button
- [x] Feature: Contact Links
  - [x] Scenario: Contacts Exists
  - [x] Scenario: Contacts Do not Exists
- [x] Feature: Repository Metrics Display
  - [x] Scenario: Metrics exist
  - [x] Scenario: Metrics do not exist
- [x] Feature: Dashboard Display
- [x] Feature: Link to related works 
  - [x] Scenario: The repository has related works
- [x] Feature: Advise Message

### Product Engineering Checklist @kjgarza 
- [x] Feature: Repository Search
  - [x] Scenario: Searching repository/client that exist in datacite API under repository/datacenter/clients
- [x] Feature: Filtering Repository Search Results
  - [x] Scenario: Filtering by Certificates
- [x] Feature: Individual Repository Page
  - [x] Scenario: Repository Exists
- [x] Feature: Goto Repository button
- [x] Feature: Contact Links
  - [x] Scenario: Contacts Exists
  - [x] Scenario: Contacts Do not Exists
- [x] Feature: Repository Metrics Display
  - [x] Scenario: Metrics exist
  - [x] Scenario: Metrics do not exist
- [x] Feature: Dashboard Display
- [x] Feature: Link to related works 
  - [x] Scenario: The repository has related works
- [x] Feature: Advise Message

**Comment by kjgarza** [comment]
another set of cosmetics things 
https://app.frontapp.com/open/msg_hc0uw2d

thanks, its going great

**Comment by jrhoads** [comment]
3.1 Scenario: Repository Exists works.
All other cosmetic changes have been addressed.
