### ISSUE TITLE
Remove prefix 10.25633 from DataCite (transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1429]
Prefix 10.25633 
repository, RADS.SPUTNIK
964 DOIs
status: approved

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2q6z9)

**Comment by MaryHirsch** [comment]
please remove the prefix and set the associated DOIs to registered state.

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.25633 has been transferred to Crossref could you delete it and set metadata to registered state. thanks!

**Comment by codycooperross** [comment]
Prefix 10.25633 has been removed from DataCite and its associated metadata has been set to Registered state.
