### ISSUE TITLE
API for Prefix transfer

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#143]
As DataCite Dev, I want an API to make prefix trasnfers and datacentre cleaning

**Comment by kjgarza** [comment]
Not For first Release of the Datacentre API

**Comment by mfenner** [comment]
We should discuss in more detail. E.g. whether a solution involving multiple API calls would be in scope:

* move list of DOIs to new data center
* remove prefix from old data center
* add prefix to new data center
* delete old data center

I think the only API call that is a bit more complex is the first one.
