### ISSUE TITLE
RelatedIdentifiers are limited to 25 in the metadata form 

### ISSUE THREAD

**Issue by ChantelRidsdale** [datacite/datacite#1437]
### Describe the bug
I am developing a Dataset Collection for a researcher, and the Fabrica form limits relatedIdentifiers to 25 DOIs, which doesn't make sense. IF DataCite supports Collections (it's an option in the dropdown menu), why is this limited to 25?

#### Expected Behaviour
Not limited to 25 identifiers

#### Current Behaviour
When a user reaches 25 identifiers, the UI offers to collapse them, no option to continue and add more 

#### Steps to Reproduce
https://doi.datacite.org/dois/10.26152%2Fg315-ph34/edit is the draft record I am working on

To reproduce, you can manually by trying to add more than 25 relatedIdentifiers in the Form
1. Go to Fabrica
2. Click on 'Create Form'
3. Scroll down to 'Recommended Properties' 
4. Select Related Identifiers
5. Try to add more than 25 DOIs
6. Once you reach 25 the UI offers to collapse the list, no option to continue with more

### Context (Environment)
The researcher is trying to publish a journal article and would like a Collection DOI with all related DOIs for datasets he's used, instead of just individually listing them

### Proposal
Please extend the functionality of the related identifiers section, to go beyond 25 for collections. 

#### Possible Implementation
Please extend the functionality of the related identifiers section, to go beyond 25 for collections.

**Comment by kjgarza** [comment]
thanks @ChantelRidsdale 

This is a design decision on the form to maintain usability. Any user needing to add more than 25 relatedIdentifiers can use the file upload or the API.  https://support.datacite.org/docs/fabrica-create-doi-file-upload

**Comment by kjgarza** [comment]
:wave: @ChantelRidsdale, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
