### ISSUE TITLE
Field "Publication year" does not allow year year greater than 2021

### ISSUE THREAD

**Issue by glefebvr1** [datacite/datacite#1438]
### Describe the bug
in Datacite Fabrica,  (API not testes), when entering a new DOI / update it, it is not possible to enter a year greater than 2021 (see image attached).

#### Expected Behaviour
Be able to enter any year in "publication year" field

#### Current Behaviour
See above.

#### Steps to Reproduce
-

### Context (Environment)
Fabrica

### Screenshot
<img width="1255" alt="Capture d’écran 2022-01-24 à 05 18 54" src="https://user-images.githubusercontent.com/12847543/150745939-1917aca1-0526-4040-a2fb-1e4b432df5a5.png">

**Comment by richardhallett** [comment]
Original issue is resolved, long term fix is being done as part of bracco#626
