### ISSUE TITLE
API Explorer example requests return error responses

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/datacite#1444]
### Describe the bug
Using the example requests in the [API Reference](https://support.datacite.org/reference) returns an error message because the generated JSON blob is invalid.

#### Expected Behaviour
The example requests should be valid and return a 20X range HTTP response from the API (when correct authorisation is supplied)

#### Current Behaviour
An HTTP 400 error is returned: "You need to provide a payload following the JSONAPI spec".

#### Steps to Reproduce

1. Go to https://support.datacite.org/reference/post_dois
2. In the Example Code box in the right hand column, click on the Requests dropdown and select Request Example
3. Fill in some valid auth details
4. Submit using the Try It! button and receive the error

#### Hypothesis

The pre-built examples are missing the wrapping `data` key in the JSON body. If you manually construct a response by using the form in the middle column, you can see that the wrapping `data` element is added.

Using the Request Example, missing the `data` key:
![Screenshot 2022-02-08 at 11-06-29 Add a new doi ](https://user-images.githubusercontent.com/93522067/152975667-68760999-9a95-4931-bca3-8ea7df3f00d6.png)

Constructed manually using the form, with the `data` key in place:
![Screenshot 2022-02-08 at 11-08-23 Add a new doi ](https://user-images.githubusercontent.com/93522067/152975768-7ac72f83-e941-46f9-a670-3b84f56ac34c.png)

#### Possible Implementation

This could be an error with how our examples are formatted in the OpenAPI yaml config, or at the Readme.io end in how they parse that file and turn it into the live code demonstration.

**Comment by digitaldogsbody** [comment]
I think this was fixed by @KellyStathis in https://github.com/datacite/lupo/pull/842

**Comment by richardhallett** [comment]
Confirmed now working
