### ISSUE TITLE
Broken link on DataCite Commons page

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1445]
At the bottom of the DataCite Commons interface (https://commons.datacite.org/doi.org), the link for “Metadata search” under "Services" incorrectly directs to the "Governance" page. This link should updated or removed
<img width="661" alt="Screenshot 2022-02-08 at 16 12 45" src="https://user-images.githubusercontent.com/44582654/153028403-d886b2dd-a74d-4049-9aff-313a93d5244e.png">

**Comment by jrhoads** [comment]
Where should that link point?
