### ISSUE TITLE
Cannot edit a contact when logged in as a consortium organization admin.

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1449]
### Describe the bug

When logged in as a consortium organization admin, I can't edit any of the organization's contacts.  When I click on a contact to edit it, I end up at the organization settings page.

#### Expected Behaviour

When I click on a contact, I should end up in the contact details page with the 'update contact' button available.  

#### Current Behaviour

When I click on a contact, I end up in the organization settings page.

#### Steps to Reproduce

1. In the test environment, log in with username OKHB for that consortium organization.
2. Go to the settings page for the consortium organization ['OHKB'](https://doi.test.datacite.org/providers/ohkb)
2. Click  on the 'contacts' tab.
3. Scroll down and click on any contact.  
4. You should end up on the contact details page with the 'update contact' button available.  Instead, you end up on the organization [settings page](https://doi.test.datacite.org/providers/ohkb).

This is reproducible from any consortium organization when logged in the admin for that organization.

A workaround is to right click on the contact, copy the link, go to that link in a new browser tab.  You will end up on the contact edit page.

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2redx)

**Comment by errortryagain** [comment]
Hi,
Unfortunately, the workaround no longer works for me as consortium lead. Hence, now neither the consortium member nor we can edit/delete any contacts on Fabrica anymore.
