### ISSUE TITLE
Audit Projects for  Software support End of Life (EOL)

### ISSUE THREAD

**Issue by jrhoads** [datacite/datacite#1450]
We should go through our projects to determine if language (ruby, node, python), frameworks (Rails, Django, Flask), or containers are soon to reach, or have reached, end of life (EOL) as far as security updates.

A resource for this is https://endoflife.date/

Specifically there are a few coming up with

- ruby 2.6 reaching EOL in March (31 March 2022)
- nodejs 12 reaching EOL in April (30 Apr 2022)
- rails 5.2 reaching EOL in June (01 Jun 2022), 

We can then have further discussions about if, how and when to upgrade the projects, or whether they should be retired.

**Comment by digitaldogsbody** [comment]
The last Ember 3 LTS release (3.28) is EOL in January 2023

**Comment by digitaldogsbody** [comment]
Not stale

**Comment by richardhallett** [comment]
Lots of upgrades happened in 2024 yay!
