### ISSUE TITLE
Incorrect total number of DOIs under a specific consortium account 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1458]
#### Expected Behaviour

Total DOIs on consortium lead dashboard reflects total of each consortium organization

#### Current Behaviour

The total in Fabrica and API is incorrect for a consortium account ID: VIENNACO

#### Steps to Reproduce

https://doi.datacite.org/providers/viennaco/dois the number of DOIs shown here is 349

The api also only counts 339 https://api.datacite.org/dois?consortium-id=viennaco

The total should be more like 46K

### Context (Environment)

Production

**Comment by svogt0511** [comment]
Closing this.  @richardhallett was right, the dois needed to be reindexed in ElasticSearch. Should be ok now.

**Comment by svogt0511** [comment]
Re-opening.  There is still an issue.

**Comment by svogt0511** [comment]
Re-indexed again.  Matches what is in the database now.
