### ISSUE TITLE
Certain characters do not render correctly in Fabrica and Commons

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1459]
#### Expected Behaviour

Character and symbols can be displayed in the metadata in Fabrica and Commons

#### Current Behaviour

Certain characters do not render correctly in Fabrica and Commons

#### Steps to Reproduce

Displaying correctly:
[Search.datacite.org](http://search.datacite.org/): https://search.datacite.org/works?query=10.15120%2Fgr-2014-1-nqm-cbm-35
Notes: none.

Displaying incorrectly:
https://doi.datacite.org/repositories/tib.gsi/dois?client-id=tib.gsi&page=NaN&query=testing%20of&sort=relevance

### Context (Environment)

Production

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2sgd1)

**Comment by jrhoads** [comment]
Can you give an example in commons?

**Comment by MaryHirsch** [comment]
https://commons.datacite.org/doi.org?query=10.15120%2Fgr-2014-1-nqm-cbm-35

**Comment by kjgarza** [comment]
closing as it will be handle as described in https://github.com/datacite/bracco/issues/86
