### ISSUE TITLE
Salesforce Sync Repositories

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#1461]
Repository information did not sync properly. Please see error messages in the #ops Slack channel on Friday, March 25th.

### Describe the bug
The sync attempts to send Fabrica repository data e.g. number of registered DOIs to Salesforce and is unable to obtain exclusive access to the Salesforce record. The error code: UNABLE_TO_LOCK_ROW

#### Expected Behaviour
Data to be transferred from Fabrica to Salesforce. 

#### Current Behaviour
Data is transferred from Fabrica to Salesforce.

#### Steps to Reproduce
The sync is working properly now (03/28). Error messages in #ops (Friday, March 25th): The CDL repositories have been deleted and no longer exist in Fabrica nor Salesforce. The TIB, MTAKIK and RADS repositories are active and correctly displayed in Fabrica and Salesforce. The repository TIB.UBTDOIS in Fabrica: https://doi.datacite.org/repositories/tib.ubtdois and in Salesforce: 
https://datacite.lightning.force.com/lightning/r/Repositories__c/a1D1U000002oT9wUAE/view.

**Comment by brittadreyer** [comment]
Today the error described affected several RADS repositories. Please see #ops channel.

**Comment by svogt0511** [comment]
Unfortunately we are using the salesforce rest api.  I am reading that you can only use the locking mentioned from within Apex code, not from the Salesforce Rest API.  Looking for an alternative.

**Comment by svogt0511** [comment]
Just a quick update.  I am still looking into this.  It appears that there are collisions where some other process is updating a particular salesforce record when we run the sync job and so we get this error.  The 'FOR UPDATE' solution, above is only useful from Apex code.  I have read that the Salesforce REST API tries to lock records for update and returns this error if it has waited the prescribed period of time and the lock hasn't been released by the other process.  I am trying to find out a little more about what is going on and will add updates as I go.

**Comment by svogt0511** [comment]
I turned on logging in Salesforce so we can hopefully get some information about the record locking.  I have not been able to find a setting (yet) that would allow us to tell the API to wait a little longer before giving up on waiting for a locked record.  

Nothing to do with the record locking issue, but I noticed that the sync job timed out once this week while syncing the repositories.  I maxed out the AWS lambda function timeout, so hopefully we will see no timeouts for a while.  I just wanted to note that as that is another potential issue.

**Comment by svogt0511** [comment]
[Salesforce documentation](https://developer.salesforce.com/docs/atlas.en-us.draes.meta/draes/draes_object_relationships_record_level_locking.htm) states that the when a child record is being updated, Salesforce locks the parent record as well as child record. The organization and repository records in Salesforce have this relationship, so when updating a repository, the organization record is locked as well as the repository record.  

Looking at the Salesforce 'UNABLE_TO_LOCK_ROW' error messages in #ops, the record identifier in the error message is that of the organization record. Salesforce is attempting to lock the organization record as well as the repository record.

Given the number of organizations that have multiple repositories and the short period of time where update requests are submitted, it is very possible to see this kind of concurrency problem.  

The screen grab, below, seems to illustrate this pattern.  There are 2 error messages showing Salesforce trying to lock the same organization record during update of that organization's repositories.  A more general look at other error messages seems to support this pattern.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/4681304/167528173-ef1830ab-dfc6-46cc-91cd-97a572033d30.png">

A workaround recommended by Salesforce ([here](https://developer.salesforce.com/docs/atlas.en-us.draes.meta/draes/draes_object_relationships_record_level_locking.htm)) is to add retry logic to the integration code.  We can do that in our Salesforce API integration by checking for this error and retrying the call a limited number of times.

**Comment by svogt0511** [comment]
Just re-opening until we are sure this works.

**Comment by svogt0511** [comment]
Closing.  Seems to be working. Can re-open if necessary.
