### ISSUE TITLE
Citation counts sometimes display incorrectly for References and Citations in Commons

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1464]
### Describe the bug
The citation count corresponding to a given Reference or Citation, as shown here, is not consistent:
![Screen Shot 2022-04-14 at 5 52 43 PM](https://user-images.githubusercontent.com/17298577/163502941-081225f2-c5d3-47ce-a905-569acf5172eb.png)

#### Expected Behaviour
The citation count should be 5 citations for this DOI: 10.1117/12.2293584 when viewed from this Commons page: https://commons.datacite.org/doi.org/10.7302/z23r0r29

#### Current Behaviour
It initially displays as 2 citations, but after clicking through to the reference/citation DOI (where it shows 5 citations) and then returning to the original DOI, it changes to 5 citations.

#### Steps to Reproduce
See Loom video: https://loom.com/share/2d9fd79f96104e1abcf1a9dcdf7f508d

1. Go to https://commons.datacite.org/doi.org/10.7302/z23r0r29
2. Scroll down to the 1 Reference and click "Retinal fundus images for glaucoma analysis: the RIGA dataset" - leads to https://commons.datacite.org/doi.org/10.1117/12.2293584
3. On that page, click "5 Citations"
4. Click  "Retinal fundus images for glaucoma analysis: the RIGA dataset" to return to the original record (https://commons.datacite.org/doi.org/10.7302/z23r0r29)

**Comment by digitaldogsbody** [comment]
This appears to be an indexing issue (like #1490) - the DOI in question has a citation_count of 2 in ElasticSearch, but 5 when queried via graphql.

Citation count is derived from the number of unique DOIs appearing in the citation_events relationship of the DOI model:
https://github.com/datacite/lupo/blob/master/app/models/doi.rb#L1382-L1384

I will reindex this individual DOI - and we should look at a way of systematically finding other DOIs where this is an issue and doing a data cleanup.

**Comment by digitaldogsbody** [comment]
DOI now reindexed and the citation count is correct on first load
