### ISSUE TITLE
Submitting XML metadata via the API does not allow for suffix generation without placeholder DOI

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1489]
### Describe the bug
Following the instructions [here](https://support.datacite.org/docs/is-it-possible-to-auto-generate-a-doi-via-the-rest-api) to have DataCite randomly generate a suffix, it is unclear what to do with the <identifier> field when providing XML. When I tried various combinations, the only one that worked was providing an arbitrary suffix.

#### Expected Behaviour
I would expect that in order to have DataCite randomly generate the suffix, the identifier field in the XML should be either blank or include only the prefix. For example:

`<identifier identifierType="DOI"></identifier>`
`<identifier identifierType="DOI">10.82247/</identifier>`

I would not expect that I have to provide an arbitrary suffix in order to generate a random suffix.

#### Current Behaviour
Using either of the above returns a 404 error. However, **including an arbitrary suffix triggers a randomly generated suffix.** 

I can create a test DOI with `<identifier identifierType="DOI">10.82247/abc</identifier>` in the XML, specifying only the prefix in the "attributes", and it creates a DOI with a randomly generated suffix - not /abc.

#### Steps to Reproduce

 **1. Example with arbitrary suffix that generates a random suffix**

This request generated this test DOI: https://doi.test.datacite.org/dois/10.82247%2F17b2-bm05.

*XML:*

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource
    xmlns="http://datacite.org/schema/kernel-4"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
    <identifier identifierType="DOI">10.82247/abc</identifier>
    <creators>
        <creator>
            <creatorName nameType="Organizational">DataCite</creatorName>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Test title</title>
    </titles>
    <publisher>Test publisher</publisher>
    <publicationYear>2022</publicationYear>
    <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
    <language>eng</language>
    <version>v1</version>
    <descriptions>
        <description descriptionType="Abstract" xml:lang="en">Test description</description>
    </descriptions>
</resource>
```

*Request:*
```
curl --request POST \
    --url https://api.test.datacite.org/dois \
    --header 'Authorization: Basic [redacted]' \
    --header 'Content-Type: application/vnd.api+json' \
    --data '
{
    "data": {
         "attributes": {
              "prefix": "10.82247",
              "url": "https://datacite.org",
              "xml": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8cmVzb3VyY2UKICAgIHhtbG5zPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtNCIKICAgIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhzaTpzY2hlbWFMb2NhdGlvbj0iaHR0cDovL2RhdGFjaXRlLm9yZy9zY2hlbWEva2VybmVsLTQgaHR0cHM6Ly9zY2hlbWEuZGF0YWNpdGUub3JnL21ldGEva2VybmVsLTQuMy9tZXRhZGF0YS54c2QiPgogICAgPGlkZW50aWZpZXIgaWRlbnRpZmllclR5cGU9IkRPSSI+MTAuODIyNDcvYWJjPC9pZGVudGlmaWVyPgogICAgPGNyZWF0b3JzPgogICAgICAgIDxjcmVhdG9yPgogICAgICAgICAgICA8Y3JlYXRvck5hbWUgbmFtZVR5cGU9Ik9yZ2FuaXphdGlvbmFsIj5EYXRhQ2l0ZTwvY3JlYXRvck5hbWU+CiAgICAgICAgPC9jcmVhdG9yPgogICAgPC9jcmVhdG9ycz4KICAgIDx0aXRsZXM+CiAgICAgICAgPHRpdGxlIHhtbDpsYW5nPSJlbiI+VGVzdCB0aXRsZTwvdGl0bGU+CiAgICA8L3RpdGxlcz4KICAgIDxwdWJsaXNoZXI+VGVzdCBwdWJsaXNoZXI8L3B1Ymxpc2hlcj4KICAgIDxwdWJsaWNhdGlvblllYXI+MjAyMjwvcHVibGljYXRpb25ZZWFyPgogICAgPHJlc291cmNlVHlwZSByZXNvdXJjZVR5cGVHZW5lcmFsPSJEYXRhc2V0Ij5EYXRhc2V0PC9yZXNvdXJjZVR5cGU+CiAgICA8bGFuZ3VhZ2U+ZW5nPC9sYW5ndWFnZT4KICAgIDx2ZXJzaW9uPnYxPC92ZXJzaW9uPgogICAgPGRlc2NyaXB0aW9ucz4KICAgICAgICA8ZGVzY3JpcHRpb24gZGVzY3JpcHRpb25UeXBlPSJBYnN0cmFjdCIgeG1sOmxhbmc9ImVuIj5UZXN0IGRlc2NyaXB0aW9uPC9kZXNjcmlwdGlvbj4KICAgIDwvZGVzY3JpcHRpb25zPgo8L3Jlc291cmNlPg=="
         },
        "type": "dois"
    }
}
'
```

**2. Examples that return a 404:**

*XML*:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource
    xmlns="http://datacite.org/schema/kernel-4"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
    <identifier identifierType="DOI">10.82247</identifier>
    <creators>
        <creator>
            <creatorName nameType="Organizational">DataCite</creatorName>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Test title</title>
    </titles>
    <publisher>Test publisher</publisher>
    <publicationYear>2022</publicationYear>
    <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
    <language>eng</language>
    <version>v1</version>
    <descriptions>
        <description descriptionType="Abstract" xml:lang="en">Test description</description>
    </descriptions>
</resource>
```

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource
    xmlns="http://datacite.org/schema/kernel-4"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
    <identifier identifierType="DOI"></identifier>
    <creators>
        <creator>
            <creatorName nameType="Organizational">DataCite</creatorName>
        </creator>
    </creators>
    <titles>
        <title xml:lang="en">Test title</title>
    </titles>
    <publisher>Test publisher</publisher>
    <publicationYear>2022</publicationYear>
    <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
    <language>eng</language>
    <version>v1</version>
    <descriptions>
        <description descriptionType="Abstract" xml:lang="en">Test description</description>
    </descriptions>
</resource>
```

### Context (Environment)
We received a support request where a member was trying to auto-generate a suffix and provide XML metadata via the API. The only solution that worked was providing an arbitrary suffix, which is inconsistent with how the API works for JSON metadata.

The requirement to provide an arbitrary suffix is not in our documentation anywhere, so if this is expected behaviour, we should make this clear.

#### Screenshots
n/a

#### Further details
When providing XML in Fabrica, the "doi" attribute is provided in the payload because the suffix is randomly generated in the interface. Therefore, the above XML examples work correctly.

#### Hypothesis
n/a 

#### Possible Implementation
n/a

**Comment by richardhallett** [comment]
This is working as expected, it is not possibly to generate random DOI by only supplying the prefix in the XML.

The XML must always have a valid identifier, a prefix alone is not valid identifier.

However the REST API does support replacing this when you specify the prefix as an attribute via the JSON, this effectively then overwrites whatever has been put in the XML identifier field with the randomly generated prefix/suffix combination.
Which is why your first example works and this would be how I'd tell the member to do this.

**Comment by KellyStathis** [comment]
Hi @richardhallett, apologies for missing your reply earlier!

I understand that the XML must have a valid identifier for it to be _published_. But if we are replacing it with the auto-generated DOI anyway, why does that validation check happen before it is replaced?
