### ISSUE TITLE
403 Forbidden responses for Content Negotiation requests

### ISSUE THREAD

**Issue by mpaluch** [datacite/datacite#1491]
Hello,

Yesterday we ran some batches of content negotiation requests against DataCite DOIs to retrieve formatted citation and Citeproc JSON data. During the runs we received a 403 Forbidden response for over half of the requests, 801 out of about 1,300. This only happened for DataCite DOIs.

The response headers for the failed requests show that they seem to be coming from an AWS server.

statusCode = "403", headers = "{null=[HTTP/1.1 403 Forbidden], Server=[**awselb/2.0**], Connection=[keep-alive], Content-Length=[118], Date=[Mon, 09 May 2022 11:58:44 GMT], Content-Type=[text/html]}"

Typical request batch that we send for each DOI:
GET "Accept: text/x-bibliography; style=chicago-fullnote-bibliography; locale=fr-CA" https://doi.org/10.4224/crm.2018.aphe-1
GET "Accept: text/x-bibliography; style=chicago-fullnote-bibliography; locale=en-GB" https://doi.org/10.4224/crm.2018.aphe-1
GET "Accept: application/vnd.citationstyles.csl+json" https://doi.org/10.4224/crm.2018.aphe-1

Each batch of requests started off fine but then at some point we only start seeing 403 responses until the end of the run. The full request event log is attached. First error timestamp is **2022-05-09 07:56:42,778**.

[content_neg_errors_20220509.csv](https://github.com/datacite/datacite/files/8662618/content_neg_errors_20220509.csv)

Could this possibly be related to [this issue](https://github.com/datacite/datacite/issues/1426#issuecomment-1083407735)? Or is there a problem with the requests themselves?

**Comment by mpaluch** [comment]
We have run into these errors for three straight days this week.

2022-05-19:   60 errors between 12:09 and 12:13 EDT.
2022-05-18: 101 errors between 11:20 and 12:04 EDT.
2022-05-17: 100 errors between 15:55 and 16:02 EDT.

**Comment by codycooperross** [comment]
The issue is related not to the requests themselves but rather to a firewall rate limit for the Content Negotiation service. The rate limit has been increased to 1000 requests per five minutes, which is now documented on the [DataCite Support site](https://support.datacite.org/docs/is-there-a-rate-limit-for-making-requests-against-the-datacite-apis).
