### ISSUE TITLE
Filter by "Author" in DataCite Commons not working

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1499]
#### Expected Behaviour

Selecting an Author from the facet filters the results

#### Current Behaviour

The results are not filtered

#### Steps to Reproduce

1. Go to Commons
2. Search "Bragança"
3. In the Author facet and select:
Bragança, Gustavo 29
4. Nothing happens

https://commons.datacite.org/doi.org?query=Bragan%C3%A7a&filterQuery=creators.nameIdentifiers.nameIdentifier%3A%22https%3A%2F%2Forcid.org%2F0000-0002-5682-1508%22 

### Context (Environment)

Commons

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2vetx)

**Comment by kjgarza** [comment]
this only happens in the `https://commons.datacite.org/doi.org` path

**Comment by KellyStathis** [comment]
I just encountered this bug as well, I was trying to filter for my own works: https://commons.datacite.org/doi.org?query=stathis&filterQuery=creators.nameIdentifiers.nameIdentifier%3A%22https%3A%2F%2Forcid.org%2F0000-0001-6133-4045%22
