### ISSUE TITLE
cc-by license not pickup up from Yoda metadata

### ISSUE THREAD

**Issue by Danny-dK** [datacite/datacite#1501]
### Describe the bug
This work https://commons.datacite.org/doi.org/10.24416/uu01-clv1f1 leading to this doi landing page https://public.yoda.uu.nl/dgk/UU01/CLV1F1.html has the licence CC-by (Creative Commons Attribution 4.0 International Public License (https://creativecommons.org/licenses/by/4.0/legalcode). When searching for this work and selecting the filter cc-by on the left hand side of the page, it doesn't show up (https://commons.datacite.org/doi.org?query=Serra+Bragan%C3%A7a&license=cc-by-4.0). The work is findable when filtering only on language (https://commons.datacite.org/doi.org?query=Serra+Bragan%C3%A7a&language=en).

#### Expected Behaviour
Detect the correct license from the metadata from the repository Yoda.

#### Steps to Reproduce
- Go to commons.datacite.org.
- In the works section, search for (including the squiggly c): Serra Bragança
- In the left hand side of the window, select the filter option cc-by.

#### Further details
Done on Firefox (101.0.1 x64) and Chrome (102.0.5005.115 x64).

**Comment by kjgarza** [comment]
license metadata has not been sent to datacite  https://api.datacite.org/dois/10.24416/uu01-clv1f1

**Comment by lwesterhof** [comment]
Yes, currently the Access Level (https://guidelines.openaire.eu/en/latest/literature/field_accesslevel.html) is sent to DataCite in the rights field instead of the license URI. This will be resolved in a future release.
