### ISSUE TITLE
[Bibliometricians Access] Usage Stats Processing as a Service (RH)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1506]
<p></p>

# **User Stories**

<p></p>

- As a bibliometrician, I would like the collected usage stats were available via the Datacite GraphQL API to run my data analysis in Jupyter notebooks and scripts.

-  As a bibliometrician, I would like the processing service to process usage according to the COUNTER code of practice, So I can compare usage stats from using this method with other usage stats collected from other methods (SUSHI reports).

- As a repository admin, I would like the collected usage stats to be available via the REST API, GraphQL, and data metrics badge, So that my usage stats can be distributed to the web.

- As a repository admin, I would like the collected usage stats to be available as SUSHI Reports (JSON) in the DataCite API (/reports) So that we can audit the monthly usage stats if we need it to do it.

-  As a repository admin, I would like to have access to a tracker code directly from Fabrica, So I don't have to go to any other place to configure my usage stats processing.

-  As a repository admin, I would like to enable and configure the usage tracking directly from Fabrica, So I don't have to go to any other place to configure my usage stats processing.

<p></p>

<p></p>

 Product Spec: <https://docs.google.com/document/d/13ms8mBtf6kdp15JZRp36CAVa_yqjU9LJfZzVNTtumF8/edit#heading=h.gfpb58ica065>

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/8671828

**Comment by richardhallett** [comment]
December 2022 Update
The epic has been reassessed to focus on the most important aspects, which is generating COUNTER usage reports for sending to our usage reports service, this enables the data to be available in various places where we consume/show usage statistics i.e. api, commons

This is an entirely new service that will be launched and will then be tied into existing services.

**Comment by richardhallett** [comment]
Closing as this is launched and in production.
