### ISSUE TITLE
Works with Contributors with ORCID IDs aren't showing up on the corresponding People pages

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1507]
#### Expected Behaviour

If a Contributor with an ORCID ID is added to a DOI, that work should show up on the contributor's person page.

#### Current Behaviour

The work does not show up on the contributor's page.

#### Steps to Reproduce

I added myself as a Contributor on Mike's blog post and included my ORCID: https://doi.org/10.5438/cq8g-b226
```
<contributor contributorType="Other">
    <contributorName nameType="Personal">Stathis, Kelly</contributorName>
    <givenName>Kelly</givenName>
    <familyName>Stathis</familyName>
    <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org">https://orcid.org/0000-0001-6133-4045/</nameIdentifier>
    <affiliation/>
</contributor>
```
It does not show up on this page: https://commons.datacite.org/orcid.org/0000-0001-6133-4045?orcid=0000-0001-6133-4045&published=2021

Another real example is this work: https://commons.datacite.org/doi.org/10.48321/d17p5x which does not show up in the Works on this page: https://commons.datacite.org/orcid.org/0000-0003-3585-6733?orcid=0000-0003-3585-6733&published=2022

#### Screenshots

n/a

#### Further details

This is different from how Organizations are processed. When a Contributor is added to a work and includes a ROR ID in the nameIdentifier field, the work shows up on the Organization's Commons page. Cody described this in Slack (message from May 27th in #support):

> My understanding from the query in the [Organization type](https://github.com/datacite/lupo/blob/1a3a071b95bf53fc996f0927b89ed03a19f154e9/app/graphql/types/organization_type.rb#L350) and the generated ElasticSearch query in the [Doi model](https://github.com/datacite/lupo/blob/1a3a071b95bf53fc996f0927b89ed03a19f154e9/app/models/doi.rb#L947) is that the following DOI ElasticSearch fields are searched when an Organization is pulled up in Commons. (These look a little different than API field queries because they include the full ElasticSearch record.)
> - affiliation_id
>   - This is [a list of all ROR affiliation identifiers in the creators and contributors fields in the metadata](https://github.com/datacite/lupo/blob/1a3a071b95bf53fc996f0927b89ed03a19f154e9/app/models/doi.rb#L1717).
> - creators.nameIdentifiers.nameIdentifier
> - contributors.nameIdentifiers.nameIdentifier
> - provider.ror_id
>   - This is the ROR ID entered in Fabrica.
> - funding_references.funderIdentifier

>  So I think these two should technically appear in the Organization profile list:
> - Creator or Contributor nameIdentifier = ROR ID of organization
> - Contributor affiliationIdentifier = ROR ID of organization

It would follow that if organizational contributors cause the work to show up on the organization's page, individual contributors should cause the work to show up on the person's page. However, I did not verify this and it appears not to be the case currently. Given the behaviour for organizations, I do not think this is expected behaviour.

#### Hypothesis

The underlying GraphQL query to fetch a person's works may not be looking at Contributor metadata.

#### Possible Implementation

n/a

**Comment by kjgarza** [comment]
Showing works in which the profile owner is not an author is not a use case supported in commons. 
The works section use case is to display works in which the profile is an author.

**Comment by KellyStathis** [comment]
We show works in which the *organization* is a contributor on the organization page. Given this, it is reasonable to expect that we would show works in which the *person* is a contributor on the person's (profile) page. Is there a reason we do not intend to support the analogous use case here?

**Comment by kjgarza** [comment]
@KellyStathis I just want to clarify that it is not a bug, and the current behavior is expected. 

There is a significant history of the purpose of each page. The profiles pages were meant to show authorship. You can see that when claiming an ORCID, you can only claim it as an Author, not as a contributor.

On the other hand, the Organisation pages are not about authorship but about the relationship with the Organisation and are more open about the inclusion criteria. 

Two different pages, two different purposes. 

And @digitaldogsbody said changing that behavior would fit more a feature. If you feel like there is a strong use case for that, please feel free to forward this to product-board. If you label it as "to_productboard" it will be automatically forwarded ;)

**Comment by kjgarza** [comment]
:wave: @KellyStathis, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .

**Comment by KellyStathis** [comment]
@kjgarza Thanks for explaining more of the thinking behind the pages. I do think that from the user's perspective, this is going to be perceived an inconsistency so it is important to consider as a new feature / feature change—so I've sent it to product board. I'm also happy to seek additional input on this.
