### ISSUE TITLE
Rails Upgrade 6.1 - Lupo

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1509]
Upgrade to Rails 6.1 (this is not latest version) because our current version is now no longer supported officially.
This issue is to track overall status and make any comments/plans for how to deploy.

**Comment by richardhallett** [comment]
Release schedule:
1. Monday 8th - Staging deploy
2. Wednesday 10th - Production and Test Deploy
3. Feature freeze on Lupo until Week commencing 15th.

Deployment:
1. Merge PR into main branch
2. Tag release starting at major release 5.x
3. Check AWS has deployed all containers successfully.
4. Production - Go onto deployed container **client-api.local** - run the database migrations
**Check rails -v matches 6**
5. Test - Go onto deployed container **client-api.test.local** - run the database migrations

Rollback:

1. Unmigrate first on the container
2. Then github deploy previous tag.

Testing:

1. Everyone to check API endpoints
2. Check fabrica integration cypress tests pass
3. Test basic Fabrica functionality 
- Create a DOI file upload, 
- Create a DOI form
- Create a new repository, update repository.

**Comment by digitaldogsbody** [comment]
Reopening because we need to test/validate and so the auto-close from PR by Github was premature

**Comment by digitaldogsbody** [comment]
Rails6 deploy to staging went well - rails seemed not to complain before the migrations were run, perhaps because they are just character set changes. Deployment to Test/Prod going ahead as scheduled on Wednesday.

**Comment by digitaldogsbody** [comment]
Deployment of Rails 6.1 version of Lupo to Test & Production instances is now complete :tada:
