### ISSUE TITLE
Fabrica Improvements - Feature 2: Home Landing Page

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1513]
This feature has 1 scenario with:

- A logged in user will be directed to the 'info tab'. 
- The info tab will display the user role as described in the product spec.

TASKS:

- [x] Exchange the page definitions for the settings and info tabs, making the info tab the new ‘index’ page.
- [x] Add the user role to the new index page.
- [x] Correct any relevant tests.

**Comment by bklaing2** [comment]
I have finished this, and set up a meeting with Kristian to make sure the changes look good
