### ISSUE TITLE
Fabrica Improvements - Feature 3: New Navigation Bar

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1514]
This feature has 3 scenarios with that basically change the look of the header/nav bar:
- User is repository-admin or staff-admin - should see the new Fabrica logo on every page instead of the "DataCite Fabrica" title.
- User is consortium-admin - should see the new Fabrica logo on every page instead of the "DataCite Fabrica" title.  The upper right nav bar should have a Primary dark blue background color.
- User is consortium-organization or direct member admin - uld see the new Fabrica logo on every page instead of the "DataCite Fabrica" title.  The upper right nav bar should have a Primary light blue background color.

TASKS:

- [x] Deposit new log into assets.datacite.org.  Link to logo file in application.hbs component.
- [x] Style navbar - appropriate background color given user role, and rounded corners. (application.hbs and assets.datacite.org/stylesheets/doi.css)
- [x] Add a test for this to check the for the logo and appropriate color background for the navbar.

Questions:
- How are the minimized css files in assets.datacite.org generated?

**Comment by bklaing2** [comment]
I have finished development for this. I'll set up a meeting with Suzanne to go over it

**Comment by bklaing2** [comment]
Demo build that includes these changes: https://bracco-q6plu92bu-datacite.vercel.app/
