### ISSUE TITLE
Fabrica Improvements - Feature 10: Add Terms to Controlled Vocabularies

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1521]
This feature has 2 scenarios:

- Adding/editing a repository, 'Software' option - add new options as listed in the product spec.
- Adding/updating member organization, 'Member Type' option - add new options as listed in the product spec.
- Lupo requirements: make sure that Lupo does not reject the new options.

TASKS:

- [x] Add new software types to ‘const softwareList’ declared in each of these files: app/components/repository-show.js, app/controllers/providers/show/repositories/new.js, app/controllers/repositories/show/edit.js.  The same constant software list is enumerated in all of these files.  We might want to change that to one place where the same list is enumerated.
- [x] Add a new organization type to const organizationTypeList in files app/controllers/providers/new.js, app/controllers/providers/show/edit.js, and app/controllers/providers/organizations/new.js.  We might want to centralize this list similar to the softwareTypesList, above.
- [x] Add tests or alter existing tests in the test suite appropriately.

**Comment by codycooperross** [comment]
Closed by datacite/bracco#668
