### ISSUE TITLE
Send usage stats to Event Data Bus

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#153]
- from: https://github.com/CDLUC3/Make-Data-Count/issues/116

Add usage stats reporting to https://github.com/datacite/toccatore, which is our service to send events to Event Data Bus.

Parent datacite/toccatore#2, datacite/sashimi#14, datacite/mastino#13, datacite/sashimi#16

**Comment by kjgarza** [comment]
parent of datacite/toccatore#2, datacite/sashimi#14,atacite/mastino#13, datacite/sashimi#16
