### ISSUE TITLE
Upgrade services to Terraform 1.x

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/datacite#1559]
Upgrade mastino to use Terraform 1.x

Going from 0.x -> 1.0: https://www.terraform.io/language/upgrade-guides/1-0
1.0 -> 1.1: https://www.terraform.io/language/upgrade-guides/1-1
1.1 -> 1.2: https://www.terraform.io/language/upgrade-guides/1-2
1.2 -> 1.3 https://developer.hashicorp.com/terraform/language/upgrade-guides
_Note you may want to do stage/production services in pairs as large part of their configuration changes will most likely be the same._

**Comment by richardhallett** [comment]
In an effort to simplify our terraform setup and also reduce the burden for upgrading, I've started work on a new module based setup, this helps us reduce a lot of redundant configuration that is essentially the same per service and environment.

PR for reference on how this might work: https://github.com/datacite/mastino/pull/158

There still however may need to be individual version upgrades of existing workspaces as they have state associated with them, this will be to avoid any service interuption as moving.

**Comment by richardhallett** [comment]
Slightly changed thoughts on how best to use modules, detailed notes can be found here:
https://github.com/datacite/datacite/issues/1956
And then reusing this epic to contain phase 2 of upgrade plan, migrating all individual services.

**Comment by richardhallett** [comment]
All services across prod/stage/test are now upgraded to 1.6 terraform
Where possibly I removed and tidied unused workspaces and configurations.
Further refactoring is still required but this allows us to refactor easier.

As a reminder this is part of various epics, next on list will be datacite/datacite#1962 which are the service configuration files, these need care and thought as some are very out of date and not in sync with AWS.
