### ISSUE TITLE
Evaluate single-sign on options

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#157]
The single-sign on via GitHub, Google and Facebook is rarely used. We should evaluate what we want to keep, and whether to consider other options (e.g. Twitter, username/password) for single-sign on.

#### DEV NOTES

* as of June 24, we have user accounts at https://profiles.datacite.org
* 100% have ORCID ID, since it is required
* 406 have Facebook ID
* 1158 have Google ID
* 127 have GitHub username
* 1414 have email address (via Google or Facebook)

**Comment by mfenner** [comment]
<img width="593" alt="bildschirmfoto 2017-07-02 um 11 26 39" src="https://user-images.githubusercontent.com/23151/27768676-6384a7aa-5f19-11e7-97f2-5b48abe127b5.png">

**Comment by mfenner** [comment]
<img width="665" alt="bildschirmfoto 2017-07-12 um 11 17 42" src="https://user-images.githubusercontent.com/23151/28110898-084cf472-66f4-11e7-9c9e-8f4c2f437b57.png">

**Comment by mfenner** [comment]
<img width="573" alt="bildschirmfoto 2017-07-12 um 11 17 58" src="https://user-images.githubusercontent.com/23151/28110946-28a50246-66f4-11e7-9043-25d9c57ba260.png">

**Comment by mfenner** [comment]
<img width="646" alt="bildschirmfoto 2017-07-12 um 11 18 10" src="https://user-images.githubusercontent.com/23151/28110963-34e208ec-66f4-11e7-9d37-31ac61ffb264.png">

**Comment by mfenner** [comment]
Decided to drop Facebook and add email login.

**Comment by kjgarza** [comment]
![ids.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46e1908961cec1b99de6b546a749b2ce6b137e212c5df77d29d5b079be4328515f5c1baa120b5f45a9eb9539e4e76224d50152a7842f4d7ed43e10a6b9871fbe04ba218f4d87b3b58d5e8d.png)
