### ISSUE TITLE
Transfer subset of DOIs from USGS.PROD to USNPS.USNPS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1571]
Old repository ID: USGS.PROD
New repository ID: USNPS.USNPS
Number of DOIs: 646 DOIs 
List to be transferred: [nps_full_doi_list.csv](https://github.com/datacite/datacite/files/9478403/nps_full_doi_list.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2yez9)

**Comment by codycooperross** [comment]
The listed 646 DOIs have been transferred from USGS.PROD to USNPS.USNPS.
