### ISSUE TITLE
Transfer subset of 115 DOIs to OIBK.OHYCFA

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1572]
Old Repository ID: JALC.JALC
New Repository ID: OIBK.OHYCFA
Prefix: [10.34968](https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.34968)
Number of DOIs to be transferred: 115
[NIMS DOI LIST to transfer.csv](https://github.com/datacite/datacite/files/9504376/NIMS.DOI.LIST.to.transfer.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ygk5)

**Comment by codycooperross** [comment]
The transfer of the 115 listed DOIs and the prefix 10.34968 from JALC.JALC to OIBK.OHYCFA is complete.
