### ISSUE TITLE
Opening a repository record generates an error in Commons

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1579]
#### Expected Behaviour

Clicking a repository record in the list displays the full record

#### Current Behaviour

Clicking on repository NAKALA generates an error in Commons

#### Steps to Reproduce

1. Search "NAKALA"
2. Click on the record https://commons.datacite.org/repositories/x3oc821
3. an error is generated

<img width="1410" alt="Screenshot 2022-09-29 at 13 21 14" src="https://user-images.githubusercontent.com/44582654/193029964-89f598da-3f95-45d5-b447-4620176baee8.png">

### Context (Environment)

Commons

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2z5hx)

**Comment by codycooperross** [comment]
This appears to be an issue with author aggs in the GraphQL response. Likely identical to: https://github.com/datacite/lupo/issues/847#issuecomment-1213120377

**Comment by codycooperross** [comment]
This appears to be fixed for https://commons.datacite.org/repositories/x3oc821
