### ISSUE TITLE
Communications of Full support for metadata schema 4.4 (MB)

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1581]
ToDo

- [ ] Documentation
- [ ] Blogpost/Announcement

Phase 2 Spec: <https://docs.google.com/document/d/1IrJDVJGYQBfeBpNugq0kZ-h24azrCtYeytpK_cS-vT8/edit#>

Key points:

<p></p>

- All DataCite APIs will support **full** metadata schema version 4.4

- Fabrica interface will support further selected changes from metadata schema version 4.4.

<p></p>

**SP3: Supporting community use cases with a focus on metadata**

**Comment by digitaldogsbody** [comment]
Duplicate of #1367

**Comment by paulvierkant** [comment]
Blog post is published and will be mentioned in the January Newsletter.
