### ISSUE TITLE
Event data API occurred-at updates when any new event is created

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1599]
#### Expected Behaviour

`occurred-at` should reflect the initial creation of an event.

#### Current Behaviour

If a new event is created, `occurred-at` (and `timestamp`) of existing events are updated to match the creation time of the new evnet.

#### Steps to Reproduce

1. Add a related identifier to a DOI (note `occurred-at` value)
2. Add a second related identifier to a DOI 

After adding the second related identifier, the `occurred-at` values for *both* events will have changed.

See for example: https://api.datacite.org/events?doi=10.5438/ecz0-er30 the related identifiers were added on 2022-10-31, and this changed the `occurred-at` value for `is-authored-by` and `is-authored-at`.

#### Further details

Significance: this `occurred-at` date is used for the date of citation (thanks @digitaldogsbody for finding this): https://github.com/datacite/lupo/blob/master/app/models/doi.rb#L1388-L1393

However, the citation date shouldn't change if another part of the DOI metadata is updated.

Note: an interesting/positive side effect of this update to the `is-authored-by` event time was that it re-triggered a missing ORCID auto-update for me.

#### Hypothesis

n/a

#### Possible Implementation

n/a

**Comment by kjgarza** [comment]
same-as: https://github.com/datacite/lupo/issues/652

**Comment by kjgarza** [comment]
actually, I think the definition of `occurred-at` is to be the yearOfPublication. See https://github.com/datacite/lupo/issues/652. As well this might aligned according to the source-id of the event, so no all sources should be treated equally

**Comment by KellyStathis** [comment]
Thanks! Sorry I didn't see that one. Should we keep this one with the description?

**Comment by kjgarza** [comment]
@KellyStathis 
I think you should put this info in the original as a comment and close this one. 

Let's not lose context. This a well know bug and the original issue is already part of a work package.
