### ISSUE TITLE
ORCID iD normalization may not be working

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1602]
#### Expected Behaviour

ORICD normalization should occur in bolognese: https://github.com/datacite/bolognese/blob/b0a7df3c9dd6a45eaf56fd0e06d304e4db9b837d/lib/bolognese/author_utils.rb#L35

#### Current Behaviour

There are newly registered DOIs where ORCID iDs in the `0000-0000-0000-0000` format are not being normalized to `https://orcid.org/0000-0000-0000-0000`.

#### Steps to Reproduce

Example: https://api.datacite.org/dois/10.34804/supra.20220128415
```
"nameIdentifiers": [
{
"nameIdentifier": "0000-0003-0498-7298",
"nameIdentifierScheme": "ORCID"
}
]
```

#### Screenshots

n/a

#### Further details

As a result of this, non-URL ORCID iDs don't appear in the authors facet in GraphQL (which assumes a URL format). For example:

```
{ 
  repository(id: "tib.suprabank") {
    name
    clientId
    works {
      totalCount
      authors {
        count
        id
        title
      }
      nodes {
        id
        creators {
          id
        }
      }
      affiliations {
        count
        id
        title
      }
    }
  }
}
```

#### Hypothesis

n/a

#### Possible Implementation

n/a

**Comment by KellyStathis** [comment]
@codycooperross, please feel free to update this if my summary isn't accurate 🙂

**Comment by ashwinisukale** [comment]
I worked on similar type of issue, hence assigned to myself.

**Comment by ashwinisukale** [comment]
I have tested this, its working as expected. I have added a test case which will cover this scenario with and without ORCID schemeURI.
