### ISSUE TITLE
Configure http://support.datacite.org

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#161]
blocker: have we bought this?

**Comment by espacial** [comment]
Britta is taking care of the readme.io upgrde

**Comment by mfenner** [comment]
Configured our proxy. Request to http://support.datacite.org now redirect to https://datacite.readme.io. This will be done via DNS once our membership is upgraded.

**Comment by kjgarza** [comment]
links go to http://support.datacite.org in https://mds.datacite.org/

**Comment by espacial** [comment]
Note SSL is supported (yay!)
