### ISSUE TITLE
Remove remaining doc links

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#162]
https://mds.datacite.org/static/apidoc 
Responsible: Laura

**Comment by espacial** [comment]
I can't modify the MDS. I should be either @kjgarza or @mfenner

**Comment by mfenner** [comment]
@kjgarza can you took into this until team meeting tomorrow, i.e. what is the effort of removing the documentation links?

**Comment by kjgarza** [comment]
@mfenner This is the HTML page. So i guess needs no compilation. right. So i can do it even without restarting. Am I right?

**Comment by kjgarza** [comment]
And I added GoogleAnalytics for the fun BANG!!

**Comment by mfenner** [comment]
@kjgarza Cool. But please change the link to http://support.datacite.org/docs/mds-2 once that DNS works (hopefully later today).
