### ISSUE TITLE
Include Support links: (github issues)

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#163]
- [x] Main website: menu bar
- [x] Main website: service sections, add direct doc link to the menu on the right
- [x] Main website: remove Tech doc and Outreach sections
- [x] All portals: menu bar and footer

**Comment by espacial** [comment]
I have the first three prepared

**Comment by kjgarza** [comment]
probably this should be moved to "in progress"

**Comment by mfenner** [comment]
<img width="639" alt="bildschirmfoto 2017-07-03 um 12 38 37" src="https://user-images.githubusercontent.com/23151/27789359-99b6d536-5fec-11e7-854a-cfce4d2125a6.png">

**Comment by mfenner** [comment]
- [ ] Assets
- [ ] Blog
- [ ] Schema
- [ ] API
- [ ] Profiles
- [ ] Search
