### ISSUE TITLE
Migrate Google Analytics to new version

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1643]
Google is sunsetting Universal Analytics. 

https://support.google.com/analytics/answer/11583832

- [x] Create functional GA4 property for Commons
- [x] Ensure tag events are being collected for Commons
- [x] Create functional GA4 property for Fabrica
- [x] Ensure tag events are being collected for Fabrica

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_302vp)

**Comment by kjgarza** [comment]
Just wondering, Does this plan includes the code changes in akita and bracco?

**Comment by codycooperross** [comment]
The listed steps are simply pulled from GA's transition documentation. It's possible that no code changes will be necessary, but further exploration is needed.

**Comment by kjgarza** [comment]
I thought that since we have UA codes hardcoded (or in env variables),we would need to replace these with the GA4 equivalent, which will require changes to your codebase.

Plus, if fabrica at least we are directly using the Universal Analytics analytics.js library in the code, migrating to GA4 will require changes to that code. GA4 has its own gtag.js library which has a different syntax and configuration options.
