### ISSUE TITLE
Transfer subset of 78 DOIs to DZHW.FDZ-DZHW

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1644]
Old repo: GESIS.DZHW
New repo: DZHW.FDZ-DZHW
Prefix:10.21249 
Number of DOIs: 78

[10.21249-DOIs to be transfered.csv](https://github.com/datacite/datacite/files/10068839/10.21249-DOIs.to.be.transfered.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_307kl)

**Comment by codycooperross** [comment]
The 78 DOIs have been transferred from GESIS.DZHW to DZHW.FDZ-DZHW. I wasn't sure whether to transfer prefix 10.21249, so this has not yet been transferred.
