### ISSUE TITLE
Usability improvement: switch Fabrica form order of latitude and longitude

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1646]
**Is your feature request related to a problem? Please describe.**
It is standard to enter latitude, then longitude (e.g. lat, long). However, the Fabrica form has longitude first, which is not expected.

**Describe the solution you'd like**
We should switch latitude and longitude. 
<img width="804" alt="Screen Shot 2022-11-23 at 19 44 38" src="https://user-images.githubusercontent.com/17298577/203689532-906a9f1f-e8a8-4d41-86ab-b0a48483d64e.png">

The field labels should also be visible somewhere once values have been entered to facilitate the user in troubleshooting error messages. Otherwise, you have this:
<img width="821" alt="Screen Shot 2022-11-23 at 19 44 58" src="https://user-images.githubusercontent.com/17298577/203689440-9cbc32b8-b9f5-4da0-94db-3f7e112c3ae4.png">

This error message then appears at the bottom, and it is not immediately clear what it refers to (particularly since it is at the bottom, not adjacent to the relevant field):

<img width="833" alt="Screen Shot 2022-11-23 at 19 45 03" src="https://user-images.githubusercontent.com/17298577/203689510-1b24b297-c044-414d-a35f-818bc709eaa2.png">

**Describe alternatives you've considered**
At minimum we should have the fields labeled, not just prompt text. If we keep the order as is, it would also be good to have the error at the bottom closer to the field as helper text. (see https://uxdesign.cc/ui-cheat-sheet-text-fields-2152112615f8)

**Additional context**
n/a

**Comment by kjgarza** [comment]
:wave: @KellyStathis, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
