### ISSUE TITLE
Index all subfields in geoLocations

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1649]
**Is your feature request related to a problem? Please describe.**
I am trying to assess usage of all metadata properties and subproperties. However, I am unable to query for geoLocationPoint, geoLocationBox and geoLocationPolygon because they are not mapped.

These queries work:
https://api.datacite.org/dois?query=geoLocations:*
https://api.datacite.org/dois?query=geoLocations.geoLocationPlace:*

But these don’t:
https://api.datacite.org/dois?query=geoLocations.geoLocationPoint:*
https://api.datacite.org/dois?query=geoLocations.geoLocationBox:*
https://api.datacite.org/dois?query=geoLocations.geoLocationPolygon:*

**Describe the solution you'd like**
These fields should be mapped so they can be searched.

**Describe alternatives you've considered**
I could query for https://api.datacite.org/dois?query=geoLocations:*, pull all records, and write a script to parse out the sub-property usage. But this is 3.5+ million DOIs so that's a lot to pull using the REST API.

**Additional context**
I knew that geolocationPolygon wasn't mapped (https://github.com/datacite/lupo/issues/327) but can't find documentation for why box and point aren't mapped.

**Comment by kjgarza** [comment]
:wave: @KellyStathis, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
