### ISSUE TITLE
Show line numbers in Fabrica file upload

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1651]
**Is your feature request related to a problem? Please describe.**
It is difficult to tell what the xml validation errors refer to.

**Describe the solution you'd like**
Since the validation errors refer to a line number, it would be useful to show line numbers in the form so that users don't have to manually count lines to find the error.

**Describe alternatives you've considered**
n/a

**Additional context**
example of where this is inconvenient:
![Screen Shot 2022-11-25 at 15 40 27](https://user-images.githubusercontent.com/17298577/204063457-a8853d0b-f0f4-4d29-b76c-17c5f8b4b623.png)

**Comment by kjgarza** [comment]
:wave: @KellyStathis, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
