### ISSUE TITLE
List common values of schemURI

### ISSUE THREAD

**Issue by nichtich** [datacite/datacite#1658]
It is hard to find common values of schemeURI and even the documentation contradicts the examples:

- ORCID: http://orcid.org/ (the PDF contains "http://orcid.org" instead)
- ISNI: http://isni.org/isni/ (the PDF contains "http://isni.org" instead)
- VIAF: http://viaf.org/viaf/ (why not "http://viaf.org/" ?)
- OBI: http://purl.obolibrary.org/obo/obi
- MeSH: http://www.nlm.nih.gov/mesh/meshhome.html (this does not look like an URI!)
- GRID: ?
- GND: ?
- ...

**Comment by KellyStathis** [comment]
Thanks for the suggestion, @nichtich! For 4.5, I can say that we will update to recommending https for ORCID and ISNI.
