### ISSUE TITLE
Password management

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#166]
Decision on how DataCite passwords are managed. Currently we provide authentication in the MDS and via Profiles services.

* Profiles doesn't manage passwords and depends on third-party single-sign on. A JWT is created after each login with an expiration date (exp) of 14 days. The JWT is stored as cookie and not shown to the user.
* MDS has option to **reset password**. New password will be sent to email address associated with account. Passwords can not be changed to a user-specified password. 

#### DEV NOTES

* only allow **reset password**. Show password in the UI upon creation, but not afterwards (as in GitHub personal access tokens). 
* don't send reset password via email. This would provide a second validation, but doesn't work so well with accounts used by multiple users, and exposes the password to additional risks.
* in first iteration only provide one password per MDS account, and don't use JWT.

**Comment by kjgarza** [comment]
Let me get this right.

**Comment by mfenner** [comment]
Depends on #137.
