### ISSUE TITLE
JSONSchema: remove use of uniqueItems to align with XML schema/documentation

### ISSUE THREAD

**Issue by lnielsen** [datacite/datacite#1662]
Most properties in the schema of type ``array`` have ``"uniqueItems": true``. E.g. following is **invalid**:

```json
{
    "sizes": ["4 kb", "4 kb"]
}
```

On the other hand, the following is **valid** according to the XML schema:

```xml
<sizes>
  <size>4 kb</size>
  <size>4 kb</size>
</sizes>
```

The schema documentation does not say anything about that values have to be unique.

### Proposal

- Remove all usage of ``"uniqueItems": true`` from the JSONSchema so that it is aligned with the XML schema and the schema documentation. 

If you agree, I'm happy to make a PR.

**Comment by kjgarza** [comment]
:wave: @lnielsen, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
