### ISSUE TITLE
Json schema for 4.4

### ISSUE THREAD

**Issue by jcoyne** [datacite/datacite#1664]
Currently there are json schemas in this directory: https://github.com/datacite/schema/blob/master/source/json but I don't see one for 4.4. Is this coming?

**Comment by seweissman** [comment]
@kjgarza Are these viewable to folks outside the datacite organization? I'd like to to keep tracking this issue.

**Comment by KellyStathis** [comment]
Hi @seweissman (and all)—apologies for the flurry of activity on these issues today! For context, I'm cleaning up stale issues in the datacite/schema repository. As that repository is primarily for hosting https://schema.datacite.org, we weren't always closely monitoring it for feedback.

We know the JSON schema is of interest to the community and it is in our backlog, as @kjgarza mentioned. I want to make sure this feedback isn't missed when we do get to this, so I am saving the contents of these issues to "productboard" (which is an internal tool).

You can see our plans for the current year here: https://datacite.org/roadmap.html and this will be updated for 2023 soon.
