### ISSUE TITLE
schema requires too many values for the update request

### ISSUE THREAD

**Issue by jcoyne** [datacite/datacite#1666]
The API specifies that we can provide just a fragment of the data https://support.datacite.org/docs/updating-metadata-with-the-rest-api

However the schema indicates a number of required values that the example does not provide:
https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json#L481-L489

Can you reconcile these two documents?

**Comment by KellyStathis** [comment]
Hi @jcoyne @tmorrell—apologies that we missed this question! I'm reviewing up some old issues today and saw no one responded to you.

The fragment shown in the documentation at https://support.datacite.org/docs/updating-metadata-with-the-rest-api is for updating metadata on an existing DOI. That DOI must already have the required fields. The REST API should not allow a DOI to be created with incomplete metadata. If you come across a case where it does, please let us know at support@datacite.org. I hope that helps answer our question!
