### ISSUE TITLE
Add event property to json schema? 

### ISSUE THREAD

**Issue by jcoyne** [datacite/datacite#1668]
Currently https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json does not have a property for "event" but the documentation (https://support.datacite.org/docs/api-create-dois#create-a-findable-doi) shows to use an event property with "publish" in order to create a findable DOI. Was that property omitted?

**Comment by kjgarza** [comment]
:wave: @jcoyne, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
