### ISSUE TITLE
DataCite accounts

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#167]
Clarify the account types used by DataCite, and harmonize all services around this. We currently have:

* **Members**, there is a legal relationship, and they pay membership fees. Members have accounts in the MDS.
* **Data Centers**. There is currently no direct relationship with DataCite, e.g. no requirement for contact information. Data centers have accounts in the MDS.
* **Users**. Accounts in the Profiles service, used mainly for ORCID claiming.

#### DEV NOTES

* authentication is via web interface, and via API.
* authentication via web interface is for users, and will be standardized using the existing Profiles service workflow. Users can be associated with members or data centers.
* authentication via API is mostly for organizations, as in the MDS. Some user authentication via API is happening, e.g. in ORCID claiming workflows.

#### Questions

* should **member** and **data center** accounts be consolidated into **organization** accounts?

**Comment by pcruse** [comment]
I would slice this up a bit differently: there are members and members administer accounts and DataCite has a legal relationship with them. There are data centers and DataCite has a relationship with some -- those that are direct consumers of DOIs.

**Comment by mfenner** [comment]
Team decision: keep the following account types

* member
* data center (user account)
* user (consumer)

We need to clarify the terminology.
