### ISSUE TITLE
Add "Instrument" to controlled list of values for "resourceTypeGeneral"

### ISSUE THREAD

**Issue by RKrahl** [datacite/datacite#1670]
The [RDA Persistent Identification of Instruments Working Group](https://rd-alliance.org/groups/persistent-identification-instruments) seeks to explore a community-driven solution for globally unique identification of measuring instruments operated in the sciences.  In a first step, the group formulated a generic metadata schema to describe instruments.  In a second step, we evaluated DataCite DOIs.  To this end, we tried to [map our generic schema onto the DataCite Metadata Schema](https://github.com/rdawg-pidinst/schema/blob/map_to_datacite/schema.rst).  It was found that most of the metadata needed to describe instruments could indeed be represented in the DataCite schema, even though some of the definitions need to be stretched a little bit.  As a result, DataCite DOIs were found to be usable in principle for our purpose. There are however a few shortcomings.  Some minor amendments of the DataCite schema would significantly facilitate its use for instruments.

One of the issues is property 10.a `resourceTypeGeneral`: there is no suitable value to represent a measuring instrument.  I therefore suggest to add `Instrument` to the controlled list of values for `resourceTypeGeneral`.

**Comment by kjgarza** [comment]
:wave: @RKrahl, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
