### ISSUE TITLE
Add a value indicating "was used in" to "relationType"

### ISSUE THREAD

**Issue by RKrahl** [datacite/datacite#1671]
The [RDA Persistent Identification of Instruments Working Group](https://rd-alliance.org/groups/persistent-identification-instruments) seeks to explore a community-driven solution for globally unique identification of measuring instruments operated in the sciences. As explained in datacite/datacite#1670, we evaluated DataCite DOIs and found them usable in principle for this purpose.  There are however a few shortcomings. Some minor amendments of the DataCite schema would significantly facilitate its use for instruments.

One issue is that there should be a way to relate an instrument with events, such as the deployment of an instrument in an expedition, using `RelatedIdentifier`. However it is not clear which `relationType` in the DataCite schema would be suitable for such a "has been deployed in" or "was used in" relation.

**Comment by kjgarza** [comment]
:wave: @RKrahl, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
