### ISSUE TITLE
Add a "Series" property

### ISSUE THREAD

**Issue by RKrahl** [datacite/datacite#1674]
The [RDA Persistent Identification of Instruments Working Group](https://rd-alliance.org/groups/persistent-identification-instruments) seeks to explore a community-driven solution for globally unique identification of measuring instruments operated in the sciences. As explained in datacite/datacite#1670, we evaluated DataCite DOIs and found them usable in principle for this purpose.  There are however a few shortcomings. Some minor amendments of the DataCite schema would significantly facilitate its use for instruments.

The most serious issue is that there seem to be no suitable place to put the model name of the instrument, although this is considered a very important piece of information. A possible solution could be to add a new optional `Series` property, to indicate that this resource is one of a series of the same kind. This could also be beneficial for other types of resources, such as conferences.

**Comment by kjgarza** [comment]
:wave: @RKrahl, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
