### ISSUE TITLE
Transfer subset of 1190 DOIs to dipf.rdcedu

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1676]
[DoiPrefix7477_complete.csv](https://github.com/datacite/datacite/files/10216606/DoiPrefix7477_complete.csv)
Old repository ID: gesis.dipf
New repository ID: dipf.rdcedu
Prefix: 10.7477 (transfer prefix)
Number of DOIs: 1,190 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_30l5h)

**Comment by codycooperross** [comment]
The 1,190 DOIs and 10.7477 prefix have been transferred to dipf.rdcedu.
