### ISSUE TITLE
Transfer subset of 222 DOIs to iabg.rdciab

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1678]
[DoiPrefix5164_complete.csv](https://github.com/datacite/datacite/files/10229402/DoiPrefix5164_complete.csv)
Old repository ID: gesis.iab
New repository ID: iabg.rdciab
Prefix: 10.5164 (also transfer prefix)
Number of DOIs: 222

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_30mfp)

**Comment by codycooperross** [comment]
The 222 DOIs and prefix 10.5164 have been transferred to iabg.rdciab.
