### ISSUE TITLE
DataCite contact types

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#169]
DataCite is currently providing two special contact types:

* member representative
* member technical contact

Crossref is using five different contact types:

* billing contact, will receive invoices
* voting contact, will vote in the board election
* business contact, will receive important strategic information about products and services
* technical contact, will receive anything requiring platform updates or API work
* metadata quality contact, will receive detailed reports such as errors in metadata deposits or conflicts with other records

The first two of these are only applicable to DataCite members, whereas the last three are also applicable to DataCite data centers.

Contact types require an associated email address. Each user can be associated with multiple contact types. We want to have exactly one of each contact type for each member or data center. Contact types are different from roles (#139), the latter are about permissions.

**Comment by pcruse** [comment]
DataCite has a 1) voting representative; 2) billing contact; 3) technical contact; 4) signing authority; 5) general

**Comment by brittadreyer** [comment]
We used to have a "working-level contact", which included Rachael, Joan etc. I would like to suggest to refer to this group as "administrative contact", as they are engaged in activities that support the day-to-day operations of the DOI Registration Service i.e. metadata quality, support questions. I am not sure about the definition of "general", but if there are similarities I would prefer "administrative contact".

**Comment by pcruse** [comment]
I don't think that administrative contact is quite right. To me, an admin contact is someone that works on billing, contracts, logistics, etc.  Also, not all institutions will have all of these people.

**Comment by mfenner** [comment]
Crossref is saying that it needs at least three people for their five contact types. I think a similar approach could work for DataCite, i.e. that a person can be more than one contact type. E.g. voting representative and signing authority.

**Comment by mfenner** [comment]
One other question: do we need this information in our user profiles, or can all this be managed in the DataCite CRM? The main reason to have this in the user profiles is to allow members to update the information themselves. Obviously we then want to sync this with the CRM system automatically.

**Comment by pcruse** [comment]
We already have all of the people that I listed in the first box, but they are not all kept in the same place. Some we never interact with (signing authority), but we need to track.
