### ISSUE TITLE
Non-ISO 639-1 values in Language property are not displayed in Fabrica form

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1693]
### Describe the bug

The DOI Fabrica form does not display Language values outside the ISO 639-1 controlled vocabulary, even when submitted by other mechanisms (e.g. XML). Submitting the form overwrites previously submitted value.

#### Expected Behaviour

Language values should display and not be overwritten. A fix was implemented for the xml:lang attribute on Title and Description (https://github.com/datacite/bracco/issues/335); similar logic should apply to the Language property.

Although the form restricts users to selecting from ISO 639-1 (this has been requested to change), it should already be able to display other languages **when submitted through XML** or via the REST API outside Fabrica.

#### Current Behaviour

The DOI Fabrica form does not display Language values outside controlled vocabulary, even when submitted by other mechanisms (e.g. XML). 

If an existing DOI with a non-ISO-639-1 language is updated via the form, submitting the form overwrites previously submitted Language value.

#### Steps to Reproduce

1. Create DOI with Fabrica form, select Language "English"
2. Update XML through file upload to change Language to "cmn" (Mandarin)
3. Return to the form - language is blank:
![Screen Shot 2023-01-04 at 11 20 54](https://user-images.githubusercontent.com/17298577/210632831-90db87b1-341b-4b61-9fde-af028b9594dc.png)
4. Saving the form erases the language

#### Screenshots

n/a

#### Further details

n/a

#### Hypothesis

n/a 

#### Possible Implementation

Similar logic to the fix in https://github.com/datacite/bracco/issues/335 could be applied

**Comment by richardhallett** [comment]
This is a difficult one and arguably not a bug, Metadata created via the form is designed to be set up with the form as being the only you are editing your data really, or at the very least it was originally designed as a means to easily create and maintain a low volume of DOIs with then caveats and restrictions presented as to what we think are our best practices, i.e. ISO 639-1

Therefore I would say this is actually a feature request to change the behaviour of the form and not a bug. CC: @kjgarza

**Comment by KellyStathis** [comment]
@richardhallett I would agree if not for the precedent in https://github.com/datacite/bracco/issues/335. With that documentation, this seems more like a bug that we account for values created via XML for the xml:lang attributes but not for the Language property, as it is inconsistent behaviour for the same controlled list.

**Comment by codycooperross** [comment]
This should now be fixed for the Language property as a consequence of changes to support Fabrica Improvements feature 12, which allows for non-ISO 639-1 to be input via Fabrica form and the REST API. https://github.com/datacite/datacite/issues/1590
