### ISSUE TITLE
An error message appears when the user tries to access Commons when logged in with ORCID

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1702]
#### Expected Behaviour

A user can access Commons when logged in with their profiles/ORCID account

#### Current Behaviour

An error message appears when the user tries to access Commons when logged in:

"Application error: a client-side exception has occurred (see the browser console for more information)."

#### Steps to Reproduce

1. Go to (https://commons.datacite.org/)
2. Click on "sign in"
3. Sign in to profiles with ORCID

<img width="885" alt="Screenshot 2023-01-10 at 09 33 23" src="https://user-images.githubusercontent.com/44582654/211516505-62bcf88e-0b49-4404-b63d-d3d1752781f0.png">

### Context (Environment)

Commons

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_316dx)

**Comment by digitaldogsbody** [comment]
This is the error I am seeing in the console: `TypeError: invalid 'instanceof' operand p`

**Comment by digitaldogsbody** [comment]
There appears to only be one `instanceof` statement in Akita: https://github.com/datacite/akita/blob/1cf72f530d8c879160468363d04b87dceae6613c/src/pages/_app.tsx#L46

**Comment by digitaldogsbody** [comment]
Yes it's not there

**Comment by digitaldogsbody** [comment]
It's in one of the dependencies somewhere, but almost impossible to tell because of the minimized code

**Comment by digitaldogsbody** [comment]
https://commons.datacite.org/_next/static/chunks/808-0421f7367444cb5c.js

Line 10, Char 70306

`if(null!=a&&!(a instanceof p))try{a=d(a)}catch(O){try{a=h("string"==typeof a?n.from(a):a)}catch(x){return b(new i("secretOrPublicKey is not valid key material"))}}`

**Comment by digitaldogsbody** [comment]
Ok got it - `.node_modules/jsonwebtoken/verify.js` L120

```typescript
if (secretOrPublicKey != null && !(secretOrPublicKey instanceof KeyObject)) {
```

**Comment by digitaldogsbody** [comment]
`KeyObject` comes from an import at the top:
```typescript
const {KeyObject, createSecretKey, createPublicKey} = require("crypto");
```

**Comment by digitaldogsbody** [comment]
`jsonwebtoken` was bumped up a major version in the last release: https://github.com/datacite/akita/commit/201e0ca84196e0f98f2bf5dda999b7bfd4342653 -> 
https://github.com/datacite/akita/releases/tag/1.4.7

Recommend we roll that particular version bump back and see if it fixes the issue

**Comment by digitaldogsbody** [comment]
Looks like it is a break in v9.0.0: https://github.com/auth0/node-jsonwebtoken/issues/863

**Comment by digitaldogsbody** [comment]
Now fixed in production
