### ISSUE TITLE
Transfer prefixes: 10.17625/10.15476/10.24362 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1712]
Prefixes: 10.17625/10.15476/10.24362
Repository IDs:MTAKIK.NKE/MTAKIK.ELTE/MTAKIK.GONDOLAT
DOIs: 121/1444/1 
Status approved

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_31hhx)

**Comment by MaryHirsch** [comment]
Prefix 10.24362 has been transferred and the 1 DOI re-registered with Crossref. @codycooperross could you remove prefix from DataCite and set the DOI to registered state? 

*I opened a Github issue for all 3 prefixes because they all belong to the same consortium, but it seems the re-registrations will happen asynchronosly for each prefix. If it's easier to have a Github issue for each prefix just let me know.

**Comment by codycooperross** [comment]
Prefix 10.24362 has been removed from DataCite and the DOI was set to registered state.
