### ISSUE TITLE
Profiles page in commons generates an error

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1766]
#### Expected Behaviour

Full record of research profile is displayed in DataCite Commons

#### Current Behaviour

An error is generated when opening a researcher profile in DataCite Commons

#### Steps to Reproduce

1. Go to: https://commons.datacite.org/orcid.org/0000-0002-5660-2970
see error 

<img width="1263" alt="Screenshot 2023-03-20 at 10 05 14" src="https://user-images.githubusercontent.com/44582654/226293530-ab250562-899c-454a-9895-21d1d851b135.png">

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_33ead)

**Comment by codycooperross** [comment]
This has been resolved with this PR datacite/lupo#969 and is related to this issue datacite/lupo#968
