### ISSUE TITLE
Transfer subset of 153 DOIs to DIAS.DIAS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1768]
Old repository ID: JALC.JALC (https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.20783)
New repository ID: DIAS.DIAS
Prefix: 10.20783 (please also transfer the prefix to the new repo dias.dias)
DOIs: 153
[dias.dias_153.txt](https://github.com/datacite/datacite/files/11061423/dias.dias_153.txt)

**Comment by codycooperross** [comment]
The 153 DOIs and 10.20783 prefix have been transferred to DIAS.DIAS.
