### ISSUE TITLE
Transfer subset of 84 DOIs to KYUSHUU.KYUSHUU

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1769]
Old repository ID: JALC.JALC
New repository ID: KYUSHUU.KYUSHUU
Prefix: 10.48708 (please also transfer prefix to KYUSHUU.KYUSHUU)
DOIs: 84 https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.48708
[KYUSHUU.KYUSHUU_84.txt](https://github.com/datacite/datacite/files/11061467/KYUSHUU.KYUSHUU_84.txt)

**Comment by codycooperross** [comment]
The 84 DOIs and 10.48708 prefix have been transferred to KYUSHUU.KYUSHUU.
