### ISSUE TITLE
Transfer subset of 3395 and 17 DOIs to JAMSTEC.JAMSTEC

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1770]
Old repository ID: JALC.JALC
New repository ID: JAMSTEC.JAMSTEC
Prefixes: 10.17596 + 10.48518 
https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.17596 
https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.48518
DOIs: 3395 + 17
[JAMSTEC.JAMSTEC_17.txt](https://github.com/datacite/datacite/files/11061555/JAMSTEC.JAMSTEC_17.txt)
[JAMSTEC.JAMSTEC_3395.txt](https://github.com/datacite/datacite/files/11061556/JAMSTEC.JAMSTEC_3395.txt)

**Comment by codycooperross** [comment]
The 3395 DOIs with prefix 10.17596 and 17 DOIs with prefix 10.48518 have been transferred to JAMSTEC.JAMSTEC as have  prefix 10.17596 and 10.48518.
