### ISSUE TITLE
Transfer subset of 137 DOIs to NIPR.NIPR

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1771]
Old repository ID: JALC.JALC https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.17592
New repository ID: NIPR.NIPR 
Prefix: 10.17592 (please also transfer prefix to NIPR.NIPR )
DOIs: 137
[NIPR.NIPR_137.txt](https://github.com/datacite/datacite/files/11061622/NIPR.NIPR_137.txt)

**Comment by codycooperross** [comment]
The 137 DOIs and 10.17592 prefix have been transferred to NIPR.NIPR.
