### ISSUE TITLE
Transfer subset of 38 and 1017 DOIs to JAXA.JAXA

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1773]
Old repository ID: JALC.JALC 
https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.17597
https://doi.datacite.org/repositories/jalc.jalc/dois?prefix=10.57746
New repository ID: JAXA.JAXA
Prefixes: 10.17597 + 10.57746
DOIs: 38 + 1017
[JAXA.JAXA_38.txt](https://github.com/datacite/datacite/files/11061686/JAXA.JAXA_38.txt)
[JAXA.JAXA_1017.txt](https://github.com/datacite/datacite/files/11061715/JAXA.JAXA_1017.txt)

**Comment by codycooperross** [comment]
The 38 DOIs with prefix 10.17597 and 1017 DOIs with prefix 10.57746 have been transferred to JAXA.JAXA as have prefixes 10.17597 and 10.57746.
