### ISSUE TITLE
Remove 7 prefixes (transferred to JALC)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1775]
Repository ID: JALC.JALC
prefixes: 

- [x] 10.17591
- [x] 10.17593
- [x] 10.17594
- [x] 10.17598
- [x] 10.48673
- [x] 10.48682
- [x] 10.48696

DOIs: 122
status: remove prefixes from DataCite and set 122 DOIs to registered state

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_33m39)

**Comment by MaryHirsch** [comment]
@codycooperross it might be easier to do this after the other JALC DOIs have been transferred to the new JALC consortium today.

**Comment by codycooperross** [comment]
The following DOIs have been removed from DataCite and the containing 122 DOIs have been set to registered state:

-  10.17591
-  10.17593
-  10.17594
-  10.17598
-  10.48673
-  10.48682
-  10.48696
