### ISSUE TITLE
Transfer subset of 297 to BMLM.BGC

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1778]
Old repository ID:           TIB.MPDL
New repository ID:         BMLM.BGC
Prefix:                               10.17871
Number of DOIs:            297

[transfer_dois_mpibgc.csv](https://github.com/datacite/datacite/files/11109828/transfer_dois_mpibgc.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_33qtx)

**Comment by codycooperross** [comment]
The 297 DOIs have been transferred to BMLM.BGC.
