### ISSUE TITLE
Remove prefix 10.34860 (transferred to JALC)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1788]
Repository ID: jalc.jalc
Prefix: 10.34860
number of DOIs:4
status: remove prefix and set DOIs to registered state.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3493p)

**Comment by codycooperross** [comment]
Prefix 10.34860 has been removed and the 4 10.34860 DOIs are set to registered state.
