### ISSUE TITLE
Harvesting and Public Data Dump

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1805]
- **Component 1:** PID Graph access via APIs and data dump  \(Accessing\)

- <https://docs.google.com/presentation/d/1cfc6kT-zxcj67-e1cw0WowiX1s7It038gZKIsIm_Muk/edit#slide=id.g22df2ead793_0_5>

related: https://github.com/datacite/datacite/issues/709

<span data-preserve-white-space></span>  

- [ ] Technical Specification
- [ ] Implementation

Enable a regular dump of all public DataCite DOI metadata\. <span data-preserve-white-space></span>

<span data-preserve-white-space></span>  <span data-preserve-white-space></span>

**User stories:**

As a data integrator,

I would like a convenient way to retrieve all of DataCite's metadata, <span data-preserve-white-space></span>

so that I can incorporate it into my platform for analysis and reuse\. <span data-preserve-white-space></span>

<span data-preserve-white-space></span>  <span data-preserve-white-space></span>

**Similar services:**

- JSTOR Data for Research \(<https://www.jstor.org/dfr/>\) \- In addition to an everything dump, also has ways to request datasets based on parameters and to get a sample dataset for use in teaching\.

**Comment by sarala** [comment]
Link to subfeature: https://datacite.productboard.com/feature-board/planning/features/1922696

**Comment by miku** [comment]
Just to note: We are using a small command-line utility called [dcdump](https://github.com/miku/dcdump) to create metadata snapshots (see also notes and updates in #709).

**Comment by digitaldogsbody** [comment]
This is complete as of the release of the first official Public Data File earlier this year: https://doi.org/10.14454/zhaw-tm22
