### ISSUE TITLE
Invalid types in CSL JSON items returned by DOI content negotiation

### ISSUE THREAD

**Issue by dhimmel** [datacite/datacite#182]
See https://github.com/CrossRef/rest-api-doc/issues/187: DOI Content negotiation that requests CSL JSON should retrieve valid CSL Items.

I'm currently getting an invalid CSL type for a DOI registered with DataCite.

```
curl --location --silent \
  --header "Accept: application/vnd.citationstyles.csl+json" \
  https://doi.org/10.6084/m9.figshare.4906367.v1 \
  | python -m json.tool
```

Returns

```json
    "type": "other",
```

`other` is not a valid CSL `type`. See the [valid options here](https://github.com/citation-style-language/schema/blob/4846e02f0a775a8272819204379a4f8d7f45c16c/csl-data.json#L8-L48).

**Comment by mfenner** [comment]
@dhimmel thanks for opening the issue. Please be aware that the DataCite code is independent of the Crossref code. The library that is doing the conversion is here: https://github.com/datacite/bolognese. 

In this particular case the content type is `software`. @adam3smith suggested to me via email recently to use `article` until csl implements `software`. I will do that mapping.

**Comment by mfenner** [comment]
I have applied the fix in the conversion library. Will be deployed to content negotation server after some more testing.
