### ISSUE TITLE
Feature 1 (Backend) - Getting all scholarly ouputs linked to an organization

### ISSUE THREAD

**Issue by jrhoads** [datacite/datacite#1824]
Criteria for works related to an organization has changed.
It can be any of the following:

1. Direct work( Org is creator): creator.nameIdentifier == Organization.rorID
2. Association through creator affiliation
3. Org is direct sponsor of contributor
4. Association through contributor affiliation
5. Association through DMP

**Comment by jrhoads** [comment]
A DOI would appear on an Organisation page under any of the following conditions:

- `creator.nameIdentifier.affiliantionIdentifier` has the ROR-ID of the organization
- `creator.nameIdentifier` has the ROR-ID of the organization
- `memberId` of the repository that created the DOI has the ROR-ID of the organization
- `contributor.nameIdentifier` has the ROR-ID of the organization && the contributorType is “Sponsor”
- `relatedIdentifier` has the DMP-ID (GrantID or ProjectID)  which metadata has:
`contributor.nameIdentifier` has the ROR-ID of the organization && the contributorType is “Sponsor”

**Comment by KellyStathis** [comment]
@jrhoads sorry to jump in here—I got a notification and I'm curious about this one!

First, this list seems to omit organization references in funderIdentifier. Does this mean that organization pages will no longer include links from funderIdentifier? Currently they include DOIs that have the organization's Crossref Funder ID (as mapped to ROR) in funderIdentifier. 

I was also wondering about contributors and their affiliations:
- Why is contributor.nameIdentifier only included if contributorType is “Sponsor”? What's the reasoning behind excluding organizational contributors w/other roles?
- "Association through contributor affiliation" is listed, should  `contributor.affiliation.affiliantionIdentifier` be added to the list of properties (the 2nd comment)? Note this is currently part of the criteria (see: https://support.datacite.org/docs/connecting-to-organizations).

Related—there has been some discussion recently about how it would be helpful for the organization pages to also include DOIs where the ROR ID is in funderIdentifier... this would be quite helpful for the GREI project (Matt and I can share more context), where they'd like to track cases where NIH is the funder, and may be referenced using a ROR ID. I don't want to overstep here, but if we're already examining the scope of the organization page for FAIR Island, I wonder if it would be relatively straight-forward to include this condition. There are a few notes on productboard about this with more context.

**Comment by KellyStathis** [comment]
Ah, I see the comment on funderIdentifier was raised earlier: https://docs.google.com/document/d/1vlA-LE9VrSHKJg_HettSBp0oHzcVZo_07B1sCa-8x3M/edit?disco=AAAArWbLTnE. At the time, I didn't realize these were proposed changes to the main/existing Organization page on Commons. 

I think this needs more discussion—just because funderIdentifier isn't in the use cases for FAIR Island doesn't mean that it should be removed entirely... I hope I'm missing something here! Looping in @kjgarza for clarification on the product spec.

**Comment by jrhoads** [comment]
Bringing over notes from a conversation on slack about this with an emphasis on scenario 5 (thank you Kelly)

> Scenarios 1-4 get works directly related to an Organization (let’s call this the Org-Works List) via the Creator or Contributor nameIdentifier or affiliationIdentifier.
> For each work in the Org-Works list, if the work has resourceTypeGeneral = OutputManagementPlan:
> 1) Get all relatedIdentifiers for that work (“outgoing”) that are DOIs, and add them to the Org-Works List.
> 2) Get all DOIs that reference that work in a relatedIdentifier (“incoming”), and add them to the Org-Works List.

**Comment by jrhoads** [comment]
Scenario 1, 3 are grouped together in that the the organization is a direct creator or a contributor(sponsor)
Index this in `organization_id`

Scenario 2, 4 can be grouped together in that a creator or contributor(sponsor) is affiliated with  the organization
Index this in 'affiliation_id`

Scenario 5 says that the primary Work, should be recognized as an organizational work if it is related to a DMP-work, AND that DMP work has the organization as a direct contributor(sponsor) as in scenario 3.
**Question:**  Is it intentional that we do not consider DMPs that fall under Scenarios 1,2,4?

**Comment by kjgarza** [comment]
> Question: Is it intentional that we do not consider DMPs that fall under Scenarios 1,2,4?

@jrhoads I think you are asking whether DMPs will be shown in the list under the scenarios 1,2,4. If that's the question, then the answer is yes. All the scenarios talk `Given there exist DOIs`, since all DMPs (aka OutputManagementPlans) have a DOI (otherwise they wouldn't be in the PID graph) then thell fall under that scenario.

is that clear?
