### ISSUE TITLE
Transfer 137 DOIs to INIST.ETNET

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1830]
Old repository ID: JBRU.HEAVEN
New repository ID: INIST.ETNET
DOIs: 137 (only DOIs not prefix)
[DOI_ETNET.csv](https://github.com/datacite/datacite/files/11451565/DOI_ETNET.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_39n9x)

**Comment by codycooperross** [comment]
The 137 DOIs have been transferred from JBRU.HEAVEN to INIST.ETNET.
