### ISSUE TITLE
Transfer a subset of DOIs to VZEK.EASY

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1849]
old Repository ID:       gesis.gesis

New Repository ID:    VZEK.EASY

Prefix:                         10.15464 (also transfer the prefix)
[10.15464_vzek.easy.csv](https://github.com/datacite/datacite/files/11677673/10.15464_vzek.easy.csv)

Number of DOIs:        238

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3fvpx)

**Comment by codycooperross** [comment]
The 238 listed DOIs and prefix 10.15464 have been transferred to VZEK.EASY.
