### ISSUE TITLE
classificationCode not added to XML when submitted in Fabrica form

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1858]
#### Expected Behaviour

The classificationCode for a FOS heading is automatically populated in the Fabrica form. This is then included in the XML classificationCode attribute.

#### Current Behaviour

classificationCode is in the resulting JSON but not the XML.

See JSON: https://api.test.datacite.org/dois/10.82247/ktfh-qa24
```json
"subjects": [
{
"subject": "FOS: Health sciences",
"valueUri": "",
"schemeUri": "http://www.oecd.org/science/inno/38235147.pdf",
"subjectScheme": "Fields of Science and Technology (FOS)",
"classificationCode": "3.3"
}
],
```

vs. XML:
```xml
<subject subjectScheme="Fields of Science and Technology (FOS)" schemeURI="http://www.oecd.org/science/inno/38235147.pdf" valueURI="">FOS: Health sciences</subject>
```

#### Steps to Reproduce

1. Go to Fabrica create DOI form
2. Add required metadata
3. In Subject, Type "health sciences" and select the FOS heading
4. Create in Findable state

#### Screenshots

![Screen Shot 2023-06-19 at 12 08 48](https://github.com/datacite/datacite/assets/17298577/590a4d93-3fe9-425c-b928-d318e54e3afc)

#### Further details

n/a

#### Hypothesis

n/a

#### Possible Implementation

n/a

**Comment by codycooperross** [comment]
`classificationCode` may be excluded in all conversions from JSON to XML, likely because the DataCite XML writer in bolognese does not seem to include this value: https://github.com/datacite/bolognese/blob/513cdfd43203fd2c2f131bcbc1384d96110d67ce/lib/bolognese/datacite_utils.rb#L174C24-L174C24

**Comment by ashwinisukale** [comment]
@KellyStathis @MaryHirsch @codycooperross 

I'm working on adding a test case for these code changes, and I need a valid DOI for testing purposes. The current DOI used in the test case is https://doi.org/10.5061/DRYAD.8515. However, I'd like to use a different DOI to ensure that I cover the current scenario of having a subject with different attributes in it.

Current DOI does not have the subject with provided attributes.

If either of you could provide me with a DOI or suggest where I can obtain one, your help is highly appreciated :)

**Comment by MaryHirsch** [comment]
@ashwinisukale Kelly included this DOI: 10.82247/ktfh-qa24 as an example from their own repo
https://doi.test.datacite.org/dois/10.82247%2Fktfh-qa24
https://api.test.datacite.org/dois/10.82247/ktfh-qa24

**Comment by ashwinisukale** [comment]
Can I find a DOI on other platform with these attributes like on doi.org?

**Comment by codycooperross** [comment]
@ashwinisukale You may be able to find an adequate production DOI example using a REST API query. Does this query help? https://api.datacite.org/dois?query=_exists_:subjects.valueUri%20_exists_:subjects.schemeUri%20_exists_:subjects.classificationCode If not, feel free to let me know a bit more about what your test will look like so I can help further.

**Comment by ashwinisukale** [comment]
wow thanks @codycooperross thats awesome, it solved all my queries. I did not know I can query like that. Thanks a lot
