### ISSUE TITLE
affiliation schemeURI does not map to DataCite JSON when submitted as XML

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1859]
#### Expected Behaviour

When DataCite XML is submitted, the attributes affiliationIdentifier, affiliationIdentifierScheme, and schemeURI should map to the DataCite JSON.

#### Current Behaviour

When DataCite XML is submitted,  the affiliation schemeURI does not appear in the DataCite JSON.

#### Steps to Reproduce

Example in test: https://doi.test.datacite.org/dois/10.82247%2Fkb0k-9d10

1. Submit XML via the Fabrica file upload containing affiliation schemeURI:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI">10.82247/kb0k-9d10</identifier>
  <creators>
    <creator>
      <creatorName>Account, Testing</creatorName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0002-4734-4551</nameIdentifier>
      <affiliation affiliationIdentifier="https://ror.org/04tj63d06" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">North Carolina State University</affiliation>
    </creator>
  </creators>
  <titles>
    <title>Test affiliation schemeURI as XML</title>
  </titles>
  <publisher>DataCite</publisher>
  <resourceType resourceTypeGeneral="Dataset">dataset</resourceType>
  <publicationYear>2023</publicationYear>
</resource>
```

2. Compare the resulting XML and JSON for affiliation:

```xml
<affiliation affiliationIdentifier="https://ror.org/04tj63d06" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">North Carolina State University</affiliation>
```

```json
      "affiliation": [
        {
          "name": "North Carolina State University",
          "affiliationIdentifier": "https://ror.org/04tj63d06",
          "affiliationIdentifierScheme": "ROR"
        }
      ],
```

#### Screenshots

n/a

#### Further details

See Dryad's writeup here: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2587

#### Hypothesis

Possibly a bug in this function: https://github.com/datacite/bolognese/blob/010a854e642fefdcdf17d04dffa2b4de8721808c/lib/bolognese/author_utils.rb#L139

**Comment by codycooperross** [comment]
I believe this bug is resolved by this PR: https://github.com/datacite/bolognese/pull/157 @ashwinisukale , does that seem right?

**Comment by ashwinisukale** [comment]
Yes @codycooperross thats correct.
