### ISSUE TITLE
Control DOI quantity in the data center account

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#186]
Members or data centers want to set a limit to DOIs that they want to register in a given time period.

**Comment by pcruse** [comment]
OR -- Members want to be alerted when they go above a certain threshold of DOIs within a year

**Comment by mfenner** [comment]
I like alerting, as it is easier to implement technically, and is a good intermediate step. Based on feedback we can keep it this way, or move to a system where members can set a limit. 

What we need to implement would be a **Notifications** page, and an indicator for unread notifications in the menu bar.
