### ISSUE TITLE
FC4E T3.5

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/datacite#1861]
Harvester service epic

Product spec: https://docs.google.com/document/d/1SGUdJp5JEtQc9V-oRPV96_aUMz3iKZhTPSCP5qgFjYE/edit#heading=h.r0s2ly9b14w9
Tech spec: https://docs.google.com/document/d/1zYmrgboRtx7fR0UzA6KwvWYovWA-zhEHDINzhRkLdko/edit#

**Comment by kjgarza** [comment]
I think the EPIC for this work was already created inhttps://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/gh/datacite/datacite/1805 @digitaldogsbody

**Comment by digitaldogsbody** [comment]
Oh. I couldn't find it when I searched the list of epics in zenhub :(
