### ISSUE TITLE
Downloadable dataset of all DataCite DOIs

### ISSUE THREAD

**Issue by maxogden** [datacite/datacite#188]
Hi DataCiters! I am working on some dataset archiving and backup projects and it would be useful to have a list of all DataCite DOIs. 

A simple CSV with the list of all DOIs would be plenty. If there is any other relevant metadata that wouldn't get returned in the Handle DOI resolution then that would be nice to have as well. For example eLife gave me the data in this format for all their datasets: https://gist.github.com/maxogden/40f96f69ed7e5edb2bd148255212f546

Another avenue could potentially be to use the Handle LIST_HANDLES operation, which I believe requires administrative access to the DataCite handle servers. But I've never used this operation and am not sure if it's widely supported.

If this is possible to do through an API I can do that as well. I'm using this code to get the type:dataset entries from CrossRef: https://gist.github.com/maxogden/95b16e2bcd4c295d77ccfd6b5615370f

**Comment by mfenner** [comment]
@maxogden if you want a listing of all DataCite DOIs, then our sitemaps file in DataCite Search might be easiest: https://search.datacite.org/sitemaps/sitemap.xml.gz. There is minimal parsing to do to translate the URLs into DOIs, but that should be straightforward.

The handle system doesn't store any metadata for DataCite (or Crossref DOIs), so that is probably not getting you very far.

You can of course use our API, very similar to how you retrieve datasets from Crossref: https://api.datacite.org/works?resource-type-id=dataset&rows=1000. API documentation is at https://support.datacite.org/docs/api.

**Comment by maxogden** [comment]
@mfenner using the sitemaps I got 8432463 DOIs, does that seem accurate? Here's the code I used: https://gist.github.com/maxogden/322864dfe13dfa5e377fade1c96891af

**Comment by maxogden** [comment]
@mfenner ahh API says 8439760 via https://api.datacite.org/works?rows=10. So I guess I should use the API to make sure I get them all

**Comment by mfenner** [comment]
Remember, this is all DOIs. Filter by resource-type-id to only get datasets, a little over 3 million.

--- original message ---
> Di. 8. Aug. at 6:32 PM, <notifications@github.com> wrote:


> @mfenner ahh API says 8439760 via https://api.datacite.org/works?rows=10. So I guess I should use the API to make sure I get them all

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by bnewbold** [comment]
I'm also interested in bulk access to either the "list of all registered DataCite DOIs" (which can be used to enumerate metadata via content negotiation or the metadata API), or, better, bulk snapshots of the metadata corpus. We would be happy to host mirrors at archive.org.

The existing options seem to be full enumeration via OAI-PMH, or to iterate through the REST API; the later seems like it could cause unnecessary load on your service.

**Comment by mfenner** [comment]
If you just want a list of all public DataCite DOIs, the quickest way is via the sitemap files at https://search.datacite.org/sitemaps/sitemap.xml.gz (also linked from https://search.datacite.org/robots.txt). 

We made significant changes to the REST API, most importantly switching to Elasticsearch and enabling deep paging via the `page[cursor]` query parameter (see https://support.datacite.org/docs/pagination for details).

**Comment by openAccess** [comment]
The root sitemap file seems to be stale or not updating correctly - there are actually more than 200 individual sitemaps. 

<sitemap><loc>https://search.datacite.org/sitemaps/sitemap1.xml.gz</loc>
<lastmod>2019-04-17T06:10:58+00:00</lastmod>
</sitemap>
<sitemap><loc>https://search.datacite.org/sitemaps/sitemap2.xml.gz</loc>
<lastmod>2019-04-17T06:10:59+00:00</lastmod>
</sitemap>
<sitemap><loc>https://search.datacite.org/sitemaps/sitemap3.xml.gz</loc>
<lastmod>2019-04-17T06:11:04+00:00</lastmod></sitemap>

**Comment by miku** [comment]
As a sidenote: #709 mentions a yearly data dump, that will be made available. Until then, there is datacite dump that has been created from the API, accessible here: https://archive.org/details/datacite_dump_20191122. 

> it would be useful to have a list of all DataCite DOIs

```
$ curl -sL "https://archive.org/download/datacite_dump_20191122/datacite.ndjson.xz" | \
    xz -cd | jq -r .attributes.doi
```

**Comment by kjgarza** [comment]
:wave: @maxogden, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
