### ISSUE TITLE
Some Creators with ORCID iDs do not appear in the Organization page Authors filter

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1891]
#### Expected Behaviour

The Creators with ORCID iDs that appear the most should appear in the Authors filter on the Organizations.

#### Current Behaviour

There are fewer entries in the Authors sidebar than expected. Also, there are inconsistent counts for the number of results.

#### Steps to Reproduce

Example with Tetiaroa Society page:

1. Go to https://commons.datacite.org/ror.org/04p8xrf95?rorid=04p8xrf95. The Authors filter only contains "BOSSIN, Hervé" with 4 results:
<img width="277" alt="Screen Shot 2023-07-24 at 17 52 06" src="https://github.com/datacite/datacite/assets/17298577/d63c6a35-9ab4-485f-8273-1e7948477801">

2. Click on BOSSIN, Hervé. Note this returns 6 Works when the filter originally said 4:
<img width="1212" alt="Screen Shot 2023-07-24 at 17 53 17" src="https://github.com/datacite/datacite/assets/17298577/ddfae784-a67b-4f01-8a3e-5a9785d39419">
The 6 DOIs are unique and they are all DataCite DOIs.

- https://doi.org/10.17913/f3mw27
- https://doi.org/10.17913/f3/100501.30885
- https://doi.org/10.17913/f3/100501.30879
- https://doi.org/10.17913/f3/100501.31234
- https://doi.org/10.17913/f3/100501.42690
- https://doi.org/10.17913/f3/100501.48843

3. Change the ORCID iD in the filter to Neil Davies' ORCID iD: https://commons.datacite.org/ror.org/04p8xrf95?filterQuery=creators.nameIdentifiers.nameIdentifier%3A%22https%3A%2F%2Forcid.org%2F0000-0001-8085-5014%22&rorid=04p8xrf95

4. Note the sidebar says 3 results and the list shows 4. Either way it is odd that Neil isn't in the sidebar.
<img width="1109" alt="Screen Shot 2023-07-24 at 17 54 37" src="https://github.com/datacite/datacite/assets/17298577/92d3d6b8-8315-402e-9f95-ac5ca5e829b4">

#### Hypothesis

This isn't quite a hypothesis but I tried out graphql queries and was able to replicate this there. Interestingly Hervé shows up for authors but not creatorsAndContributors:

```graphql
{ organization(id:"https://ror.org/04p8xrf95") {
  name
  id
  works (first:100) {
    authors {
      count
      id
      title
    }
    creatorsAndContributors {
      count
      id
      title
  }
  }
}
}
```

response:
```json
{
  "data": {
    "organization": {
      "name": "Tetiaroa Society",
      "id": "https://ror.org/04p8xrf95",
      "works": {
        "authors": [
          {
            "count": 4,
            "id": "https://orcid.org/0000-0002-3655-0923",
            "title": "BOSSIN, Hervé"
          }
        ],
        "creatorsAndContributors": []
      }
    }
  }
}
```

With a filter query for Hervé Bossin's ORCID they appear in both with 6 works:

```graphql
{ organization(id:"https://ror.org/04p8xrf95") {
  name
  id
  works (first:100, query: 
"creators.nameIdentifiers.nameIdentifier:\"https://orcid.org/0000-0002-3655-0923\"") {
  totalCount  
  authors {
      count
      id
      title
    }
    creatorsAndContributors {
      count
      id
      title
  }
  }
}
}
```

```json
{
  "data": {
    "organization": {
      "name": "Tetiaroa Society",
      "id": "https://ror.org/04p8xrf95",
      "works": {
        "totalCount": 6,
        "authors": [
          {
            "count": 6,
            "id": "https://orcid.org/0000-0002-3655-0923",
            "title": "BOSSIN, Hervé"
          }
        ],
        "creatorsAndContributors": [
          {
            "count": 6,
            "id": "https://orcid.org/0000-0002-3655-0923",
            "title": "BOSSIN, Hervé"
          }
        ]
      }
    }
  }
}
```

**Comment by jrhoads** [comment]
It turns out that non-orcid identifiers for names were getting picked up when we created the facets here
https://github.com/datacite/lupo/blob/38c5b5387c83f71201bcfb110e166053334822fc/app/models/doi.rb#L670

And then filtered out since they were not orcids here
https://github.com/datacite/lupo/blob/38c5b5387c83f71201bcfb110e166053334822fc/app/controllers/concerns/facetable.rb#L469

So the if the top 10 faceted identifiers were mostly or all non-orcid then the final result would be a mostly empty or empty array.
