### ISSUE TITLE
DataCite schema: appropriate method for describing a workflow

### ISSUE THREAD

**Issue by hrzepa** [datacite/datacite#190]
We generate metadata for sending to DataCite using a workflow that includes scanning of submitted datasets using text and content mining software  and then deriving canonical identifiers using other software.  To allow others to reproduce this process, we need to record the software used, along with version numbers etc, and indeed perhaps a  PID to the overall workflow used.

What are the best parts of Scheme 4.0 for this application, or is there something in  V5.0 that would be appropriate?

**Comment by mfenner** [comment]
Schema 4.0 and its documentation each have a DOI: http://schema.datacite.org/meta/kernel-4.0/.
