### ISSUE TITLE
Transfer 68 DOIs to VZEK.GESISBLOG

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1904]
old repository ID: gesis.gesis
New repository ID: VZEK.GESISBLOG
Prefix: 10.34879 (also transfer prefix)
Number of DOIs: 68

[10.34879_vzek.gesisblog.csv](https://github.com/datacite/datacite/files/12312638/10.34879_vzek.gesisblog.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3zkwl)

**Comment by codycooperross** [comment]
Prefix 10.34879 and the 68 DOIs have been transferred to VZEK.GESISBLOG.
