### ISSUE TITLE
Transfer subset of 493 to JFCH.YSNBOE

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1905]
Old Repository ID: DANS.ARCHIVE
New Repository ID: JFCH.YSNBOE
Number of DOIs: 493
Prefix: do not transfer

[DANS to CenterData - DOI (2).xlsx](https://github.com/datacite/datacite/files/12312825/DANS.to.CenterData.-.DOI.2.xlsx)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3zl79)

**Comment by codycooperross** [comment]
The 493 DOIs have been transferred to JFCH.YSNBOE.
