### ISSUE TITLE
Transfer 11 DOIs to VZEK.GESISONLINE

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1909]
old repository ID: gesis.gesis
New repository ID: VZEK.GESISONLINE
Prefix: 10.17622 (also transfer the prefix)
Number of DOIs: 11

[dois_10.17622.csv](https://github.com/datacite/datacite/files/12367574/dois_10.17622.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_42a39)

**Comment by codycooperross** [comment]
The 11 DOIs and prefix 10.17622 have been transferred to VZEK.GESISONLINE.
