### ISSUE TITLE
Transfer 108 DOIs to VZEK.PRETEST

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1911]
old repository ID: gesis.gesis
New repository ID: VZEK.PRETEST
Prefix: 10.17173
Number of DOIs: 108

[dois_10.17173_pretest.csv](https://github.com/datacite/datacite/files/12371854/dois_10.17173_pretest.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_42jv9)

**Comment by codycooperross** [comment]
Prefix 10.17173 and the 108 DOIs have been transferred to VZEK.PRETEST.
