### ISSUE TITLE
Newlines in description properties are removed when read from DataCite XML

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#1920]
### Describe the bug

Newlines in description properties are removed when submitted and read from DataCite XML. For example, when submitting DataCite XML via MDS API or via the file upload in Fabrica, a description XML property like this: 

        <description xml:lang="de" descriptionType="Abstract">Dies ist ein Test.
          Dies ist eine zweite Zeile.
          Dies ist eine dritte Zeile.</description>
          
Will appear like so in the REST API and as DataCite JSON:

        "descriptions": [
        {
        "lang": "de",
        "description": "Dies ist ein Test. Dies ist eine zweite Zeile. Dies ist eine dritte Zeile.",
        "descriptionType": "Abstract"
        }
        ],

#### Expected Behaviour

Newlines in descriptions are maintained across formats.

#### Current Behaviour

Newlines in descriptions are removed when read from DataCite XML and potentially other formats.

#### Steps to Reproduce

Submit above DataCite XML description property via MDS API, Fabrica file upload, etc. 

#### Hypothesis

When reading from DataCite JSON, bolognese uses a `sanitize` method that is likely the culprit: https://github.com/datacite/bolognese/blob/010a854e642fefdcdf17d04dffa2b4de8721808c/lib/bolognese/readers/datacite_reader.rb#L97-L105

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4a8r9)

**Comment by ashwinisukale** [comment]
**Root case:**

We are using the https://github.com/datacite/bolognese/blob/010a854e642fefdcdf17d04dffa2b4de8721808c/lib/bolognese/utils.rb#L1060 `squish` method to remove new lines, extra internal spaces and any ASCII or unicodes form the string.
eg.
`" foo   bar    \n   \t  \u2003Hello\u2009  boo".squish # => "foo bar Hello boo" `

**Question**

@KellyStathis @codycooperross do we want to keep the description as it is? for example if description has any extra internal spaces or new lines.?

What I think is we can keep internal spaces or new lines and just remove the ASCII or unicodes from the string.

**Comment by KellyStathis** [comment]
@ashwinisukale I'm sorry for the delay getting back to you!

I think it would be helpful to allow newlines to remain in the description. I'm not sure what we should accept as new lines (`\n`, `U+000A`, `<br>`). @codycooperross may be of more help here!

I will note that the schema documentation currently advises using `<br>`: https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/descriptionType/. If we remove support for `<br>` in our systems, ideally this would wait for a new schema version so we can update the documentation.

**Comment by ashwinisukale** [comment]
Thanks @KellyStathis for the clarification :)

As per the discussion with Kelly in the call, we are going to keep new lines for the `description` element only, not for the other XML node elements.
