### ISSUE TITLE
Commons unable to search on staging

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1933]
After upgrading package dependencies you are unable to search on any page.
The error only appears on production builds

Recreate with
yarn build
yarn start

This shows an error in javascript console.

**Comment by richardhallett** [comment]
The above PR will fix the error by updating nextjs to a newer version. As per PR notes I believe this is due to the webpack upgrade within nextjs that presumably fixes some problem we're having with minifying part and certain packages, notably vega-embed.

However upgrading to this also ugprades the react version and therefore we'd also need to upgrade cypress.

**Comment by codycooperross** [comment]
I believe this is resolved.
