### ISSUE TITLE
DataCite Commons gives a 401 in some browsers

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1940]
#### Expected Behaviour

A user can search in Commons in all browsers regardless as to whether they are logged in or out

#### Current Behaviour

When searching in Firefox and Chrome, a 401 error is generated. This looks to be related to the browser session expiring because it was resolved when logging in.

#### Steps to Reproduce

1. Log in to Commons
2. Leave the session open in the browser
3. Return to run a search
4. 401 error

https://app.usersnap.com/#/projects/dcda5f2e-46d4-4590-a8c4-b8d6d5bdaac6/list?number=1304

**Comment by jrhoads** [comment]
@MaryHirsch and @codycooperross 

Do you still see this behavior?  I am not able to repeat it.

**Comment by codycooperross** [comment]
I'm not sure I can reproduce this. @MaryHirsch , OK to close?

**Comment by MaryHirsch** [comment]
Yes, I cannot reproduce either. thanks.
