### ISSUE TITLE
Certain DOIs cause 422 errors when requesting DataCite XML via content negotiation

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#1942]
### Describe the bug

Certain DOIs cause 422 errors and return the message "The request could not be processed" when requesting DataCite XML via content negotiation

#### Expected Behaviour

The DataCite XML is returned. 

#### Current Behaviour

A 422 error is returned with the message "The request could not be processed"

#### Steps to Reproduce

Run `curl -LH "Accept: application/x-datacite+xml" https://data.datacite.org/10.3205/23gma016` or any other command pulling DC XML metadata for DOI `10.3205/23gma016`

#### Hypothesis

From local testing, this seems to be caused by an older bug in an earlier version of bolognese installed with content-negotiation. The bug seems to occur in a relatedItems block, so some or all DOIs with relatedItems may be affected.

#### Possible Implementation

Updating bolognese to the latest version in content-negotiation. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4l2vp)

**Comment by ashwinisukale** [comment]
@codycooperross 
I tried the above DOI, when use curl I do get the same error message, but when I tried it through test case, I do get the metadata.

https://github.com/datacite/bolognese/blob/master/spec/datacite_utils_spec.rb#L6

I replaced the input URL here in the test case, and deleted VCR cassette of first test, and checked the response, 
```
describe Bolognese::Metadata, vcr: true do
  let(:input) { "https://doi.org/10.3205/23gma016" }

  subject { Bolognese::Metadata.new(input: input, from: "datacite") }

  context "insert_identifier" do
    it "doi" do
      byebug
      xml = Nokogiri::XML::Builder.new(:encoding => 'UTF-8') { |xml| subject.insert_identifier(xml) }.to_xml
      response = Maremma.from_xml(xml)
      expect(response["identifier"]).to eq("identifierType"=>"DOI", "__content__"=>"10.5061/dryad.8515")
    end
  end
end
```

**Comment by ashwinisukale** [comment]
This is fixed now
