### ISSUE TITLE
Transfer 2915 DOIs to DRYAD.DRYAD

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1955]
Old repo id: (CDL.CDL 17, CDL.UCD 646, CDL.UCSB 257, CDL.CDL 8, CDL.UCLA 224, CDL.UCM 119, CDL.UCSD 115, CDL.UCB 503, CDL.UCR 174,  CDL.UCSF 283, CDL.UCI 345, CDL.UCI 224)
[EZID Dryad DOIs for DataCite Transfer (2023-11-02) - Final list for DataCite.csv]
New repo id:DRYAD.DRYAD
prefixes: none
DOIs: 2915 (total)

(https://github.com/datacite/datacite/files/13278787/EZID.Dryad.DOIs.for.DataCite.Transfer.2023-11-02.-.Final.list.for.DataCite.csv)

note: in the sheet the CDL.UCB DOIs are separated into two sections.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4z05x)

**Comment by codycooperross** [comment]
The 2195 listed DOIs have been transferred to DRYAD.DRYAD. No prefixes have been transferred.
