### ISSUE TITLE
Commons/GraphQL: DOI with affiliationIdentifier not appearing in Organization works list

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1958]
#### Expected Behaviour

The DOI `10.57760/sciencedb.07968` has two creators with the affiliationIdentifier `https://ror.org/05f0yaq80` for Stockholm University: https://api.datacite.org/dois/10.57760/sciencedb.07968?affiliation=true. 

Therefore, this DOI should appear on the Organization page for Stockholm University in Commons.

#### Current Behaviour

The DOI is not part of the Works list: 
https://commons.datacite.org/ror.org/05f0yaq80?filterQuery=10.57760%2Fsciencedb.07968

or returned by this GraphQL query:
```
{
  organization(id: "https://ror.org/05f0yaq80") {
    name
    id
    works (first:4000) {
      totalCount
      nodes {
        id
      }
    }
  }
}
```

#### Steps to Reproduce

search for the DOI in Commons:
https://commons.datacite.org/ror.org/05f0yaq80?filterQuery=10.57760%2Fsciencedb.07968

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4zwr9)

**Comment by codycooperross** [comment]
@KellyStathis The metadata is lacking `affiliationIdentifierScheme="ROR"` in the affiliation metadata, which seems to be causing this issue.

**Comment by KellyStathis** [comment]
Thanks @codycooperross , I had missed that detail! I think in that case this is not a bug, the repository needs to update the metadata to include `affiliationIdentifierScheme="ROR"`.
