### ISSUE TITLE
Transfer 135 DOIs into two subsets

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1982]
Old Repository ID: TIB.TUCHEM 

New repo 1: IFOT.OEZNAP
Transfer subset of 107 DOIs with prefix 10.14464
[10.14464.csv](https://github.com/datacite/datacite/files/13718335/10.14464.csv)

New repo 2: IFOT.FKMXDR
Transfer subset of 27 DOIs with prefix 10.21935
[10.21935.csv](https://github.com/datacite/datacite/files/13718325/10.21935.csv)

Total DOIs: 135

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5giqd)

**Comment by codycooperross** [comment]
The 135 DOIs have been transferred to IFOT.OEZNAP and IFOT.FKMXDR.
