### ISSUE TITLE
Transfer subset of DOIs to XAQP.JAMQZM

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1990]
Old Repository ID: TIB.LDEO 
New Repository ID: XAQP.JAMQZM
DOI: 1437 (739 + 698)
Prefixes: 10.26022 and 10.1594 (do not transfer)

[ecl_dois_10302023 (1).csv](https://github.com/datacite/datacite/files/13888133/ecl_dois_10302023.1.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5nnh1)

**Comment by codycooperross** [comment]
The 1437 DOIs have been transferred to XAQP.JAMQZM.
