### ISSUE TITLE
Transfer subset of DOIs to OCUL.SPDV

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2001]
Old Repository ID: UMAN.DATAVERSE

New Repository ID: OCUL.SPDV

Prefix: 10.5203 and 10.34990

DOIs: 502
Prefix 1: 10.5203 prefix includes 141 DOIs
Prefix 2: 10.34990 prefix includes 359 DOIs

[doi_dataverse_Nov08 (2).xlsx](https://github.com/datacite/datacite/files/13922533/doi_dataverse_Nov08.2.xlsx)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5ozdh)

**Comment by MaryHirsch** [comment]
Hi Suzanne. The University of Manitoba have requested this transfer on Monday. please see linked Front ticket for further details. Thank you!

**Comment by richardhallett** [comment]
Transfered as per the attached spreadsheet.
FYI: There are still 7 DOIS remaining in UMAN.DATAVERSE I do not know if this intentional: https://doi.datacite.org/repositories/uman.dataverse/dois?client-id=uman.dataverse&page=NaN
If not I suggest just manually moving if required.
