### ISSUE TITLE
Transfer subset of DOIs to VZEK.SDM

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2003]
Old repository ID: gesis.gesis
New repository ID: VZEK.SDM
Prefix: 10.15465
Number of DOIs: 88

[dois_10.15465.csv](https://github.com/datacite/bracco/files/13953171/dois_10.15465.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5q1g5)

**Comment by codycooperross** [comment]
The 88 DOIs and prefix 10.15465 have been transferred to VZEK.SDM.
