### ISSUE TITLE
This website is under heavy load (queue full)

### ISSUE THREAD

**Issue by hrzepa** [datacite/datacite#204]
Requests such as e.g. http://data.datacite.org/chemical/x-mnpub/10.14469/hpc/1281

are returning 

_This website is under heavy load (queue full)
We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later._

Its been like this for 3-4 days now?

**Comment by dhimmel** [comment]
We have seen this error is some of our build logs as well!

**Comment by mfenner** [comment]
This has been fixed in October. Please report if there are again issues.
