### ISSUE TITLE
Transfer subset of DOIs to YLYL.FAIR 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2046]
Old repository ID: BL.OXDB (NB: only DOIs with prefix 10.25504 to be migrated - all other prefixes stay in the old repository)
New repository ID: YLYL.FAIR 
Prefix: 10.25504 (transfer prefix to new repo)
Number of DOIs: 3,920 (as at 25/01/2024)

[FAIRsharing_DOIs.csv](https://github.com/datacite/datacite/files/14086359/FAIRsharing_DOIs.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5wx91)

**Comment by codycooperross** [comment]
The listed DOIs and prefix 10.25504 have been transferred to YLYL.FAIR. Because of duplicates in the original CSV, the following DOIs were also transferred:
[20240129-bl.oxdb-1.csv](https://github.com/datacite/datacite/files/14101388/20240129-bl.oxdb-1.csv)
