### ISSUE TITLE
Transfer prefix 10.25834  and 10.24363 to Crossref

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2050]
Prefix 10.25834 and 10.24363
repository, MTAKIK.BTKNT and MTAKIK.MRADIOL
123 DOIs and 0 DOIS
status: delete

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5yknp)

**Comment by MaryHirsch** [comment]
@codycooperross prefixes 10.25834 and 10.24363 have been transferred to Crossref and can be deleted and the metadata set to registered state. Thanks.

**Comment by codycooperross** [comment]
Prefixes 10.25834 and 10.24363 have been removed from DataCite and their associated metadata has been set to Registered state.
