### ISSUE TITLE
Example data in JSON doesn't correspond to XML, and have both missing and extra properties   

### ISSUE THREAD

**Issue by edager** [datacite/datacite#2063]
The xml and json version of the full example on found at https://schema.datacite.org/meta/kernel-4.5/index.html does not contain the same information, and there appear to be inconsistencies in the JSON version.

### Describe the bug

The  "contributors" in the JSON version of the [full example](https://api.test.datacite.org/dois/10.82433/B09Z-4K37?publisher=true&affiliation=true)  is populated with  "schemeUri" and "nameIdentifierScheme" without having a "nameIdentifier", which doesn't really make sense. 

It especially doesn't make sense given that  "nameIdentifier" is present in the [XML version](https://schema.datacite.org/meta/kernel-4.5/example/datacite-example-full-v4.xml) of most of the "contributors".       

#### Expected Behaviour

The xml and json should contain the same information, and "schemeUri" and "nameIdentifierScheme" should only be present if 
"nameIdentifier" is present.

#### Steps to Reproduce

1. Go to  https://api.test.datacite.org/dois/10.82433/B09Z-4K37?publisher=true&affiliation=true
2. compare with https://schema.datacite.org/meta/kernel-4.5/example/datacite-example-full-v4.xml

### Context (Environment)

I'm trying to implement schema version 4.5 into Invenio's datacite wrapper, however for that I need valid test data. Both to be able to make sure that the json-schema can validate a full metadata set, but also to make sure that we can freely convert between the xml and json versions.   

#### Hypothesis

Looks like an error in conversion from XML to JSON

**Comment by KellyStathis** [comment]
Thanks for reporting this @edager. I think there are a couple issues here: 
- These two examples were meant to be equivalent, but there are [numerous differences in the values](https://www.diffchecker.com/yUUfy1Ab/) including Dates (2023 vs 2022), Rights (CC-BY vs public domain), and others. This is a human error - the XML hosted on the schema site is static whereas the JSON shared is for a test DOI, so they were manually updated separately and got out of sync. I'll look into correcting this soon!

- There may also be a conversion problem with contributor nameIdentifier, as I'm seeing these are missing from [JSON](https://api.test.datacite.org/dois/10.82433/B09Z-4K37?publisher=true&affiliation=true) but present in the [XML](https://api.test.datacite.org/dois/application/vnd.datacite.datacite+xml/10.82433%2Fb09z-4k37) for the same test DOI. We'll compare these more closely and look into the cause.
