### ISSUE TITLE
Transfer subset of DOIs to SMF.REPO

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2067]
Old Repository ID: SWIN.REPO2
New Repository ID: SMF.REPO
Prefix: do not transfer.
DOIs:1,324 DOIs 

[APO DOIS TO MOVE.csv](https://github.com/datacite/datacite/files/14404184/APO.DOIS.TO.MOVE.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6af4l)

**Comment by codycooperross** [comment]
The listed DOIs were transferred to SMF.REPO aside from 10.4225/50/589a464ee7471, which is not a registered DOI.
