### ISSUE TITLE
Kong Error  An invalid response was received from the upstream server.

### ISSUE THREAD

**Issue by hrzepa** [datacite/datacite#207]
When submitting a query such as 

http://data.datacite.org/chemical/x-mnpub/10.14469/hpc/1281

Kong Error  An invalid response was received from the upstream server.

The issue seems intermittent/temporary?

**Comment by dhimmel** [comment]
Likely related to https://github.com/datacite/datacite/issues/212. DOI Content Negotiation for DataCite DOIs seems to be entirely unavailable.

**Comment by mfenner** [comment]
Fixed in October. Please report if there are again issues.
