### ISSUE TITLE
DOI Fabrica BlogPost

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#208]
https://github.com/datacite/blog/blob/master/source/posts/doi-fabrica-announcement.html.md

**Comment by pcruse** [comment]
@kjgarza I am getting a 404 error here https://github.com/datacite/blog/blob/master/source/posts/doi-fabrica-announcement.html.md

**Comment by kjgarza** [comment]
I don't think the blog post has been finished yet.

Britta might have a update on this.
