### ISSUE TITLE
Transfer subset of DOIs to SWIN.REPO2

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2092]
Old repository ID: SWIN.REPO1
New repository ID: SWIN.REPO2
Prefixes: do not transfer
DOIs: 44

[SWIN.REPO1.csv](https://github.com/datacite/datacite/files/14745041/SWIN.REPO1.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6oqs5)

**Comment by codycooperross** [comment]
The 44 listed DOIs have been transferred to SWIN.REPO2.
