### ISSUE TITLE
Including a non-existant prefix at the `/prefixes` endpoint results in 500 error

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#2109]
### Describe the bug

Including a non-existant prefix at the `/prefixes` endpoint results in 500 error

https://api.datacite.org/prefixes/10.60890

#### Expected Behaviour

If a prefix doesn't exist, the API should return a 404. 

#### Current Behaviour

The API returns a 500 error.

#### Steps to Reproduce

1. Go to https://api.datacite.org/prefixes/10.608900 (non-existant)
2. Compare with https://api.datacite.org/prefixes/10.60890 (existing)

**Comment by wendelfabianchinsamy** [comment]
@codycooperross I have a fix for this. This has come up as a result of the Rails 7.1 upgrade. Here is the pr -> https://github.com/datacite/lupo/pull/1180
