### ISSUE TITLE
Clicking the `Add to ORCID Record` in Commons button does not claim the DOI in ORCID record

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#2110]
### Describe the bug

Clicking the `Add to ORCID Record` in Commons button does not claim the DOI in ORCID record. The button does not transition to a waiting state, the claim does not appear in Profiles/volpino, and the DOI does not appear in the relevant ORCID record.

#### Expected Behaviour

The claimed DOI is added to the relevant ORCID record.

#### Current Behaviour

The interface does not react and the claim does not occur. 

#### Steps to Reproduce

1. Use the `Add to ORCID Record` button on any Commons DOI page, ex. https://commons.datacite.org/doi.org/10.14454/3w3z-sa82 

#### Further details

The GQL `createClaim` operation seems to go out and receives a 200 response, but this does not generate a claim in Profiles/volpino https://profiles.datacite.org/admin/claims 

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7ijkl)

**Comment by wendelfabianchinsamy** [comment]
@bklaing2 it appears the button is disabled in the html and as such does support any click events. As such, I don't believe this is related to the Lupo upgrade.

![image](https://github.com/datacite/datacite/assets/9653909/6a3d3d8b-18a6-4de8-a5df-d86458913457)
