### ISSUE TITLE
Usage Reports API is returning 500 requests primarily affecting POST requests

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#2117]
### Describe the bug

The Usage Reports API is returning 500 requests. This primarily seems to be affecting POST requests and the creation of new reports. PUT and GET requests seems unaffected. 

#### Steps to Reproduce

See logs in Datadog: https://app.datadoghq.com/logs?query=%40http.url_details.path%3A%2Freports%2A%20&agg_m=count&agg_m_source=base&agg_q=%40http.status_code%2C%40aws.awslogs.logGroup&agg_q_source=base%2Cbase&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&storage=hot&stream_sort=desc&top_n=10%2C10&top_o=top%2Ctop&viz=stream&x_missing=true%2Ctrue&from_ts=1712678225924&to_ts=1713974225924&live=true 

#### Hypothesis

The appearance of the 500 errors seems to align with the Rails 7.1 release. 

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_73bo5)

**Comment by wendelfabianchinsamy** [comment]
![image](https://github.com/datacite/datacite/assets/9653909/5fd5eb37-ddfc-4592-891d-08025f99539e)
The issue has not happened in the last four hours.

Seems to have begun on the 18th April 2024.
So far, nothing found in the logs (Datadog or Cloudwatch).
