### ISSUE TITLE
DOI Content Negotiation failing for all DataCite DOIs

### ISSUE THREAD

**Issue by dhimmel** [datacite/datacite#212]
As our [builds show](https://travis-ci.org/greenelab/scihub-manuscript/builds/285690098#L2009), it appears that DOI [content negotiation](https://citation.crosscite.org/docs.html) is currently failing (5:28 PM, Monday, October 9, 2017, Coordinated Universal Time (UTC)) for DataCite but not Crossref DOIs. Specifically, API calls for the following DOIs failed:

```
Citeproc retrieval failed for:
doi:10.5061/dryad.q447c/1
doi:10.5062/f4g73bp3
doi:10.5281/zenodo.472493
doi:10.6084/m9.figshare.1186832.v23
doi:10.6084/m9.figshare.3443876.v3
doi:10.6084/m9.figshare.4542433.v6
doi:10.6084/m9.figshare.4816720.v1
doi:10.6084/m9.figshare.5231245.v1
doi:10.6084/m9.figshare.5255365.v1
doi:10.6084/m9.figshare.5255368.v1
doi:10.7287/peerj.preprints.3100v1
doi:10.7287/peerj.preprints.3119v1
```

Over the last few weeks, it seems that DataCite DOI Content Negotiation has been really spotty! This is not ideal as we're using these APIs in production and it's essential to be able to get metadata for DOIs.

Here is an example of a failing query:

```sh
curl --location \
  --header "Accept: application/vnd.citationstyles.csl+json" \
  https://doi.org/10.7287/peerj.preprints.3100v1
```

Which returns:

```
An invalid response was received from the upstream server
```

Tagging @mfenner.

**Comment by hrzepa** [comment]
Also #204  where content negotiation failure was reported about two weeks ago.

**Comment by mfenner** [comment]
I changed the proxy configuration.

@dhimmel I have done some load testing (see attached screenshot), and there seem to be bigger issues. Will investigate further.

<img width="954" alt="bildschirmfoto 2017-10-12 um 01 42 44" src="https://user-images.githubusercontent.com/23151/31472388-bac1e7ec-aeee-11e7-9934-cfb927c916a4.png">

**Comment by mfenner** [comment]
Fixed in October. Please report if there are new issues.
