### ISSUE TITLE
Transfer a subset of DOIs to SMF.REPO

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2122]
Old repository ID: SWIN.REPO2 
New repository ID: SMF.REPO
Prefix: do not transfer
DOIs: 53

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_76gt1)

**Comment by codycooperross** [comment]
The 53 DOIs are now in the SMF.REPO.
