### ISSUE TITLE
Transfer subset of DOIs to NIHOD.BIOC

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2124]
Consortium Organization: NIHNCI

Existing Repository: NIHNCI.NCI

New repository ID: NIHOD.BIOC

Prefix: 10.18129  (also transfer the prefix)

DOIs: All DOIs with prefix 10.18129 (4,185) PLUS two registered DOIs (https://doi.org/10.18121/n2rp4v and https://doi.org/10.17917/b9.bioc.escher)

[Bioc_dois.csv](https://github.com/datacite/datacite/files/15251388/Bioc_dois.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_79uc5)

**Comment by codycooperross** [comment]
4113 DOIs and prefix 10.18129 were transferred to NIHOD.BIOC. There were 74 duplicates in the provided list, accounting for the reduced DOI transfer count.
