### ISSUE TITLE
DOI Content Negotiation redirecting from HTTPS to HTTP

### ISSUE THREAD

**Issue by larsgw** [datacite/datacite#213]
Basically the same as https://github.com/CrossRef/rest-api-doc/issues/221, only this time with DataCite. Sample cURL:

     curl -X GET https://doi.org/10.5281/zenodo.1005176 -H 'accept: application/vnd.citationstyles.csl+json' -H 'cache-control: no-cache' -v

Response:

```
< HTTP/1.1 303 See Other
< Server: Apache-Coyote/1.1
< Vary: Accept
< Location: http://data.datacite.org/10.5281%2Fzenodo.1005176
< Expires: Wed, 11 Oct 2017 21:08:47 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 183
< Date: Wed, 11 Oct 2017 20:50:34 GMT
< 
<html><head><title>Handle Redirect</title></head>
* Curl_http_done: called premature == 0
* Connection #0 to host doi.org left intact
<body><a href="http://data.datacite.org/10.5281%2Fzenodo.1005176">http://data.datacite.org/10.5281%2Fzenodo.1005176</a></body></html>
```

**Comment by mfenner** [comment]
I am making some proxy configuration changes to address the issues several people are seeing, and I am not done yet. Keep in mind that the DataCite and Crossref content negotation services are unrelated after the first redirection from https://doi.org.

**Comment by larsgw** [comment]
Okay, I just meant that the symptoms seem the same on my end. By the way, the http page seems to actually get redirected back to https, but this still causes mixed content errors.

**Comment by mfenner** [comment]
Thanks for reporting. http/https will behave weird until my changes are done, hopefully in the next hour (when our proxy server is rebuilt using a script and deployed).
