### ISSUE TITLE
XML contained in the base64 encoded xml attribute of the json payload is not being processed on the server side on a test repository 

### ISSUE THREAD

**Issue by nickbywell** [datacite/datacite#2130]
### Describe the bug
Using both v1.1.3 of the pypi datacite python package with the "draft_doi" method and curl calls via a command window, the server side of the API does not seem to process the content of a base64 encoded xml attribute in the json payload, and subsequently display it in a datacite test repository.

#### Expected Behaviour
The relevant xml elements should be displayed within the doi record created in a test respository.
I do not yet have access to a production repository, so cannot say whether it is processed in that environment.

#### Current Behaviour
The following error message is returned:
{"errors":[{"status":"400","title":"Error occurred while parsing request parameters"}]}

Presumably, the "title" is the first mandatory field the processing looks for, and when it does not find it in the json, and then fails to process the encoded xml, it stops and reports the error indicated above.

#### Steps to Reproduce
The relevant propcessing is indicated in the datacite documentation, about two thirds of the way down page https://support.datacite.org/docs/api-create-dois

### Context (Environment)
When our requirements became a bit more complex, I thought it would be more elegant/efficient to use xml rather than purely json.

**Comment by codycooperross** [comment]
Apologies for not catching this issue sooner, and thank you for taking the time to submit! The best way to report an issue or question related to DataCite services or metadata is via our support channel [support@datacite.org](mailto:support@datacite.org). This way we can ensure it is triaged to the right people in line with our standard workflows and you get a prompt response to your query. Hoping you've already found us there!
