### ISSUE TITLE
Transfer subset of DOIs and prefix to WZBDE.RATSWD

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#2139]
Consortium Organization: WZBDE

Existing Repository:  gesis.wzb

New repository ID: WZBDE.RATSWD

Prefix: 10.17620 (also transfer the prefix)
- Also remove 10.60835 from WZBDE.RATSWD and 10.48581 from GESIS.WZB - both unused

DOIs: 93 DOIs [ratswd_10.17620.csv](https://github.com/datacite/datacite/files/15458172/ratswd_10.17620.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7fvbp)

**Comment by codycooperross** [comment]
The listed DOIs and prefix 10.17620 have been transferred to WZBDE.RATSWD. 10.60835 and 10.48581 have been removed from WZBDE.RATSWD and GESIS.WZB respectively.
