### ISSUE TITLE
Transfer subset of 173 DOs to QEFW.IQS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2159]
Old repository ID: gesis.bifie
New repository ID: QEFW.IQS
Prefix: 10.17888 (please also transfer the prefix)
Number of DOIs: 173

[10.17888 (1).csv](https://github.com/user-attachments/files/15911737/10.17888.1.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7ivpx)

**Comment by codycooperross** [comment]
Prefix 10.17888 and the 173 listed DOIs have been transferred to QEFW.IQS.
