### ISSUE TITLE
Transfer 2 subsets of DOIs 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2162]
prefix 10.18444
old repository ID: gesis.rki
new repository ID: EPUA.ZFKD
number of DOIs: 17
[10.184444.csv](https://github.com/user-attachments/files/15987340/10.184444.csv)

prefix 10.7797
old repository ID: gesis.rki
new repository ID: EPUA.RDCRKI
number of DOIs: 17
[10.7797.csv](https://github.com/user-attachments/files/15987356/10.7797.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7jkt1)

**Comment by codycooperross** [comment]
Prefix 10.18444 and the listed DOIs have been transferred to EPUA.ZFKD.
Prefix 10.7797 and the listed DOIs have been transferred to EPUA.RDCRKI.
