### ISSUE TITLE
Transfer subset of DOIs to JBRU.COCOON

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2163]
Old repository ID: INIST.HUMANUM 
New repository ID: JBRU.COCOON
Not the prefix
DOIs: 24565
[DOI-COCOON-A-MIGRER.txt](https://github.com/user-attachments/files/16010359/DOI-COCOON-A-MIGRER.txt)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7jnx1)

**Comment by codycooperross** [comment]
The 24565 listed DOIs have been transferred to JBRU.COCOON.
