### ISSUE TITLE
Transfer subsets of DOIs to REPOD.MXRDR and REPOD.RDS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2168]
Old repository ID: TIB.REPOD
New repository ID: REPOD.MXRDR
Prefix: 10.18150 do not transfer
Number of DOIs: 492
[REPOD.MXRDR.txt](https://github.com/user-attachments/files/16264152/REPOD.MXRDR.txt)

Old repository ID: TIB.REPOD
New repository ID: REPOD.RDS
Prefix: 10.18150 do not transfer
Number of DOIs: 453
[REPOD.RDS.txt](https://github.com/user-attachments/files/16264150/REPOD.RDS.txt)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7m07p)

**Comment by codycooperross** [comment]
The 453 DOIs listed in REPOD.RDS.txt were transferred from TIB.REPOD to REPOD.RDS.
491 of the DOIs listed in REPOD.MXRDR.txt were transferred from TIB.REPOD to REPOD.MXRDR. One DOI (10.18150/ZVP6LT) did not appear in our systems.
