### ISSUE TITLE
Transfer 2 RADS prefixes to Crossref

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#2186]
Prefixes:
10.25985
10.48445
repository: RADS.MAIN
324 DOIs
Status: approved

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7pwt1)

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.48445 has been transferred to Crossref and can be deleted and the associated metadata set to registered. Thanks.

**Comment by codycooperross** [comment]
Prefix 10.48445 has been removed from DataCite and its associated metadata has been set to Registered state.

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.25985 has been transferred to Crossref and can be deleted and the associated metadata set to registered state,. Thanks.

**Comment by codycooperross** [comment]
Prefix 10.25985 has been removed from DataCite and its associated metadata has been set to Registered state.

**Comment by MaryHirsch** [comment]
@codycooperross prefix 10.25985 has been transferred to Crossref and can be deleted and the associated metadata set to registered state. thanks.
