### ISSUE TITLE
REST API /totals endpoints lack pagination

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#2196]
#### Expected Behaviour

All REST API endpoints returning lists of results have pagination, with a max page size of 1,000 records. 

#### Current Behaviour

- https://api.datacite.org/clients/totals has 2,774 results in the response.
- https://api.datacite.org/providers/totals has 1,290 results in the response.
- https://api.datacite.org/prefixes/totals returns 204 no content, but has the same structure without pagination (e.g. https://api.datacite.org/prefixes/totals?client-id=datacite.blog,dryad.dryad).

Each of these returns a single array and doesn't follow our usual list response structure with "data", "meta", and "links" sections.

#### Steps to Reproduce

see above
#### Further details

I was reviewing openapi.yaml when I noticed this. I actually don't know where or how these /totals endpoints are typically used.

#### Possible Implementation

while some variability in default page size could be ok if documented, returning over 2K results in a single response is difficult to work with.

**Comment by codycooperross** [comment]
I'm not sure this is a bug as this is the intended representation. I believe the call is primarily used for the [DataCite Statistics](https://support.datacite.org/docs/datacite-statistics#retrieving-statistics-via-the-rest-api) page and potentially by users for reporting. In either case, pagination would be a breaking change.

**Comment by KellyStathis** [comment]
Thanks for the additional context about where this is used! When this was first implemented, we didn't have as many clients/providers and we could get away with not having pagination; I'd view the inconsistency with our other endpoints as an oversight. I realize this would be a breaking change, though—maybe there is a better spot for this idea.

**Comment by KellyStathis** [comment]
Noting this is documented for users here: https://support.datacite.org/docs/datacite-statistics#retrieving-statistics-via-the-rest-api

**Comment by codycooperross** [comment]
Helpful feedback for sure! Would you mind logging this as a suggestion instead since it's not a broken feature? I think it might be helpful to think about in the context of other enhancements. You can link to this issue.

**Comment by KellyStathis** [comment]
Filed as a suggestion here: https://github.com/datacite/datacite-suggestions/discussions/100
