### ISSUE TITLE
Google Analytics not receiving any Commons analytics data since 2024-06-04

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#2199]
### Describe the bug

Google Analytics is not receiving any Commons analytics data since 2024-06-04. 

#### Expected Behaviour

Google Analytics data is sent by Commons pages.

#### Current Behaviour

No Google Analytics data exists since 2024-06-04 after a drop-off starting around 2024-04-13.  

#### Steps to Reproduce

1. Check https://analytics.google.com/analytics/web/#/p316928511/reports/intelligenthome?params=_u..nav%3Dmaui 

#### Hypothesis

This may have to do with the transition to app router since the timing seems to line up with the gradual transition to app router pages ending on June 5.

**Comment by jrhoads** [comment]
I think the hypothesis is correct.  In the pages router there was an explicit call to GA and an event that was triggered.

This was set up in the [_app.tsx file](https://github.com/datacite/akita/blob/a5a26496e2fe548b41f1cbd95d523f47190627ae/src/pages/_app.tsx#L30)

This is currently not present using the app router.  The method of doing so may have changed, but this is what we should be looking to do.
