### ISSUE TITLE
Usage reports from the Usage Tracker service are not currently generating usage events

### ISSUE THREAD

**Issue by codycooperross** [datacite/datacite#2200]
### Describe the bug

Usage reports from the Usage Tracker service are not currently generating usage events. 

#### Expected Behaviour

The Usage Tracker service generates usage reports on a monthly basis and usage events are generated from them. 

#### Current Behaviour

No usage events appear for Usage Tracker service usage reports.

#### Hypothesis

There are multiple issues at play:

1. The Usage Tracker service was not generating usage reports for some time. (This should be fixed. Any missed usage reports still may need to be re-generated.)   

2. The Usage Tracker service generates compressed reports. Because the reports are compressed, the `if: :normal_report?` here returns false, and sashimi doesn't push the report to levriero: https://github.com/datacite/sashimi/blob/a26fe85e098f3f0f110312cc6d94dde0123d5d4e/app/models/report.rb#L37 

With `0623c474-965b-44fa-a6a0-55c4fe01b0fb` as an example:

```
3.1.0 :001 > r = Report.where(uid:"0623c474-965b-44fa-a6a0-55c4fe01b0fb").first
 => 
#<Report:0x00007f529e68c700
... 
3.1.0 :002 > r.normal_report?
 => nil 
3.1.0 :004 > r.compressed_report?
 => true 
3.1.0 :005 > r.resolution_report?
 => false 
```

3. When the reports are manually pushed to levriero, they are not processed for usage events. This levriero code assumes that the first exception will be code 69, but in the case of these reports, it’s the second: https://github.com/datacite/levriero/blob/e3d38d3fa40a8afa3d86a92fc7b67b17448750bc/app/models/report.rb#L91-L103 So `.get_type` returns `normal` instead of `compressed`, and this code consequently doesn’t run the correct method for extracting usage data: https://github.com/datacite/levriero/blob/e3d38d3fa40a8afa3d86a92fc7b67b17448750bc/app/models/usage_update.rb#L45-L54

When running the correct command:
```
3.1.0 :014 > Report.parse_multi_subset_report(report)
```
. . . events are generated for the compressed report `0623c474-965b-44fa-a6a0-55c4fe01b0fb`. Example events here: https://api.datacite.org/events?doi=10.60707/7k9y-n295&source-id=datacite-usage 

#### Possible Implementation

Some options:

- Have the Usage Tracker service send uncompressed reports.
- Have sashimi send compressed reports to levriero, and adjust levriero to respond to compressed report exceptions that aren't first in the exceptions list of the report. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7tbx1)

**Comment by richardhallett** [comment]
So I'm opting for the second options of changing levriero and sashimi.
From what you've said Levriero does parse and generates correctly for compressed reports, it's just failing the check for the exception code, but that's a bug, So I'm fixing that with:

https://github.com/datacite/levriero/pull/186

Next sashimi should send in first place, I really can't speak for historical reasons but to me it makes perfect sense to send compressed or not usage reports. I've changed this to then just ignore resolution reports which are different.

https://github.com/datacite/sashimi/pull/188

With this that should fix overall problem, then we can just run rake tasks to fix for missing usage reports in levriero.

**Comment by codycooperross** [comment]
I pushed the reports for XAQP.GRCILE missing from Event Data to levriero, and all relevant events now appear to be represented. These were:

- 3445257b-8d14-4103-b4ed-4e05bdce9ef5
- 3a5e0276-85e1-4dd0-86f0-845e47dc371c
- 49f56624-a7d1-4d76-8f63-9b31d644d8f0
- 80845078-98eb-4c2c-8e12-028f6a056090
- 840bf0ce-7fba-483f-8f2b-749edd050184
- 8e36eb26-4ae9-417f-b086-d5ab7ff92dff
