### ISSUE TITLE
Transfer subset of 52 DOIs to RDG.PROD

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2218]
Old Repository ID: INIST.DDE
New Repository ID: RDG.PROD
Prefix: (please let us know if the prefix should be transferred to the new repository of not) Only the DOIs need to be transferred
Number of DOIs: 52

[DOREL_datacite_transfert_to_RDG_data-1729156424602.csv](https://github.com/user-attachments/files/17433050/DOREL_datacite_transfert_to_RDG_data-1729156424602.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7xod1)

**Comment by codycooperross** [comment]
The 52 DOIs listed in DOREL_datacite_transfert_to_RDG_data-1729156424602.csv were transferred from INIST.DDE to RDG.PROD.
