### ISSUE TITLE
Transfer subset of DOIs to ENERGY.JOURNALS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2219]
Old repository ID:RADS.MAIN
New repository ID: ENERGY.JOURNALS
Prefix: 10.34831 (already transferred)
List of DOIs: 1669

[Enegroprogress.csv](https://github.com/user-attachments/files/17462864/Enegroprogress.csv)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7xxqt)

**Comment by codycooperross** [comment]
The 1667 listed DOIs have been transferred to ENERGY.JOURNALS. The following two DOIs were listed erroneously:

- 10.1134/s0040601520120071
- 10.1134/s0040601522030016
