### ISSUE TITLE
#5980 URLs in cyrillic alphabet

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#222]
I have notices that MDS does not accept datasets URLs in cyrillic alphabet (even if it is a unicode).
 
For example:
 
https://ouipiir.ru/content/%D0%BC%D0%B8%D1%84%D0%BE-%D1%84%D0%BE%D0%BB%D1%8C%D0%BA%D0%BB%D0%BE%D1%80%D0%BD%D0%B0%D1%8F-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B0-%D1%81%D0%BA%D0%B0%D0%B7%D0%BE%D0%BA-%D1%81%D0%B1%D0%BE%D1%80%D0%BD%D0%B8%D0%BA%D0%B0-%D0%BD-%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B0%D0%BA%D0%BE%D0%B2%D0%BE%D0%B9-%C2%AB%D0%BF%D0%BE%D0%B4%D0%B0%D1%80%D0%BE%D0%BA-%D1%87%D0%B0%D0%B9%D0%BA%D0%B8%C2%BB
 
Which is https://ouipiir.ru/content/мифо-фольклорная-основа-сказок-сборника-н-большаковой-«подарок-чайки»
 
Would appreciate your assistance

**Comment by mfenner** [comment]
This has been fixed with the new MDS software deployed July 16.
