### ISSUE TITLE
Transfer subset of DOIs to NIHNCI.CANANO

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2227]
Consortium: NIH
Consortium Organization: NIHNCI
Old Repository: NIHNCI.NCI
New Repository:NIHNCI.CANANO
Prefix: 10.17917
Number of DOIs: 191

[NIH NCI DOIs to transfer.xlsx](https://github.com/user-attachments/files/17648133/NIH.NCI.DOIs.to.transfer.xlsx)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7zyfp)

**Comment by codycooperross** [comment]
The 191 DOIs listed in NIH NCI DOIs to transfer.xlsx and prefix 10.17917 were transferred from NIHNCI.NCI to NIHNCI.CANANO.
