### ISSUE TITLE
Discrepancies between XML/JSON > metadata values missing

### ISSUE THREAD

**Issue by selgebali** [datacite/datacite#2247]
### Describe the bug
There are multiple DOIs in the metadata for the INISTCO consortium missing mandatory creator information. Despite the missing details in the JSON responses, the XML responses reveal that some creator information is available but not properly encoded in the JSON schema.

#### Expected Behaviour
The JSON metadata for each DOI should include complete and accurate property information, adhering to the required schema.

#### Current Behaviour
Some DOIs have missing creator fields in the JSON metadata. For example:
`"creators": [
    {
      "affiliation": [],
      "nameIdentifiers": []
    }
  ]`

Other DOIs have null schemaVersion fields but still show schema information in the XML when decoded. Example:

- DOI: [10.12763/4371A_NNN](https://api.datacite.org/dois/10.12763/4371A_NNN)
- Some DOIs show no creator information in JSON but include complete creator data in the XML. Example:
- DOI: [10.25518/CIRIEC.WP201918](https://api.datacite.org/dois/10.25518/CIRIEC.WP201918)
- JSON: Missing creator information
- XML:

`<creators>
  <creator>
    <creatorName nameType="Personal">Behrendt, Gerlinde</creatorName>
    <givenName>Gerlinde</givenName>
    <familyName>Behrendt</familyName>
  </creator>
</creators>`

#### Steps to Reproduce

1.	Query the metadata for the INISTCO consortium DOIs via the API.
2.	Observe that certain JSON metadata is missing creator information.
3.	Decode the XML metadata for the same DOIs and note the presence of creator details.

### Context (Environment)
The missing creator information impacts the quality and completeness of the metadata.

#### Further details
Consortium ID: INISTCO
List of 170 affected DOIs is attached for reference.
[INISTCO_DOIs_noCreator.csv](https://github.com/user-attachments/files/18025788/INISTCO_DOIs_noCreator.csv)

#### Hypothesis
The bug may be due to an inconsistency in how data is encoded or extracted for JSON metadata.

**Comment by KellyStathis** [comment]
Thanks @selgebali for this description!

Highlighting for @codycooperross that the missing `Creator` information is the core issue we are observing here. I thought we had a similar bug before but couldn't find it! I know the `schemaVersion` issue has been discussed and is related to other bugs.

**Comment by KellyStathis** [comment]
Maybe related to https://github.com/datacite/datacite/issues/1944 as an underlying cause? I noticed that the DOI in that issue 10.13009/EUCASS2023-323 is also in the INISTCO set with missing Creators.

**Comment by codycooperross** [comment]
Thanks for pointing this out, @selgebali . It looks like these are quite old, so there may have been an issue with the XML import that has since been resolved. I will take a look.

**Comment by codycooperross** [comment]
10.12763/4371A_NNN
Looking through the history of the metadata, this DOI has always had blank creators in the XML. The XML Schema of the DOI seems to be 2.2, so it may be that that was valid at the time. The DOI will need to be updated with creator metadata using Schema 4 for creators to appear. 

10.25518/CIRIEC.WP201918
I re-imported the XML metadata to JSON (`Doi.import_one(doi_id: "10.25518/CIRIEC.WP201918"`), and the creators now appear: https://api.datacite.org/dois/10.25518/CIRIEC.WP201918 I can perform this action for all of the listed DOIs if that's appropriate.

**Comment by KellyStathis** [comment]
@codycooperross Yes, if you could perform the re-import on these DOIs I think that would be appropriate. Thank you for looking into this!

**Comment by codycooperross** [comment]
I re-imported these, which corrected about 40 of the DOIs. The following contains the creators values before and after import: [inistco reimport.csv](https://github.com/user-attachments/files/18283419/inistco.reimport.csv) For the values that continue to be blank, this is likely for the same reason as 10.12763/4371A_NNN above, i.e. that there is no creator metadata in the XML itself.
