### ISSUE TITLE
Implement state machine for DOIs

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#226]
As a client, I want to have a clear understanding of the status of all my DOIs, so that I can address issues if something is wrong.

## Dev Notes

We want to implement a state machine in the DOI model that uses the following states:

* draft
* tombstoned (URL resolves to generic tombstone page)
* registered
* public
* flagged (issues with metadata quality)
* broken (URL doesn't properly resolve)

These states should all be indexed, so that we can filter DOIs by state. And certain actions, e.g. registration in the handle system or link checking returning a broken link, should trigger state changes. 

### Draft

A draft DOI requires a unique and valid DOI. Everything else (URL, metadata, media) is optional.

### Tombstoned
Registered with the global handle system, the URL is for a generic tombstone page without any specific metadata. DOIs with the test prefix 10.5072 will never go to this state or beyond.

### Registered

Registered with the global handle system, i.e. the DOI resolves properly to a landing page.

### Public

These DOIs show up in the public search index and API, i.e. without authentication.

### Flagged

The first implementation will flag those DOIs that still use Schema 2.x (more than 1.5 million), and those DOis that don't have `resourceTypeGeneral` metadata, required since schema 4.

### Broken

Once the link checker service that we will implement in Q1 2018 is available, we can change the state of DOIs that reliably don't resolve to `broken`. 

### Implementation
In the https://github.comdatacite/lupo API, using the https://github.com/aasm/aasm gem.

**Comment by mwittin** [comment]
Either as a part of this issue or for a new one, clients should have the option of displaying citation metadata of tombstoned DOI with reason for why DOI intentionally does not to resolve to a resource, e.g., the resource was deaccessioned. DataCite should provide this as a part of its platform to support eventual failing of clients/members. Also some client's systems do not provide this capability. This functionality is used by current EZID subscribers, so it may be considered important for some for migration as potential new members.

**Comment by mfenner** [comment]
Added this to an issue that is a better fit: https://github.com/datacite/freya/issues/1

**Comment by pcruse** [comment]
Question: once a DOI is public can it revert to a previous state -- for example from public to registered?

**Comment by mfenner** [comment]
We need to decide what transitions are possible. In the current MDS you can transition from public to registered (i.e. "delete" a DOI), so I expect this to be possible in DOI Fabrica.

**Comment by mfenner** [comment]
Implemented.
