### ISSUE TITLE
Transfer subset of 228 DOIs to GDCC.JHU

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#2262]
Old Repository ID: JHU.PMA202
New Repository ID: GDCC.JHU
Prefix:  10.34976 (Please transfer this prefix to the new repository)
Number of DOIs: 228

[datacite-dois.xlsx](https://github.com/user-attachments/files/18200962/datacite-dois.xlsx)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_85c45)

**Comment by codycooperross** [comment]
The 228 DOIs listed in datacite-dois.xlsx and prefix 10.34976 were transferred from JHU.PMA202 to GDCC.JHU.
