### ISSUE TITLE
More fine-grained roles in DOI Fabrica

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#227]
As a client admin, I want to be able to administer all aspects of my DOI Fabrica account, so that I have to contact my provider only when needed.

As a client user, I want to be able to see all the DOIs registered by the client, and stats related to this activity (number of DOIs broken down over time, by resource type, link checker, usage stats, etc.)

**Comment by brittadreyer** [comment]
One user story from Mohamed out of the webinar Nov. 8, 2017: What would be useful is that a client who has many laboratories located in different areas be able to give associates or users permission to mint DOIs
