### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#229]
Suggested use case form Rachael Kotarski in the webinar Nov 8, 2017: I would see a use for 3 levels: Admins, who adjust the client account and assign DOIs; Users who can assign DOIs, but not edit the account info or manage; read-only Users who can view e.g. stats but can't assign DOIs. I think the middle use-case doesn't seem to be met at the moment.

**Comment by mfenner** [comment]
See also #227 for user stories for the different user roles.

One question: can we drop the read-only user role for now and simply add the ability to assign DOIs to the `client_user` role?

**Comment by brittadreyer** [comment]
I would prefer it.

**Comment by mfenner** [comment]
No longer relevant with new authentication.
