### ISSUE TITLE
Prefix Trasnfer PeerJ 6792

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#238]
CDL client PeerJ has communicated their decision to transfer prefix doi:10.7287/ from DataCite to Crossref where it will be added to PeerJ’s existing Crossref membership account. As of this writing, 27,580 DOIs registered with the 10.7287 prefix (per EZID). The client is continuously using the prefix so the number will likely rise until we agree on dates for a brief moratorium to conduct the transfer. Regarding scheduling the transfer, please note that CDL participants have (staggered) out-of-office time from November 13 to 24, so we would prefer the transfer to take place in early December.

**Comment by kjgarza** [comment]
https://api.datacite.org/prefixes/10.7287

**Comment by kjgarza** [comment]
I thought this was completed already? @mfenner can you confirm?

**Comment by mfenner** [comment]
Still in progress.
