### ISSUE TITLE
Remove Bower Depedency

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#251]
Relevant for the following **datacite** and **crosscite** repos:

- [x] volpino
- [ ] segugio
- [x] blog
- [x] homepage
- [x] schema
- [x] doi-metadata-search

**Comment by mfenner** [comment]
Dependency in `doi-metadata-search` removed via https://github.com/crosscite/doi-metadata-search/pull/80.

**Comment by mfenner** [comment]
Keep open.
