### ISSUE TITLE
Member listings on DataCite webpage

### ISSUE THREAD

**Issue by pcruse** [datacite/datacite#255]
Modify the current member page at https://www.datacite.org/members.html to allow: 

- sorting by country
- sorting by institution type (national organization, academic institution, research institution, government organization, publisher, association, service provider)

The default view of the page should be alphabetical and include the organization's logo and descriptive information.

**Comment by mfenner** [comment]
#### DEV NOTES

* in the member database in Profiles service add institution type category
* classify all existing members into these institution type categories

* in tne homepage redo member page following instructions above, using https://orcid.org/members as a starting point

**Comment by daslerr** [comment]
A more compact form of the alphabetical listing including logo and descriptive information (which includes institution type) was deployed as part of #728. Sorting by country and institution type was deemed unnecessary at this point in time, but we may revisit that.
