### ISSUE TITLE
Standarise Reverse Proxy

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#260]
Keep using kong but we can potentially use https://traefik.io/ to solve the lack of support for Terrafom Enterprise

**Comment by mfenner** [comment]
We have migrated to AWS Application Load balancers last week and there is no need for a reverse proxy anymore. We need to tweak the `datacite/oaip` and `datacite/search` docker images to not need a path.

The only reverse proxy remaining is the `fixed-ip` proxy to cover the use case of registering DOIs through a firewall that expects a specific IP address.
