### ISSUE TITLE
Define standard github labels

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#262]
We currently use terraform to help us create a standard set of labels across all repositories, this needs to be clarified and documented, including definitions as to what each label means and is used for.

**Comment by mfenner** [comment]
This is now managed here: https://github.com/datacite/mastino/tree/master/global/github. 

We should improve the terraform implementation: we currently use a list of GitHub repos as input, and adding a repo not at the end breaks existing labels. A good opportunity for a terraform module.
