### ISSUE TITLE
API Health Checks

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#263]
Currently we have sporadic insight into data for the health of API end points, it would be good to gather more data in order to be able to make better architectural decisions.

Main goals to get things like 
* No of Requests
* Status Codes
* Avg Request time.

Note some of this may be available already but bring together in this issue to figure out where and how this should be found going forward.

**Comment by mfenner** [comment]
Implemented via AWS Application Load Balancer.

Future work could look at specific API endpoints.
