### ISSUE TITLE
Technical Debt - Guiding principles

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#265]
During internal discussions we discussed how DataCite should handle Technical Debt, this needs documenting for all future reference.

**Comment by richardhallett** [comment]
Notes from internal discussion:

* When doing database migrations ensure that changes are as small as possible and existing code does not depend. Gradually remove old existing structure until no longer needed.
* Do small incremental changes.
* Track bugs of different type separately, Refactoring vs Re-Designing
* When new bugs occur fix them now not later in principle.
* Use bugsnag to either create an issue or ignore, basically do something with bugsnag reporting issues.

**Comment by mfenner** [comment]
This is a Ruby gem that can help with safe database migrations: https://github.com/ankane/strong_migrations
