### ISSUE TITLE
Internal Technical Documentation - Location

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#266]
Currently we need a standard place for all internal technical documentation for DataCite.
This needs to be easily accessible for editing and creating new documentation, especially clear location for new team members.
Some possible options so far:
* Google Docs
* Confluence
* A Gitbook

**Comment by mfenner** [comment]
Github/markdown would align well with our broader strategy, described publicly at https://blog.datacite.org/roadmap/

**Comment by mfenner** [comment]
Also consider https://readthedocs.org/

**Comment by mfenner** [comment]
I helped with this book, using jekyll: http://book.openingscience.org/

**Comment by mfenner** [comment]
We decided to use Confluence.
