### ISSUE TITLE
DOCKER EXEC not working in ECS.TESt

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#267]
docker exec -it 52ede57a30bc /bin/bash
connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

**Comment by kjgarza** [comment]
it seems redeployment of the docker host fixed this. please review @mfenner

**Comment by kjgarza** [comment]
can this be closed?

**Comment by mfenner** [comment]
yes.
