### ISSUE TITLE
Separate testing for users and testing for DataCite

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#271]
Currently the test system is used for those wanting to test DOI's both from an end user of the DOI systems and those of DataCite directly, there is a need to ensure DataCite has the ability to test new functionality that does not adversely affect any end users.

**Comment by mfenner** [comment]
### DEV Notes

- [ ] Document preferred workflow in documentation
- [ ] Blog post
- [ ] Remove unused (> 2 years) accounts in test system

**Comment by mfenner** [comment]
Blog post is tracked in https://github.com/datacite/bracco/issues/79.
