### ISSUE TITLE
Access to services via SSH

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#274]
Currently we have old keys for accessing services via ssh (including tunnelling to services like RDS) this is not per user and is all handled under default ubuntu account.

What we ideally want to do is handle all access via bastion using separate accounts with individual keys, this way access can be granted removed without affecting other users, currently if we lose the key everyone has to get a new key.

If conveniant we might want to manage access via SSH, see 
https://cloudonaut.io/manage-aws-ec2-ssh-access-with-iam/
and terraform
https://www.terraform.io/docs/providers/aws/r/iam_user_ssh_key.html

For an initial stage we can still access actual EC2 instances via default ubuntu user.

Things we need to do:

1. Per user access to bastion via authorised SSH keys
2. Generate a new key that is used by images and swap out old MDS one.

**Comment by mfenner** [comment]
Related: #279

**Comment by richardhallett** [comment]
More thoughts:

To get this working what you need to be able to do is:
* Obtain the public keys of specific IAM users
* Register within a created EC2 instance local users.
* The public ssh keys need to be in those local users authorised keys file.

## Option 1

If we assume that IAM users are created via the IAM management dashboard (or already exist) then:

One option is the usage of sshd AuthorizedKeysCommand command, which you can then reference a shell script to retrieve the respective IAM users public key, so possibly matching based on local username. This is what https://github.com/widdix/aws-ec2 ssh/blob/master/authorized_keys_command.sh this is - Using the aws cli command line tool to get the information.

It would be nicer to use terraform to actually get the users from IAM and then generate the required authorisation files, but as far as I can tell, terraform does not allow a datasource to retrieve public keys for IAM users.

##  Option 2
A reverse option is that we do all configuration for IAM via terraform in the first place, so it:
* Creates the users within IAM via https://www.terraform.io/docs/providers/aws/r/iam_user.html and also adds public keys and such.
* Creates local users to match IAM users
* For local users adds the authorised_keys public keys in.

This does mean all user accounts will be in terraform config, however this might be possible to manage via terraform variables.

**Comment by mfenner** [comment]
We have created all our IAM users with terraform and the `iam_user` resource. So maybe option 2 is easier to implement.

**Comment by richardhallett** [comment]
Thinking more we could do a bit of a combo something like:

1. Use Terraform to create IAM users and also upload the public keys for various users as applicable.
2. Use a bash script to install AWS cli tools that can then:
a. Get all the IAM users and create local user accounts
b. Get the SSH assign authorised keys to those local user accounts.

This means that 1. and 2. Can be separate in terms of possible public/private configs if required to avoid exposure of potentially sensitive information.

**Comment by mfenner** [comment]
I would think about how 2) can also be done in Terraform, `user-data` is pretty powerful. And you can use a template that feeds in the users from a particular IAM group, meaning that the EC2 instance is recreated when new users are added to the group.

**Comment by mfenner** [comment]
Potentially relevant: https://github.com/sportebois/aws-ec2-ssh-sync
