### ISSUE TITLE
Update cloudfront after changes in S3

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#277]
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ReplacingObjectsSameName.html
 
### DEV NOTES

* use the Python AWS API client, installed via `sudo pip install awscli`
* invalidate the Cloudfront distribution in an `after_deploy` block

```
after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
```

**Comment by kjgarza** [comment]
this could be related to the issue we have with the ghost /board.html page in the homepage site. It could be that the invalidation is not working. At the moment I have run an invalidation manually and removed board.html from S3 (now the page leads to 404). However, the redirection is not working. 


its strange as is only happening in production and not in stage
