### ISSUE TITLE
Solr container can't write index when running in ECS

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#278]
Described at https://stackoverflow.com/questions/42296368/sorl4-failing-to-index-when-using-ebs-volume-in-ecs

**Comment by mfenner** [comment]
What has been tested:

Operating system
- [ ] Ubuntu 16.04
- [ ] Amazon Linux

Docker volume driver
- [ ] aufs
- [ ] overlay2
- [ ] device mapper

**Comment by kjgarza** [comment]
@mfenner Is the volume attached to the ECS instance before docker daemon starts? That is, is the volume attached during the boothook? 
If so, can one write from the solr container into the volume?

**Comment by mfenner** [comment]
@kjgarza yes. But writing to the volume independent of the index has not been tested by me. But using the root block device gives the same errors.

**Comment by kjgarza** [comment]
@mfenner are we closing this issue?

**Comment by mfenner** [comment]
Yes.
