### ISSUE TITLE
Send all Logs to AWS Cloudwatch

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#294]
This is the easiest and probably cheapest approach for centralized logging.

For Docker we would need to use the `awslogs` log driver.

Cloudwatch is not so good at visualizing logs. We need to investigate whether we

* use custom Cloudwatch dashboards
* send to Papertrail (via AWS Lambda)
* use different third-party service (e.g. Loggly) to read from Cloudwatch logs
* send Cloudwatch logs to Logstash/Elasticsearch

**Comment by richardhallett** [comment]
This was fixed in part by our move to DataDog and relates to #378
