### ISSUE TITLE
DOI Registration functionality for Providers

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#304]
As a Provider Admin I need to be able to use the DOI Registration functionality to register DOIs for one or more clients because I am the only person in my organization responsible for RDM. I also need to be enabled to demonstrate the DOI Registration functionality to interested parties and new clients.

**Comment by mfenner** [comment]
Not possible with the new authentication workflow (which uses MDS permissions to register DOIs), so closing for now.
