### ISSUE TITLE
Consolidate APIs under a single Domain

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#307]
At the moment we have a reading API (api.datacite.org) and a writing API (mds.datacite.org). Additionally `Lupo` can do both operations read and write. However, `Lupo` can only access to MySQL. and we need a faster way to access to that data. Enter `Levriero`; this is an API that wraps ES. 

Both  `Lupo` and `Levriero` can be easily syncronised for wrtting and reading. But we would like to provide a single domain for their access. api.datacite.org.

On issue is to redirect GET requests to `Levriero`  and other requests to  `Lupo`.

**Comment by kjgarza** [comment]
There are 4 options to do that: 

- *Using a Gateway API:*
  -  https://stackoverflow.com/questions/41957556/amazon-api-gateway-in-front-of-elb-and-ecs-cluster
  - Disadvatages: Currently we have an ELB and we cannot combine the ELB with the Gateway API. This seems to be a huge missing piece for the API gateway technology, given the way it's pushed. Not being able to call into an internal-facing server in the VPC severely restricts its usefulness as an authentication front-door for internet access. FWIW, in Azure, API Management supports this out of the box - it can accept requests from the internet and call directly into your virtual network which is otherwise firewalled off. The only way this seems to be possible under AWS is using Lambdas, which adds a significant layer of complexity, esp. if you need to support various binary protocols.
  - Adv: its the most elegant solution.
- *Redirecting in NGIXN in the API container.*
  - https://medium.com/@thien.an.vo.nguyen/https-with-rails-app-behind-nginx-and-aws-elb-fae125984eff
  - Disadvatages: The proxy configuration  of the APIs is a specific container in ECS rather than abstracted.
  - Advtaches: Doesn't touch the codebase.
- *Using Routin the Rails app*
  - Disadvatages: Modify the codebase.
- *Using Application Logic*
  - Disadvatages: Modify the codebase.

**Comment by kjgarza** [comment]
None of the options provides a clean solution for the configuration of the APIs. Before choosing the least-worst, should we reconsider the idea of consolidating all APIs under a single domain? 

 Clients that use the MDS API will not use the `Lupo` to mints DOIs  in the near future as they need to transtion to a JSONAPI spec first. This could take many months. Therefore, with very few exceptions, we will have most users using `mds.datacite.org` to write and `api.datacite.org` to read. Unless we also consolidate the MDS API into `api.datacite.org`

*Single domain for all APIs.*

Advantages:
-  Simpler interfacing for API consumers.

Disadvantages:
- One cannot make independet requests to either backend. POST requests will only lead to `mysql-backend`never to `ES-backend` and viceversa.

**Comment by mfenner** [comment]
My comments:

* MDS API and EZ API are so different in format that they should stay separate
* API gateway needs to be behind ELB, as we use ELB for SSL termination
* API gateway makes sense if we need additional functionality, such as rate-limiting
* Bracco frontend expects the same API URL for `read` and `write`, so splitting REST API into a `read` and `write` API would need tweaking.
* because of auto-scaling we need to connect all containers via ELB and can't connect containers directly. We could have a 2nd internal ELB for this purpose.
