### ISSUE TITLE
title not mapped to JSON format

### ISSUE THREAD

**Issue by adam3smith** [datacite/datacite#324]
Looking at this DOI 10.17899/on_ed.2018.1.1
There is no item title in either the CSL or Datacite JSON format
```
curl -LH "Accept:  application/vnd.citationstyles.csl+json" https://doi.org/10.17899/on_ed.2018.1.1
curl -LH "Accept:  application/vnd.datacite.datacite+json" https://doi.org/10.17899/on_ed.2018.1.1
```

Since title is mandatory in both the 3 and 4 metadata kernel that seemed weird, so I looked at the XML, and the title is right there:
```
curl -LH "Accept:  application/vnd.datacite.datacite+xml" https://doi.org/10.17899/on_ed.2018.1.1
(...)
 <titles>
    <title lang="en" text="Citizenship, Structural Inequality and the Political Elite"/>
  </titles>
```

This breaks Zotero import among other things (reported here: https://forums.zotero.org/discussion/comment/304264#Comment_304264)

**Comment by mfenner** [comment]
Attributes such as `lang="en"`, and more importantly multiple titles, are still sometimes an issue. I will look into this.

**Comment by mfenner** [comment]
```
{
"@context": "http://schema.org",
"@type": "Dataset",
"@id": "https://doi.org/10.5061/dryad.m53r1",
"funding": {
  "@type": "Grant",
  "identifier": "1452510",
  "funder": {
     "@type": "Organization",
     "name": National Science Foundation",
     "identifier": "https://doi.org/10.13039/100000001"
  }
}

**Comment by mfenner** [comment]
This was part of a bigger issue of metadata formatting, and has been resolved.
