### ISSUE TITLE
Visibility in other platforms

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#33]
As a repository manager, I  want my datasets to be visible/discoverable outside my platform so that they can be found/reused by other researchers.

#### Related User Story

* As a data center, I want to be visible, so that I can justify the investment in human resources needed to run our services.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
