### ISSUE TITLE
Provide reason why DOI is not findable

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#330]
With EZID it was possible to create a Tombstone Page if required. There were to steps:

1. set DOI inactive or not findable
2. Provide a reason for unavailability

EZID service creates a Tombstone Page including the contact/creator information out of the metadata.

**Comment by mfenner** [comment]
The EZ API already supports 1), i.e. changing the state from `findable` to `registered`, and providing a `reason`. 

We can add `reason` to DOI Fabrica.

**Comment by mfenner** [comment]
Keep open.

**Comment by mfenner** [comment]
don't close.
