### ISSUE TITLE
DOI resolution stats December 2017 to March 2018

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#335]

**Comment by kjgarza** [comment]
this takes a long process so it takes two points size

**Comment by kjgarza** [comment]
there is a new way to copy logs from the CNRI server 

> wget --no-directories --recursive --no-parent --no-check-certificate --user=datacite --ask-password https://loganalysis.handle.net/datacite/logs

**Comment by kjgarza** [comment]
I'm very likely need to change the logs reporter.
Its currently failing when calling:

> https://search.datacite.org/list/datacentres?fq=prefix:%s&facet.mincount=1

as

> requests.exceptions.ConnectionError: HTTPConnectionPool(host='search.datacite.org', port=80): Max retries exceeded with url: /list/datacentres?fq=prefix:10.5062&facet.mincount=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1444e3a90>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by mfenner** [comment]
Configuration here: https://github.com/datacite/search/blob/master/docker/webapp.conf.tmpl

But https://search.datacite.org/list/datacentres?fq=prefix:%s&facet.mincount=1 works for me when using the browser. Also try solr.datacite.org.

**Comment by kjgarza** [comment]
it might be related to the port maybe ? https://github.com/elastic/elasticsearch-py/issues/598
i'll check during the train

**Comment by kjgarza** [comment]
closed in #6192dd86c4ca6ec1dd37a992256e23991a13c6c0
