### ISSUE TITLE
Correctly register DOI in handle system

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#343]
```
Apr 17 23:20:27 client-api ecs-client-api-141-client-api-ecdbf292c28793e87800: 2018-04-17T21:20:27Z 190 TID-1fbffs ActiveJob/HandleJob/production_lupo/5bcdbd19-41a0-4aaf-b6bb-9bb9c09b3f44 WARN: [Handle] Error updating URL https://blog.datacite.org/ for DOI 10.5438/DHSM-8219. 
Apr 17 23:21:27 client-api ecs-client-api-141-client-api-ecdbf292c28793e87800: 2018-04-17T21:21:27Z 190 TID-1any7k ActiveJob/HandleJob/production_lupo/fafb3c76-a10e-4b61-ba50-f1ac969711d5 WARN: [Handle] Error updating URL https://blog.datacite.org/ for DOI 10.5438/XC6C-EF54. 
Apr 17 23:32:00 client-api ecs-client-api-141-client-api-ecdbf292c28793e87800: 2018-04-17T21:32:00Z 190 TID-1j9hwc ActiveJob/HandleJob/production_lupo/6e06964d-ce9e-4abc-b8e3-c6bfb5fc9fbe WARN: [Handle] Error updating URL https://blog.datacite.org/data-driven-development/ for DOI 10.5438/DHSM-8219. 

```

> ActiveJob/HandleJob/production_lupo/6e06964d-ce9e-4abc-b8e3-c6bfb5fc9fbe WARN: [{"status"=>400, "title"=>"Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback), or `Excon.defaults[:ssl_verify_peer] = false` (less secure)."}]

**Comment by kjgarza** [comment]
We need to test that registering or changing a URL in Fabrica or the EZ API triggers the correct response in the handle system. For our test system I checked that, but the production system seems to have issues. The trick is that it is a background job, so might take a moment. Lupo is logging this activity, filter logs for "[Handle]".

**Comment by kjgarza** [comment]
So after checking this a bit more I have a few questions. 

I can't find longs of successful DOI registrations using the `production_lupo` however I can find many successful registrations in `stage_lupo`.  The main difference between production and stage is that they use different Handle server, right?

**Comment by mfenner** [comment]
This all makes sense, thanks @kjgarza. I am not sure about the certificate issues. Keep in mind that `lupo` talks to the MDS API, not directly to the Handle server.

**Comment by kjgarza** [comment]
it actually a very strange bug. I am running the sequece of commands in the console from the container. It fails in production but not locally for the same container. The queue is working ok. So it leads me to think that is when LUPO instance in AWS calls MDS API things do not work. 

I was thinking maremma might be an issue but i think i have discarded that. Any reason we are not running the lastests  version (4..0.5)?

**Comment by mfenner** [comment]
Thanks a lot for the investigation, I think it now all comes together:

* this is a configuration issue, and has to do with SSL
* our internal DNS for mds.datacite.org points to the EC2 instance and not the load balancer, so that there is no SSL termination
* the EC2 instance only understands requests to http://mds.datacite.org but not https://mds.datacite.org and raises and SSL error
* reconfiguring internal DNS for mds.datacite.org to point to the load balancer should fix the issue
