### ISSUE TITLE
Access to previous metadata versions

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#346]
As a client, I want to have easy access to previous metadata versions for a DOI so that I can make comparisons between versions or investigate potential errors. 

child of datacite/datacite#437.

**Comment by mfenner** [comment]
The activities API can be used to implement this functionality.

**Comment by kjgarza** [comment]
:wave: @daslerr, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
