### ISSUE TITLE
ORCID Works syncing

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#353]
With the ORCID registry and the DataCite works search it would be beneficial to be able to remove from orcid and have this synced within DataCite.

Currently without syncing, this can manifest an error in the datacite search interface with a "An error occured while adding to ORCID record"

Example workflow:

1. Login to orcid interface
2. From within works delete a work previously added via datacite search.
3. Delete work
4. Goto DataCite search, notice that the record still says "In your Orcid Record"
5. Delete the record in DataCite search

DataCite and Orcid both have the orcid record now removed.

**Comment by peterdesmet** [comment]
This issue has been marked as `wontfix`, but I'd still like to see this fixed. 😄 As described in the issue body, if a DataCite search work is deleted from the ORCID profile, that information doesn't seem to flow back to DateCite. That also means the user cannot add the work (back) to their ORCID from DataCite if the deletion was made erroneously.

**Comment by florisvdh** [comment]
Any plans to have this fixed? This issue has been closed without solving. I encountered the same problem as mentioned by @peterdesmet
