### ISSUE TITLE
Problems authenticating with python EZID package

### ISSUE THREAD

**Issue by daisieh** [datacite/datacite#354]
I’ve been trying to update Dryad’s EZID DOI scripts to use the new DataCite servers, and I’m having problems authenticating to the server. I’m using the EZID python module v0.3, installed via pip, and when I try to use the test server at https://ez.test.datacite.org instead of https://ezid.cdlib.org, I get the following error:

```
error: one-time login and session cookies not supported by this service
Traceback (most recent call last):
  File "/home/ubuntu/dryad-utils/doi_tool.py", line 107, in <module>
    main()
  File "/home/ubuntu/dryad-utils/doi_tool.py", line 36, in main
    run_ezid(opt_array)
  File "/home/ubuntu/dryad-utils/doi_tool.py", line 99, in run_ezid
    print EZID_CLIENT.create(dc_doi, data)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/EZID.py", line 210, in create
    self.session_id = self.login()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/EZID.py", line 189, in login
    self.session_id = self._get_request(request, login=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/EZID.py", line 167, in _get_request
    c = self._opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/EZID.py", line 67, in http_response
    response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 501: Not Implemented
```

I’m not sure what to do with this. Am I missing an authentication method that is described in the [API docs](https://support.datacite.org/docs/datacite-ez-api-guide)? I can't see a way to authenticate using the python EZID package without submitting the username/password credentials and logging in at some point.

If it helps, the code that I'm using is at https://github.com/daisieh/dryad-utils/blob/ezid-to-datacite/doi_tool.py.

**Comment by daisieh** [comment]
As far as I can tell, https://bitbucket.org/mredar/ezid/src/default/EZID.py implements the same basic authentication code that is described in https://support.datacite.org/v1.1/reference#ez-api, so it should work.

**Comment by mfenner** [comment]
@daisieh EZID supports two ways of authentication. The DataCite EZ API does not support the `/login` route with a session then stored in a cookie. The main reason is that our API intentionally doesn't support sessions, and there are no plans to do so (The EZID service also supports using logging in via  a browser).

To authenticate with the DataCite EZ API, use basic authentication in the header, the other authentication method supported by the EZID API.

**Comment by daisieh** [comment]
Isn't that the method used in EZID.py? 

```
if self._credentials:
            h = urllib.request.HTTPBasicAuthHandler()
            h.add_password("EZID", self._server, self._credentials['username'], self._credentials['password'])
            self._opener.add_handler(h)
```

**Comment by mfenner** [comment]
Daisy, see https://ezid.cdlib.org/doc/apidoc.html#authentication. DataCite only supports authentication method #1, but not #2. The error message you get indicates that you try to authenticate via #2.

**Comment by daisieh** [comment]
The problem I have is that I'm trying to use the package recommended by DataCite, https://bitbucket.org/mredar/ezid/src/default/EZID.py, and it seems to me that it is a problem for DataCite if the officially recommended Python client doesn't actually work with the new DataCite API. I can certainly modify my local copy of EZID.py to do the right thing, but it seems to me that either the package needs to be updated, or DataCite shouldn't recommend that package to be used.

**Comment by mfenner** [comment]
Ok, then we will no longer recommend that package. We will update the documentation accordingly. Thanks for raising this issue.

**Comment by daisieh** [comment]
That seems harsh too! Can you not help them update their package to work correctly?

**Comment by mfenner** [comment]
It is a package that works with the EZID API. We try to be compatible, but that is never 100% possible. You are the first person who raises this issue after a beta period for a few months, so I am not sure how many people are affected. 

I am not sure whether it is possible to use the package to authenticate with DataCite. We can investigate, but not before next week.
