### ISSUE TITLE
Add labels for prefixes

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#361]
As a client I want to be able to add a label to each of my prefixes, so I that I can keep track of what the prefix applies to, like one for a journal, one for ETDs, one for regular pubs, etc.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cfy3)

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
