### ISSUE TITLE
add helpful error message when account doesn't exist

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#373]
If a user tries to log into Fabrica using an account ID that does not exist, the page does not provide a helpful error message explaining the problem. It just turns the password box red and fills it with `[object Object]`.

![image003 1](https://user-images.githubusercontent.com/3181623/40835136-e1c73b66-6592-11e8-95e0-5d5755d6e797.png)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_by37)

**Comment by mfenner** [comment]
This worked fine in the development system, but our bug tracker is interfering here because we send a 404 not found status.

**Comment by mfenner** [comment]
![bildschirmfoto 2018-06-05 um 12 29 46](https://user-images.githubusercontent.com/23151/40970892-352dcf0a-68bc-11e8-8a55-8decf6294788.png)
