### ISSUE TITLE
Prefix transfer UOREGON

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#389]
Prefix:
10.7246

All DOIS:
True

From:
CDL.UOREGON
To:
ORBIS.UOREGON

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_carn)

**Comment by daslerr** [comment]
Transfer complete 20 June.
