### ISSUE TITLE
prefix transfer VIVA.GMU

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#391]
Prefix: 10.13021

All dois

FROM:
CDL.GMU

To:
VIVA.GMU

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_caxn)

**Comment by pcruse** [comment]
please include a date / time so all parties (EZID, Provider, DataCite) are aware of when the move will take place -- we can then share.

**Comment by richardhallett** [comment]
Transfer complete.
