### ISSUE TITLE
prefix transfer UVa

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#394]
Prefix: 10.18130 (Their other prefix will be moved later.)

All dois with the 10.18130 prefix

FROM:
CDL.UVA

To:
VIVA.UVA-LIBRA

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cbab)

**Comment by kjgarza** [comment]
25th June 4pm
