### ISSUE TITLE
bibtex view does not render

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#400]
Client reports that for several of their DOIs, the bibtex view does not render in Fabrica. When viewing the individual DOI record in Fabrica, selecting other view options like DataCite XML or Citeproc JSON appropriately renders the metadata in the selected format, but selecting bibtex returns the view to summary view and the bibtex does not render. 

Example DOIs: 
10.5067/ADEOS-II/AMSR/AMSR-L1A.003
10.5067/ADEOS-II/AMSR/AA_L2A.001
10.5067/ALTCY-TJ122
10.5067/ASTER/AST14DEM.003

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cfqb)

**Comment by richardhallett** [comment]
This appears not Fabrica specific but related to content-negotiation.
Reproducing using a httpie call: http https://data.datacite.org/10.5067/ADEOS-II/AMSR/AMSR-L1A.003 Accept:application/x-bibtex

**Comment by richardhallett** [comment]
As content-negotiation is also directly supported in lupo, httpie calls to reproduce:
> http https://app.datacite.org/10.5067/adeos-ii/amsr/amsr-l1a.003 Accept:application/x-bibtex
Returns 200 OK but there is no body content

**Comment by mfenner** [comment]
10.5067/ASTER/AST14DEM.003 generates bibtex (maybe because of a fix for frozen strings), the other three DOIs do not. Looks like an issue specific to the metadata rather than a generic issue.

**Comment by mfenner** [comment]
Bibtex is generated for all four DOIs using the `bolognese` command line tool.

**Comment by richardhallett** [comment]
The lupo code makes a call to citation.crosscite.org and uses the citeproc json format as the payload for converting to other formats.
Using httpie you can do a similar call (citeproc.json is the metadata for 10.5067/ADEOS-II/AMSR/AMSR-L1A.003):
http -v POST https://citation.crosscite.org/format style==bibtex locale==en-US < citeproc.json
This however works, my current theory is it's related to the maremma library specifically as opposed to any specific formatting problems.

**Comment by mfenner** [comment]
Lupo is only calling citation.crosscite.org for formatted citations (when `format.citation`): https://github.com/datacite/lupo/blob/master/app/controllers/index_controller.rb#L12-L25

**Comment by mfenner** [comment]
This has been fixed.

**Comment by richardhallett** [comment]
Original problem was fixed and further problem of the public data citation service has also been resolved.
Solution: Updating maremma and bolognese in the main citation code base.

**Comment by katrinleinweber** [comment]
I'm having a similar problem with [_many_, almost all audiovisual items from TIB of 2018](https://search.datacite.org/works?query=&resource-type-id=audiovisual&data-center-id=tib.kmo&year=2018&registered=2018): `Cite > BibTeX` remains empty. Worth another issue, or re-opening this one?

**Comment by daslerr** [comment]
@katrinleinweber This appears to have been fixed in the course of other updates. Let us know if you're still having trouble.

**Comment by katrinleinweber** [comment]
Yes, fixed :-) Thank you!
