### ISSUE TITLE
Grouping in search ignored

### ISSUE THREAD

**Issue by hrzepa** [datacite/datacite#405]
The two searches

https://search.datacite.org/works?query=(subjectScheme:inchikey+subject:KTOSDSJYNBIDCN-UHFFFAOYSA-N)+(subjectScheme:Gibbs_Energy+subject:-1082.980914)
and
https://search.datacite.org/works?query=(subjectScheme:inchikey+subject:KTOSDSJYNBIDCN-UHFFFAOYSA-N)+(subjectScheme:Gibbs_Energy+subject:-1082.980914)

return the same result.  They should not.  How should such grouping be formulated such that the first search succeeds and the second search returns no results?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_d51f)

**Comment by daslerr** [comment]
Those two searches appear to be identical. @hrzepa Did you mean for one of them to be

https://search.datacite.org/works?query=subjectScheme:inchikey+subject:KTOSDSJYNBIDCN-UHFFFAOYSA-N+subjectScheme:Gibbs_Energy+subject:-1082.980914

**Comment by hrzepa** [comment]
Yers, I meant the other to be 

https://search.datacite.org/works?query=subjectScheme:inchikey+subject:-1082.980914+subjectScheme:Gibbs_Energy+subject:KTOSDSJYNBIDCN-UHFFFAOYSA-N

Thus transposing the subject term and its value should give different results, but this is not the result obtained.

Thus 

https://search.datacite.org/works?query=(subjectScheme:inchikey+subject:KTOSDSJYNBIDCN-UHFFFAOYSA-N)+(subjectScheme:Gibbs_Energy+subject:-1082.980914)

is how I want the grouping.  But in fact the grouping is ignored.

**Comment by hrzepa** [comment]
This issue is illustrated at https://doi.org/10.14469/hpc/5920 (example  6).  As of today both searches in 6 yield a positive result, whereas only one should.
