### ISSUE TITLE
Compare mds test points

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#410]
Compare test MDS endpoints for both MDS and new MDS interface (poodle).

**Comment by richardhallett** [comment]
httpie calls
------------

# MDS API

http --session=rph -a datacite.rph:7FLkb6F7jsXliJQ6zkLl mds.test.datacite.org
http --session=rph -a datacite.rph:7FLkb6F7jsXliJQ6zkLl mds-legacy.test.datacite.org

## Get URL for DOI
http --session=rph GET https://mds-legacy.test.datacite.org/doi/10.70048/xdh4-w045

	HTTP/1.1 200 OK
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 66
	Content-Type: text/plain;charset=ISO-8859-1
	Date: Fri, 13 Jul 2018 09:25:52 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

http --session=rph GET https://mds.test.datacite.org/doi/10.70048/xdh4-w045

	HTTP/1.1 200 OK
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 09:26:01 GMT
	ETag: W/"697de2fc32ced78c52238cfbbc94f25f"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 200 OK
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 0307c436-27e7-4229-9584-da97560fe600
	X-Runtime: 0.114035

## List all DOIs

http --session=rph GET https://mds-legacy.test.datacite.org/doi

	HTTP/1.1 200 OK
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 56
	Content-Type: text/plain;charset=ISO-8859-1
	Date: Fri, 13 Jul 2018 09:27:50 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	10.70048/G3D2-G922
	10.70048/XDH4-W045
	10.70048/YWZ5-6741

http --session=rph GET https://mds.test.datacite.org/doi

	HTTP/1.1 200 OK
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 09:29:57 GMT
	ETag: W/"fbe56c06ffe5a99954903e6e5121f89a"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 200 OK
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 721b0911-09d1-4f95-ae56-4c2e6174226d
	X-Runtime: 0.099949

	10.70048/G3D2-G922
	10.70048/XDH4-W045
	10.70048/YWZ5-6741

## Get Metadata for DOI

http --session=rph GET https://mds-legacy.test.datacite.org/metadata/10.70048/xdh4-w045

	HTTP/1.1 200 OK
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 780
	Content-Type: application/xml;charset=UTF-8
	Date: Fri, 13 Jul 2018 09:31:42 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	<?xml version="1.0" encoding="UTF-8"?>
	<ns0:resource xmlns:ns0="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
	    <ns0:identifier identifierType="DOI">10.70048/XDH4-W045</ns0:identifier>
	    <ns0:creators>
	        <ns0:creator>
	            <ns0:creatorName>GSFC</ns0:creatorName>
	        </ns0:creator>
	    </ns0:creators>
	    <ns0:titles>
	        <ns0:title>Integrated Multi-Mission Ocean Altimeter Data for Climate Research Version 2</ns0:title>
	    </ns0:titles>
	    <ns0:publisher>NASA PO.DAAC</ns0:publisher>
	    <ns0:publicationYear>2013</ns0:publicationYear>
	    <ns0:resourceType resourceTypeGeneral="Dataset">Dataset</ns0:resourceType>
	    <ns0:descriptions>
	        <ns0:description descriptionType="Abstract" />
	    </ns0:descriptions>
	</ns0:resource>

http --session=rph GET https://mds.test.datacite.org/metadata/10.70048/xdh4-w045

	HTTP/1.1 200 OK
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: application/xml; charset=utf-8
	Date: Fri, 13 Jul 2018 09:31:57 GMT
	ETag: W/"a7f42d9d8fece43293fac45a62d1761c"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 200 OK
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 9cd1cdcd-9056-4287-81f2-0490596ccf03
	X-Runtime: 0.096972

	<?xml version="1.0" encoding="UTF-8"?>
	<ns0:resource xmlns:ns0="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
	    <ns0:identifier identifierType="DOI">10.70048/XDH4-W045</ns0:identifier>
	    <ns0:creators>
	        <ns0:creator>
	            <ns0:creatorName>GSFC</ns0:creatorName>
	        </ns0:creator>
	    </ns0:creators>
	    <ns0:titles>
	        <ns0:title>Integrated Multi-Mission Ocean Altimeter Data for Climate Research Version 2</ns0:title>
	    </ns0:titles>
	    <ns0:publisher>NASA PO.DAAC</ns0:publisher>
	    <ns0:publicationYear>2013</ns0:publicationYear>
	    <ns0:resourceType resourceTypeGeneral="Dataset">Dataset</ns0:resourceType>
	    <ns0:descriptions>
	        <ns0:description descriptionType="Abstract" />
	    </ns0:descriptions>
	</ns0:resource>

## Get Media for DOI

http --session=rph GET https://mds-legacy.test.datacite.org/media/10.70048/ywz5-6741

	HTTP/1.1 200 OK
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 71
	Content-Type: text/plain;charset=ISO-8859-1
	Date: Fri, 13 Jul 2018 09:33:40 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	image/jpeg=https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg

http --session=rph GET https://mds.test.datacite.org/media/10.70048/ywz5-6741

	HTTP/1.1 200 OK
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 09:34:08 GMT
	ETag: W/"fd801ed92cc987887e35fcbdc23fc9d7"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 200 OK
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: c2789b11-d825-4760-81d8-eca5ef41fb7b
	X-Runtime: 0.092353

	image/jpeg=https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg

## Create Metadata for DOI

http --session=rph POST https://mds-legacy.test.datacite.org/metadata/ Content-Type:application/xml charset:UTF-8 < 10.70048/283t-8j41.xml

	HTTP/1.1 201 Created
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 23
	Content-Type: application/json;charset=UTF-8
	Date: Fri, 13 Jul 2018 09:40:55 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Location: http://mds-legacy.test.datacite.org/metadata//10.70048/283t-8j41
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	OK (10.70048/283t-8j41)

http --session=rph POST https://mds.test.datacite.org/metadata/ Content-Type:application/xml charset:UTF-8 < 10.70048483t-8j42.xml

	HTTP/1.1 201 Created
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 09:58:10 GMT
	ETag: W/"212eabef026e94beaf4f22b54fa369d3"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 201 Created
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 459f7c41-2460-487b-9067-cf9f340cd4c9
	X-Runtime: 0.486023

	OK (10.70048/483T-8J42)

## Create DOI

printf 'doi=10.70048/283t-8j41\nurl=http://example.org/' | http --session=rph -f PUT https://mds-legacy.test.datacite.org/doi/10.70048/283t-8j41 Content-Type:text/plain charset:UTF-8

	HTTP/1.1 201 Created
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 2
	Content-Type: application/json;charset=UTF-8
	Date: Fri, 13 Jul 2018 09:52:30 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	OK

printf 'doi=10.70048/483t-8j42\nurl=http://example.org/' | http --session=rph -f PUT https://mds.test.datacite.org/doi/10.70048/483t-8j42 Content-Type:text/plain charset:UTF-8

	HTTP/1.1 201 Created
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 09:59:12 GMT
	ETag: W/"cbb8d261d226601b78edf92947714c74"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 201 Created
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 67ea9373-0b42-4e24-8ab1-5dec15ebc5e6
	X-Runtime: 0.157495

	http://example.org/

### Notes
* URL Is returned as opposed to just OK

## Delete Metadata

http --session=rph DELETE https://mds-legacy.test.datacite.org/metadata/10.70048/283t-8j41

	HTTP/1.1 200 OK
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 2
	Content-Type: application/json;charset=UTF-8
	Date: Fri, 13 Jul 2018 10:10:53 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	OK

http --session=rph DELETE https://mds.test.datacite.org/metadata/10.70048/xdh4-w045

	HTTP/1.1 200 OK
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 10:26:54 GMT
	ETag: W/"849b0a220e155bdc29ae39fd09f6c3a8"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 200 OK
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 5785e577-b777-49ce-af88-4562789158af
	X-Runtime: 0.251558

	OK

### Notes
* New API does not mark is_active flag like legacy does.

## Create Media 

echo "image/jpeg=https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg" | http --session=rph POST https://mds-legacy.test.datacite.org/media/10.70048/xdh4-w045 Content-Type:text/plain charset:UTF-8

	HTTP/1.1 200 OK
	Cache-Control: no-cache
	Cache-Control: no-store
	Connection: keep-alive
	Content-Length: 2
	Content-Type: application/json;charset=UTF-8
	Date: Fri, 13 Jul 2018 10:35:24 GMT
	Expires: Thu, 01 Jan 1970 00:00:00 GMT
	Pragma: no-cache
	Server: Apache-Coyote/1.1

	OK

echo "image/jpeg=https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg" | http --session=rph POST https://mds.test.datacite.org/media/10.70048/G3D2-G922 Content-Type:text/plain charset:UTF-8

	HTTP/1.1 200 OK
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Encoding: gzip
	Content-Type: text/plain; charset=utf-8
	Date: Fri, 13 Jul 2018 10:36:24 GMT
	ETag: W/"3d9f2abd7dc0d3e40f6c0573cdc38e80"
	Server: nginx/1.14.0 + Phusion Passenger 5.3.3
	Status: 200 OK
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.3
	X-Request-Id: 73ac776d-94d7-48ec-8d2c-8284b19d9852
	X-Runtime: 0.054421

	OK

**Comment by kjgarza** [comment]
closed by https://github.com/datacite/poodle/pull/2

**Comment by mfenner** [comment]
Fixed updates of `is_active` with DELETE method and added tests to confirm.
