### ISSUE TITLE
MDS Legacy - DB Conflicts

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#416]
Within the MDS Legacy setup we're getting 500 back from DOI PUT requests to the service.

Examining the logs it appears to be DB transaction conflicts:

2018-07-19 10:09:55,784 [http-bio-8080-exec-16] DEBUG org.datacite.mds.web.api.ApiHandlerExceptionResolver - handling exception: 
org.springframework.orm.jpa.JpaOptimisticLockingFailureException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.datacite.mds.domain.Dataset#15584934]; nested exception is javax.persistence.OptimisticLockException: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [org.datacite.mds.domain.Dataset#15584934]

**Comment by mfenner** [comment]
No further investigation needed, as the new MDS service has replaced this functionality.
