### ISSUE TITLE
Stats for DOIs created

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#42]
As a data manager, I want to report to my boss how many DOIs are created each month/year, so I can share, if the outreach we invested in is paying off.

#### Related User Story

* As a member. I want to see a powerful and meaningful statistics (e.g. DOI per member/datacenter per year (not only per month) so that I could provide reporting to my funding bodies.

**Comment by Aaron-M** [comment]
As a data repository manager I want to know how often dois to data held in the repository are resolved, and how often the data is reused (cited, downloaded...), so I can demonstrate the value of the investment in the repository, and profile datasets that are generating interest (which promotes deposit of data to other researchers in the organisation).

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
