### ISSUE TITLE
Generate random DOI in MDS API

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#432]
To generate a random DOI, use `POST /metadata/10.5072`, i.e. add at least a prefix. You can also add more characters. The random DOI is checked to make sure it doesn't exist already. Use `?number=1234` (any number) to generate a predictable random DOI, e.g. for testing. 

child of #431.

**Comment by kjgarza** [comment]
This is more testing for Random DOI creation. Dois seem to be created 



## Metadata in DataCite xml
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/datacite.xml Content-Type:application/xml;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 2031
Content-Type: application/xml
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI"></identifier>
  <creators>
    <creator>
      <creatorName>Fenner, Martin</creatorName>
      <givenName>Martin</givenName>
      <familyName>Fenner</familyName>
      <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0003-1419-2405</nameIdentifier>
    </creator>
  </creators>
  <titles>
    <title>Eating your own Dog Food</title>
  </titles>
  <publisher>DataCite</publisher>
  <publicationYear>2016</publicationYear>
  <resourceType resourceTypeGeneral="Text">BlogPosting</resourceType>
  <alternateIdentifiers>
    <alternateIdentifier alternateIdentifierType="Local accession number">MS-49-3632-5083</alternateIdentifier>
  </alternateIdentifiers>
  <subjects>
    <subject>datacite</subject>
    <subject>doi</subject>
    <subject>metadata</subject>
  </subjects>
  <dates>
    <date dateType="Created">2016-12-20</date>
    <date dateType="Issued">2016-12-20</date>
    <date dateType="Updated">2016-12-20</date>
  </dates>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.70043/0012</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.70043/55E5-T5C0</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.70043/0000-00SS</relatedIdentifier>
  </relatedIdentifiers>
  <version>1.0</version>
  <descriptions>
    <description descriptionType="Abstract">Eating your own dog food is a slang term to describe that an organization should itself use the products and services it provides. For DataCite this means that we should use DOIs with appropriate metadata and strategies for long-term preservation for...</description>
  </descriptions>
</resource>

HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:42 GMT
ETag: W/"5049edef22c6ca5ff585f6b1dad5926d"
Location: https://mds.test.datacite.org/metadata/10.70043/tecm-e431
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: 390175a1-3549-48e3-beec-58a2c112cb75
X-Runtime: 0.194905

OK (10.70043/TECM-E431)



## Metadata in RDF Turtle
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/datacite.trt Content-Type:text/turtle;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 854
Content-Type: text/turtle
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

@prefix schema: <http://schema.org/> .

<http://archaeologydataservice.ac.uk/archives/view/greylit> a schema:CreativeWork .

<> a schema:ScholarlyArticle;
   schema:alternateName "13979";
   schema:author [ schema:name "Archaeological Project Services"];
   schema:datePublished "1995"^^schema:Date;
   schema:identifier <>;
   schema:inLanguage "en";
   schema:isPartOf <http://archaeologydataservice.ac.uk/archives/view/greylit>;
   schema:keywords "Archaeology, Grey Literature";
   schema:license <http://archaeologydataservice.ac.uk/advice/termsOfUseAndAccess>;
   schema:name "Excavation of a Romano-British Cemetery at the water treatment plant, Saltersford, Grantham, Lincolnshire";
   schema:publisher [
     a schema:Organization;
     schema:name "Archaeology Data Service"
   ];
   schema:schemaVersion <http://datacite.org/schema/kernel-3> .

HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:45 GMT
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 400 Bad Request
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: acd70111-e799-49ae-9dc3-ffc487b042e2
X-Runtime: 0.059835

Missing child element(s). expected is ( {http://datacite.org/schema/kernel-4}creator ). at line 4, column 0



## Metadata in Citeproc JSON
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/citeproc.json Content-Type:application/vnd.citationstyles.csl+json;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 879
Content-Type: application/vnd.citationstyles.csl+json
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

{
    "DOI": "",
    "URL": "https://blog.datacite.org/eating-your-own-dog-food",
    "abstract": "Eating your own dog food is a slang term to describe that an organization should itself use the products and services it provides. For DataCite this means that we should use DOIs with appropriate metadata and strategies for long-term preservation for...",
    "author": [
        {
            "family": "Fenner",
            "given": "Martin"
        }
    ],
    "categories": [
        "Phylogeny",
        "Malaria",
        "Parasites",
        "Taxonomy",
        "Mitochondrial genome",
        "Africa",
        "Plasmodium"
    ],
    "container-title": "DataCite Blog",
    "id": "",
    "issued": {
        "date-parts": [
            [
                2016,
                12,
                20
            ]
        ]
    },
    "publisher": "DataCite",
    "title": "Eating your own Dog Food",
    "type": "post-weblog"
}

HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:48 GMT
ETag: W/"f5619da9bf26d70eafd577d088332434"
Location: https://mds.test.datacite.org/metadata/10.70043/azkn-0w50
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: baa441e2-f593-451e-a763-bd87275850b9
X-Runtime: 0.092268

OK (10.70043/AZKN-0W50)



## Metadata in Schema.org in JSON-LD
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/schema_org.json Content-Type:application/vnd.schemaorg.ld+json;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 1632
Content-Type: application/vnd.schemaorg.ld+json
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

{
    "@context": "http://schema.org",
    "@id": "",
    "@type": "BlogPosting",
    "alternateName": "MS-49-3632-5083",
    "author": [
        {
            "@id": "http://orcid.org/0000-0003-1419-2405",
            "@type": "Person",
            "familyName": "Fenner",
            "givenName": "Martin",
            "name": "Martin Fenner"
        }
    ],
    "citation": [
        {
            "@id": "https://doi.org/10.70043/0012",
            "@type": "CreativeWork"
        },
        {
            "@id": "https://doi.org/10.70043/55E5-T5C0",
            "@type": "CreativeWork"
        }
    ],
    "dateCreated": "2016-12-20",
    "dateModified": "2016-12-20",
    "datePublished": "2016-12-20",
    "description": "Eating your own dog food is a slang term to describe that an organization should itself use the products and services it provides. For DataCite this means that we should use DOIs with appropriate metadata and strategies for long-term preservation for...",
    "encoding": {
        "@id": "https://blog.datacite.org/eating-your-own-dog-food/eating-your-own-dog-food.xml",
        "@type": "MediaObject",
        "fileFormat": "application/xml"
    },
    "image": "https://blog.datacite.org/images/2016/12/230785.jpg",
    "isPartOf": {
        "@id": "https://doi.org/10.70043/0000-00SS",
        "@type": "Blog",
        "name": "DataCite Blog"
    },
    "keywords": "datacite, doi, metadata, featured",
    "license": "https://creativecommons.org/licenses/by/4.0/",
    "name": "Eating your own Dog Food",
    "publisher": {
        "@type": "Organization",
        "name": "DataCite"
    },
    "url": "https://blog.datacite.org/eating-your-own-dog-food/",
    "version": "1.0"
}

HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:50 GMT
ETag: W/"9c49a90dec3f421a9fbb576d6cf5bccf"
Location: https://mds.test.datacite.org/metadata/10.70043/4reh-c905
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: 3eb7d492-d6bd-4987-8798-d8b3715ebc81
X-Runtime: 0.090765

OK (10.70043/4REH-C905)



## Metadata in Codemeta
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/codemeta.json Content-Type:application/vnd.codemeta.ld+json;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 3193
Content-Type: application/vnd.codemeta.ld+json
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

{
    "@context": "https://raw.githubusercontent.com/codemeta/codemeta/master/codemeta.jsonld",
    "@type": "SoftwareSourceCode",
    "agents": [
        {
            "@id": "http://orcid.org/0000-0003-0077-4738",
            "@type": "person",
            "affiliation": "NCEAS",
            "email": "jones@nceas.ucsb.edu",
            "isMaintainer": true,
            "isRightsHolder": true,
            "mustBeCited": true,
            "name": "Matt Jones",
            "role": {
                "namespace": "http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode",
                "roleCode": [
                    "originator",
                    "resourceProvider"
                ]
            }
        },
        {
            "@id": "http://orcid.org/0000-0002-2192-403X",
            "@type": "person",
            "affiliation": "NCEAS",
            "email": "slaughter@nceas.ucsb.edu",
            "isMaintainer": false,
            "isRightsHolder": false,
            "mustBeCited": true,
            "name": "Peter Slaughter",
            "role": {
                "namespace": "http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode",
                "roleCode": "contributor"
            }
        },
        {
            "@type": "organization",
            "email": "info@ucop.edu",
            "name": "University of California, Santa Barbara",
            "role": {
                "namespace": "http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode",
                "roleCode": "copyrightHolder"
            }
        }
    ],
    "codeRepository": "https://github.com/DataONEorg/rdataone",
    "controlledTem": "software",
    "dateCreated": "2016-05-27",
    "dateModified": "2016-05-27",
    "datePublished": "2016-05-27",
    "depends": {
        "@type": "URL",
        "@value": "https://github.com/ropensci/datapack"
    },
    "description": "Provides read and write access to data and metadata from the DataONE network of data repositories.Each DataONE repository implements a consistent repository application programming interface. Users call methods in R to access these remote repository functions, such as methods to query the metadata catalog, get access to metadata for particular data packages, and read the data objects from the data repository.Users can also insert and update data objects on repositories that support these methods.",
    "downloadLink": "https://cran.r-project.org/src/contrib/dataone_2.0.0.tar.gz",
    "funding": "National Science Foundation grant #012345678",
    "identifier": "",
    "isAutomatedBuild": false,
    "issueTracker": "https://github.com/DataONEorg/rdataone/issues",
    "licenseId": "Apache-2.0",
    "programmingLanguage": {
        "URL": "https://www.r-project.org",
        "name": "R",
        "version": "> 3.1.1"
    },
    "publisher": "https://cran.r-project.org",
    "readme": "https://github.com/DataONEorg/rdataone/README.md",
    "relatedPublications": "ISBN:0201703726",
    "relationship": {
        "relatedIdentifier": "urn:uuid:F1A0A7AF-ECF3-4C7D-B675-7C6949963995",
        "relatedIdentifierType": "UUID",
        "relationshipType": "isPartOf"
    },
    "softwarePaperCitationIdentifiers": "http://doi.org/0000/0000",
    "tags": [
        "data sharing",
        "data repository",
        "DataONE"
    ],
    "title": "R Interface to the DataONE REST API",
    "uploadedBy": {
        "@id": "http://orcid.org/0000-0003-0077-4738",
        "@type": "person",
        "email": "mbjones@nceas.ucsb.edu",
        "name": "Matt Jones"
    },
    "version": "2.0.0",
    "zippedCode": "https://cran.r-project.org/src/contrib/dataone_2.0.0.tar.gz"
}

HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:53 GMT
ETag: W/"11123e6c0147f6477fe936c28ef2563c"
Location: https://mds.test.datacite.org/metadata/10.70043/wt34-ac62
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: 951c3e92-7480-4625-b49b-b3a8080020df
X-Runtime: 0.087869

OK (10.70043/WT34-AC62)



## Metadata in RIS
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/crossref.ris Content-Type:application/x-research-info-systems;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 537
Content-Type: application/x-research-info-systems
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

TY  - JOUR
T1  - Automated quantitative histology reveals vascular morphodynamics during Arabidopsis hypocotyl secondary growth
T2  - eLife
AU  - Sankar, Martial
AU  - Nieminen, Kaisa
AU  - Ragni, Laura
AU  - Xenarios, Ioannis
AU  - Hardtke, Christian S
DO  -
UR  -
AB  - Among various advantages, their small size makes model organisms preferred subjects of investigation. Yet, even in model systems detailed analysis of numerous developmental processes at cellular level is severely hampered by their scale.
PY  - 2014
VL  - 3
ER  -

HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:55 GMT
ETag: W/"802b9a9ef6eebfe135f0f2d54a8983cd"
Location: https://mds.test.datacite.org/metadata/10.70043/gc5n-at76
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: c561684c-787c-41cf-a431-e8e9cd9c4d8d
X-Runtime: 0.097105

OK (10.70043/GC5N-AT76)



## Metadata in BibTeX
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043 < files_random/crossref.bib Content-Type:application/x-bibtex;charset=utf-8 `
POST /metadata/10.70043 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 740
Content-Type: application/x-bibtex
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8

@article{Sankar_2014,
  doi = {},
  url = {},
  year = 2014,
  month = {feb},
  publisher = {{eLife} Sciences Organisation, Ltd.},
  volume = {3},
  author = {Martial Sankar and Kaisa Nieminen and Laura Ragni and Ioannis Xenarios and Christian S Hardtke},
  title = {Automated quantitative histology reveals vascular morphodynamics during Arabidopsis hypocotyl secondary growth},
  abstract = {Among various advantages, their small size makes model organisms preferred subjects of investigation. Yet, even in model systems detailed analysis of numerous developmental processes at cellular level is severely hampered by their scale.},
  journal = {eLife},
  issn = {2050-084X},
  copyright = {http://creativecommons.org/licenses/by/3.0/}
 }

HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 18:53:58 GMT
ETag: W/"ede70d81a798b7307cb37754ed8affc1"
Location: https://mds.test.datacite.org/metadata/10.70043/fw7v-4833
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: 4c403c4f-df3d-4936-af05-daaadd6573dc
X-Runtime: 0.088563

OK (10.70043/FW7V-4833)

**Comment by kjgarza** [comment]
Random with partial strings:



## Random DOI with non-prefix
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.7004 < files_random/datacite.xml Content-Type:application/xml;charset=utf-8 `
POST /metadata/10.7004 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 2031
Content-Type: application/xml
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8
```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI"></identifier>
  <creators>
    <creator>
      <creatorName>Fenner, Martin</creatorName>
      <givenName>Martin</givenName>
      <familyName>Fenner</familyName>
      <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0003-1419-2405</nameIdentifier>
    </creator>
  </creators>
  <titles>
    <title>Eating your own Dog Food</title>
  </titles>
  <publisher>DataCite</publisher>
  <publicationYear>2016</publicationYear>
  <resourceType resourceTypeGeneral="Text">BlogPosting</resourceType>
  <alternateIdentifiers>
    <alternateIdentifier alternateIdentifierType="Local accession number">MS-49-3632-5083</alternateIdentifier>
  </alternateIdentifiers>
  <subjects>
    <subject>datacite</subject>
    <subject>doi</subject>
    <subject>metadata</subject>
  </subjects>
  <dates>
    <date dateType="Created">2016-12-20</date>
    <date dateType="Issued">2016-12-20</date>
    <date dateType="Updated">2016-12-20</date>
  </dates>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.70043/0012</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.70043/55E5-T5C0</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.70043/0000-00SS</relatedIdentifier>
  </relatedIdentifiers>
  <version>1.0</version>
  <descriptions>
    <description descriptionType="Abstract">Eating your own dog food is a slang term to describe that an organization should itself use the products and services it provides. For DataCite this means that we should use DOIs with appropriate metadata and strategies for long-term preservation for...</description>
  </descriptions>
</resource>
```
HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 19:47:09 GMT
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 403 Forbidden
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: ca0b57e4-a489-4de9-a69c-271463046b12
X-Runtime: 0.159550

Access is denied


## Random DOI with number
`http -v  -a DEMO.DATACITE POST https://mds.test.datacite.org/metadata/10.70043?number=77 < files_random/datacite.xml Content-Type:application/xml;charset=utf-8 `
POST /metadata/10.70043?number=77 HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Basic REVNTy5EQVRBQ0lURTpNdXNoaWx5NVJlYWJzb3JiKnN0cmFuZ2xl
Connection: keep-alive
Content-Length: 2031
Content-Type: application/xml
Host: mds.test.datacite.org
User-Agent: HTTPie/0.9.8
```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI"></identifier>
  <creators>
    <creator>
      <creatorName>Fenner, Martin</creatorName>
      <givenName>Martin</givenName>
      <familyName>Fenner</familyName>
      <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0003-1419-2405</nameIdentifier>
    </creator>
  </creators>
  <titles>
    <title>Eating your own Dog Food</title>
  </titles>
  <publisher>DataCite</publisher>
  <publicationYear>2016</publicationYear>
  <resourceType resourceTypeGeneral="Text">BlogPosting</resourceType>
  <alternateIdentifiers>
    <alternateIdentifier alternateIdentifierType="Local accession number">MS-49-3632-5083</alternateIdentifier>
  </alternateIdentifiers>
  <subjects>
    <subject>datacite</subject>
    <subject>doi</subject>
    <subject>metadata</subject>
  </subjects>
  <dates>
    <date dateType="Created">2016-12-20</date>
    <date dateType="Issued">2016-12-20</date>
    <date dateType="Updated">2016-12-20</date>
  </dates>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.70043/0012</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.70043/55E5-T5C0</relatedIdentifier>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="IsPartOf">10.70043/0000-00SS</relatedIdentifier>
  </relatedIdentifiers>
  <version>1.0</version>
  <descriptions>
    <description descriptionType="Abstract">Eating your own dog food is a slang term to describe that an organization should itself use the products and services it provides. For DataCite this means that we should use DOIs with appropriate metadata and strategies for long-term preservation for...</description>
  </descriptions>
</resource>
```
HTTP/1.1 201 Created
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Aug 2018 19:47:10 GMT
ETag: W/"317287bdf4cf926cb28f0ef8630c76f2"
Location: https://mds.test.datacite.org/metadata/10.70043/0000-2d61
Server: nginx/1.14.0 + Phusion Passenger 5.3.3
Status: 201 Created
Transfer-Encoding: chunked
Vary: Accept-Encoding, Origin
X-Credential-Username: DEMO.DATACITE
X-Powered-By: Phusion Passenger 5.3.3
X-Request-Id: c742b5cf-4f07-490e-abeb-8c0a46ebfbb3
X-Runtime: 0.267197

OK (10.70043/0000-2D61)

**Comment by mfenner** [comment]
Note: the non-prefix example is for a prefix where the client has no permission. So everything looks good. I guess the XML generated has the expected identifier, as you don't show that.

**Comment by mfenner** [comment]
Everything looks as expected.
