### ISSUE TITLE
Generate CSV file with prefix/subdomain pairs

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#435]
For some sources in Event Data we need to map the URL to the DOI. We use a list of prefix/subdomain pairs to make this work. Using the list as input, @afandian will do the actual work in Event Data, using the same workflow also used for Crossref DOIs.

**Comment by kjgarza** [comment]
This is the script to create the list of pairings. 
https://gist.github.com/kjgarza/b76bafa2efd20faf4297c6b2bb45fcb3
I have already sent a list to Joe. Thats was 1330 pairings for unique prefixes. However that list does not include many-to-many relationships.
