### ISSUE TITLE
Fabrica localization

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#44]
As a DataCite member, I need a user-interface that I can use to update my DataCite metadata in my language.

child of datacite/datacite#437.

**Comment by mfenner** [comment]
@espacial can we look into this, as it has implications for application design. Does this mean to basically replicate the multi-language functionality of the MDS UI, other language (e.g. Russian, Chinese), etc.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
