### ISSUE TITLE
Use PUT for metadata creation

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#441]
Support `PUT /metadata/10.xxx` in addition to `POST /metadata` for metadata creation and updates:

* better aligned with REST principles, as this is an idempotent action
* aligned with `PUT /doi/10.xxx`
* much easier support for other metadata formats
* easier logging (searching by DOI)

child of #431

**Comment by richardhallett** [comment]
http --session=rph PUT https://mds.test.datacite.org/metadata/10.70048/483t-8j42 Content-Type:application/xml charset:UTF-8 < 10.70048483t-8j42.xml

*Input Metadata*

	<?xml version="1.0" encoding="UTF-8"?>
	<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
	  <identifier identifierType="DOI">10.70048/483t-8j42</identifier>
	  <creators>
	    <creator>
	      <creatorName nameType="Personal">Smith, John</creatorName>
	      <givenName>Richard</givenName>
	      <familyName>Hallett</familyName>
	      <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0002-7352-517X</nameIdentifier>
	      <affiliation>DataCite</affiliation>
	    </creator>
	  </creators>
	 <titles>
	    <title xml:lang="en-US">DataCite RPH DOI Test Example</title>
	  </titles>
	  <publisher>DataCite</publisher>
	  <publicationYear>2018</publicationYear>
	  <resourceType resourceTypeGeneral="Text">XML</resourceType>
	  <subjects>
	    <subject>datacite</subject>
	    <subject>doi</subject>
	    <subject>metadata</subject>
	  </subjects>
	  <dates>
	    <date dateType="Created">2018-06-12</date>
	    <date dateType="Issued">2018-06-12</date>
	    <date dateType="Updated">2018-06-12</date>
	  </dates>
	  <version>1.0</version>
	  <descriptions>
	    <description descriptionType="Abstract">This is a test DOI xml for RPH's purposes.</description>
	  </descriptions>
	</resource>

*HTTP Response*

	HTTP/1.1 201 Created
	Cache-Control: max-age=0, private, must-revalidate
	Connection: keep-alive
	Content-Type: text/plain; charset=utf-8
	Date: Mon, 06 Aug 2018 13:15:36 GMT
	ETag: W/"929e756786896ab4199bfa37f201207c"
	Location: https://mds.test.datacite.org/metadata/10.70048/483t-8j42
	Server: nginx/1.14.0 + Phusion Passenger 5.3.4
	Status: 201 Created
	Transfer-Encoding: chunked
	Vary: Accept-Encoding, Origin
	X-Credential-Username: datacite.rph
	X-Powered-By: Phusion Passenger 5.3.4
	X-Request-Id: f0ac33bd-1c83-4109-b145-e4ff0d061a87
	X-Runtime: 0.237136

	OK (10.70048/483T-8J42)

http --session=rph GET https://mds.test.datacite.org/metadata/10.70048/483t-8j42

*Result Metadata*

	<?xml version="1.0" encoding="UTF-8"?>
	<ns0:resource xmlns:ns0="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
	    <ns0:identifier identifierType="DOI">10.70048/483T-8J42</ns0:identifier>
	    <ns0:creators>
	        <ns0:creator>
	            <ns0:creatorName nameType="Personal">Smith, John</ns0:creatorName>
	            <ns0:givenName>Richard</ns0:givenName>
	            <ns0:familyName>Hallett</ns0:familyName>
	            <ns0:nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org/">0000-0002-7352-517X</ns0:nameIdentifier>
	            <ns0:affiliation>DataCite</ns0:affiliation>
	        </ns0:creator>
	    </ns0:creators>
	    <ns0:titles>
	        <ns0:title xml:lang="en-US">DataCite RPH DOI Test Example</ns0:title>
	    </ns0:titles>
	    <ns0:publisher>DataCite</ns0:publisher>
	    <ns0:publicationYear>2018</ns0:publicationYear>
	    <ns0:resourceType resourceTypeGeneral="Text">XML</ns0:resourceType>
	    <ns0:subjects>
	        <ns0:subject>datacite</ns0:subject>
	        <ns0:subject>doi</ns0:subject>
	        <ns0:subject>metadata</ns0:subject>
	    </ns0:subjects>
	    <ns0:dates>
	        <ns0:date dateType="Created">2018-06-12</ns0:date>
	        <ns0:date dateType="Issued">2018-06-12</ns0:date>
	        <ns0:date dateType="Updated">2018-06-12</ns0:date>
	    </ns0:dates>
	    <ns0:version>1.0</ns0:version>
	    <ns0:descriptions>
	        <ns0:description descriptionType="Abstract">This is a test DOI xml for RPH's purposes.</ns0:description>
	    </ns0:descriptions>
	</ns0:resource>

**Comment by richardhallett** [comment]
This was an update above and my observation is that it returned 201 Created, I'd probably prefer 200 if it's just an update rather than a created.

**Comment by mfenner** [comment]
Thanks. I also prefer 200 (and this is what the Lupo API returns), but the MDS API expects 201 for both: https://github.com/datacite/poodle/blob/master/app/controllers/metadata_controller.rb#L54-L55

**Comment by mfenner** [comment]
Looking good, closing this issue.
