### ISSUE TITLE
improve text contrast in support site menus

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#443]
The text in the left sidebar menus on the support site is a very pale grey, and that lack of contrast makes it hard to read. To solve this, we'll have to add a custom stylesheet to our readme.io settings. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_d58r)

**Comment by mfenner** [comment]
Keep issue open.

**Comment by mfenner** [comment]
don't close.
