### ISSUE TITLE
Document link checking

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#450]
Document the link checker and it's functionality within the support site.
* What does it do
* What results it gathers
* What they mean
* Where it is presented.

Child of #444

**Comment by richardhallett** [comment]
Rough summary notes:
Provides information about registered URL's for dois, this is based upon a random sample that an automated crawler will check once per day.
Over time we hope to be able to build a larger picture across all our clients.
It finds information about: HTTP details, (status, content/type) and looks for metadata information... schema.org, dc metadata, citation meta tags.
This is available via authorised clients to our API it is also available per DOI within Fabrica.

**Comment by daslerr** [comment]
Docs done: https://support.datacite.org/docs/link-checker
