### ISSUE TITLE
Embedded schema.org not recognized

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#452]
https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1339

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_d6qz)

**Comment by richardhallett** [comment]
This issue is related to using the functionality of the file upload form within Fabrica to automatically register using embedded schema.org on the landing page.
The example above given when used returns invalid metadata, however an initial cursory glance suggests the metadata is valid.

**Comment by richardhallett** [comment]
Initial investigations, this isn't a Fabrica issue but related to our underlying parsing of schema.org in bolognese.

**Comment by richardhallett** [comment]
Further detailed investigation has actually traced the problem through to the request we're making via our Maremma library.
Without a "Host" header specified, the end server for this specific URL rejects and returns a 503.

**Comment by mfenner** [comment]
The specific place where a change is needed for this functionality is https://github.com/datacite/bolognese/blob/master/lib/bolognese/readers/schema_org_reader.rb#L19

**Comment by richardhallett** [comment]
@mfenner thanks!
Tested original users use-case, now fixed in production.
