### ISSUE TITLE
prefix transfer LabArchives

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#466]
prefix: 10.5060 and 10.6070

dois: all

old: CDL.LABARCH

new: LABARC.PRO

date: 23 August

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dd5v)

**Comment by pcruse** [comment]
thanks!
