### ISSUE TITLE
move sidebars to the left side of the page

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#467]
On the Fabrica DOI search page, move the list of facets from the right side of the page to the left.

**Comment by mfenner** [comment]
@daslerr can you clarify? Is this true for all search pages (e.g. providers, clients, prefixes)? What about other pages that have a sidebar on the right, e.g. the page for a single DOI?

**Comment by mfenner** [comment]
<img width="1017" alt="bildschirmfoto 2018-08-23 um 22 33 04" src="https://user-images.githubusercontent.com/23151/44550428-8b263b80-a724-11e8-8905-554523568094.png">

**Comment by mfenner** [comment]
<img width="1223" alt="bildschirmfoto 2018-08-23 um 22 34 19" src="https://user-images.githubusercontent.com/23151/44550481-b7da5300-a724-11e8-8289-d19580709339.png">

**Comment by daslerr** [comment]
Move all sidebars and buttons to the left. I've updated the issue title.
