### ISSUE TITLE
Add ability to return to blank slate for searching

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#469]
In the DOI search for Fabrica, users requested the ability to be able to quickly return to a blank slate for the purposes of starting a search over. This is in 2 parts: 

1. Clicking the x in the search bar to clear a search should also reset the results. Right now the results don't change until other filters are selected or the user searches again, but users preferred having the visual feedback of the search resetting when the bar was cleared.

2. Users would like a button or link to click to reset the search (i.e. clear the search bar, deselect all the selected filters, and return all results instead of a subset).

**Comment by mfenner** [comment]
Can you clarify 1.? Isn't that the current implementation of the x in the search bar? Is the delay too long, or does this not work with some browsers?

**Comment by mfenner** [comment]
How does a user distinguish 1. and 2.? Should there be two reset options, one for the query string and one for the facets? Or just one option that resets everything?

**Comment by daslerr** [comment]
The delay must have been too long. It seems to work now that the faceting delay improvements have been implemented. So number 1 is already fixed.

**Comment by daslerr** [comment]
The impression I got from testing was that there should be two options, but it should be one for the query string and one for everything.

**Comment by daslerr** [comment]
The current implementation has one option for clearing the query string and one for clearing the facets. The link for clearing the facets should instead clear all searching (so, facets and query string). Can it be relabeled as "Reset all"?

**Comment by mfenner** [comment]
Will make the suggested change.
