### ISSUE TITLE
Track indexing delay in logs

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#471]
Add Elasticsearch DOI indexing to the logs so we can measure the delay and send an alert when it's too long.

**Comment by mfenner** [comment]
![bildschirmfoto 2018-08-25 um 17 09 00](https://user-images.githubusercontent.com/23151/44619589-9e065080-a889-11e8-84e4-a059fcf1e4c5.png)

**Comment by mfenner** [comment]
Will add alerts once we have more data and understand what delay to expect.
