### ISSUE TITLE
DOI state change made in MDS UI not showing in Fabrica

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#474]
User reports that they unchecked the `is active` checkbox in the MDS UI for a DOI and saved, but that DOI is still appearing in Fabrica as Findable. When they log into the MDS UI, the DOI does not show up at all. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_deaz)

**Comment by richardhallett** [comment]
Okay this is to be expected, while our documentation says it relates to findable with:
"This state maps to "is_active=true" in the DataCite Metadata Store."
This is true, but it doesn't mean that if you change it in the MDS UI it updates it in the fabrica UI, or at least not that I can tell, I think the idea was that it's analogous to the "findable" state, but not necessarily that changing one updates the other.

The question then here is whether or not we want to allow changing is_active in MDS UI to reflect in findable, my argument is no given that MDS UI will be retired in the near future. CC @mfenner

**Comment by richardhallett** [comment]
Okay this issue that relates to MDS UI and I understand a bit better now.
If somebody creates a DOI in MDS UI or changes the details, it's possible that the state will be in an Undetermined state.
Once a day a script runs that will fix this.
Obviously ideally people should just be using Fabrica and not MDS UI.
