### ISSUE TITLE
unable to create new clients

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#476]
User reports being unable to create a new client in DOI Fabrica. Information entered into new client form validates and appears to be error-free, but clicking the Create Client button does nothing. I tried to create the client for them manually in Fabrica, and I encountered the same issue. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dec3)

**Comment by mfenner** [comment]
I have fixed the automatic prefix registration step. @kjgarza the tests are failing for other reasons and need more work. They are currently commented out.
