### ISSUE TITLE
unable to assign prefix to a client

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#477]
User reports being unable to assign a prefix to a client. User seems to have successfully assigned the prefix to the provider, and it appears in the provider's list of available prefixes, but the Assign Prefix button does not appear on the client prefixes page. Staff attempt to assign the prefix via Fabrica also failed. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_decj)

**Comment by mfenner** [comment]
Can't reproduce.

**Comment by daslerr** [comment]
This was a similar problem to https://github.com/datacite/bracco/issues/102. The prefix appeared in provider's list of available prefixes, but the client field for the prefix was empty, even though the facet numbers indicated the prefix should be assigned to a client. It appears to have been fixed by the fix for https://github.com/datacite/bracco/issues/102.
