### ISSUE TITLE
unable to transfer DOIs

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#478]
User reports being unable to transfer DOIs between clients. User makes it to the transfer DOI screen and selects the client from the dropdown, but clicking the Transfer DOI button does nothing. I am also unable to perform this action in staff mode. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_decr)

**Comment by mfenner** [comment]
Error message returned from API is `{"errors":[{"status":"422","title":"found unpermitted parameters: :givenName, :familyName"}]}`.

**Comment by kjgarza** [comment]
I don't think I can find any attempt of DOI trasnfer i nthe logs. https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%5D&event&from_ts=1532776472412&index=main&live=true&query=%2210.4227%2F05%2F58b7902525db5%22+%7C%7C+%2210.4227%2F05%2F54F8F99CC756E%22+%7C%7C+%2210.4227%2F05%2F54F7CBFAEAB85%22&stream_sort=desc&to_ts=1535368472412

The api seems to be working ok. I made a spec for a single transfer and ther seem to be not a problem. https://github.com/datacite/lupo/commit/60010c2941f6ad264b78e6ff0f491969cf6ffc27


So I am assuming the whole problem is in Bracco and not in the API

**Comment by kjgarza** [comment]
I have managed to trasnfer DOIs `locally` and in `stage` enviroment. this function only fails in `production`. There is not problem with the `release` last realese is sync with master. So there problem should be somewhere else.

**Comment by mfenner** [comment]
That is not how bracco works, and that's why I have added a permissions check specifically for DOI transfers: https://github.com/datacite/lupo/blob/master/app/controllers/dois_controller.rb#L226-L230

Maybe that check should be modified.

**Comment by kjgarza** [comment]
i'm not sure, I follow?  You mean bracco will always send the whole object ?and thus we need to make changes somewhere else?


This is what `bracco` is sending:
```
{
  "data": {
    "id": "10.23725/at5e-0s42",
    "attributes": {
      "identifier": "https://handle.test.datacite.org/10.23725/at5e-0s42",
      "doi": "10.23725/at5e-0s42",
      "confirm-doi": null,
      "prefix": "10.23725",
      "suffix": "at5e-0s42",
      "url": "http://example.com",
      "author": [{
        "type": "Person",
        "id": "https://orcid.org/0000-0003-1419-2405",
        "name": "Fenner, Martin",
        "givenName": "Martin",
        "familyName": "Fenner"
      }],
      "title": "Eating your own Dog Food",
      "publisher": "DataCite",
      "published": "2016",
      "description": "Eating your own dog food is a slang term to describe that an organization should itself use the products and services it provides. For DataCite this means that we should use DOIs with appropriate metadata and strategies for long-term preservation for...",
      "license": null,
      "xml": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPG5zMDpyZXNvdXJjZSB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4bWxuczpuczA9Imh0dHA6Ly9kYXRhY2l0ZS5vcmcvc2NoZW1hL2tlcm5lbC00IiB4c2k6c2NoZW1hTG9jYXRpb249Imh0dHA6Ly9kYXRhY2l0ZS5vcmcvc2NoZW1hL2tlcm5lbC00IGh0dHA6Ly9zY2hlbWEuZGF0YWNpdGUub3JnL21ldGEva2VybmVsLTQvbWV0YWRhdGEueHNkIj4KICA8bnMwOmlkZW50aWZpZXIgaWRlbnRpZmllclR5cGU9IkRPSSI+MTAuMjM3MjUvYXQ1ZS0wczQyPC9uczA6aWRlbnRpZmllcj4KICA8bnMwOmNyZWF0b3JzPgogICAgPG5zMDpjcmVhdG9yPgogICAgICA8bnMwOmNyZWF0b3JOYW1lPkZlbm5lciwgTWFydGluPC9uczA6Y3JlYXRvck5hbWU+CiAgICAgIDxuczA6Z2l2ZW5OYW1lPk1hcnRpbjwvbnMwOmdpdmVuTmFtZT4KICAgICAgPG5zMDpmYW1pbHlOYW1lPkZlbm5lcjwvbnMwOmZhbWlseU5hbWU+CiAgICAgIDxuczA6bmFtZUlkZW50aWZpZXIgc2NoZW1lVVJJPSJodHRwOi8vb3JjaWQub3JnLyIgbmFtZUlkZW50aWZpZXJTY2hlbWU9Ik9SQ0lEIj4wMDAwLTAwMDMtMTQxOS0yNDA1PC9uczA6bmFtZUlkZW50aWZpZXI+CiAgICA8L25zMDpjcmVhdG9yPgogIDwvbnMwOmNyZWF0b3JzPgogIDxuczA6dGl0bGVzPgogICAgPG5zMDp0aXRsZT5FYXRpbmcgeW91ciBvd24gRG9nIEZvb2Q8L25zMDp0aXRsZT4KICA8L25zMDp0aXRsZXM+CiAgPG5",
      "resource-type-subtype": "BlogPosting",
      "version": "1.0",
      "metadata-version": "1",
      "schema-version": "http://datacite.org/schema/kernel-4",
      "is-active": true,
      "source": "mds",
      "state": "findable",
      "event": null,
      "created": "2018-08-29T13:45:34.000Z",
      "registered": "2018-08-29T14:07:53.000Z",
      "updated": "2018-08-29T14:07:53.000Z",
      "mode": "transfer"
    },
    "relationships": {
      "client": {
        "data": {
          "type": "clients",
          "id": "datacite.rph"
        }
      },
      "resource-type": {
        "data": {
          "type": "resource-types",
          "id": "text"
        }
      }
    },
    "type": "dois"
  }
}
```

**Comment by mfenner** [comment]
I am sure you can tweak that, but that is standard ember operation. Why don't you take `"mode": "transfer"` and check that in lupo?

**Comment by mfenner** [comment]
@kjgarza I am not sure why you commit tests that confirm the bug. It is a good approach to start like this, but you should then implement a fix before you push to the repo.

**Comment by kjgarza** [comment]
closed on https://github.com/datacite/lupo/commit/660508f64c9b0e356f467967dbeddba5c983228b

**Comment by kjgarza** [comment]
Reopned as the user problem now similar to the staff problem. This link provide a video in which actually the `Bracco` application DOES NO EXECUTE any request to lupo upon clicking 

https://www.dropbox.com/s/ps66kifhjaebmdo/DOI%20Transfer.mov?dl=0

I have not been able to reproduce this locally. I need to investigate further.

**Comment by kjgarza** [comment]
There has not any change but it is working now. Potentially could be related with other dependencies deployment. 

I have tested transfer as a PROVIDER and Staff in both the Productio and Test system.

@daslerr
