### ISSUE TITLE
updated URLs show in MDS UI but not in Fabrica

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#479]
User reports that they have updated the URLs for several DOIs, but these updated URLs do not show in Fabrica. They only appear in the MDS UI. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_desb)

**Comment by mfenner** [comment]
Keep in mind that DOI Fabrica shows the URL stored in the database whereas the MDS UI shows the URL from the handle system. We haven't yet backfilled the database will all records from the handle system (only about 50%).

**Comment by mfenner** [comment]
@daslerr please investigate whether the issue is with DOIs registered after July 15. For older DOIs we have to backfill the database. This is a display issue and doesn't affect the functionality of the DOIs.

**Comment by richardhallett** [comment]
Based upon the conversation above, I don't think there is any bug to solve here at this time, aside from some housekeeping that might need to be done. Closing for now.
