### ISSUE TITLE
add additional fields to Fabrica client settings

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#481]
Add fields to Fabrica client settings to help with client contact and management. These include: 
1. Contact name, in addition to contact email address.
2. More than one type of contact, such as administrative contact or billing contact. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dezn)

**Comment by mfenner** [comment]
We have had `contact name` for some time. Can you clarify the contacts you want to see in DOI Fabrica?

**Comment by daslerr** [comment]
Whoops. I shouldn't have combined these issues. Contact name doesn't show on the list of clients in the provider view. I've made a separate issue for that. #483
