### ISSUE TITLE
DOI registration with metadata larger than 1 MB not working

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#484]
Recently implemented (see #426 and https://github.com/datacite/mds/issues/334) support for registering DOIs with large metadata files is not working properly. 

From support: "... our ingest still fails on the DataCite upload, particularly during ‘POST /metadata’. While we got a ‘413 - Request Entity Too Large’ before the issue was fixed, yesterday I got a ‘504 - Gateway Time-out’ and today (at 8:25 AM, Dutch time) I got a ‘500 - Internal Server Error’. Also when I tried to use the production version of DataCite yesterday, using our test account, I got the same ‘500 - Internal Server Error’."

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dgdv)

**Comment by mfenner** [comment]
This has been resolved.
