### ISSUE TITLE
CreativeWork is automatically added as resourceType when a user leaves the field blank

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#488]
In Fabrica, if you leave the free-text resourceType field blank, it is automatically filled in by `CreativeWork`, which is the schema.org term for anything, and is used internally in our metadata conversion library. However, if you look at the DataCite XML view of the record, it shows CreativeWork inserted in the metadata. Some users have expressed concern that their metadata record is being altered. 
![screen shot 2018-08-29 at 20 55 38](https://user-images.githubusercontent.com/3181623/44809174-4429c180-abce-11e8-811e-107225be8007.png)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dhu3)

**Comment by richardhallett** [comment]
Can not reproduce, this is possible no longer an issue. Please re-open with reproducible steps if you think it's still a problem.
