### ISSUE TITLE
Undetermined State

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#491]
Using Fabrica, creating a doi and switching the state can cause it to enter into a Undetermined state.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dhv7)

**Comment by richardhallett** [comment]
This appears to just be a noticable delay rather than it not working, I'm guessing something to do with various background processes that occur, but needs more investigation.
Currently it's a bit confusing for users who see "Undetermined" immediately when switching states.

**Comment by richardhallett** [comment]
I've managed to reproduce in Fabrica Test, The scenario I've created appears to be when you use Metadata without an ID. This is valid for draft but it seems to put it in the undetermined state.

**Comment by richardhallett** [comment]
I've been unable to reproduce this in a unit test, using the same POST request seems to not reproduce, this is proving difficult to reproduce in a way that can help fixing the problem.

One thing with the doi's in undetermined on "doi.test.datacite.org" environment is that in the database the state is correctly set to draft, it just in the result that it's 'undetermined'. One theory I had was potentially the update wasn't occurring in elasticsearch.

**Comment by mfenner** [comment]
The main issue causing this is the caching in the DOI serializer in the API. Caching with the `fast_jsonapi` gem works differently than with `active_model_serializers` and is not a good fit for the DOI model. See also https://github.com/Netflix/fast_jsonapi/issues/300

Another (minor) issue was the default state `undetermined` for new DOIs. I changed that to `draft`, as DOIs can no longer be registered via the legacy MDS API, so everything goes through the Lupo API. The only exception for another month is the MDS UI.
