### ISSUE TITLE
prefix transfer Galter

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#492]
dois: all
prefix: 10.18131
old: PURDUE.GHSL
new: GHSL.GALTER
date: 4 September, 6:00 pm Europe

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dhwb)

**Comment by kjgarza** [comment]
I performed the transfer. It said it would take a few minutes, but I has not occurred yet. it was 750 DOIs, is that normal ?? @mfenner

**Comment by daslerr** [comment]
transfer was completed successfully
