### ISSUE TITLE
searches returning records from related identifiers

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#493]
Some users have reported metadata from related identifiers being returned instead of the metadata for the DOI they're looking for. In one case the affected metadata was found in the downloadable metadata on the record view in DataCite Search, and in another it was retrieved in content negotiation. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dhwz)

**Comment by mfenner** [comment]
This has been fixed.
