### ISSUE TITLE
remove CISTI.CRIFPE DOIs

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#494]
CISTI.CRIFPE transferred their DOIs to Crossref in 2016, but the metadata was not removed from our system. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dhyb)

**Comment by mfenner** [comment]
client account, prefix, DOIs and metadata have been deleted.
