### ISSUE TITLE
DOI transfer NOAA NCEI

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#508]
old: CDL.NOAA
new: NOAA.NCEI
dois: subset with prefix 10.3334 according to list submitted via support (1131 total)
prefix: Prefix is not assigned to them. This is a takeover from an earlier transfer within EZID.

old: CDL.NOAA
new: NOAA.NCEI-NCL
dois: all remaining DOIs after the transfer above
prefix: 10.7289

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dqx7)

**Comment by kjgarza** [comment]
child: https://github.com/datacite/cirneco/issues/3
