### ISSUE TITLE
re3data badge not displaying accurately colored icons

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#527]
User reports that their re3data badge in Fabrica is not showing the PID icon colored blue (to indidcate they offer PIDs), even though this information is up to date in re3data. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e09n)

**Comment by re3data** [comment]
PI-Icon hasn't been shown in the badge for repositories supporting multiple PID systems. The bug has been fixed, all badges have been regenerated and should show the correct information now.

**Comment by mfenner** [comment]
Thank you!
