### ISSUE TITLE
Fabrica form and file upload does not create draft DOI without metadata

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#582]
To reproduce:

Go to DOI Fabrica client account
Click create DOI
In the form view do not fill in metadata, click "create DOI" nothing happens
Repeat with file upload
Draft state selected in both instances

Expected output
It should be possible to create a DOI with no metadata or URL
Function to create Draft DOI with no metadata is working in doi.test

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fibf)

**Comment by mfenner** [comment]
This issue has been resolved.
