### ISSUE TITLE
Problem with content negotiation

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#585]
Content negotiation issue affecting Citeproc JSON and schema.org

https://data.datacite.org/application/vnd.citationstyles.csl+json/10.17171/2-7-10-39

https://data.datacite.org/application/vnd.schemaorg.ld+json/10.17171/2-7-10-39

Error Message:

 `The resource you are looking for doesn't exist.`.

possible related Front ticket https://app.frontapp.com/open/cnv_147ya8r reports:

"Extracting content from the metadata store is still not functional, but now the error message is instead "HTTP/1.1 404 Not Found".

E.g.

https://data.datacite.org/application/vnd.datacite.datacite+xml/10.5438/MRR6-MF3Q

https://data.datacite.org/application/rdf+xml/10.5438/MRR6-MF3Q

**Comment by richardhallett** [comment]
Updated various places using old app.datacite.org links, all should be working now.
