### ISSUE TITLE
MDS API - Register DOI call does not transition from draft to findable

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#594]
This was originally raised as a invalid metadata issue via a support request: https://app.frontapp.com/open/msg_247j1c3
However taking the metadata and putting it into a test DOI via 10.70048/xfnr-sf41 the metadata appears valid, however doing a PUT call to the MDS /doi endpoint does not transition from DRAFT to FINDABLE.

Call is:

curl -H "Content-Type:text/plain;charset=UTF-8" -X PUT --user datacite.rph:password -d "$(printf 'doi=10.70048/xfnr-sf41\nurl=http://example.org/')" https://mds.test.datacite.org/doi/10.70048/xfnr-sf41

The DOI remains in the Draft state.

**Comment by richardhallett** [comment]
This now instead appears to raise "Is Invalid" as the error.

Child of #597

**Comment by mfenner** [comment]
This works if the metadata in draft state are valid, see #600.
