### ISSUE TITLE
Add ES query options for landing page data

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#595]
Add ES Query options to allow querying for Landing Page information.

**Comment by richardhallett** [comment]
Commits:
https://github.com/datacite/lupo/commit/0a6e9977fcae5e7a5376e0585188a80106289b12
https://github.com/datacite/lupo/commit/7dd652b0b8e4387f4a6cd7563b4a8e8f3d129953
https://github.com/datacite/lupo/commit/4f7d5cad29a39b959eb7e5cb741634a9496340fd

**Comment by mfenner** [comment]
Looks good. Maybe adjust if you change the aggregations.
