### ISSUE TITLE
Add ES Aggregations for landing page data

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#596]
Consider adding new aggregations for landing page information.
E.g. Total Checked, Total with Schema org.
Expose in meta properties of REST API.

**Comment by richardhallett** [comment]
This was added under https://github.com/datacite/lupo/commit/7d43ddc4d0ed47c16be42ba474808c60d0b656b6

**Comment by mfenner** [comment]
Suggest to consolidate into one (or two) objects.
