### ISSUE TITLE
MDS API - Get DOI's 500 error

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#599]
Child of #597

http --session=rph GET https://mds.test.datacite.org/doi

Call to /doi should return list of DOI's instead return a 500.

Error from Lupo:
Error 500
Error [{"status"=>500, "title"=>{"responseCode"=>2, "message"=>"HandleException (INVALID_VALUE) The requested prefix doesn't live here", "handle"=>"10.70048"}}]

However the prefix is listed correctly for this client.

https://doi.test.datacite.org/clients/datacite.rph/prefixes

**Comment by richardhallett** [comment]
Right but from what call in the MDS API or Lupo I guess, as I say the error doesn't match up with what the data I can return from the prefixes, they are all homed.

**Comment by mfenner** [comment]
Code is here: https://github.com/datacite/lupo/blob/master/app/models/concerns/helpable.rb

**Comment by richardhallett** [comment]
I had a further look and it does appear the call to the test handle server for handles is failing:

http -a 300%3ATEST/ADMIN:pass GET https://handle.test.datacite.org/api/handles?prefix=10.23725

So this maybe unrelated to the API, but it seems strange this isn't working, it does work in production although of course that uses the global handle server.

Maybe this isn't worth prioritizing atm as it only seems to be a problem for listing DOI's.

**Comment by mfenner** [comment]
Adding `0.NA/10.23725` (instead of the existing `10.23725`) to the `nas` table of the handle server fixed it.

**Comment by mfenner** [comment]
We should do that for all prefixes in the test system where we see this error in our logs.
