### ISSUE TITLE
"Set password" button not responding

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#605]
Environment: DOI Fabrica production

To reproduce
Log in with ADMIN
Create client: e.g DATACITE.MARYTEST
Click "Set Password"
Type a password e.g: zxy2345xyz2345
No response

Expected result: a new password is set and saved

Work around: set the password from the email that is generated and sent to the email contact when the account is set up

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fsrf)

**Comment by MaryHirsch** [comment]
I cannot reproduce this now because I reset the password from the email. To reproduce you need to set up a new client.

**Comment by mfenner** [comment]
This appears not to be related to the "set password" functionality, but to saving changes in client settings in general. Under some circumstances that is not possible, and no error message appears.

**Comment by mfenner** [comment]
The issue is errors with provider accounts, specifically outdated values in provider categories. The issue should be resolved for this provider, otherwise update the provider settings.
