### ISSUE TITLE
Creator Field [object Object]

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#610]
Environment : doi.test.datacite.org

Users report : When clicking on 'Create DOI', the 'Creators' field keeps getting reset. If I enter 2 names, it gets reset to the following string (without the quotes): '[object Object],[object Object]'

I was not able to reproduce this in TEST

However, the same issue has been reported twice:

https://app.frontapp.com/open/cnv_11nwezv
https://app.frontapp.com/open/cnv_1455itn

And a possible related message with the api.test  (Empty Content-Type) [object Object] 
https://app.frontapp.com/open/cnv_13vtraj

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fwkj)

**Comment by MaryHirsch** [comment]
I can reproduce this here when trying to update the URL in this doi 10.17590/20190107-113939-0 from  this http://bfr.bund.de/receive/openagrar_mods_00046145 to this https://www.bfr.bund.de/cm/349/release-of-metals-from-enamel-coated-grill-racks-several-give-too-much.pdf as requested here https://app.frontapp.com/open/cnv_16i2g2b

**Comment by richardhallett** [comment]
This is somewhat of a red herring, the problems are actually more likely related to users attempting to use the form to update previously submitted xml and therefore causing an underlying validation error.

However, the appearance of [object OBject] and other invalid text has been corrected in the test environment.

The solution was to use a computedProperty for the creators field, this then can do it's own serialisation/deserialisation when the data is get/set back to the original creators field which is what is then submitted to the API.

**Comment by richardhallett** [comment]
Deployed to live, this should have removed any validation errors related to Creators field.
