### ISSUE TITLE
orcid claiming return missing data

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#628]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g3b7)

**Comment by kjgarza** [comment]
I reviewed the whole claiming workflow from Search. I still track the problem with Metadata creation with bolognese. However, independently of the version,  every DOI that I try to get metadata with bolognese fails(doesn't return metadata).

But I have some questions actually on the whole thing. Because maybe I’m mistaken but it seems that Bolognese still depends on SOLR for obtaining a DOI metadata https://github.com/datacite/bolognese/blob/8e797412d211e6a9b3e5e26f5f4510198d481871/lib/bolognese/readers/datacite_reader.rb#L11

        ```params = { q: "doi:#{doi}",```


I am wondering whether this is truly necessary. To me this feels like a big dependency, but I am unsure if there another requirement here. 


![image](https://user-images.githubusercontent.com/1092861/50094698-1071b680-0214-11e9-95ee-3d8e895bb9aa.png)

**Comment by kjgarza** [comment]
In essence, this should never fail. Search uses solr in the background, Therefore, claiming a DOI guarantees that the metadata exists.

**Comment by kjgarza** [comment]
Nevertheless the errors for missing data shoot-off 3 month ago in Oct 20th https://app.bugsnag.com/datacite/profiles-backend/errors?filters[event.since][0]=all&filters[error.status][0]=open&sort=last_seen

**Comment by mfenner** [comment]
And please keep in mind that this is not just the search and link workflow that is affected, but also auto-update.

**Comment by mfenner** [comment]
And there is Event Data, which currently only tracks auto-update.
