### ISSUE TITLE
Problems creating "findable" DOIs in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#631]
Environment: https://doi.datacite.org/

Users report issues:

1. Creating new DOIs in Findable state:
https://app.frontapp.com/open/cnv_15px8ln
https://app.frontapp.com/open/cnv_15o7a37
https://app.frontapp.com/open/cnv_15o16cr

2. Changing DOIs from draft to findable state:
https://app.frontapp.com/open/cnv_15nn4aj
https://app.frontapp.com/open/cnv_15nlzij

**Comment by MaryHirsch** [comment]
also this one: https://app.frontapp.com/open/cnv_15miipn

**Comment by MaryHirsch** [comment]
https://app.frontapp.com/open/cnv_15d34eb

**Comment by mfenner** [comment]
Fixed via https://github.com/datacite/bracco/issues/115.
