### ISSUE TITLE
Errors with EZ API

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#634]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g5hn)

```
<response>
  <status_code>422</status_code>
  <error>error: found unpermitted parameter: :author</error>
 </response>
```

**Comment by shlake** [comment]
Yes, UVa just sent in an email to support. Our DOI minting service via EZ API is not working and has not worked since the upgrade.

We are able to create draft DOIs, but do not get the same response back on a "success" and thus cannot update-register DOIs.

**Comment by mfenner** [comment]
@shlake could you give me an example API call, e.g. as curl command or text file containing the ANVL you send?

**Comment by UVADave** [comment]
Martin,

We were unable mint DOI's because (it seems) that the protocol for the mint changed 
(POST /shoulder/doi:10.5072/FK2) and we now need to tokenize the response into lines by splitting on the \r instead of the \n character. This fix allows us to mint DOI's now but 5 other tests in our test suite now fail and instead of debugging each one, I wondered if we can get an understanding of what changes have just been deployed.

--- FAIL: TestDeleteDataCite (0.91s)
    delete_test.go:25: Expected 200, got 404
--- FAIL: TestGetDataCite (0.72s)
    get_test.go:39: Expected 200, got 500
--- FAIL: TestRevokeDataSite (0.97s)
    revoke_test.go:38: Expected 200, got 404
--- FAIL: TestUpdateDataCite (0.83s)
    update_test.go:33: Expected 200, got 404
--- FAIL: TestUpdateBadSchema (0.92s)
    update_test.go:46: Expected 400, got 404

Dave

**Comment by shlake** [comment]
@mfenner Any update.
We cannot generate DOIs, nor update existing ones. We have two systems that are non-functioning because of this problem.

**Comment by mfenner** [comment]
@shlake nothing yet that would really helpful. Unfortunately we have a number of issues coming up this week, and are working through them since this morning. I will give an update here later today.

@UVADave no change in delimiting character, but a change in how ANVL is parsed. This change has been running in the test system for several weeks and addresses an UTF-8 encoding issue: https://github.com/datacite/cheetoh/blob/master/config/application.rb#L78-L81

**Comment by mfenner** [comment]
@UVADave is the test system working ok, or do you have the same issues there?

**Comment by mfenner** [comment]
I am re-running the tests using the UVA examples that you gave us a few months ago:

```
_profile: datacite
_status: reserved
_target: http://google.com
datacite: <resource xmlns="http://datacite.org/schema/kernel-4"%0A          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"%0A          xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">%0A%0A    %0A    <identifier identifierType="DOI">(:tba)</identifier>%0A    %0A%0A    %0A    <creators>%0A       %0A           %0A           <creator>%0A              %0A              <creatorName>Smith, John</creatorName>%0A              %0A              %0A              <givenName>John</givenName>%0A              %0A              %0A              <familyName>Smith</familyName>%0A              %0A              %0A              %0A              <affiliation>Biology, UVa</affiliation>%0A              %0A           </creator>%0A           %0A       %0A    </creators>%0A    %0A%0A    %0A    <titles>%0A       <title>my datacite title</title>%0A    </titles>%0A    %0A%0A    %0A    <publisher>UVa Press</publisher>%0A    %0A%0A    %0A    <publicationYear>2002</publicationYear>%0A    %0A%0A    %0A    <subjects>%0A        %0A           <subject>keyword1</subject>%0A        %0A           <subject>keyword2</subject>%0A        %0A    </subjects>%0A    %0A%0A    %0A    <contributors>%0A      %0A          %0A           <contributor contributorType="Other">%0A              %0A              <contributorName>Blow, Joe</contributorName>%0A              %0A              %0A              <givenName>Joe</givenName>%0A              %0A              %0A              <familyName>Blow</familyName>%0A              %0A              %0A              <affiliation>UVa</affiliation>%0A              %0A           </contributor>%0A           %0A       %0A    </contributors>%0A    %0A%0A    %0A    <dates>%0A       <date dateType="Issued">2002-02-02</date>%0A    </dates>%0A    %0A%0A    %0A    <resourceType resourceTypeGeneral="Sound">Audio</resourceType>%0A    %0A%0A    %0A    <rightsList>%0A       <rights>All rights reserved</rights>%0A    </rightsList>%0A    %0A%0A    %0A    <descriptions>%0A       <description descriptionType="Abstract">my interesting abstract</description>%0A    </descriptions>%0A    %0A%0A    %0A    <fundingReferences>%0A      %0A       <fundingReference>%0A          <funderName>sponsor1</funderName>%0A       </fundingReference>%0A      %0A       <fundingReference>%0A          <funderName>sponsor2</funderName>%0A       </fundingReference>%0A      %0A    </fundingReferences>%0A    %0A%0A</resource>
```

Both `POST /shoulder/doi:10.5072/fk2` and `delete /id/doi:10.5072/fk2-1-4gvq-zw33` work as expected.

**Comment by UVADave** [comment]
Hi Martin, the next change I can see is that there is no XML response to a create request... previously, we received an XML payload in that response...

**Comment by UVADave** [comment]
I am using the test system now and all test cases pass once I make the change to support the above.

**Comment by mfenner** [comment]
With change you mean tokenizing by "\r" instead of "\n"? I have not seen that one before, but that could explain it. I can make the code more generic to accept "\r" and or "\n". What platform are you generation the ANVL on, Linux, Mac, Windows?

**Comment by UVADave** [comment]
Sorry if that was unclear. The change is to handle the case of no XML payload in the response from a DOI create. Previously, the create would return an XML payload in the "datacite:" tag in the response

**Comment by UVADave** [comment]
Now it returns nothing. We were expecting the XML and were failing the DOI create if it was not present.

**Comment by mfenner** [comment]
Ok. there should be a payload. I see that in the tests, but I can double-check with the production system that there is XML returned.

**Comment by mfenner** [comment]
> Now it returns nothing. We were expecting the XML and were failing the DOI create if it was not present.

@UVADave this comment was really helpful, as it helped me understand the specific problem, and apply a fix. The underlying issue is that the url to to get the DataCite XML back has changed slightly (see https://github.com/datacite/cheetoh/commit/7db424a16c3a978654fb8e02cf74e33bf567fd50#diff-4a07abe40929a2b2d94ac79e73c5a0a1R46), and my testing didn't pick this up. 

I am deploying a fix to test and production that should be live in 30 min or so. This should fix the issue.
