### ISSUE TITLE
Bulk change registered state to findable

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#635]
All DOIs for client TIB.UBBS registered between 26 June 2018 and 14 December 2018.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g6j7)

**Comment by kjgarza** [comment]
After reading the front conversation, I am unsure if the action plan here is (a) to investigate why the DOIs were not made findable or (b) create a bulk operation to change dois status (this in place will help us to fix the issue). i'm leaning towards (b) but I juts want to clarify. any comments?

**Comment by mfenner** [comment]
(b)

**Comment by kjgarza** [comment]
- [ ] To create a bulk operation to change DOI status in cirneco

**Comment by kjgarza** [comment]
```
select doi
from dataset
where created BETWEEN '2018-06-26 00:00:00' and '2018-12-15 00:00:00'
```

**Comment by mfenner** [comment]
That looks right (I assume you also select by client_id). Do you want to do this via a file, one DOI per line, similar to transfers?

**Comment by kjgarza** [comment]
it is like that
