### ISSUE TITLE
OAI-PMH Replacement

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#642]
DataCite currently runs a service for a OAI-PMH data provider here: https://oai.datacite.org/
based on this software: https://github.com/datacite/oaip

We however need to modernise this to work with our new infrastructure changes, namely removing the Solr dependency and instead retrieve the data it needs via our REST API, this also means that it will be retrieving the data from our new Elasticsearch indexing.

**Comment by miku** [comment]
Just a (hopefully) related note: I encountered an HTTP 500 [while harvesting](https://oai.datacite.org/oai?resumptionToken=1567517956997,2019-08-01T00:00:00Z,2019-08-31T23:59:59Z,100000,null,oai_dc&verb=ListRecords) (via [metha](https://github.com/miku/metha)).

![](https://i.imgur.com/SktKSc7.png)

Apache Tomcat says:

> HTTP Status 500 - datacite.oai.provider.service.ServiceException: org.apache.solr.client.solrj.SolrServerException: Error executing query

> type Status report

> message datacite.oai.provider.service.ServiceException: org.apache.solr.client.solrj.SolrServerException: Error executing query

> description The server encountered an internal error that prevented it from fulfilling this request.
> Apache Tomcat/7.0.68 (Ubuntu)

Datacite support pointed me to this issue (06/2019), mentioning

>  some issues with deep paging around OAI-PMH

Meanwhile, if anyone can point me towards a ways to retrieve a data dump, I'd be grateful.
