### ISSUE TITLE
Delete University of Nebraska-Lincoln Libraries

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#643]
Client: PURDUE.UNL
Prefix: 10.13014
DOIs: all

DOIs and prefix have been transferred to Crossref.
Perry confirms that DOIs were already registered with Crossref : https://app.frontapp.com/open/cnv_16alhhf
Please delete PURDUE.UNL DOIs and prefix 10.13014 from DataCite.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gd2b)

**Comment by mfenner** [comment]
We now have a rake task to make this easier.
