### ISSUE TITLE
Transfer prefix  10.19084 from Crossref to DataCite

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#646]
Transfer prefix 10.19084 from Crossref to DataCite client FCT.SARC
https://app.frontapp.com/open/cnv_168mf97

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gdcb)

**Comment by kjgarza** [comment]
trasnfer using cirneco is very slow. At the end the code in lupo was modified to make the indexing faster.

changed https://github.com/datacite/lupo/issues/195
