### ISSUE TITLE
Link to support site from Create DOI page broken 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#647]
Expected Behaviour

Link in the "Create DOI" header 
More information about DOI registration via form can be found on our Support Website." Should resolve to https://support.datacite.org/docs/fabrica-create-doi-form (please confirm this is the correct link)

Current Behaviour

Clicking the link takes the user here: https://support.datacite.org/docs/datacite-doi-fabrica-for-clients#section-registering-dois and gives a 404 error

Steps to Reproduce

1. Log in to Fabrica 
2. Go to "Create DOI" (form)or (file)  https://doi.datacite.org/clients/datacite.datacite/dois/new
3. At the top of the page is a link to the support site " More information about DOI registration via form can be found on our Support Website." 
4. Click "Support Website"

Context 
Fabrica Production
https://doi.datacite.org/

Hypothesis

Update the link

Detailed Description

<img width="1393" alt="screen shot 2019-01-04 at 10 11 35" src="https://user-images.githubusercontent.com/44582654/50683642-0a047c80-1013-11e9-98bb-518688de864e.png">

Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gdw3)

**Comment by richardhallett** [comment]
This appears to be working as far as I can tell, takes to DOI States.
