### ISSUE TITLE
Meta counts for sample groups do not match new returned results

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#651]
When making a query such as:
https://api.test.datacite.org/dois?sample_group=client&sample=2

The meta data returned does not now match the results returned.

This may not be possible for aggregations to change however totals should accurately reflect.

**Comment by richardhallett** [comment]
Fixed the meta counts to reflect that there is no pagination.
IF we need pagination this is very complex because while we might be able to use composite_aggregation that supports pagination, it in itself doesn't know how many total potential sample groups there are.

For now this is the easiest workaround and does accurately reflect what is returned in the results.

**Comment by mfenner** [comment]
Sounds good. Might become an issue when we have significantly more clients, but that might be years away.
