### ISSUE TITLE
Redirect to client homepage when clicking "Update DOI (File Upload)"

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#652]
Expected Behaviour
Clicking on "Update DOI (File Upload)" leads to the update page for file upload

Current Behaviour
Two separate clients (tib.ukon and subgoe.iciber) report that when they click "Update DOI (File Upload)" they are redirected to the client homepage.
https://app.frontapp.com/open/cnv_16cqrz7
https://app.frontapp.com/open/cnv_16g7a7v

Steps to Reproduce
Details from the client (I wasn't able to reproduce)
- load client https://doi.datacite.org/clients/tib.ukon. Note this page takes longer to load than usual, ~30 seconds. (screenshot 1_datacite_loadtime shows the network details about the load time.)
- click on "DOIs" from the options across the top. The result shows up as expected.
- click on any DOI from the list. The result shows up as expected. (screenshot 2_load_doi)
- click on "Update DOI (File Upload)" in the orange box on the left side. Redirected back to the landing page https://doi.datacite.org/clients/tib.ukon rather than the normal result

Context (Environment)
https://doi.datacite.org/
Client cannot update DOI using file upload

Hypothesis

Detailed Description

### Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gf6r)

**Comment by MaryHirsch** [comment]
[datacite_tibukon.zip](https://github.com/datacite/datacite/files/2732499/datacite_tibukon.zip)

**Comment by mfenner** [comment]
Fixed via reverting back to ember-can mixin.
