### ISSUE TITLE
Create DOI (file upload) with preselected DOI, wrong DOI displayed before refreshing the page

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#653]
### Expected Behaviour

When creating a DOI via the metadata upload file in DOI Fabrica with a pre-defined DOI (prefix and/or suffix), after clicking ‘create DOI’ button, the correct DOI appears on the screen.

### Current Behaviour

When creating a DOI via the metadata upload in DOI Fabrica the wrong DOI is displayed. It shows the DOI which initially was generated by the system. Only when the browser is refreshed the right DOI appears.

### Steps to Reproduce

1. Set the DOI before in the metadata file
2. Upload the file in Fabrica via the file upload
3. The wrong DOI appears
4. Hit refresh and the correct DOI appears 

### Context (Environment)

Fabrica production https://doi.datacite.org

### Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gfgb)

**Comment by kjgarza** [comment]
![Screenshot 2019-01-11 at 11.25.30.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7855e32a64c5b279f1102e4f5c5f5cb053181d1ba6acda6fb4bc2e75835e5ee4d56b5674c53c40fdbb821fbc54bc73d84f84e3ae965e82b96371b8d6d6056b5c17129bfe553fa19c4fcf5ff44ee44e50a2113f71ab.png)

Aftertransitioning there is a call for random doi generation.

**Comment by kjgarza** [comment]
> Since the didReceiveAttrs hook is called every time a component's attributes are updated whether on render or re-render, you can use the hook to effectively act as an observer, ensuring code is executed every time an attribute changes.

didReceiveAttrs is called on submit click as week so that causes problem on the transition to the show page.

fixed in https://github.com/datacite/bracco/commit/7649396fc8b464ffebc31d5603ada544203a82e1
