### ISSUE TITLE
Update DOI causes metadata to disappear 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#654]
### Expected Behaviour

Clicking on the Update DOI (form) or (File) all existing metadata remains unchanged

### Current Behaviour

Clicking on the Update DOI (form) causes some of the metadata in the DOI record to disappear, specifically the title.

### Steps to Reproduce

1. Log into Fabrica
2. Select a DOI (doesn't seem to matter what the state is but this has been reported with findable DOIs).
3. Click Update (Form) and click on one of the fields in the DOI, you can try to change something like the URL
4. Click update, nothing happens, the title field appears blank
5. Clicking back seems to resolve this

examples: https://doi.datacite.org/clients/bl.leeds/dois/10.5518%2F451
https://doi.datacite.org/clients/tib.hu/dois/10.17172%2Fnomad%2F2017.03.16-1 

### Context (Environment)

Fabrica production and test: https://doi.datacite.org/ ,  https://doi.test.datacite.org/

### Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gfj7)

**Comment by kjgarza** [comment]
Can't reproduce and they are using `Schema version 3`.  Any update in the form will requireme them to add missing metadata (resource type)
