### ISSUE TITLE
Delete remaining DOIs from PURDUE.UMICH

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#655]
Client: PURDUE.UMICH
Prefix: null
DOIs: 64

There are 64 DOIs in the PURDUE.UMICH data center that weren’t transferred. They seem to be mostly test DOIs created in 2013.

confirmation that dois can be deleted https://app.frontapp.com/open/cnv_16ch0df 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ghsj)

**Comment by MaryHirsch** [comment]
There are some registered DOIs in this list. Perry is in touch with the provider. They should probably be transfer to the new UMICH client.

**Comment by MaryHirsch** [comment]
Please transfer the DOIs in transfer.txt and delete the DOIs in the delete.txt
[PURDUE_UMICH_delete.txt](https://github.com/datacite/datacite/files/2759292/PURDUE_UMICH_delete.txt)
[UMICH_LIBRARY_transfer.txt](https://github.com/datacite/datacite/files/2759293/UMICH_LIBRARY_transfer.txt)

The account purdue.umich can then be deleted.

**Comment by richardhallett** [comment]
DOi's transfered and client PURDUE.UMICH deleted.
