### ISSUE TITLE
Configure subscriptions to status updates

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#66]
As a data center manager (or member), I want to be able to configure the way I am notified about incidents/maintenances/etc. so I can stay informed.

#### DEV Notes

* alerts are pushed to the status page and to Twitter
* users can subscribe to alerts via email, RSS feed, API, webhook
* this is issue is mainly about documentation of what is available and how to subscribe

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
