### ISSUE TITLE
Delete MorphoBank from DataCite

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#664]
Client ID: cdl.morphoba

All DOIs are re-registered with Crossref. Perry confirms deletion in Front ticket.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gp1f)

**Comment by mfenner** [comment]
Done.
