### ISSUE TITLE
Update link to Fabrica from the retired MDS interface

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#665]
Expected Behaviour

Link from https://mds.datacite.org/ to Fabrica goes to the correct landing page https://doi.datacite.org/

Current Behaviour

Link from Link from https://mds.datacite.org/ to Fabrica gives a 404 error

Steps to Reproduce

Click on " Use DOI Fabrica as " here https://mds.datacite.org/

Context (Environment)
https://mds.datacite.org/

Hypothesis

Detailed Description

Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gp1n)

**Comment by mfenner** [comment]
Can't reproduce.
