### ISSUE TITLE
Drexel: Replace the term "Text" with "Dissertation"

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#667]
client ID: SML.DREXEL 
Request: Batch change
What: change resourcetype (optional) from "Text" to "Dissertation" in all 352 Drexel DOIs. 

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gqiz)

**Comment by mfenner** [comment]
Done via a SQL operation (as all DOIs are affected): 

```
update dataset set types = '{
  "ris": "THES",
  "bibtex": "phdthesis",
  "citeproc": "thesis",
  "schemaOrg": "Thesis",
  "resourceType": "Dissertation",
  "resourceTypeGeneral": "Text"
}' where datacentre = xxx;
```
