### ISSUE TITLE
Minimize scheduled maintenance

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#67]
As a member or data center, I want to receive uninterrupted services, even when services are updated/maintained, so that my own services are minimally affected by scheduled maintenance.

#### Related user stories:

* As a repository manager, I want reliable services, so that I can build my services on top.
* As a repository manager, I want to invest in stable and trustworthy  services, so I reduce the risk of adapting unreliable services.

#### DEV NOTES

* this applies only to production services
* one requirement is duplication of services
* challenges: deploy new docker container, deploy new docker host, deploy new proxy
* Scheduled downtime should be minimized, using zero-downtime deployments and configuration changes.
* Right now deployment of a container means 5 min downtime, deployment of a new Amazon AMI takes 15 min.

**Comment by mfenner** [comment]
Related user stories:

* As a repository manager, I want reliable services, so that I can build my services on top.
* As a repository manager, I want to invest in stable and trustworthy  services, so I reduce the risk of adapting unreliable services.

**Comment by espacial** [comment]
Advocate is not the best label here... do we want to reintroduce reliability?

**Comment by mfenner** [comment]
`advocate` was a mistake, should have been `support`.

**Comment by mfenner** [comment]
This has been implemented via auto-scaling of docker containers and auto-scaling and blue/green deployment of EC2 instances.
