### ISSUE TITLE
Delete provider account Consorcio Madroño

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#670]
Old provider ID: MADRONO

DOIs transferred to new client account https://github.com/datacite/datacite/issues/659 under Dataverse.

Account and associated clients can now be deleted.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h2mb)

**Comment by richardhallett** [comment]
This is tricky to achieve because of this:
https://github.com/datacite/lupo/issues/229

I suggest we fix that and then we can proceed with this housekeeping item. Otherwise we have to do manual database edits and a delete/reimport of all providers.
