### ISSUE TITLE
Update URL from http to https not working for some dois

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#671]
Expected Behaviour

Changing the URL to https version in the DOI with form or file new URL is saved and appears correctly

Steps to Reproduce

    Go to DOI:10.5285/4a60ee2f-0fd1-4141-9244-7bebf240bb49 
    Add an "s" to the url https://catalogue.ceda.ac.uk/uuid/b4709a1a0bd8d3b68e388f0d1864bf4f
    Nothing happens
    URL reverts back to http version

Context (Environment)

Fabrica production https://doi.datacite.org
Hypothesis
Detailed Description
Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h2bn)

**Comment by richardhallett** [comment]
I'm closing this bug in favour of the referenced ticket #193 as that is the actual problem, this just manifests itself as though you can't change the URL when in fact it was a metadata issue.
