### ISSUE TITLE
Description is not appearing in summary view after creating doi with form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#672]
Expected Behaviour

Description appears in the summary view and xml in file upload after creating via form

Steps to Reproduce

    Create DOI (form)
    Fill in all obligatory fields
Add description: Potato yellow dwarf virus (PYDV) is the type species of the genus nucleorhabdovirus which is typified by its nucleotropic characters of the members. The virus accomplishes its replication and morphogenesis in the nuclei of infected cells. Two strains, Constricta strain (CYDV) and Sanguinolenta strain (SYDV) have been described at the level of vector-specificity. CYDV is vectored by Agallia constricta and SYDV is transmitted by Aceratagllia sanguinolenta. The full-length genome of CYDV was sequenced. The 12,792 nt antisense genome encodes seven open reading frames in the order of, nucleocapsid protein (N), unknown protein (X), phosphoprotein (P), movement protein (Y), matrix protein (M), glycoprotein (G), and large polymerase protein (L). 
    Save
    The description not appear in the summary view, nor in the xml view, it does appear when in "Update DOI (file upload)"

Context (Environment) Fabrica production https://doi.datacite.org

Hypothesis
Detailed Description
Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_h2cj)

**Comment by richardhallett** [comment]
Fixed as part of the work under datacite/bracco#155
