### ISSUE TITLE
Feedback on REST API v2 documentation

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#673]
This issue is for collecting developer feedback on the documentation for our new improved REST API v2. You can find the documentation on our support site. 

User guide: https://support.datacite.org/docs/api
API reference: https://support.datacite.org/reference

**Comment by daslerr** [comment]
duplicates https://github.com/datacite/lupo/issues/201

**Comment by croaker000** [comment]
Where can I find details on the API field descriptions (ie. what is supposed to go in each field)?

**Comment by daslerr** [comment]
The metadata schema documentation at https://schema.datacite.org has descriptions of fields and controlled vocabulary. I've updated our API documentation to point people in that direction. Thanks!

If you have additional feedback, please put it in https://github.com/datacite/lupo/issues/201. This issue we're in now is a closed duplicate.
