### ISSUE TITLE
Add a paragraph to support docs about what is allowed in the suffix for DataCite DOIs

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#677]
Document list of accepted suffixes 

/\A10\.\d{4,5}\/[-\._;()\/:a-zA-Z0-9\*~\$\=]+\z/
parse the regex and document it with some additional information for users unfamiliar about regular expressions to help them understand which characters they can't use

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hcob)

**Comment by mfenner** [comment]
don't close
