### ISSUE TITLE
Delete  CDL.UAL

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#682]
Client ID:CDL.UAL

University of Alberta has been transferred to CISTI. Please delete CDL account. (Perry was not able to delete and requests DataCite to do so)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hkvv)

**Comment by MaryHirsch** [comment]
I was not able to delete in fabrica when logged in with "admin"

**Comment by richardhallett** [comment]
Client deleted, reason it was not deleting was hidden doi's not properly transferred, had to transfer these first.
