### ISSUE TITLE
MDS API - List DOIs not working anymore

### ISSUE THREAD

**Issue by haarli** [datacite/datacite#685]
Hello,

we are using the DataCite MDS API and the following method to retrieve a list of all DOIs:
GET https://mds.datacite.org/doi (with Basic Auth)

Since some days, the method doesn't return the list anymore, but HTTP Status 204 - No Content.

On the test API https://mds.test.datacite.org/doi, the method is still working fine.

Is this an intended change on the API or a bug?

Thank you.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hv03)

**Comment by ioverka** [comment]
Any chance for an update on this issue, e.g. a rough timeline for resolution? Please note that our production system is relying on the method. Thanks! inga

**Comment by richardhallett** [comment]
Apologies for this, this is a strange one that I tried to investigate last week, as mentioned above it does appear to only be affecting the live system.

To clarify this is not an intended change and it should still work as you are currently using this. 
We are working on it and hope to be able to provide a more complete update soon.

**Comment by mfenner** [comment]
@ioverka The issue has been fixed.
