### ISSUE TITLE
Delete CDL.FSDN

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#692]
Not possible to delete client account CDL.FSDN in Fabrica. Please delete the account.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i0gr)

**Comment by kjgarza** [comment]
https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/568

**Comment by kjgarza** [comment]
completed, move dois to Iris.iris and reindex ES with :

export CLIENT_ID=cern.hepdata
bundle exec rake  client:index_all_dois
