### ISSUE TITLE
Authentication for frontend-only applications

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#7]
Provide authentication and authorization, integrated with the DataCite Profiles service, in a Javascript frontend application. This implements DataCite single sign-on (#132) and multiple user roles (#139) for Javascript frontend applications.

#### DEV NOTES
* build an Ember app
* use the same architecture as in https://github.org/crosscite/doi-metadata-search: a secure token that is accessible from all .datacite.org subdomains and contains a JWT with username, ORCID ID, role, etc.
* sign the JWT with private/public keys (RS256), as the key needed for verification will be exposed.
* no separate session cookie, no use of authentication framework at this time.
* for authorization, use https://github.com/minutebase/ember-can

**Comment by mfenner** [comment]
#### Testing

* please login to our test services at https://profiles.test.datacite.org. The test services use the ORCID sandbox, so you might have to create an ORCID account in the ORCID Sandbox.
* Once you are successfully logged in, ping me so that I can upgrade your test profiles account to an "admin" role.
* When your account has an admin role, go to https://eventdata.test.datacite.org/status, notice that you are logged in, and have access to the content on the page (a little surprise for you).
* At https://eventdata.test.datacite.org/status, go to your user menu in the upper right corner and click on "Sign out". You should be signed out now and the page at https://eventdata.test.datacite.org/status should say that you have no permission to access the page.
* At https://eventdata.test.datacite.org/status, click on "Sign in" in the upper-right corner, and you should be signed in again after a few seconds. You might have to authenticate with the ORCID Sandbox again.

**Comment by mfenner** [comment]
<img width="869" alt="bildschirmfoto 2017-07-02 um 10 32 38" src="https://user-images.githubusercontent.com/23151/27768357-d4b801d6-5f11-11e7-8285-8fe818b81e84.png">

**Comment by mfenner** [comment]
We need to redirect all requests to `index.html` and let the applcation handle the routing instead of AWS S3. We can do this via the following in our Ngnx configuration:

```
location / {
        try_files $uri /index.html;
    }
```

**Comment by brittadreyer** [comment]
I followed the instructions and it worked perfectly. Note: Don't be hungry if you do the testing;) When I tried the login with Google I got a 401 error code.

**Comment by mfenner** [comment]
Thanks @brittadreyer. Google login is currently not configured correctly at https://profiles.test.datacite.org.
