### ISSUE TITLE
Reuse stats

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#70]
As a national library or as a funder, I want to know how often data are reused (cited, downloaded, etc.), so I can justify funding the service.

**Comment by espacial** [comment]
Extended this one to funders:

As a funder, I want to know how often data are reused (cited, downloaded, etc.), so I can justify funding the service.

**Comment by Aaron-M** [comment]
As an author I want to know how often the doi to my data is resolved, and how often the data is reused (cited, downloaded...), so i can see it is worth my effort depositing and registering my data for open access.

**Comment by Aaron-M** [comment]
As a data repository manager I want to know how often doi to data held in the repository are  resolved, and how often the data is reused (cited, downloaded...), so I can demonstrate the value of the investment in the repository, and so we can ensure the most valued datasets are well curated.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
