### ISSUE TITLE
maDMP crosswalk

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#702]
https://docs.google.com/spreadsheets/d/1dx0Vav8o3Q2LHCRAlYGQBDsT_cCNsaseQpCIAB-FAJA/edit#gid=0

**Comment by kjgarza** [comment]
@daslerr  @mfenner,  is there anything else we need to change on this one. 
The ROR reference has been removed and we added the mandatory fields.

It doesn't seem we will discuss again within the DMP group before RDA.

**Comment by mfenner** [comment]
Has there been any discussion on how to model `creator`, `publisher` and `publicationYear` in DMP metadata?

**Comment by daslerr** [comment]
At this point we're just providing feedback to the RDA DMP Common Data Standards WG, and I've included some notes about those required fields needing to be considered. In a side conversation with John we discussed possibly just having DMPTool (or other services/repositories) collect that info and submit it along with whatever the resulting common data standard fields are, in the event that they're not accounted for in the common data standards themselves.
