### ISSUE TITLE
Sometimes start date in bar chart is after end date

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#704]
![image](https://user-images.githubusercontent.com/23151/54752849-c667ea80-4bdf-11e9-8606-0e13462ccf1b.png)

**Comment by kjgarza** [comment]
This is due to the Dummy data we have in search.test.datacite.org. and work in datacite/doi-metadata-search
#128
 will fix this

**Comment by mfenner** [comment]
This needs to be a separate issue. And the code needs to handle dummy data as well.

**Comment by kjgarza** [comment]
https://github.com/crosscite/doi-metadata-search/pull/133/commits/ca7f9ee86ad22be7b2646aa6af27320399f0d9b5
