### ISSUE TITLE
Rephrase text explaining COUNTER code of practice

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#705]
Make the text more generic instead of being specifically about the Code of Practice for Research Data. Place text under chart to have more width for displaying many months of usage (https://github.com/crosscite/doi-metadata-search/issues/129).

**Comment by daslerr** [comment]
We'll make the text simpler. Say: 

'Displayed usage information follows the [COUNTER Codes of Practice](https://www.projectcounter.org/). [What does this mean?](https://support.datacite.org/docs/usage-stats)'

The text has already been moved below the chart, so once the text is updated, this is done.
