### ISSUE TITLE
Public Data Dump

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#709]

**Comment by mfenner** [comment]
Link to component: https://datacite.productboard.com/feature-board/planning/features/1922696

**Comment by mfenner** [comment]
don't close yet.

**Comment by katrinleinweber** [comment]
While this issue remains open, is there a way to get the rate limit lifted? Given a list of hundreds of thousands of DOIs, I'd like to query DataCite for their presence as a `relatedIdentifier` and download DC's data about a work that was found that way.

I'm not sure whether that's the best way to do it, but I tested queries for 10, 100 & 1000 DOIs => 2-4 replies per second, both through [rdatacite](https://github.com/ropensci/rdatacite/issues/26) and [the API directly](https://support.datacite.org/docs/api-queries).

**Comment by miku** [comment]
I'd like to +1 for a (e.g. monthly or weekly) public data dump. The reason is that while it is possible to get all data out of the API as well, the updates are not evenly distributed, which in turn makes harvesting a burden on the API and the harvester.

For example on Fri, [Aug 2nd 2019](https://gist.github.com/miku/176edd1222fc42ae3b23234bc9d3cd87#file-freq-tsv-L325), I was able to detect over 8M updates to records, which, when queried via API, can get a difficult to fetch.

**Comment by miku** [comment]
Just FYI: I uploaded a data dump of newline delimited JSON to [archive.org/details/datacite_dump_20191122](https://archive.org/details/datacite_dump_20191122).

> 18210075 items, 72GB uncompressed.

**Comment by katrinleinweber** [comment]
Thank you :-) Will this be a regular process, i.e. can we plan with updated dumps every N months?

**Comment by mfenner** [comment]
DataCite will release a public data dump in early 2020 (work is on track, so early access January, official release maybe February). Currently the plan is a public data dump every 12 months.

**Comment by katrinleinweber** [comment]
Through another channel I received word that (paraphrasing a bit):

> this has been re-prioritised to 2020 Q3. Anyone else waiting for this

(but for whatever reason can't/won't use [@miku' kindly provided inofficial dump](https://github.com/datacite/datacite/issues/709#issuecomment-563976312))

> will probably be quicker to download the metadata items they're interested in via the REST or OAI-PMH interface, which have received some performance improvements in the last few months

**Comment by miku** [comment]
Added a new dump (2020-08-24); 19606708 unique DOI: [https://archive.org/details/datacite_dump_20200824](https://archive.org/details/datacite_dump_20200824) ([download](https://archive.org/download/datacite_dump_20200824/datacite_20200824.ndj.xz)).

**Comment by miku** [comment]
Added a new dump (2021-10-22); 26446306 unique docs/DOI: https://archive.org/details/datacite_dump_20211022

**Comment by miku** [comment]
Added a new dump (2022-11-18); 33672740 unique identifiers [https://archive.org/details/datacite_dump_20221118](https://archive.org/details/datacite_dump_20221118).

**Comment by miku** [comment]
Added a new dump (2023-07-13); 47689869 unique identifier ([direct download](https://archive.org/download/datacite_dump_20230713/datacite-dump-2023-07-13.ndjson.zst))

> https://archive.org/details/datacite_dump_20230713

**Comment by miku** [comment]
@huberrob - do you mean, how to cite the [linked](https://github.com/datacite/datacite/issues/709#issuecomment-1638667150) complete dataset?

**Comment by huberrob** [comment]
Sorry for the confusion, I meant: Is there a citation for the individual dumps at archive.org ? These would imho deserve a DOI ;)

**Comment by miku** [comment]
Added a new dump (2024-04-17); 56080875 unique identifier ([direct download](https://archive.org/download/datacite-2024-04-17/datacite-2024-04-17.ndj.zst), 16GB - 217GB uncompressed)

> https://archive.org/details/datacite-2024-04-17

Ps. To stream datacite DOI (only) to stdout:

```shell
$ curl -sL https://archive.org/download/datacite-2024-04-17/datacite-2024-04-17-doi.tsv.zst | \
    zstd -cd -T0
```

**Comment by miku** [comment]
Added a new dump (2024-07-31); 59572745 unique identifier ([direct download](https://archive.org/download/datacite-2024-07-31/datacite-2024-07-31.ndj.zst), 15GB - 274GB uncompressed)

> https://archive.org/details/datacite-2024-07-31

Ps. To stream datacite DOI (only) to stdout:

```shell
$ curl -sL https://archive.org/download/datacite-2024-07-31/datacite-2024-07-31-doi.tsv.zst | \
    zstd -cd -T0
```

Compared to the last dump, datacite seems to add about 30K records per day.

**Comment by digitaldogsbody** [comment]
@huberrob DataCite released the Public Data File earlier this year, which is citeable via a DOI.

Release blogpost: https://datacite.org/blog/announcing-datacites-first-public-data-file/
Data File: https://doi.org/10.14454/zhaw-tm22
