### ISSUE TITLE
Automatic metadata curation

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#71]
As a national library, I want automatic metadata curation post-DOI assignation, so that I can update large amounts of legacy metadata and services.

#### Related User Story

* As a repository, I want a service that improves metadata quality over time, so I don't have to invest into a huge amount of resources.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
