### ISSUE TITLE
Improved ORCID integration

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#711]
Whenever DataCite finds an ORCID ID in the metadata of a newly registered DOI, an update is sent to the ORCID profile of the author(s). We will improve this workflow by sending notifications to those authors who are not subscribed to the Auto-Update service (using ORCID Inbox, read more [here](https://support.orcid.org/knowledgebase/articles/665437-notifications-auto-update-and-the-orcid-inbox)).

**Comment by mfenner** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/1922710

**Comment by dshorthouse** [comment]
Can this be enhanced to better recognize versions? Here's an example on Zenodo, https://doi.org/10.5281/zenodo.2667631 where each subsequent version results in a new, undesirable entry in ORCID. The relatedIdentifiers in DataCite for a new version of an existing resource in Zenodo looks like this:

`{
      "relationType": "IsVersionOf",
      "relatedIdentifier": "10.5281/zenodo.2667631",
      "relatedIdentifierType": "DOI"
    }`

...so the "IsVersionOf" relation would need to be checked as a new DOI is minted. When present, no notification & no Auto-Updates ought to be sent to ORCID.

**Comment by mfenner** [comment]
don't close

**Comment by dshorthouse** [comment]
> Can this be enhanced to better recognize versions? Here's an example on Zenodo, https://doi.org/10.5281/zenodo.2667631 where each subsequent version results in a new, undesirable entry in ORCID. The relatedIdentifiers in DataCite for a new version of an existing resource in Zenodo looks like this:
> 
> `{ "relationType": "IsVersionOf", "relatedIdentifier": "10.5281/zenodo.2667631", "relatedIdentifierType": "DOI" }`
> 
> ...so the "IsVersionOf" relation would need to be checked as a new DOI is minted. When present, no notification & no Auto-Updates ought to be sent to ORCID.

Would you prefer a new ticket for this? The current integration has become unwieldy for users and I have received complaints. See "Natural history specimens collected and/or identified and deposited" entries at https://orcid.org/0000-0003-1105-1850 produced via an initiative I operate, https://bloodhound-tracker.net

**Comment by mfenner** [comment]
@dshorthouse yes, please open a new issue. We currently check `isIdentical` and `isNewVersionOf` when deciding whether to send a claim to the ORCID record. We can add smarter handling of `isVersionOf`.

**Comment by dshorthouse** [comment]
Thanks @mfenner for the quick response. New ticket at #998.

**Comment by mfenner** [comment]
Closing this epic in favor of datacite/akita#122, which describes our work on ORCID claiming in the new DataCite Commons service over the coming two months.
