### ISSUE TITLE
Transfer subset of 558 DOIs for University of Indiana

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#719]
Old client: IU.BL
New client: IU.SD
Prefix: none
DOIs: see csv attachment

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iaxv)

**Comment by richardhallett** [comment]
Transfer complete.
