### ISSUE TITLE
Help with metadata entry

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#72]
As a repository, I want help in metadata entry, so I can create quality metadata for my DOIs.

**Comment by espacial** [comment]
Related? https://github.com/datacite/datacite/milestone/10

**Comment by kjgarza** [comment]
This might not fit here, don't you think?. I suggested this one in Barcelona but not for a MDS stakeholder but for a more general stakholder. This is actually a user story for a *repository*.  should not we use #47   instead ?

**Comment by mfenner** [comment]
Covered in #10.
