### ISSUE TITLE
Add member roles and responsibilities page

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#725]
Create a new page describing member roles and responsibilities. 

Put page under new section About Us > Governance.

**Comment by mfenner** [comment]
Link to subfeature: https://datacite.productboard.com/feature-board/planning/features/2026930

**Comment by kjgarza** [comment]
> Create a new page describing member roles and responsibilities.

@daslerr  I think this does not apply anymore , right? 

All goes in the governance page, right?

**Comment by daslerr** [comment]
Correct. This doesn't apply anymore. Closing the issue.
