### ISSUE TITLE
Update Fabrica Provider Settings form to collect additional member information

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#727]
Add fields to Provider Settings form in Fabrica to collect the information about members that is currently collected via the onboarding form. See wireframes in planning doc: <https://datacite.atlassian.net/wiki/spaces/TEC/pages/874577924/Collecting+and+displaying+member+information>

**Comment by mfenner** [comment]
Link to subfeature: https://datacite.productboard.com/feature-board/planning/features/2026874

**Comment by richardhallett** [comment]
To get the data from the system the following API work needs to be achieved:
datacite/lupo#242
datacite/lupo#243
datacite/lupo#244

**Comment by kjgarza** [comment]
feedback
- in the UI Change:
  -  [ ] Change Billing address to Billing Street
  -  [ ] Change City to  Billing City
  - [ ] Change State to  Billing State/Province
  - [ ] Change Postcode to Billing Zip/Postal Code
  - [ ] Change Country to Billing Country
  - [ ] help text for billing information and twitter
  - add billing organisation name and departmen
- [ ] CSV change names of fields to match salforce https://help.salesforce.com/articleView?id=field_mapping_for_other_data_sources_and_organization_import.htm&type=5

**Comment by kjgarza** [comment]
closed this with the billing information part only. 

we will add contact information in https://github.com/datacite/bracco/issues/195
