### ISSUE TITLE
More compact member page

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#728]
Update the member page to be more compact, so that it's easier to see all the members. Show general descriptive information about each member. See wireframes in planning doc: <https://datacite.atlassian.net/wiki/spaces/TEC/pages/874577924/Collecting+and+displaying+member+information>

**Comment by mfenner** [comment]
Link to subfeature: https://datacite.productboard.com/feature-board/planning/features/2026911

**Comment by richardhallett** [comment]
The work for this is to follow the wireframe to produce a new members page.
* Member data is retrieved via API call to providers
* Change Javascript to match wireframe.

See https://github.com/datacite/homepage/blob/master/source/javascripts/members.js

**Comment by richardhallett** [comment]
Updates made and deployed.
