### ISSUE TITLE
Draft DOIs not retrieved in Fabrica after creation

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#739]
**Describe the bug**
User reports draft dois are not findable in Fabrica after creation

**To Reproduce**
1. Go to 'Fabrica'
2. Search 

10.25923/33z5-pm15
10.25923/x99c-c507
10.25923/4xp5-w782
10.25923/c2p3-ga46
10.25923/vj5y-hv35
10.25923/29be-qn77

3. These draft dois are not retrieved 

This was previously reported by the same user for this doi: https://doi.datacite.org/clients/noaa.library/dois/10.25923%2Fzffy-5a13  

**Expected behavior**
The dois are found in Fabrica

**Additional context**

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_j07f)

**Comment by kjgarza** [comment]
https://doi.datacite.org/clients/noaa.library/dois?client-id=noaa.library&page=NaN
I updated each DOI using the API and PUT calls
