### ISSUE TITLE
Delete CDL.UCDIRL, CDL.PISCO and CDL.NSFADC and CDL.IRIS

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#740]
CDL.UCDIRL, CDL.IRIS, CDL.PISCO and CDL.NSFADC cannot be deleted in Fabrica. Please delete them.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_j3nf)

**Comment by richardhallett** [comment]
Done: 
CDL.UCDIRL - There was 1 lost DOI that I transferred to UCD.JJL with the other doi's of the same prefix.
Deleted Client

CDL.IRIS - 10.1761 - 9 Orphased DOI's transferred to IRIS.IRIS
Deleted Client

To do still:

CDL.PISCO has 204 orphaned doi's with prefix 10.6085 - now owned by CDL.UCSB

CDL.NSFADC - has 13 orphaned doi's with prefix 10.18739 now owned by CDL.UCSB

**Comment by richardhallett** [comment]
CDL.PISCO - transferred doi's to CDL.UCSB and deleted.
