### ISSUE TITLE
Sentry is aggregating too many error under a 

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#749]
**Describe the bug**

All exceptions in Elasticsearch::Transport::Transport::Errors::BadRequest
[400]  get aggregated independently if its a different resource or index.

https://sentry.io/organizations/datacite/issues/977360183/?project=1410849&query=is%3Aunresolved

**To Reproduce**

**Expected behavior**

Different errors should give different issues

**Screenshots**
https://sentry.io/organizations/datacite/issues/977360183/?project=1410849&query=is%3Aunresolved

**Additional context**
we could look into adding fingerprints:

https://blog.sentry.io/2018/01/18/setting-up-custom-fingerprints

https://docs.sentry.io/data-management/rollups/?platform=python

**Comment by mfenner** [comment]
@kjgarza something that I have done a few times is custom error reporting in our applications, adding more specific information there.

**Comment by mfenner** [comment]
Don't close.
