### ISSUE TITLE
Transfer Penn State

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#755]
Old client: PURDUE.PSIEE
​New client: PSU.SCHOLAR 
145 DOIs 
[PSU.SCHOLAR.txt](https://github.com/datacite/datacite/files/3202501/PSU.SCHOLAR.txt)

Old client: PURDUE.PSIEE
New client: PSU.DATACOM
68 DOIs 
[PSU.DATACOM.txt](https://github.com/datacite/datacite/files/3202499/PSU.DATACOM.txt)

Old client: PURDUE.PSIEE
New client: PSU.LIB
299 DOIs 
[PSU.LIB.txt](https://github.com/datacite/datacite/files/3202500/PSU.LIB.txt)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jhwj)

**Comment by richardhallett** [comment]
Cirneco doesn't like UTF8 BOM that appears at front of CSV's, I had to change these to be ISO8601 for it to work.

Transfers now completed.
