### ISSUE TITLE
The citation not displaying creator info correctly without nameType in some cases 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#760]
### Expected Behaviour

information from creator field displays correctly in the citation

### Current Behaviour

the attribute nameType is missing causing display issues
If the schema version is 3 or less nameType is not an accepted attribute

### Steps to Reproduce

See test doi 10.70126/fzcx-xw84

### Context (Environment)

Test and production environments

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jnsz)

**Comment by MaryHirsch** [comment]
?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource xmlns="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">
  <identifier identifierType="DOI">10.70126/FZCX-XW84</identifier>
  <creators>
    <creator>
      <creatorName nameType="Organizational"> Volcanoes and Earth's Interior Research Center, Research Institute for Marine Geodynamics/JAMSTEC</creatorName>
    </creator>
  </creators>
  <titles>
    <title xml:lang="en">Global Seismic Traveltime Database</title>
  </titles>
  <publisher>JAMSTEC</publisher>
  <publicationYear>2016</publicationYear>
  <subjects/>
  <contributors/>
  <dates/>
  <language>en</language>
  <resourceType resourceTypeGeneral="Dataset">Scientific Data</resourceType>
  <alternateIdentifiers/>
  <relatedIdentifiers>
    <relatedIdentifier relationType="IsDocumentedBy" relatedIdentifierType="DOI">https://doi.org/10.5918/jamstecr.24.23</relatedIdentifier>
  </relatedIdentifiers>
  <sizes/>
  <formats/>
  <rightsList/>
  <descriptions>
    <description xml:lang="en" descriptionType="Other">Creator was changed from "Department of Deep Earth Structure and Dynamics Research/JAMSTEC" to "Volcanoes and Earth's Interior Research Center, Research Institute for Marine Geodynamics/JAMSTEC" due to organizational reconstructing in April 2019.</description>
  </descriptions>
  <geoLocations/>
</resource>

**Comment by MaryHirsch** [comment]
removing the coma from the creator field in the xml does resolve the issue. 
Seems like the coma means the the creator nameType "personal" is assigned in the json format

**Comment by MaryHirsch** [comment]
don't close

**Comment by kjgarza** [comment]
IMO, this is just a consequence of using schema 3 and `organizational` names in the creator field.  We do not have a way to differentiate them from `personal` names when using metadata schema 3.  Therefore the `formated styled citation` might look odd. I think the solution Mary has given in the front-ticket might suffice. I don't think it a bug, but what do others think?
