### ISSUE TITLE
Delete all dois with prefix 10.5195

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#768]
Prefix 10.5195 and all dois are now with Crossref and should be deleted from DataCite

https://doi.datacite.org/providers/cdl/dois?prefix=10.5195

see attached message from Maria Gould at Cdl

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lmwz)

**Comment by richardhallett** [comment]
@mfenner / @kjgarza Do you have any guidance on deleting these DOI's in our system, I don't feel comfortable deleting data, what is our preferred option for handling these?

Do we just mark them as registered not findable? 
Do we perhaps need to consider some way to flag them as transferred?

**Comment by mfenner** [comment]
If they are now managed by Crossref, we have to properly delete them from the system. There is a rake task to make this easier: `rake prefix:delete`. This deletes the prefix and associated DOIs.

**Comment by richardhallett** [comment]
DOI's and prefix 10.5195 deleted.
