### ISSUE TITLE
Delete Broad Insitute

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#769]
CDL.BROAD cannot be deleted in Fabrica. please delete this client account

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_m5z7)

**Comment by kjgarza** [comment]
that client doesn'r exist https://doi.datacite.org/clients/cdl.broad

**Comment by MaryHirsch** [comment]
responding to CDL for confirmation
