### ISSUE TITLE
Creating draft dois without url generates "This DOI name already exists" message

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#771]
### Expected Behaviour
Draft dois created with no metadata or url 

### Current Behaviour
seems like the url is required or "this doi name exists" message appears 

### Steps to Reproduce

1. Craete DOI (form)
2. Fill in title field only
3. Click "create"
4. Doi name already exists message appears

### Context (Environment)
Fabrica Production ONLY

**Comment by richardhallett** [comment]
Potentially related to https://github.com/datacite/lupo/commit/4c2caf54288d1de3f8bb1edd5e0f9bd568550dac#diff-678dd3d6654063beb356c7dad98a7d63L78
