### ISSUE TITLE
Delete client CDL.PGERR and CDL.UTAUSTIN 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#772]
Please delete CDL.PGERR and CDL.UTAUSTIN. It's not possible in Fabrica

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_mzcz)

**Comment by richardhallett** [comment]
CDL.PGERR deleted.

**Comment by richardhallett** [comment]
CDL.UTAUSTIN deleted
