### ISSUE TITLE
Make sure all Crossref DOIs from events are indexed in DataCite DOI index

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#785]
We could for example create a sentry error message when DOI creation via a Crossref DOI fails.

**Comment by mfenner** [comment]
Fixes for Crossref metadata parsing: https://github.com/datacite/bolognese/issues/65

**Comment by mfenner** [comment]
You will find errors with Crossref metadata import in our logs as `[Error for DOI 10.1002/9783527615674.ch3]...`.

**Comment by kjgarza** [comment]
TODO:

- [ ] investigate the percentage of of missing Crossref DOI metadata in crossref.citations
- [ ] Investigate postential causes

**Comment by mfenner** [comment]
Will not fix.
