### ISSUE TITLE
Transfer a subset of dois out of NOAA.NCEI-NCL

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#786]
Old client: NOAA.NCEI-NCL
New client: NOAA.NCEI/NOAA.NCL

[NOAA.NCEI.txt](https://github.com/datacite/datacite/files/3349629/NOAA.NCEI.txt)
[NOAA.LIBRARY.txt](https://github.com/datacite/datacite/files/3358404/NOAA.LIBRARY.txt)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_obsz)

**Comment by richardhallett** [comment]
NOAA.NCEI.txt DOI's transferred into NOAA.NCEI

**Comment by MaryHirsch** [comment]
correction to name of destination client NOAA.LIBRARY is the new client for the second file

**Comment by richardhallett** [comment]
NOAA.LIBRARY.txt DOI's transferred into NOAA.LIBRARY
