### ISSUE TITLE
EZ API returning 404 on POST

### ISSUE THREAD

**Issue by barmintor** [datacite/datacite#788]
**Describe the bug**
We are able to GET a EZ-API url (eg https://ez.datacite.org/id/doi:10.7916/d8-ah1j-vf76) but get a 404 when attempting to POST to the url.
**To Reproduce**

**Expected behavior**
This is a change in expected behavior which appears to have been working until very recently.

We are continuing to investigate locally.

**Comment by mfenner** [comment]
Can you please share what you are posting? E.g. as curl command.

**Comment by barmintor** [comment]
Sure, give me just a minute.

**Comment by barmintor** [comment]
anvl:
`
datacite: <?xml version="1.0"?>%0A<resource xmlns="http%3A//datacite.org/schema/kernel-3" xmlns%3Axsi="http%3A//www.w3.org/2001/XMLSchema-instance" xsi%3AschemaLocation="http%3A//datacite.org/schema/kernel-3 http%3A//schema.datacite.org/meta/kernel-3/metadata.xsd">%0A  <identifier identifierType="DOI">10.0/00</identifier>%0A  <titles>%0A    <title> Record of Interview with Robert Crane</title>%0A  </titles>%0A  <publisher>Columbia University</publisher>%0A  <publicationYear>2018</publicationYear>%0A  <dates>%0A    <date dateType="Created">2018-01-10</date>%0A    <date dateType="Updated">2019-07-09</date>%0A  </dates>%0A  <creators>%0A    <creator>%0A      <creatorName>(%3Aunav)</creatorName>%0A    </creator>%0A  </creators>%0A  <subjects>%0A    <subject>Charitable uses, trusts, and foundations</subject>%0A    <subject>Social sciences--Research</subject>%0A  </subjects>%0A  <descriptions>%0A    <description descriptionType="Abstract">The Social Science Research Council files in the Carnegie Corporation archives provide information on the social sciences development, and on the thought process of the Council and the Corporation.   In this record, Devereux Joseph, the Corporation president talks to SSRC director Robert Crane about promising directions in social science research.</description>%0A  </descriptions>%0A</resource>%0A
_target: https%3A//dlc.library.columbia.edu/carnegie/centennial/cul%3A3bk3j9kfj2
_status: public
`

**Comment by barmintor** [comment]
This is a Ruby client that has stopped working, so it's more straightforward for me to describe the requests that to reconstitute them as a cURL command. That will take a little longer.

**Comment by mfenner** [comment]
Can you share the Ruby code? Or do a pull request with a test at https://github.com/datacite/cheetoh (the EZ API is written in Ruby).

**Comment by barmintor** [comment]
```ruby
      def call_api(uri, request, request_data = nil)
        request.body = make_anvl(request_data) unless request_data.nil?

        request.basic_auth @username, @password
        request.add_field('Content-Type', 'text/plain; charset=UTF-8')
        result = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
          response = http.request(request)
          response
        end
        result
      end

      uri = URI("https://ez.datacite.org/id/doi:10.7916/d8-h2ef-yt91")
      request = Net::HTTP::Post.new uri.request_uri
      request_data = the_data_used_to_generate_the_anvl
      call_api(uri, request, request_data)
```

is more or less it. Again, it's part of an application that was until recently successfully updating DOIs, so I'm pulling things out for illustrative purposes.

**Comment by barmintor** [comment]
Is it possible that the web sever proxying that ruby application is rejecting POST requests with a 404?

I continue to see HTTP GET to (for example) https://ez.datacite.org/id/doi:10.7916/d8-rqbr-9a05 return a 200, but POST to the identical URL return a 400.

**Comment by barmintor** [comment]
I don't think this has been a change on our end - I'll continue looking - but it appears to be the case that the 404 is from the placeholder DOI in the ANVL request body. I'm closing this ticket, as it's addressable on our end.
