### ISSUE TITLE
Confirm DOI's in ES indexing from Wed 24th July

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#794]
In relation to incident on 24/07/19, ensure DOI's that were supposed to be registered in our ES index are correctly there.

**Comment by kjgarza** [comment]
We triggered a full reindex yesterday and the index grew by 85k records.

Today we are still missing the following reported DOI records in the index:

10.34697/2450-6095-sdpipp-21-001
10.34697/2450-6095-sdpipp-21-002
10.34697/2450-6095-sdpipp-21-003
10.34697/2450-6095-sdpipp-21-004
10.0353/development:abefb1a3-6ae9-4da6-a9a8-d7f66f98710e:20190723:121
10.25740/BG095CP1548 
10.17912/micropub.biology.000131
10.17912/micropub.biology.000130
10.17912/micropub.biology.000129
10.17912/micropub.biology.000128
10.17912/micropub.biology.000127
10.17912/micropub.biology.000126
10.17912/micropub.biology.000118
10.17912/micropub.biology.000115
10.17912/micropub.biology.000111
10.17912/micropub.biology.000108
10.17912/micropub.biology.000107
10.17912/micropub.biology.000106
10.17912/micropub.biology.000103

**Comment by kjgarza** [comment]
all these dois have been imported now
