### ISSUE TITLE
Recommendations about landing pages for datasets

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#80]
As a data repository, I want DataCite to make recommendations about our dataset landing pages, so that I follow best practices.

#### Background Reading

* Force11 Data Citation Implementation Pilot ([DCIP](https://www.force11.org/group/dcip))
* [A Data Citation Roadmap for Scholarly Data Repositories](https://doi.org/10.1101/097196)

#### DCIP Recommendations for Repositories (from https://doi.org/10.1101/097196)

1. All datasets intended for citation must have a globally unique persistent identifier that can be expressed as unambiguous URL.
1. Persistent identifiers for datasets must support multiple levels of granularity, where appropriate.
1. This persistent identifier expressed as URL must resolve to a landing page specific for that dataset.
1. The persistent identifier must be embedded in the landing page in machine-readable format.
1. The repository must provide documentation and support for data citation.
1. The landing page should include metadata required for citation, and ideally also metadata helping with discovery, in human-readable and machine-readable format.
1. The machine-readable metadata should use schema.org markup in JSON-LD format.
1. Metadata should be made available via HTML meta tags to facilitate use by reference managers.
1. Content negotiation for schema.org/JSON-LD and other content types maybe supported so that the persistent identifier expressed as URL resolves directly to machine-readable metadata.
1. HTTP link headers maybe supported to advertise content negotiation options.
1. Metadata maybe made available for download in Bibtex or other standard bibliographic format.

**Comment by pcruse** [comment]
This is an activity that doesn't need any development -- can we move forward on this?

**Comment by mfenner** [comment]
don't close.
