### ISSUE TITLE
New repositories not showing up in Fabrica test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#806]
### Expected Behaviour

New repository appears in Fabrica

### Current Behaviour

When a new repository is created in test it does not appear immediately in Fabrica

### Steps to Reproduce

1. Create a new repository under a provider in test
2. search using the ID of new repository
3. repository is not found

### Context (Environment)

Fabrica Test

**Comment by mfenner** [comment]
This bug has been fixed via code changes elsewhere.
