### ISSUE TITLE
Showcase example implementations and best practices

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#81]
As a potential new DataCite member or user, I want to see examples of DataCite implementation and best practice with members/data centres that are like me (in terms of subject, scale or sector), so that I can learn from their mistakes to get up and running quickly, and also to ensure I am following community best practice.

**Comment by espacial** [comment]
There is already content under Support's Basics and Best Practices section. Should be expanded.

**Comment by kjgarza** [comment]
:wave: @mfenner, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .
