### ISSUE TITLE
Title of DOI record not displayed in Fabrica production

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#811]
### Expected Behaviour

The title field of the DOI record is displayed in Fabrica

### Current Behaviour

Title is not currently showing up
### Steps to Reproduce

Please see examples:
 
https://doi.datacite.org/clients/zbmed.unikoeln/dois/10.18716%2Fnmrshiftdb2%2F2319

https://doi.datacite.org/clients/doinz.landcare/dois/10.26065%2Fs3gg-v336

### Context (Environment)

Fabrica Production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ssn7)

**Comment by mfenner** [comment]
There is an issue parsing the DataCite XML, as the title is lost in the DataCite JSON.

**Comment by MaryHirsch** [comment]
Other examples of issues that might be related to parsing json <> xml

https://app.frontapp.com/open/cnv_29nsa83
https://app.frontapp.com/open/cnv_2eaqlfn
https://app.frontapp.com/open/cnv_2e9fksj
