### ISSUE TITLE
Deactivated clients/repositories not searchable in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#827]
### Expected Behaviour

Possible to search a deativated client/repository in Fabrica

### Current Behaviour

Deativated clients/repositories are not searchable in Fabrica

### Steps to Reproduce

1.  OSTI.CXIDB not found in Fabrica 

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_t9xf)

**Comment by mfenner** [comment]
"Deactivated" means "deleted", and this information is not publicly available, with no plans to do so. Members can reach out to DataCite if they want to "reactivate" a deleted repository.
