### ISSUE TITLE
New Datasets with DOI - DOI Failed - error code 404

### ISSUE THREAD

**Issue by MichaelHarmsTIB** [datacite/datacite#828]
**Describe the bug**

Ckan 2.8. WIth DataCite (DOI), datastore, datapusher

**Please describe the expected behaviour**

I can add new resources/Datasets to public of an organisation. 

**Please describe the actual behaviour**
I have an organisation and I add first time a ressource. It works, but after i try to add a new dataset with a new resource i got a error: Creating DOI Failed - error code 404

**What steps can be taken to reproduce the issue?**

Install Ckan 2.8 with the plugins DOI, datastore, datapusher and a test-account by datacite.
Create a organisation and add new datasets.

**Comment by richardhallett** [comment]
Hello,

We don't directly support CKAN's integration however from our system, a 404 might be the result of an invalid test account.

Apologies for the delay in replying here.
Please contact us via support@datacite.org if you are still experiencing problems.
