### ISSUE TITLE
Use Crossref Member ID for Crossref Events's registrant_id  rather that DataCite client_id.

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#830]
We cannot use `registrant_id` to run citations analysis with eventData anymore. Studies like the one we presented un RDA and Force11 use the registrant_id to compare citations between data centers/repositories and journals/publishers. Currently, all events with CROSSREf citations (from journals/publishers ) have crossref.citations as their registrant_id rather than the journal/publisher ID. Therefore when we cannot analyze patterns between data centers/repositories and journals/publishers. We need a way to store the journal/publisher ID in the EVENT DATA index to continue conducting analysis.

![image](https://user-images.githubusercontent.com/1092861/63348084-dd5e6480-c358-11e9-8cc9-5bafd088ea3d.png)

There CROSSREf citations metadata is stored and extracted to/from DataCite API and although there is a publisher string there is not an ID. Using an ID would be better for aggregate data. There is not another field in the metadata to store such ID.

**Proposed solution**:

For CROSSREF citations metadata, store the publisher metadata field as: "{publisher} - { crossref_member_id}"

TODO:

- Modify Bolognese to parse Crossref DOI metadata publisher and member
- Modify Fabrica (NOT Totally NECESSARY) to hide the member_id from Publisher name
- Modify Leveriro to accept publisher as `registrant_id` rather that clien_id for  crossref DOI metadata
- Re-create Crossref events in EventData

**Comment by kjgarza** [comment]
I reviewed the events in the index, currently only the ones created in august have the registrat_id as crossref.citations. All other events have nothing. This is because up-until this fix https://github.com/datacite/lupo/pull/332/files we were not indexing registrat_id and after that fix we didn't reindex the whole index.

I have confirmed that we registrant_id needs to be fixed and we can replace it as with their old value as was before this https://github.com/datacite/levriero/commit/214f4052a302af9c1d78403a49efaeafd01ad634

This doesn't change our TODO actions as the way we obtain Crossref DOI metadata is by giving LUPO a crossref DOI name than then is parsed into DataCite Metadata. See https://github.com/datacite/levriero/blob/338ca0f00171981dc15239c740f23ca3afde2965/app/models/base.rb#L267

We still need to modify Bolognese, any comments on this @mfenner

**Comment by mfenner** [comment]
Thanks. This confirms what I was suspecting. But I don't understand why you want to modify bolognese? Isn't all you need to do fixing `registrant_id` in the events API? We can ignore/delete the events accidentally added in early August.

**Comment by mfenner** [comment]
If we want to do this properly, we would need to create a `client_id` for Crossref DOIs. If we follow the same pattern as for DataCite, that would mean `member_id.journal_id`, which are both numbers. Example at https://api.crossref.org/works/10.7554/elife.01567/transform/application/vnd.crossref.unixsd+xml

Unfortunately it would be a huge task to create members and clients/repositories in our system for all these Crossref DOIs, much more work than fixing your problem.

It should be easier to do an additional API call in levriero, fetching the member_id from Crossref..

**Comment by kjgarza** [comment]
> It should be easier to do an additional API call in levriero, fetching the member_id from Crossref.

I think this is more straightforward solution. I'll go with that
