### ISSUE TITLE
update member page to pull from displayName

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#833]
The member page (https://datacite.org/members.html) should pull the member name from the `displayName` field in Fabrica, rather than `name`. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_uvib)

**Comment by kjgarza** [comment]
closed https://github.com/datacite/homepage/commit/06af5b0f242757ec3886f986f6068550be913d2c
