### ISSUE TITLE
[Fabrica] duplicate https in affiliationIdentifier when selecting a ROR institution

### ISSUE THREAD

**Issue by DavidFichtmueller** [datacite/datacite#834]
**Describe the bug**
When a ROR institution is selected as the affiliation in Fabrica, the affiliationIdentifier has a duplicate "https://". This can not be changed and seems to be the case for every institution (several random ones tested). 
![Fabria_Issue_Duplicate_https](https://user-images.githubusercontent.com/7805030/63947811-ea293980-ca77-11e9-8dc1-9ab9c8d05cf5.PNG)

The problem is not just with the visualization, but the error is also written in the metadata, when the DOI is created and exported, e.g. via XML or JSON
![Fabria_Issue_Duplicate_https2](https://user-images.githubusercontent.com/7805030/63947832-f44b3800-ca77-11e9-9d57-8813debbc39a.png)

**To Reproduce**
1. Log into Fabrica
2. Go to "DOIs" -> "Create (Form)"
3. Scroll to and click on "Affiliation (optional)"
4. Enter one or two letters to get some suggestions for institutions
5. Select any institution of the suggested institutions
The field below now contains a duplicate "https://" in the beginning of the identifier. 

**Expected behavior**
The field for the affiliationIdentifier containing the correct ROR URI of the institution.

**Screenshots**
(see above)

**Desktop (please complete the following information):**
 - Tested in Firefox 68 and Chrome 76

**Comment by mfenner** [comment]
@DavidFichtmueller thanks for reporting that bug. I have deployed a fix, which should be live in 30 min or so.

Your example is particularly relevant for me, as I graduated at Freie Universität Berlin, before becoming DataCite Technical Director much later.

**Comment by DavidFichtmueller** [comment]
@mfenner Thanks for the quick update. I choose the example, as it is my employer. Technically I would consider my institution to be the Botanic Garden and Botanical Museum Berlin, but it is part of the FU and also doesn't have it's own ROR (yet).
