### ISSUE TITLE
Unable to create Consortium Organization in Fabrica Test

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#838]
**Describe the bug**
In the test system, after filling in the non-optional fields in the Consortium Organization creation form, clicking the Create Consortium Organization button does nothing. 

Console says POST to http://api.test.datacite.org/provider gets a 403. (See screenshot in appropriate section below.)

**To Reproduce**
1. Log in as test consortium member TESTU.
2. Click orange Create Consortium Organization button on the Consortium Organizations tab. 
3. Fill in all non-optional fields. 
4. Click black Create Consortium Organization button at bottom of the screen. 
5. Nothing happens and you are not routed to any other page. 

**Expected behavior**
Clicking Create Consortium Organization button after filling in required form fields should restul in Consortium Organization creation. 

**Screenshots**
Console output:
![Screenshot 2019-09-05 at 09 23 58](https://user-images.githubusercontent.com/3181623/64320518-03257380-cfbf-11e9-8c84-5fe11ff81823.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome 76.0.3809.132

**Comment by kjgarza** [comment]
We need to enable providers to create consortiums (other providers)

https://github.com/datacite/lupo/blob/498720420e0bb3688469b680d98c3ab3d649fd3f/app/models/ability.rb#L21

**Comment by mfenner** [comment]
Fixed in https://github.com/datacite/datacite/issues/852.
