### ISSUE TITLE
CSV import into Salesforce

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#841]
See [Spec doc](https://docs.google.com/document/d/1rEN1kS5o7KCalZqdN2EA2IxGKkB_0w2Heh_1eS-qdQ4)

Salesforce will need the following information from Fabrica representing the last day of each month:
1. All Member and Repository organization and contact information represented in the “settings” form
2. The date a  Member, Consortium Member, Consortium Organization, Direct Member, or Repository joined
3. A designation if a Member, Consortium Member, Consortium Organization, Direct Member, or Repository is inactive. This is for billing purposes as we need to track when Consortium Organization, Direct Member, or Repository leaves, or changes status (e.g. Repository becomes a Direct Member or becomes a Consortium Organization) and the date associated with that action. Inactive records must be viewable in Fabrica Admin. 
4. For each Repository, the number of DOIs issued in the past month and the current year to date.

**Comment by daslerr** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/2886969

**Comment by richardhallett** [comment]
New exports are available:
https://api.datacite.org/export/contacts
https://api.datacite.org/export/organizations

These require admin credential login

**Comment by richardhallett** [comment]
Closing this issue as we do have new CSV exports now.
Additionally we are going to re-evaluate the work needed for Salesforce.
