### ISSUE TITLE
Required fields not indicated when missing the the form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#844]
It's not clear in the form which required fields are missing when moving a draft DOI to findable, this should ideally be indicated to the user. In the screenshot publisher, publication year and resourceTypeGeneral missing.

<img width="1301" alt="Screen Shot 2019-09-20 at 14 50 58" src="https://user-images.githubusercontent.com/44582654/65332191-1a1ab700-dbb6-11e9-809d-940ea66e8847.png">

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_x9mr)

**Comment by mfenner** [comment]
This has been addressed.
