### ISSUE TITLE
Some metadata fields dropped when a DOI created via File Upload 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#846]
### Expected Behaviour

XML file loaded and metadata saved

### Current Behaviour

Some of the metadata fields are lost when the doi is moved to findable state as follows:

A - <dates>...</dates> are not processed well. It should be:

   <dates>

     <date dateType="Collected">2004-10-01 / (:tba) </date>

   </dates>

But is showes:

   <dates>

      <date dateType=”Issued”>2019</date>

   </dates>

B – The format element is missing in the download file:

   <formats>

     <format>application/x-netcdf</format>

   </formats>

C – According to the documentation (p.56) it’s allowed to insert white lines, using  (< b r > which should be < b r / >) But they have disappeared in the download xml.

D - When you update a DOI, by clicking "Update DOI (File Upload)" , then .xml is missing as supported file type in "All supported types". 

### Steps to Reproduce

1. create a draft doi using the metadata in the comments
2. check the xml view, all metadata appears
3. move doi to findable
4. the fields mentioned above disappear

### Context (Environment)

Reproducible in Fabrica production and test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_xxc3)

**Comment by MaryHirsch** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI">10.21944/omi-modis-aerosol-direct-effect</identifier>
  <creators>
    <creator>
      <creatorName>De Graaf, M.</creatorName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org">0000-0003-1282-6582</nameIdentifier>
      <affiliation>Royal Netherlands Meteorological Institute (KNMI)</affiliation>
    </creator>
    <creator>
      <creatorName>Stammes, P.</creatorName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org">0000-0002-2488-3990</nameIdentifier>
      <affiliation>Royal Netherlands Meteorological Institute (KNMI)</affiliation>
    </creator>
    <creator>
      <creatorName>Tilstra, L.G.</creatorName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="http://orcid.org">0000-0003-1282-6582</nameIdentifier>
      <affiliation>Royal Netherlands Meteorological Institute (KNMI)</affiliation>
    </creator>
  </creators>
  <titles>
    <title>OMI-MODIS aerosol direct radiative effect over clouds, version 1.0</title>
  </titles>
  <publisher>Royal Netherlands Meteorological Institute (KNMI)</publisher>
  <publicationYear>2019</publicationYear>
  <resourceType resourceTypeGeneral="Dataset">Satellite data</resourceType>
  <subjects>
    <subject>Atmosphere above-cloud aerosol direct radiative effect</subject>
    <subject>OMI</subject>
    <subject>MODIS</subject>
    <subject>TEMIS</subject>
  </subjects>
  <dates>
    <date dateType="Collected">2004-10-01 / (:tba)</date>
  </dates>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="DOI" relationType="References">10.1029/2011JD017160</relatedIdentifier>
  </relatedIdentifiers>
  <formats>
    <format>application/x-netcdf</format>
  </formats>
  <version>1.0</version>
  <descriptions>
    <description descriptionType="Abstract">The OMI-MODIS above-cloud aerosol Direct Radiative Effect (DRE) database is available for all cloud scenes in an area over the south-east Atlantic (20W - 10E, 20S - 10N) from 2002 to present during the months June - October. This is a period of massive vegetation burning in southern Africa during the dry season and often smoke plumes can be observed drifting over the Atlantic ocean. The aerosol DRE from OMI-MODIS indicates the warming effect of the smoke when it overlies clouds due to absorption of sunlight. This is measured in Watts per square meter (W/m2).<br/>The data are accompanied by images that show an overview of the warming effect on a particular day. The OMI-MODIS aerosol DRE is overplotted over MODIS RGB showing clouds.<br/>The database is described in the following paper:<br/>M. de Graaf, L.G. Tilstra, and P. Stammes, Aerosol direct radiative effect over clouds from a synergy of OMI and MODIS reflectances, Atmos. Meas. Techn., https://doi.org/10.5194/amt-2019-53, 2019, doi:/10.5194/amt-2019-53<br/>For more information, see http://www.temis.nl/climate/adre.html</description>
  </descriptions>
  <geoLocations>
    <geoLocation>
      <geoLocationBox>
        <westBoundLongitude>-20.0</westBoundLongitude>
        <eastBoundLongitude>+10.0</eastBoundLongitude>
        <southBoundLatitude>-20.0</southBoundLatitude>
        <northBoundLatitude>+10.0</northBoundLatitude>
      </geoLocationBox>
    </geoLocation>
  </geoLocations>
  <fundingReferences>
    <fundingReference>
      <funderName>Netherlands Space Office</funderName>
      <awardNumber>ALW-GO/12-32</awardNumber>
      <awardTitle>Dutch National Programme for Space Research</awardTitle>
    </fundingReference>
  </fundingReferences>
</resource>

**Comment by richardhallett** [comment]
A)

The Date is not a valid date so this is fine, what you're actually saying is not a change, but an addition of "Issued" as no "Issued" date was included in the original metadata.

B) Specific issue: https://github.com/datacite/bracco/issues/236

C) Should be <br> not <br/> documentation matches this.

D) Can not reproduce.

**Comment by richardhallett** [comment]
Note, additionally some different behaviour between going direct to findable
https://github.com/datacite/bracco/issues/237
