### ISSUE TITLE
The Fabrica form does not auto-populate the name fields for the second creator ORCID name identifier

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#847]
### Expected Behaviour

The second creator fields auto-populated when a valid ORCID is added to the name identifier field.

### Current Behaviour

When a second creator is added to the form, the name identifier does not cause the name fields to auto-populate

### Steps to Reproduce

1. Create DOI via form
2. For first creator add https://orcid.org/0000-0003-1419-2405
3. add another creator
4. add to name identifier field https://orcid.org/0000-0002-6628-8225
5. the name fields do not autopopulate

### Context (Environment)

Reproduced in Fabrica test
 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_xxkz)

**Comment by mfenner** [comment]
This has been fixed.
