### ISSUE TITLE
Bread crumbs missing on Consortium Member pages in Fabrica

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#859]
When logged in as a Consortium Member in Fabrica, the breadcrumbs at the top of the page are missing. This means that after creating a Consortium Organization, it is not always obvious how to return to the Member overview. Clicking on the Fabrica title does correctly take you to the Member overview.

**Comment by richardhallett** [comment]
This appears actually when looking at consortium organisations as logged in as consortium (member) 
Then looking at any of the sub tabs i.e .settings
It appears then disappears.

**Comment by richardhallett** [comment]
This was tricky to track down 
it's actually related to the model loading, consortium is a async promise and it isn't getting fulfilled when the template hits, therefore it just causes "undefined" which the template renderer updates to make it "disappear".

A simple fix although there might be a better way to ensure the consortium is loaded, is to just get the id/name in the model load of the route and pass down to template as different variables for use.
