### ISSUE TITLE
rename "Consortium Member" to be just "Consortium"

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#863]
We originally updated the label for the top-level consortium account in Fabrica to "Consortium Member" to make it parallel to the Direct Member (see #809). This labeling is causing confusion, since it sounds like it should mean "member of the consortium" rather than "the consortium who is a member", so we will change the labeling back to just "Consortium".

**Comment by richardhallett** [comment]
Technical considerations:
I think this should probably mean we want to rename this in API's as well as in visual labeling.
@mfenner Do you consider any problems doing this? This should just be changing references in bracco and lupo right?
