### ISSUE TITLE
remove yellow highlighting for usage and citations information messages

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#872]
The yellow highlighting on the information box about submitting usage and on the information box about submitting metadata for citations makes the message seem too urgent and severe. We will remove the highlighting but keep the message.

**Comment by daslerr** [comment]
Messages will be changed from bootstrap warning alert to light alert.

**Comment by mfenner** [comment]
Can this be changed to display a message where otherwise the count would show, without any alert box?
