### ISSUE TITLE
Citation List in DataCite Search Feedback round

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#874]
## Implementation of Citation, References, Relations List

https://github.com/crosscite/doi-metadata-search/issues/152
>A new proposal has arisen from the discussions about the citations List display. The proposal is to have each list in a TAB and have individual pagination in each TAB. 
- Similarly to what we do with the charts. 
- Only one list ( References, Relations, Citations) is visible at any given time.
- Within each Tab, there would be a pagination component (page 1,2,3,.. and NEXT).
- The default list TAB would be the Citations Tab (then References, then Relations)
- The TAB would not be shown in the number of items is zero.

Full description of the changes in
https://docs.google.com/document/d/1fz5EPIPQ8dRWQXf4hqAN1uWBCTtFVqhPYIWi9DsOweE/edit#heading=h.xfqdyzn099ov

Example with pagination functionality:
https://search.test.datacite.org/works/10.5194/acp-15-13023-2015

Example with showing citations in tabs, chart, and counter:
https://search.test.datacite.org/works/10.1594/ieda/100037

Example with no citations/relatiosn/references:
https://search.test.datacite.org/works/10.20371/researchdatatest.cab.unipd.it.00000303

Example with only relations:
https://search.test.datacite.org/works/10.24404/fk2.ucdlib_261024

**Comment by kjgarza** [comment]
Initial feedback:

On the list:
- [*] Can we say "DataCite" to make clear how this information came to us, in addition to repository name? I think it helps with transparency if we clearly map this info to Event Data sources.

On the Chart
- would also suggest to decrease the bar width, it is really wide when the publication date is fairly recent. - The chart doesn't always have to go over the full width of what is available.

**Comment by kjgarza** [comment]
On the Chart
- [ ] Modify Chart display-size responsiveness 
  - [ ] Set a minimum for the chart width to five years. If the time domain between YOP and current year is less than 5 years then we can cut the chart width. 
  - [ ] Fix the width of the bin to approx 21px. 
- [ ] Set a Chart bin maximum to 20 Years.

On the Usage Counter
- [ ] Change message to: "No usage information was reported."

On the Citation Counter
- [ ] Change message to: "No citations were reported."

On the Citation List
- [ ] Change ResourceGeneral from `Text` to `Publication`.

**Comment by mfenner** [comment]
Please cut chart width if less than 20 years.

**Comment by kjgarza** [comment]
![image](https://user-images.githubusercontent.com/1092861/68769111-10e12000-0624-11ea-9968-c9dace3de7a5.png)

There are 3 Cases for implementing this change
