### ISSUE TITLE
Representation of Material that is in the Public Domain in the Metadata-Schema

### ISSUE THREAD

**Issue by hvwaldow** [datacite/datacite#880]
**Is your feature request related to a problem? Please describe.**
Datasets might contain material that is in the Public Domain. This is actually pretty common: Measurement data & observations usually are. A lot of software, such as software by US Federal Agencies is. The proper (or most obvious) way to mark content as "in the public domain" is the ["Public Domain Mark"](https://creativecommons.org/publicdomain/mark/1.0/) by Creative Commons. This is not in the [SPDX License List](https://spdx.org/licenses/) because it is not a license. There doesn't seem to be a rightsIdentifier (16.b) that would correctly identify the public domain status of content.

**Describe the solution you'd like**
I'd like a recommendation in the docu of the metadata-schema about what "rightIdentifier" should be used for content marked with the ["Public Domain Mark"](https://creativecommons.org/publicdomain/mark/1.0/). I would appreciate if Datacite system that render a symbolic depiction of attached "Rights" would show the correct symbol that that case. 

**Describe alternatives you've considered**
With resepct to original data I am OK with using the [CC0](https://creativecommons.org/publicdomain/zero/1.0/). If other people's software is re-distributed however, that would imply the author of the dataset had created said software, which severely violates scientific community standards.

**Comment by mfenner** [comment]
@hvwaldo SPDX includes CC0 as an option, and that is also what we recommend for datasets. As you point out this might not address all use cases, but probably covers most of them.

Creative Commons licenses don't work so well for software, and we recommend to use one of the [OSI-approved](https://opensource.org/licenses) licenses here.

Does that help?

**Comment by hvwaldow** [comment]
> Does that help?
Not really. As pointed out above, the problem is software in the public domain that someone else wrote. For example all software published by USGS, NASA, US national labs, ... that was used/modified/extended to produce datasets . None of the options above is acceptable (legal and compatible with basic community norms).

**Comment by mfenner** [comment]
Ok. Can we then rephrase the problem as "appropriate rights waiver for software in the public domain"? I can ask our US government agency members such as USGS how they handle this situation.

**Comment by hvwaldow** [comment]
Yes, except it is not a "waiver" (this could be accomplished with CC0) but a "label". You don't waive but rather re-publish something that is already in the public domain.

**Comment by hvwaldow** [comment]
To avoid having this issue closed by a bot, I am renewing this note of a shortcoming in the current Datacite Schema docu:

**Material, such as data or software, in the Public Domain is very common in and important for the scientific community. Therefore the schema documentation should at least recommend a standard value for "rightsIdentifier" to properly identify material in the Public Domain.**

**Comment by mfenner** [comment]
@hvwaldow we will reconfigure our bot to not prematurely close important issues.

I will take with the metadata working group to consider adding better schema documentation regarding rights in the metadata. For `rightsidentifier` in particular for software, [SPDX](https://spdx.org/licenses/) makes a lot of sense, e.g. `CC0-1.0`.

**Comment by hvwaldow** [comment]
@mfenner, I am not suggesting to remove SPDX but rather to amend it with something suited for the most common case for data and for any software that was written by NASA or any US national lab. That should be an extremely small addition. Would it help if I created a pull request?

**Comment by richardhallett** [comment]
This is an old issue I'm closing due to various changes happening since 2020.
In addition metadata changes are handled via a different process now.

If this feedback is still relevant please consider submitting to https://github.com/datacite/datacite-suggestions
See also https://schema.datacite.org/contribute.html for how to contribute generally.
