### ISSUE TITLE
Cost monitoring and reporting

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#883]

**Comment by sarala** [comment]
I spent a few hours looking at this and it is not straight forward to generate something useful. It looks like we need to integrate with Amazon Athena and use this to analize the billing data in detail. Otherwise the reports are generated as csv files with a large number of columns and rows (daily basis) which is not really useful. I am moving this to 2021 road map.

**Comment by mfenner** [comment]
Did you look into what DataDog offers? They have some nice ready-made templates.

**Comment by mfenner** [comment]
Is the estimate correct?

I suggest to focus on the 4-5 most expensive AWS services to get started.
