### ISSUE TITLE
Issue with retrieving citation data of OP DOIs through content negotiation 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#891]
All OP DOIs upon a content negotiate request return “resource not found/DOI not found” message, although in the HS the corresponding DOI prefixes have been configured with HS_NAMESPACE

<namespace><locs>10.SERV/DATACITE</locs></namespace>

And therefore with 10320/loc

<locations http_sc="302">
<location weight="0" http_role="conneg" href_template="<https://data.crosscite.org/{hdl}"/>
</locations>

Here is an example: 10.2905/21935ffc-b797-4bee-94da-8fec85b3f9e1

It exists in Datacite: https://search.datacite.org/works/10.2905/21935ffc-b797-4bee-94da-8fec85b3f9e1

But if you use the DOI citation formatter or make a CN request (ex via Postman) either through https://doi.org or through https://data.crosscite.org or https://data.datacite.org the resource is not found

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_14myr)

**Comment by mfenner** [comment]
The underlying issue is that we were first checking the DOI DA via `https://doi.org/ra/DOI`, and that information is different from where content negotiation is redirected to. This issue has been fixed.
