### ISSUE TITLE
Citation counts don't match

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#892]
Example: https://search.datacite.org/works/10.14454/3bpw-w381

![Bildschirmfoto 2019-11-29 um 09.27.51.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/6ff191ee-bd98-4cf0-8440-4da56764f6ff)

**Comment by mfenner** [comment]
This may be related to counting the two references for the summary and visualizations. 

![Bildschirmfoto 2019-11-29 um 09.41.23.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/60ee8c6d-a6da-4d3a-b334-170decd110ea)

**Comment by kjgarza** [comment]
yes it is,      "is-supplement-by" was swapped in the lupo implementation, i'm sending a change for that

**Comment by kjgarza** [comment]
addressed in https://github.com/datacite/lupo/commit/e5729fc15c850f012ab3aea11f95aedbc544bea0

**Comment by mfenner** [comment]
The relation types in DataCite metadata are `is-supplement-to` and `is-supplemented-by`. Re-opening the issue.

**Comment by kjgarza** [comment]
good catch, change has been made now https://search.datacite.org/works/10.14454/3bpw-w381 

https://github.com/datacite/lupo/commit/597f53517ee762fb2ebc244c2c1fe02d145d44bf

**Comment by kjgarza** [comment]
fixed 
![image](https://user-images.githubusercontent.com/1092861/70042780-c407be00-15bf-11ea-9cd9-5bd7b1e8be62.png)
