### ISSUE TITLE
X-axis label should be horizontal unless there would otherwise be overlap

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#893]
Example: https://search.datacite.org/works/10.15468/3s2nuz

![Bildschirmfoto 2019-11-29 um 09.32.30.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/9220c1c3-a957-46aa-96dc-16e01237b8ae)

**Comment by kjgarza** [comment]
https://search.datacite.org/works/10.15468/3s2nuz now tilting only happens when two bars

**Comment by kjgarza** [comment]
![image.png](https://images.zenhubusercontent.com/57c7eecee40e5714b16e1fe7/af1299ec-d0cf-4cbc-9be6-19278e75ea35)
