### ISSUE TITLE
Optimise CPU and memory configurations, and trigger conditions

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#895]

**Comment by mfenner** [comment]
@sarala I think this looks mostly ok. I suggest we discuss next week and then wrap this up.

**Comment by sarala** [comment]
@mfenner, looks like you have done a lot of work on this front, thank you. I put [this](https://docs.google.com/document/d/1LfMGQUwuYkzRNOC1nUiYJQbpLceJ1PGPMtRbUA-DHn0/edit#) table together on Friday but I think some of the resourcing has changed since then. I am looking at Datadog notebooks to document and monitor our services so we can quickly identify issues and where to improve.
