### ISSUE TITLE
Some relations and sources seem wrong

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#896]
Seen at https://search.datacite.org/works/10.5438/0012

* direction for **new version** is wrong
* citations from Zenodo are labelled as originating from Crossref
* **Crossref Citations via DataCite** should be **Crossref**

**Comment by mfenner** [comment]
![Bildschirmfoto 2019-12-02 um 07.19.40.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/f7db3013-de56-481e-9f86-e07a8c619f95)

**Comment by mfenner** [comment]
![Bildschirmfoto 2019-12-02 um 07.20.33.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/b672bc46-d0fa-402c-9582-610aceba943b)

**Comment by kjgarza** [comment]
do you have the doi in question?

**Comment by kjgarza** [comment]
single graphql call requires merging with events response.  The merging was assuming ordered elements that is not the case all the time. it has been changed.

**Comment by kjgarza** [comment]
![image.png](https://images.zenhubusercontent.com/57c7eecee40e5714b16e1fe7/160597d2-ce18-4e71-adc6-27754449c061)

![image.png](https://images.zenhubusercontent.com/57c7eecee40e5714b16e1fe7/98307d6f-3c34-4b32-876b-5736ac1cb6f5)
