### ISSUE TITLE
HTTP 500 when requesting data updated between 2019-10-07 16:19:00 and 16:19:30

### ISSUE THREAD

**Issue by miku** [datacite/datacite#898]
**Describe the bug**

When querying the [datacite v2 API](https://support.datacite.org/docs/api) with the [cursor mechanism](https://support.datacite.org/docs/pagination#section-cursor) a request to fetch data updated between 2019-10-07 16:19:00 and 16:19:30 yields an HTTP 500.

**To Reproduce**

Do [a request](https://api.datacite.org/dois?page[cursor]=1&page[size]=100&query=updated%3A[2019-10-07T16%3A19%3A00Z+TO+2019-10-07T16%3A19%3A30Z]&state=findable) (interestingly, a request for a few seconds later [works ok](https://api.datacite.org/dois?page[cursor]=1&page[size]=100&query=updated%3A[2019-10-07T16%3A19%3A30Z+TO+2019-10-07T16%3A19%3A59Z]&state=findable)).

Example output in [this gist](https://gist.github.com/miku/5d0b1c75d9231b53e4c78a5279131102).

**Expected behavior**

For example, an HTTP 200 with a typical API JSON response.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Linux, Ubuntu 18.04 LTS

**Smartphone (please complete the following information):**

**Additional context**

It's a strange bug. All time windows before this date do not seem to exhibit this behavior.

**Comment by mfenner** [comment]
This has been fixed, it was caused by a bug in the code for the affiliation facet, not properly handling an edge case.
