### ISSUE TITLE
Relation counts are wrong

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#899]
For https://search.datacite.org/works/10.5438/0000-00ss:

![Bildschirmfoto 2019-12-06 um 11.36.37.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/4a3bf8f7-f9ea-4330-810c-27d54c38dcce)

**Comment by kjgarza** [comment]
![image](https://user-images.githubusercontent.com/1092861/70866147-5b78f380-1f66-11ea-8583-444d35714c24.png)
fixed
