### ISSUE TITLE
DateCite OAI goes to 500 internal server error

### ISSUE THREAD

**Issue by gjunge** [datacite/datacite#908]
**Describe the bug**
Trying to harvest DataCite data and after a while get a status code 500.

**To Reproduce**
This url works
https://oai.datacite.org/oai?verb=ListRecords&resumptionToken=metadataPrefix%3Ddatacite%26until%3D2019-12-11T22%253A45%253A09Z%26from_%3D2019-12-08T10%253A48%253A33Z%26paging_cursor%3DMTM0OTM2NDcxMTAwMCwxMC43MjcyL1E2MTU0RjAw%26cursor%3D1

The next resumption token doesn't:
https://oai.datacite.org/oai?verb=ListRecords&resumptionToken=metadataPrefix%3Ddatacite%26until%3D2019-12-11T22%253A45%253A09Z%26from_%3D2019-12-08T10%253A48%253A33Z%26paging_cursor%3DMTM1NDYyODY3MzAwMCwxMC41MTY2L2pyb2ktNC0xLTE5%26cursor%3D1

**Comment by richardhallett** [comment]
Thanks for reporting.
Deployed a fix for this, related to an internal error in DC format output handling of missing data.
Please try the OAI harvesting again.

**Comment by gjunge** [comment]
Thank you @richardhallett
