### ISSUE TITLE
Check there is nothing else running in EC2 search

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#91]
@mfenner commented on [Sat Jun 03 2017](https://github.com/datacite/search/issues/151)

@mfenner commented on [Wed May 31 2017](https://github.com/datacite/datacite/issues/2)

If not, archive and shut down EC2 instance

**Comment by kjgarza** [comment]
- [ ] Chec kall processes running
    - Only suspicious things is: php-fpm
- [ ] Check all cronjobs.  
    - There is only the solr import job currently. and I have commented now 27-Jun

# m h  dom mon dow   command
#1 0 * * * solr-client import status
#1 1 * * * add-missing-dois-to-search
#0 2 * * * solr-client import status
#1 2 * * * solr-client import delta
#0 6 * * * solr-client import status

**Comment by kjgarza** [comment]
I would like to let it run without the solr-client import for another day before we close it and shut it down.

**Comment by mfenner** [comment]
Agree.

**Comment by mfenner** [comment]
`php-fpm` might be from running the old Drupal homepage (until ca. 2014).
