### ISSUE TITLE
Transfer DOINZCO

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#914]
Old Repository ID: [DOINZ.GNSSCI]
New Repository ID: [GNSSCI.LIBRARY]
Prefix: [10.21420]
Number of DOIs: [274]

 

Old Repository ID: [DOINZ.ESR]
New Repository ID: [ESR.RESEARCH]
Prefix: [10.26091]
Number of DOIs: [322]

 

Old Repository ID: [DOINZ.LANDCARE]
New Repository ID: [LANDCARE.NZBH-NSC]
Prefix: [10.34721]
Number of DOIs: [1]

 

Old Repository ID: [DOINZ.LANDCARE]
New Repository ID: [LANDCARE.SOILS]
Prefix: [10.26060]
Number of DOIs: [0]

 

Old Repository ID: [DOINZ.LANDCARE]
New Repository ID: [LANDCARE.GENERAL]
Prefix: [10.7931]
Number of DOIs: [2,478]

 

Old Repository ID: [DOINZ.LANDCARE]
New Repository ID: [LANDCARE.NVS]
Prefix: [10.25898]
Number of DOIs: [3]

 

Old Repository ID: [DOINZ.LANDCARE]
New Repository ID: [LANDCARE.PLANTS]
Prefix: [10.26065]
Number of DOIs: [7]

 

Old Repository ID: [DOINZ.NZAU]
New Repository ID: [NZAU.DATA]
Prefix: [10.17608]
Number of DOIs: [2,598]

Old Repository ID: [DOINZ.UCNZ]
New Repository ID: [NZCU.UCRR]
Prefix: [10.18124]
Number of DOIs: [37]

 

Old Repository ID: [DOINZ.UCNZ]
New Repository ID: [NZCU.UCRR]
Prefix: [10.26021]
Number of DOIs: [0]

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1722r)

**Comment by richardhallett** [comment]
doI's transferred
