### ISSUE TITLE
Allow repositories to update their DOIs regardless of prefix ownership

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#916]
In Lupo and Fabrica, a repository should be able to update the metadata for a DOI as long as that DOI is associated with that repository, regardless of who "owns" the prefix. "Ownership" of a prefix is only relevant for DOI creation with that prefix. This accommodates the use case of DOIs from the same prefix being split across more than one repository in the event of organizational restructuring.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_17ozn)

**Comment by daslerr** [comment]
I have confirmed that staff are also unable to update these DOIs.

**Comment by richardhallett** [comment]
This is quite old now and therefore I think it's better handled by a new feature request if still required.
Closing, won't fix.

**Comment by MaryHirsch** [comment]
Is this actually still a thing even? The metadata is always managed by the repository where is sits regardless of where the prefix is.

**Comment by richardhallett** [comment]
I think it is yes, if a repository has DOIs but does not have the prefix, I think it might throw an error, but I couldn't be sure. Hence I closed it. not worth discussing given it hasnt come up again in 2 years :)
