### ISSUE TITLE
support contactEmail attribute for client updates

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#919]
A user reports receiving a 400 error ("unknown attribute 'contact_email' for Client") when attempting to update clients via the /clients endpoint. 

The contact_email attribute has been supplanted by the systemEmail attribute, but the previous contact_email attribute should still be supported by the /clients API for compatibility reasons and should still be able to be updated. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_184sj)

**Comment by mfenner** [comment]
Duplicated by https://github.com/datacite/lupo/issues/383.
