### ISSUE TITLE
HTTP 500 when using OAI-PMH

### ISSUE THREAD

**Issue by gjunge** [datacite/datacite#941]
**Describe the bug**
After reaching this page:
https://oai.datacite.org/oai?verb=ListRecords&resumptionToken=metadataPrefix%3Ddatacite%26until%3D2020-01-09T22%253A45%253A07Z%26from_%3D2019-12-11T22%253A45%253A09Z%26paging_cursor%3DMTU2MTA0MTAxODAwMCwxMC4yMTk3OC9wODUzNHc%26cursor%3D1

The next resumption token:
https://oai.datacite.org/oai?verb=ListRecords&resumptionToken=metadataPrefix%3Ddatacite%26until%3D2020-01-09T22%253A45%253A07Z%26from_%3D2019-12-11T22%253A45%253A09Z%26paging_cursor%3DMTU2MTA1MDgxMTAwMCwxMC4xMDczL3BuYXMuMTIxMTM3MTExMA%26cursor%3D1

Thanks
Gidon

**Comment by richardhallett** [comment]
Hello, this is now fixed, there was a problem with handling a specific doi's metadata.

**Comment by gjunge** [comment]
Thanks!
