### ISSUE TITLE
Mark DOI metadata in registered state as "deleted" in OAI/REST feed

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#949]
### Expected Behaviour

DOIs in registered state are retrieved from OAI/REST feed and marked as registered/not public facing

### Current Behaviour

DOIs in registered state are not appearing/are removed from the OAI/REST feed. Example: 10.18710/mwhucv 

### Steps to Reproduce

This was brought to our attention because doi: 10.18710/mwhucv (in registered state) appears here https://www.base-search.net/Search/Results?lookfor=10.18710%2Fmwhucv&name=&oaboost=  

After contacting BASEl, they report that the metadata for this DOI was completely removed from OAI/REST and request us to mark the content as "deleted" "removed" 

### Context (Environment)

OAI/REST production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1ax8j)

**Comment by richardhallett** [comment]
This is only specific to the OAI-PMH interface, the REST API is working as expected, registered DOI's do not appear in the public REST API, they do appear however for authenticated member queries.

OAI-PMH however should have been showing delete for these DOI's, there was a bug in the code preventing this, I have now fixed this and it is working as expected.

See https://oai.datacite.org/oai/?verb=GetRecord&metadataPrefix=oai_datacite&identifier=doi:10.18710/mwhucv

**Comment by mfenner** [comment]
Cool!
