### ISSUE TITLE
ORCID/DataCite integration documentation

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#951]
ORCID/DataCite integration documentation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1axxf)

**Comment by MaryHirsch** [comment]
open

**Comment by MaryHirsch** [comment]
@richardhallett I think it's done

**Comment by MaryHirsch** [comment]
@richardhallett looking at the Front ticket related to this I realised this is about the search and link wizard from ORCID which takes the user to the profiles page. I will try to update the documentation but ideally this would be improved in DataCite commons @kjgarza is there already something around this in productboard?

**Comment by richardhallett** [comment]
I think any future work needs handling via features, closing for cleanup
