### ISSUE TITLE
ORCID for user record in DataCite profiles is incorrect

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#953]
Admin: Search 0000-0001-5073-0499 in profiles takes you to the record for 0000-0002-0054-832X

<img width="1326" alt="Screen Shot 2020-02-05 at 10 28 12" src="https://user-images.githubusercontent.com/44582654/73834197-33d63700-4803-11ea-8917-6a66d88ee490.png">

**Comment by mfenner** [comment]
Fixed.

![Bildschirmfoto 2020-02-05 um 22.02.22.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/a2f165e3-09e4-4c99-9191-fdbc42bc7c00)
