### ISSUE TITLE
link-based citation formating with style returns not existent

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#956]
### Expected Behaviour

https://data.datacite.org/text/x-bibliography;style=apa/10.5061/dryad.8515     
should return 

> Ollomo, B., Durand, P., Prugnolle, F., Douzery, E. J. P., Arnathau, C., Nkoghe, D., Leroy, E., &amp; Renaud, F. (2011). <i>Data from: A new malaria agent in African hominids.</i> [Data set]. Dryad. https://doi.org/10.5061/DRYAD.8515

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1bm6b)

### Current Behaviour

it returns

> The resource you are looking for doesn't exist.

### Steps to Reproduce
1. call content negotiation with the style parameter to any doi

### Context (Environment)

https://data.datacite.org/text/x-bibliography/10.5061/dryad.8515  <- with default style works

### Hypothesis

- style parameter might not be considered anymore?

### Possible Implementation

Needs to investigate

**Comment by mfenner** [comment]
Link-based content negotiation expects `style` and/or `locale` as query parameters, e.g.

```
https://data.datacite.org/text/x-bibliography/10.5061/dryad.8515?style=apa
```

We have updated the documentation at https://support.datacite.org/docs/datacite-content-resolver accordingly.
