### ISSUE TITLE
delete  DK.GBIF-CO

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#957]
Please delete DK.GBIF-CO this cannot be done in Fabrica
<img width="1322" alt="Screen Shot 2020-02-10 at 10 47 26" src="https://user-images.githubusercontent.com/44582654/74143464-c0616a80-4bf2-11ea-8283-a5695278db25.png">

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1bseb)

**Comment by richardhallett** [comment]
Repository deleted. Stray test DOI was still existing.
