### ISSUE TITLE
Resolutions by repository not loading in stats portal, results in 500 error

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#958]
**Describe the bug**

the "registrations by repository" tab is not loading here https://stats.datacite.org/ > results in a 500 error: https://api.datacite.org/clients/totals

**To Reproduce**
1. Go to https://stats.datacite.org/ 
2. Click on resolutions by repository

**Expected behavior**

resolutions by repository loads on the page

**Desktop (please complete the following information):**

Stats portal production

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1bslf)

**Comment by kjgarza** [comment]
Only affecting `production`. stage and dev enviroment do not show the same problem https://api.test.datacite.org/clients/totals

**Comment by kjgarza** [comment]
``` 
Elasticsearch::Transport::Transport::Errors::ServiceUnavailable ([503] {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"too_many_buckets_exception","reason":"Trying to create too many buckets. Must be less than or equal to: [10000] but was [10001]. This limit can be set by changing the [search.max_buckets] cluster level setting.","max_buckets":10000}},"status":503}):
```

it seems that we have too many repositories to show. Again this is related to the breaking changes in  [ES@7](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#search-max-buckets-cluster-setting) 

https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket.html
> The maximum number of buckets allowed in a single response is limited by a dynamic cluster setting named search.max_buckets. It defaults to 10,000, requests that try to return more than the limit will fail with an exception.

**Comment by kjgarza** [comment]
I think we should `remove` the repository-tab view from the UI as we did with the prefixes. And use the on-click navigation to get to the subset of counts (this can be done).  Otherwise, we would be stretching the capabilities of ES once again. What do others think? @MaryHirsch @mfenner

**Comment by kjgarza** [comment]
addressed in https://github.com/datacite/stats-portal/pull/47

further changes will addressed in https://github.com/datacite/datacite/issues/963
