### ISSUE TITLE
Transfer dois from TUW.REPOSITUM to 2 separate repositories

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#959]
prefix https://doi.datacite.org/repositories/tuw.repositum/dois?prefix=10.22022 
 TUW.REPOSITUM to IIASA.DARE

prefix https://doi.datacite.org/repositories/tuw.repositum/dois?prefix=10.25536 
TUW.REPOSITUM  to MEMO.JOURNAL

**Comment by richardhallett** [comment]
DOI's transferred.
