### ISSUE TITLE
PID Services Frontend MVP

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#962]
First stage of PID Service Registry as required by FREYA T2.3. 

<p></p>

Spec: <https://docs.google.com/document/d/1urqzTfzSDXAsDMuUSsIWm-Ko7GjUVaQSZwuCJZ6DVN4/>

<p></p>

**Comment by daslerr** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/1938015

**Comment by richardhallett** [comment]
Initial MVP available at https://github.com/datacite/beagle

Further work needs to be done for meeting all Freya requirements and deploying, continuing via datacite/datacite#1000
