### ISSUE TITLE
Search results fail on certain queries (including terms argo+floats)

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#976]
Search results fail on certain queires

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1dq2r)

### Expected Behaviour

https://search.datacite.org/works?query=argo floats
should return results in search with the text argo and floats

### Current Behaviour

Return too long query

https://search.datacite.org/works?query=argo+floats

it also fail in the  api 

https://api.datacite.org/dois?query=argo+floats

### Steps to Reproduce

1. visit  https://search.datacite.org/works?query=argo+floats

### Context (Environment)

its weird, it doesn't fail in fabrica https://doi.datacite.org/dois?page=NaN&query=argo floats&sort=relevance

### Hypothesis

There is very long metadata file with the text argo float

**Comment by kjgarza** [comment]
the item retrieved might be the problem. As sorting the items in a different way bring no problems

https://api.datacite.org/dois?query=argo+floats&sort=relevance

**Comment by mfenner** [comment]
@kjgarza is this issue really resolved?

**Comment by kjgarza** [comment]
@mfenner  the problem its mostly related to large metadata retrieval. that query retrieves some very large records (for example 10.15468/dl.n51mv2 its 6MB and its amoung the results). The search interface doesn't have much problem to show that record individually but with as a query response it is struggling to show it. TBF even the browser or a http-client have problems rendering that payload. 

I opted to get the results sorted different so that record won't appear immedetely and doesn't crash the UI interface. The record might be still being retrieved in subsequent pages but might not be grouped with other similar large records. 

I am not sure, what shall we do with those records though, we cannot restrict them from the API or queries. Any thoughts?
