### ISSUE TITLE
DataCite search not loading in some browsers (chrome)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#991]
### Expected Behaviour

DataCite Search loads in Chrome browser

### Current Behaviour

In some Chrome browsers DataCite Search gives "incomplete response from the application message"
<img width="654" alt="Screen Shot 2020-03-16 at 15 25 29" src="https://user-images.githubusercontent.com/44582654/76768684-a68be800-679b-11ea-9879-9f1c6b913de1.png">

### Steps to Reproduce

1. Version 80.0.3987.100 (Official Build) (64-bit)
2. Version 79.0.3945.130 (Official Build) (64-bit)
3.  My system is Debian Linux, v10.
My browser is Chromium, v79.

### Context (Environment)

DataCite Search

**Comment by kjgarza** [comment]
I ran a test under different browsers and OSs. See the link below:

https://www.browserstack.com/screenshots/9c3651ded168f6c67fdd66039b8bbc3200f4b64b

I found no issues about accessing search

**Comment by kjgarza** [comment]
chrome 80 in OSx 
![image](https://user-images.githubusercontent.com/1092861/77405034-e44bca80-6db2-11ea-9f38-24e324e6d5d9.png)

chrome 79 in OSx
![image](https://user-images.githubusercontent.com/1092861/77405106-fded1200-6db2-11ea-82bc-01f2099276ad.png)

**Comment by kjgarza** [comment]
@MaryHirsch  i dont think, we can reproduce this one. The screenshot are tests from a virtual machine (not even my laptop, where it also works)

**Comment by kjgarza** [comment]
I went trough Sarala's browsers, her problems was her browser Cache.
