### ISSUE TITLE
Add checks for isVersionOf when sending claims to ORCID record

### ISSUE THREAD

**Issue by dshorthouse** [datacite/datacite#998]
Please add isVersionOf check prior to sending claims to ORCID as is done for isIdentical and isNewVersionOf.

The current integration without checks for isVersionOf has become unwieldy for users and I have received complaints. See "Natural history specimens collected and/or identified and deposited" entries at https://orcid.org/0000-0003-1105-1850 produced via an initiative I operate, https://bloodhound-tracker.net.

Here's an example on Zenodo, https://doi.org/10.5281/zenodo.2667631 where each subsequent version results in a new, undesirable entry in ORCID. The relatedIdentifiers in DataCite for a new version of an existing resource in Zenodo looks like this:

{ "relationType": "IsVersionOf", "relatedIdentifier": "10.5281/zenodo.2667631", "relatedIdentifierType": "DOI" }

**Comment by mfenner** [comment]
Thank you @dshorthouse, I will look into it. The relevant code is here: https://github.com/datacite/levriero/blob/master/app/models/orcid_claim.rb#L48-L50

You see that we check for `isVersionOf`, but something is obviously not working correctly.

**Comment by dshorthouse** [comment]
Forgive my ignorance, but this same job queue is used for DataCite auto-update on ORCID, correct?

**Comment by mfenner** [comment]
Longer story. This is the service that extracts ORCID IDs from DOI metadata and puts them into our Event Data Service. The filtering by relation type happens here. You can see all events in Event Data for the ORCID ID you mentioned earlier here: https://api.datacite.org/events?orcid=0000-0003-1105-1850&sort=-created

The next step is sending the information to ORCID, but no filtering by relation type happens there. And ignore the Crossref DOIs in Event Data (e.g. https://doi.org/10.1002/aps3.1028), we are not sending those claims to ORCID.

**Comment by dshorthouse** [comment]
Thanks for the background – makes sense. Hard for me to see what's happening in your `push_item` method wrt your "IsVersionOf" check when I can't find where your `item` hash is created and whether or not it has a `relatedIdentifier` key to an array from the metadata produced by Zenodo.

**Comment by dshorthouse** [comment]
Marked as stale but not sure if any new actions has been taken. At my end, the number of purported new entries (rather than versions of existing) that get pushed into ORCID as a result of this oversight frustrates users of https://bionomia.net.

**Comment by richardhallett** [comment]
This is an old issue I'm closing due to various changes happening since 2020.
In addition metadata changes are handled via a different process now.

If this feedback is still relevant please consider submitting to https://github.com/datacite/datacite-suggestions
See also https://schema.datacite.org/contribute.html for how to contribute generally.

EDIT: I realized the above response was about metadata and in fact the request was about how we handle claims, but still generally submitting a new suggestion would be the better place for this discussion.
