### ISSUE TITLE
Provide a message when repository deletion not possible

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#999]
**The problem**

Some repository accounts cannot be deleted because DOIs still assigned to the account in the db, not in elastic search

**Solution**

Users see a message when they try to delete the account "This account cannot be deleted. Please contact support@datacite.org"

**Comment by mfenner** [comment]
don't close.

**Comment by mfenner** [comment]
This will be addressed via , i.e. fixing the issue of DOIs in the database, but not the Elasticsearch index. datacite/datacite#965.
